- templates/Uwp/Projects/DefaultVB/Services/ActivationService.vb
- templates/Uwp/_composition/MVVMBasic/Project.SplitViewVB/Views/ShellPage.xaml.vb
Build dev.templates.tests.full_20180625.2 failed #2391
> Test fixes

- templates/Uwp/Pages/ImageGallery.CaliburnMicro/Views/ImageGalleryViewPage.xaml.cs
- templates/Uwp/Pages/ImageGallery.CodeBehind/Views/ImageGalleryViewPage.xaml.cs
- templates/Uwp/Pages/ImageGallery.CodeBehindVB/Views/ImageGalleryViewPage.xaml.vb
- templates/Uwp/Pages/ImageGallery.Prism/Views/ImageGalleryViewPage.xaml.cs
- templates/Uwp/Pages/ImageGallery/Views/ImageGalleryViewPage.xaml.cs
- templates/Uwp/Pages/ImageGalleryVB/Views/ImageGalleryViewPage.xaml.vb
- templates/Uwp/_composition/CaliburnMicro/Page.ImageGallery.LoadData_Blank_SplitView/.template.config/template.json
- templates/Uwp/_composition/CaliburnMicro/Page.ImageGallery.LoadData_Blank_SplitView/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/Uwp/_composition/CaliburnMicro/Page.ImageGallery.LoadData_TabbedPivot/.template.config/template.json
- templates/Uwp/_composition/CaliburnMicro/Page.ImageGallery.LoadData_TabbedPivot/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/Uwp/_composition/CodeBehind/Page.ImageGallery.LoadData_Blank_SplitView/.template.config/template.json
- templates/Uwp/_composition/CodeBehind/Page.ImageGallery.LoadData_Blank_SplitView/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/Uwp/_composition/CodeBehind/Page.ImageGallery.LoadData_Blank_SplitViewVB/.template.config/template.json
- templates/Uwp/_composition/CodeBehind/Page.ImageGallery.LoadData_Blank_SplitViewVB/Views/wts.ItemNamePage_postaction.xaml.vb
- templates/Uwp/_composition/CodeBehind/Page.ImageGallery.LoadData_TabbedPivot/.template.config/template.json
- templates/Uwp/_composition/CodeBehind/Page.ImageGallery.LoadData_TabbedPivot/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/Uwp/_composition/CodeBehind/Page.ImageGallery.LoadData_TabbedPivotVB/.template.config/template.json
- templates/Uwp/_composition/CodeBehind/Page.ImageGallery.LoadData_TabbedPivotVB/Views/wts.ItemNamePage_postaction.xaml.vb
- templates/Uwp/_composition/_shared/Page.ImageGallery.LoadData_Blank_SplitView/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.ImageGallery.LoadData_Blank_SplitView/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/Uwp/_composition/_shared/Page.ImageGallery.LoadData_Blank_SplitViewVB/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.ImageGallery.LoadData_Blank_SplitViewVB/Views/wts.ItemNamePage_postaction.xaml.vb
- templates/Uwp/_composition/_shared/Page.ImageGallery.LoadData_TabbedPivot/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.ImageGallery.LoadData_TabbedPivot/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/Uwp/_composition/_shared/Page.ImageGallery.LoadData_TabbedPivotVB/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.ImageGallery.LoadData_TabbedPivotVB/Views/wts.ItemNamePage_postaction.xaml.vb
Image Gallery does not restore connected animation on Pivot Project #2382
> Issue2382 pivot

- docs/roadmap.md
Changes hadn't been made since v2.2 was released
> bring roadmap up to date

- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
Only adding messages for now, to get translation.
#2404 Add more validations to naming of pages in wizard
> Added Error and Warning messages for Page and View suffixes

- docs/roadmap.md
> fix typo on roadmap doc

- templates/Uwp/_composition/CaliburnMicro/Project.SplitView/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/CodeBehind/Project.SplitView/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/CodeBehind/Project.SplitViewVB/Views/ShellPage.xaml.vb
- templates/Uwp/_composition/MVVMBasic/Project.SplitView/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/MVVMBasic/Project.SplitViewVB/Views/ShellPage.xaml.vb
- templates/Uwp/_composition/MVVMLight/Project.SplitView/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/MVVMLight/Project.SplitViewVB/Views/ShellPage.xaml.vb
- templates/Uwp/_composition/Prism/Project.SplitView/Views/ShellPage.xaml.cs
Added todo on codebehind of shellpage to make it visible on tasklist 
#2395 TODO comments should not be on xaml
> Added todo on codebehind of shellpage to make it visible on tasklist

- code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyFixture.cs
- code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyTests.cs
Update right click tests
#2432 Build dev.templates.tests.full_20180703.2 failed
> Update right click tests

- README.md
#2288 Reference projects we like/collaborate with
> Added reference to projects we like

- code/src/Core/PostActions/PostActionFactory.cs
- templates/Uwp/Pages/InkDraw.CaliburnMicro/Views/InkDrawViewPage.xaml
- templates/Uwp/Pages/InkDraw.CodeBehind/Views/InkDrawViewPage.xaml
- templates/Uwp/Pages/InkDraw.Prism/Views/InkDrawViewPage.xaml
- templates/Uwp/Pages/InkDraw/Views/InkDrawViewPage.xaml
- templates/Uwp/Pages/InkDrawPicture.CaliburnMicro/Views/InkDrawPictureViewPage.xaml
- templates/Uwp/Pages/InkDrawPicture.CodeBehind/Views/InkDrawPictureViewPage.xaml
- templates/Uwp/Pages/InkDrawPicture.Prism/Views/InkDrawPictureViewPage.xaml
- templates/Uwp/Pages/InkDrawPicture/Views/InkDrawPictureViewPage.xaml
- templates/Uwp/Pages/InkSmartCanvas.CaliburnMicro/Views/InkSmartCanvasViewPage.xaml
- templates/Uwp/Pages/InkSmartCanvas.CodeBehind/Views/InkSmartCanvasViewPage.xaml
- templates/Uwp/Pages/InkSmartCanvas.Prism/Views/InkSmartCanvasViewPage.xaml
- templates/Uwp/Pages/InkSmartCanvas/Views/InkSmartCanvasViewPage.xaml
- templates/Uwp/Projects/Default/Styles/_Colors.xaml
- templates/Uwp/Projects/DefaultPrism/Styles/_Colors.xaml
- templates/Uwp/Projects/DefaultVB/Styles/_Colors.xaml
- templates/Uwp/_composition/_shared/Page.Ink.AddBasicInkServices/Styles/_Colors_postaction.xaml
- templates/Uwp/_composition/_shared/Page.Ink.AddTransformService/Services/Ink/InkTransformService.cs
#2443 - Show ink canvas always with white background
> Set white background to ink canvas

- code/src/Core/Core.csproj
- code/src/Core/Gen/GenParams.cs
- code/src/Core/Gen/GenShell.cs
- code/src/Core/PostActions/Catalog/AddReferenceToProjectPostAction.cs
- code/src/Core/PostActions/Catalog/Merge/MergePostAction.cs
- code/src/Core/PostActions/Catalog/Merge/SearchAndReplacePostAction.cs
- code/src/Core/PostActions/Catalog/NewItemGeneration/CopyFilesToProjectPostAction.cs
- code/src/Core/PostActions/PostActionFactory.cs
- code/src/UI/VisualStudio/RightClickActions.cs
- code/src/UI/VisualStudio/SolutionWizard.cs
- code/src/UI/VisualStudio/VsGenShell.cs
- code/test/Core.Test/PostActions/Catalog/GenerateTestCertificatePostActionTest.cs
- code/test/Core.Test/PostActions/Catalog/MergeResourceDictionaryPostactionTest.cs
- code/test/Templates.Test/BaseTestContextProvider.cs
- code/test/UI.Test/TemplatesFixture.cs
- code/test/VsEmulator/FakeContextProvider.cs
- code/test/VsEmulator/Main/MainViewModel.cs
- templates/Uwp/Features/_CoreProject/.template.config/template.json
- templates/Uwp/Features/_CoreProjectVB/.template.config/template.json
- Save the project after adding the reference
- Fix Refresh project to refresh the project by path instead of active project
#2386, #2252
> Fix AddReferenceToProject Postaction

- code/test/Templates.Test/BaseGenAndBuildTests.cs
> Fix legacy tests

- docs/projectTypes/navigationpane.md
- docs/projectTypes/navigationpane.vb.md
- templates/Uwp/_composition/_shared/Project.SplitView.AddNavigationPaneResources/.template.config/template.json
- templates/Uwp/_composition/_shared/Project.SplitView.AddNavigationPaneResourcesVB/.template.config/template.json
For #2407
Also add docs for how to change this if desired
Adding tests for other unused resources will follow later.
> Don't include unused resource for Settings in NavView

- templates/Uwp/_composition/Prism/Page.TabbedPivot.AddBehavior/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.InkSmartCanvas.AddNavigation_TabbedPivot/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/Uwp/_composition/_shared/Page.TabbedPivot.AddBehavior/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.TabbedPivot.AddBehaviorVB/.template.config/template.json
#2461 - InkSmartCanvas Page doesn't work with Tab&Pivot navigation
- Add initialization flag to csharp template.
- Add Page.TabbedPivot.AddBehavior composition template to InkSmartCanvasPage
> Fix InkSmartCanvas Page with Tab&Pivot navigation

- docs/pages/ink.md
Added overview about which features are implemented in which ink page 
#2470 Inconsistencies and issues in ink pages
> Added overview about which features are implemented in which ink page

- templates/Uwp/_composition/Prism/Page.TabbedPivot.AddBehavior/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.TabbedPivot.AddBehavior/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.TabbedPivot.AddBehaviorVB/.template.config/template.json
Remove pivot behaviour composition for smart ink
#2461 Ink SmartCanvas does not work with Tabbed Pivot
> Remove pivot behaviour composition for smart ink

- code/src/UI/Services/DataService.cs
- code/src/UI/ViewModels/NewItem/TemplateSelectionViewModel.cs
- docs/features/deep-linking.md
- docs/features/multiple-views.md
- docs/features/user-activity.md
- templates/Uwp/Features/DeepLinking.MVVMLight/Activation/SchemeActivationData.cs
- templates/Uwp/Features/DeepLinking.MVVMLight/Activation/SchemeActivationHandler.cs
- templates/Uwp/Features/DeepLinking.MVVMLightVB/.template.config/template.json
- templates/Uwp/Features/DeepLinking.MVVMLightVB/Activation/SchemeActivationData.vb
- templates/Uwp/Features/DeepLinking.MVVMLightVB/Activation/SchemeActivationHandler.vb
- templates/Uwp/Features/DeepLinking.Prism/Activation/SchemeActivationData.cs
- templates/Uwp/Features/DeepLinking/Activation/SchemeActivationData.cs
- templates/Uwp/Features/DeepLinking/Activation/SchemeActivationHandler.cs
- templates/Uwp/Features/DeepLinkingVB/.template.config/template.json
- templates/Uwp/Features/DeepLinkingVB/Activation/SchemeActivationData.vb
- templates/Uwp/Features/DeepLinkingVB/Activation/SchemeActivationHandler.vb
- templates/Uwp/_composition/Prism/Feature.MultiView/.template.config/template.json
- templates/Uwp/_composition/Prism/Feature.MultiView/App.xaml_postaction.cs
- templates/Uwp/_composition/_shared/Feature.MultiView/.template.config/template.json
- templates/Uwp/_composition/_shared/Feature.MultiView/Services/ActivationService_postaction.cs
Add functionality for adding to the user activity #2283
> Updates on User Activity & documentation

- templates/Uwp/Pages/InkDraw.CaliburnMicro/ViewModels/InkDrawViewViewModel.cs
- templates/Uwp/Pages/InkDraw.CodeBehind/Views/InkDrawViewPage.xaml.cs
- templates/Uwp/Pages/InkDraw.CodeBehindVB/Views/InkDrawViewPage.xaml.vb
- templates/Uwp/Pages/InkDraw.Prism/ViewModels/InkDrawViewViewModel.cs
- templates/Uwp/Pages/InkDraw/ViewModels/InkDrawViewViewModel.cs
- templates/Uwp/Pages/InkDrawVB/ViewModels/InkDrawViewViewModel.vb
- templates/Uwp/Pages/InkSmartCanvas.CaliburnMicro/ViewModels/InkSmartCanvasViewViewModel.cs
- templates/Uwp/Pages/InkSmartCanvas.CodeBehind/Views/InkSmartCanvasViewPage.xaml.cs
- templates/Uwp/Pages/InkSmartCanvas.CodeBehindVB/Views/InkSmartCanvasViewPage.xaml.vb
- templates/Uwp/Pages/InkSmartCanvas.Prism/ViewModels/InkSmartCanvasViewViewModel.cs
- templates/Uwp/Pages/InkSmartCanvas/ViewModels/InkSmartCanvasViewViewModel.cs
- templates/Uwp/Pages/InkSmartCanvasVB/ViewModels/InkSmartCanvasViewViewModel.vb
- templates/Uwp/_composition/_shared/Page.Ink.AddTransformService/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.Ink.AddTransformService/Services/Ink/InkTransformService.cs
- templates/Uwp/_composition/_shared/Page.Ink.AddTransformService/Services/Ink/UndoRedo/ClearStrokesAndShapesUndoRedoOperation.cs
- templates/Uwp/_composition/_shared/Page.Ink.AddTransformServiceVB/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.Ink.AddTransformServiceVB/Services/Ink/InkTransformService.vb
- templates/Uwp/_composition/_shared/Page.Ink.AddTransformServiceVB/Services/Ink/UndoRedo/ClearStrokesAndShapesUndoRedoOperation.vb
#2484 - Add undo action for "clear all" from ink canvas
> Issue2484 undo redo clear all ink

- templates/Uwp/Projects/Default/wts.DefaultProject.csproj
- templates/Uwp/Projects/DefaultPrism/wts.DefaultProject.csproj
- templates/Uwp/Projects/DefaultVB/wts.DefaultProject.vbproj
Update Nuget Reference: Microsoft.NETCore.UniversalWindowsPlatform #2512
> Update Nuget Reference Microsoft.NETCore.UniversalWindowsPlatform

- templates/Uwp/Features/UserActivity.MVVMLight/_postaction.csproj
- templates/Uwp/Features/UserActivity.MVVMLightVB/_postaction.vbproj
- templates/Uwp/Features/UserActivity.Prism/_postaction.csproj
- templates/Uwp/Features/UserActivity/_postaction.csproj
- templates/Uwp/Features/UserActivityVB/_postaction.vbproj
Update AdaptiveCards NuGet packages to the latest versions. #2511
> Update Nuget Reference AdaptiveCards

- templates/Uwp/Features/FirstUsePrompt.Prism/_postaction.csproj
- templates/Uwp/Features/FirstUsePrompt/_postaction.csproj
- templates/Uwp/Features/FirstUsePromptVB/_postaction.vbproj
- templates/Uwp/Features/LiveTile.Prism/_postaction.csproj
- templates/Uwp/Features/LiveTile/_postaction.csproj
- templates/Uwp/Features/LiveTileVB/_postaction.vbproj
- templates/Uwp/Features/ToastNotifications.Prism/_postaction.csproj
- templates/Uwp/Features/ToastNotifications/_postaction.csproj
- templates/Uwp/Features/ToastNotificationsVB/_postaction.vbproj
- templates/Uwp/Features/WhatsNewPrompt.Prism/_postaction.csproj
- templates/Uwp/Features/WhatsNewPrompt/_postaction.csproj
- templates/Uwp/Features/WhatsNewPromptVB/_postaction.vbproj
- templates/Uwp/Pages/DataGrid.CodeBehind/_postaction.csproj
- templates/Uwp/Pages/DataGrid.CodeBehindVB/_postaction.vbproj
- templates/Uwp/Pages/DataGrid.Prism/_postaction.csproj
- templates/Uwp/Pages/DataGrid/_postaction.csproj
- templates/Uwp/Pages/DataGridVB/_postaction.vbproj
- templates/Uwp/Pages/MasterDetail.CaliburnMicro/_postaction.csproj
- templates/Uwp/_composition/_shared/Page.MasterDetail/_postaction.csproj
- templates/Uwp/_composition/_shared/Page.MasterDetailVB/_postaction.vbproj
Update Windows Community Toolkit NuGet packages to the latest versions. #2509
Also, update from preview DataGrid page reference
Add page using new DataGrid from the community toolkit #2238
> Update Nuget Reference Windows Community Toolkit

- templates/Uwp/Features/FeedbackHub.CaliburnMicro/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.CodeBehind/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.CodeBehindVB/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.MVVMBasic/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.MVVMBasicVB/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.MVVMLight/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.MVVMLightVB/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.Prism/.template.config/template.json
- templates/Uwp/Features/VSAppCenterAnalytics/_postaction.csproj
- templates/Uwp/Features/VSAppCenterAnalyticsVB/_postaction.vbproj
- templates/Uwp/Pages/DataGrid.CodeBehind/.template.config/template.json
- templates/Uwp/Pages/DataGrid.CodeBehindVB/.template.config/template.json
- templates/Uwp/Pages/DataGrid.Prism/.template.config/template.json
- templates/Uwp/Pages/DataGrid/.template.config/template.json
- templates/Uwp/Pages/DataGridVB/.template.config/template.json
- templates/Uwp/Pages/ImageGallery.CaliburnMicro/.template.config/template.json
- templates/Uwp/Pages/ImageGallery.CodeBehind/.template.config/template.json
- templates/Uwp/Pages/ImageGallery.Prism/.template.config/template.json
- templates/Uwp/Pages/ImageGallery/.template.config/template.json
- templates/Uwp/Pages/ImageGalleryVB/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.MasterDetail/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.MasterDetailVB/.template.config/template.json
Uwp Community Toolkit reference appears two times in Licenses list #2518
> Fix Licenses

- code/src/Core/Naming/PageSuffixValidator.cs
- code/src/UI/ViewModels/Common/DataItems/SavedTemplateViewModel.cs
Add more validations to naming of pages in wizard #2404
> Fix link on view naming validation notification

- docs/WTSNaming.md
Sort reserved names alphabetically in doc
#2404 Add more validations to naming of pages in wizard
> Sort reserved names alphabetically

- templates/Uwp/_composition/_shared/Page.Camera.AddResource/Controls/CameraControl.xaml.cs
- templates/Uwp/_composition/_shared/Page.Camera.AddResourceVB/Controls/CameraControl.xaml.vb
Camera page throws exception when denying permission #2537
> Show Camera error message

- templates/Uwp/Features/BackgroundTask.Prism/App_postaction.xaml.cs
- templates/Uwp/Features/LiveTile.Prism/App_postaction.xaml.cs
- templates/Uwp/_composition/Prism/Project.Blank.AddNavigation/App_postaction.xaml.cs
- Change execution order for app initialization in prism 
- #2533 Dev-nightly: Prism app chrashes when adding LiveTile and MultiView
> Issue2533 prisminitialize

- code/src/UI/Generation/GenComposer.cs
Only get namespace from active project in the case of NewItem (Right click) generation. For NewProject, namespace is always ProjectName
#2541 Generation fails when adding project to existing solution while having project selected
> Issue2541 Adjusted namespace resolution

- code/test/Fakes/FakeGenShell.cs
- code/test/Fakes/Solution/FakeSolution.cs
#2386 - "Add reference to project" postaction
>  Add reference to project in fake gen shell

- code/src/Core/Fs.cs
- code/src/Core/Resources/StringRes.Designer.cs
- code/src/Core/Resources/StringRes.cs-CZ.resx
- code/src/Core/Resources/StringRes.de-DE.resx
- code/src/Core/Resources/StringRes.es-ES.resx
- code/src/Core/Resources/StringRes.fr-FR.resx
- code/src/Core/Resources/StringRes.it-IT.resx
- code/src/Core/Resources/StringRes.ja-JP.resx
- code/src/Core/Resources/StringRes.ko-KR.resx
- code/src/Core/Resources/StringRes.pl-PL.resx
- code/src/Core/Resources/StringRes.pt-BR.resx
- code/src/Core/Resources/StringRes.resx
- code/src/Core/Resources/StringRes.ru-RU.resx
- code/src/Core/Resources/StringRes.tr-TR.resx
- code/src/Core/Resources/StringRes.zh-CN.resx
- code/src/Core/Resources/StringRes.zh-TW.resx
- code/src/UI/Generation/GenController.cs
#2565 - 3.0: Generation fails when adding two ImageGalleries
> Fix moving files in the generation code

- templates/Uwp/Pages/ImageGallery.CodeBehind/Views/ImageGalleryViewDetailPage.xaml.cs
- templates/Uwp/Pages/ImageGallery.CodeBehindVB/Views/ImageGalleryViewDetailPage.xaml.vb
- templates/Uwp/Pages/ImageGalleryVB/ViewModels/ImageGalleryViewDetailViewModel.vb
#2569 - Build v3.0.templates.tests.full_20180917.2 failed
> Restory some namespaces

- code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyFixture.cs
Exclude MVVMLight from right click tests as there are breaking changes
#2487 Multiview fails with MVVMLight
> Exclude MVVMLight from right click tests as there are breaking changes

- code/test/Templates.Test/BaseGenAndBuildFixture.cs
- code/test/Templates.Test/WACK/WindowsAppCertKitTests.cs
-Remove background task from wack
- Cleanup after tests
#2573 Wack tests fail due to missing space
#2358 Wack tests fail on 17134
> Issue2358 backgroundtaskwack

- code/src/UI/Validators/HasNavigationViewValidator.cs
- code/src/UI/Validators/HasOldMvvmLightLocatorValidator.cs
> Fix 3.0 build

- docs/frameworks/updatemvvmlightlocator.md
Update MVVMLight breaking change doc
Multi view fails with Mvvm Light #2487
> Update MVVMLight breaking change doc

- docs/frameworks/updatemvvmlightlocator.md
Some polishing on documentation
#2487 Multiview fails for mvvmlight
> Updates on updatemvvmlightlocator

- README.md
This version sounds a bit better than the previous way it was written.
It also fixes the numbering in that section. (It worked but my OCD kicked in. :) )
> [SKIP CI] Improve sentence in Principles section in README

- code/src/UI/VisualStudio/RightClickActions.cs
#2452 Support adding projects from right click
> Initialize project and projectreferences for right click

- code/src/UI/Controls/Notification.cs
- code/src/UI/Controls/NotificationsControl.xaml.cs
- code/src/UI/Services/DragAndDropService/DragAndDropService.cs
- code/src/UI/Services/NavigationService.cs
- code/src/UI/Services/OrderingService.cs
- code/src/UI/Services/Styles/BaseStyleValuesProvider.cs
- code/src/UI/Services/Styles/UIStylesService.cs
- code/src/UI/Services/Styles/VSStyleValuesProvider.cs
- code/src/UI/Services/SystemService.cs
- code/src/UI/ViewModels/Common/BaseMainViewModel.cs
- code/src/UI/Views/NewItem/MainPage.xaml.cs
- code/src/UI/Views/NewItem/WizardShell.xaml.cs
- code/src/UI/Views/NewProject/MainPage.xaml.cs
- code/src/UI/Views/NewProject/WizardShell.xaml.cs
- code/test/VsEmulator/Main/MainView.xaml.cs
> Change UnsuscribeEventHandlers to UnsubscribeEventHandlers

- code/test/Core.Test/PostActions/Catalog/MergePostactionTest.cs
- code/test/Core.Test/PostActions/Catalog/SearchAndReplacePostActionTest.cs
Make tests culture-independant 
#2653 Build dev.version failed
> Make tests culture-independant

- templates/Uwp/Features/BackgroundTask.Prism/BackgroundTasks/BackgroundTaskFeature.cs
- templates/Uwp/Features/BackgroundTask/BackgroundTasks/BackgroundTaskFeature.cs
- templates/Uwp/Features/BackgroundTaskVB/BackgroundTasks/BackgroundTaskFeature.vb
#2505 - BackgroundTask trigger change not registered
> Fix background task registration

- code/test/Core.Test/Locations/RemoteTemplateSourceTests.cs
> Fix full tests

- templates/Uwp/_composition/CaliburnMicro/Project.SplitView/_postaction.csproj
- templates/Uwp/_composition/CodeBehind/Project.SplitView/_postaction.csproj
- templates/Uwp/_composition/CodeBehind/Project.SplitViewVB/_postaction.vbproj
- templates/Uwp/_composition/MVVMBasic/Project.SplitView/_postaction.csproj
- templates/Uwp/_composition/MVVMBasic/Project.SplitViewVB/_postaction.vbproj
- templates/Uwp/_composition/MVVMLight/Project.SplitView/_postaction.csproj
- templates/Uwp/_composition/MVVMLight/Project.SplitViewVB/_postaction.vbproj
- templates/Uwp/_composition/Prism/Project.SplitView/_postaction.csproj
Add Navigation view (Preview version) support #2488
Update WinUI version
> Update WinUI version

- code/test/Core.Test/Locations/RemoteTemplateSourceTests.cs
- code/tools/WtsTool/CommandOptions/RemoteSourcePublishOptions.cs
- code/tools/WtsTool/RemoteSource.cs
- code/tools/WtsTool/RemoteSourceWorker.cs
Add language, platform and wizardversion to blob metadata when publishing templates
#1478 Split templates content
> Issue2217 splittemplates

- code/tools/WtsTool/RemoteSourceWorker.cs
> Fix versions in config.json

- templates/Uwp/_composition/MVVMLight/Project.TabbedPivotVB/.template.config/template.json
- templates/Uwp/_composition/MVVMLight/Project.TabbedPivotVB/Helpers/PivotItemExtensions.vb
Added missing PivotItemExtension.vb file
#2690 dev.tests.full fails
> Added missing PivotItemExtension.vb file

- code/tools/WtsTool/App.config
- code/tools/WtsTool/WtsTool.csproj
- code/tools/WtsTool/packages.config
Update to odata 5.8.4
#2685 Update OData
> Update to odata 5.8.4

- code/src/Core/PostActions/Catalog/SortNamespaces/ListStringExtensions.cs
- code/src/Core/Templates/ITemplateInfoExtensions.cs
- code/src/UI/Generation/GenComposer.cs
- code/src/UI/Generation/ProjectConfigInfo.cs
- code/src/UI/ViewModels/Common/DataItems/SavedTemplateViewModel.cs
- code/test/Templates.Test/BaseGenAndBuildFixture.cs
- code/test/Templates.Test/GenTests/LanguageComparisonTests.cs
- code/test/Templates.Test/VisualTests/VisualComparisonTests.cs
- code/test/VsEmulator/Main/MainViewModel.cs
- code/test/VsEmulator/TemplatesContent/TemplatesContentViewModel.cs
#874 - Remove SA1008 suppression for tuples once stylecop is updated
> Remove supress messages to SA1008 stylecop rule

- code/test/Core.Test/PostActions/Catalog/CreateSummaryPostActionTest.cs
Set cultureInfo for tests that depend on language 
#2700 Build dev.version_0.19.18292.02 failed
> Set cultureInfo for tests that depend on language

- templates/Uwp/_composition/CaliburnMicro/Project.SplitView/ViewModels/ShellViewModel.cs
Alt+Left tooltip shows up everywhere on NavigationView #2650
> Fix Alt + Left in caliburn micro

- templates/Uwp/Features/HubNotifications.Prism/Services/HubNotificationsFeatureService.cs
- templates/Uwp/Features/HubNotifications/Services/HubNotificationsFeatureService.cs
- templates/Uwp/Features/HubNotificationsVB/Services/HubNotificationsFeatureService.vb
- templates/Uwp/Features/LiveTile.Prism/Services/LiveTileFeatureService.cs
- templates/Uwp/Features/LiveTile/Services/LiveTileFeatureService.cs
- templates/Uwp/Features/LiveTileVB/Services/LiveTileFeatureService.vb
- templates/Uwp/Features/StoreNotifications.Prism/Services/StoreNotificationsFeatureService.cs
- templates/Uwp/Features/StoreNotifications/Services/StoreNotificationsFeatureService.cs
- templates/Uwp/Features/StoreNotificationsVB/Services/StoreNotificationsFeatureService.vb
- templates/Uwp/Features/ToastNotifications.Prism/Services/ToastNotificationsFeatureService.cs
- templates/Uwp/Features/ToastNotifications/Services/ToastNotificationsFeatureService.cs
- templates/Uwp/Features/ToastNotificationsVB/Services/ToastNotificationsFeatureService.vb
Review calls to external APIs #2695
> add try catch to external api callls

- templates/Uwp/Features/FirstUsePrompt.Prism/_postaction.csproj
- templates/Uwp/Features/FirstUsePrompt/_postaction.csproj
- templates/Uwp/Features/FirstUsePromptVB/_postaction.vbproj
- templates/Uwp/Features/LiveTile.Prism/_postaction.csproj
- templates/Uwp/Features/LiveTile/_postaction.csproj
- templates/Uwp/Features/LiveTileVB/_postaction.vbproj
- templates/Uwp/Features/ToastNotifications.Prism/_postaction.csproj
- templates/Uwp/Features/ToastNotifications/_postaction.csproj
- templates/Uwp/Features/ToastNotificationsVB/_postaction.vbproj
- templates/Uwp/Features/WhatsNewPrompt.Prism/_postaction.csproj
- templates/Uwp/Features/WhatsNewPrompt/_postaction.csproj
- templates/Uwp/Features/WhatsNewPromptVB/_postaction.vbproj
- templates/Uwp/Pages/DataGrid.CodeBehind/_postaction.csproj
- templates/Uwp/Pages/DataGrid.CodeBehindVB/_postaction.vbproj
- templates/Uwp/Pages/DataGrid.Prism/_postaction.csproj
- templates/Uwp/Pages/DataGrid/_postaction.csproj
- templates/Uwp/Pages/DataGridVB/_postaction.vbproj
- templates/Uwp/Pages/MasterDetail.CaliburnMicro/_postaction.csproj
- templates/Uwp/Pages/MasterDetail.CodeBehind/_postaction.csproj
- templates/Uwp/Pages/MasterDetail.CodeBehindVB/_postaction.vbproj
- templates/Uwp/Pages/MasterDetail.Prism/_postaction.csproj
- templates/Uwp/Pages/MasterDetail/_postaction.csproj
- templates/Uwp/Pages/MasterDetailVB/_postaction.vbproj
- templates/Uwp/_composition/Prism/Page.SplitView.MasterDetail/Views/wts.ItemNamePage_postaction.xaml
- templates/Uwp/_composition/_shared/Page.SplitView.MasterDetail/Views/wts.ItemNamePage_postaction.xaml
- templates/Uwp/_composition/_shared/Page.SplitView.MasterDetailVB/Views/wts.ItemNamePage_postaction.xaml
#2488 - Add Navigation view (Preview version) support
> Issue2488 support uwp toolkit v5

- templates/Uwp/Pages/ImageGallery.CaliburnMicro/Views/ImageGalleryViewDetailPage.xaml
- templates/Uwp/Pages/ImageGallery.CodeBehind/Views/ImageGalleryViewDetailPage.xaml
- templates/Uwp/Pages/ImageGallery.CodeBehindVB/Views/ImageGalleryViewDetailPage.xaml
- templates/Uwp/Pages/ImageGallery.Prism/Views/ImageGalleryViewDetailPage.xaml
- templates/Uwp/Pages/ImageGallery/Views/ImageGalleryViewDetailPage.xaml
- templates/Uwp/Pages/ImageGalleryVB/Views/ImageGalleryViewDetailPage.xaml
#2726 - Warning message when building a project with a image gallery page
> Fix warning message to image gallery detail page

- templates/Uwp/Features/BackgroundTask.Prism/App_postaction.xaml.cs
#2733 Build dev.fulltests failed
> Fix stylecop for prism

- docs/frameworks/updatemvvmlightlocator-vb.md
- docs/frameworks/updatemvvmlightlocator.md
- docs/projectTypes/fromnavigationviewtowinui/codebehind-vb.md
- docs/projectTypes/fromnavigationviewtowinui/mvvmbasic-vb.md
- docs/projectTypes/fromnavigationviewtowinui/mvvmlight-vb.md
- docs/projectTypes/navigationpane.md
- docs/projectTypes/navigationpane.vb.md
- docs/projectTypes/updatetonavigationview/codebehind-cs.md
- docs/projectTypes/updatetonavigationview/mvvmbasic-vb.md
- docs/projectTypes/updatetonavigationview/mvvmlight-cs.md
- docs/projectTypes/updatetonavigationview/mvvmlight-vb.md
- docs/projectTypes/updatetonavigationview/prism-cs.md
- docs/projectTypes/updatetowinuinavigationview.md
- Updated vb documentation
- Added info on NavViewHeaderBehavior 
- #2488 Add NavigationView
> Updated vb documentation

- code/src/Core/Locations/RemoteTemplatesSource.cs
#1478 Split template content by language/platform
> Return content info if content is already there

- templates/Uwp/_composition/MVVMLight/Project.SplitView.Page.MasterDetailVB/.template.config/template.json
#2746 Dev.templates.publish failed
> Fix composition filter

- templates/Uwp/Features/DeepLinking.MVVMLight/Views/SchemeActivationSamplePage.xaml
- templates/Uwp/Features/DeepLinking.MVVMLightVB/Views/SchemeActivationSamplePage.xaml
- templates/Uwp/Features/DeepLinking.Prism/Views/SchemeActivationSamplePage.xaml
- templates/Uwp/Features/DeepLinking/Views/SchemeActivationSamplePage.xaml
- templates/Uwp/Features/DeepLinkingVB/Views/SchemeActivationSamplePage.xaml
- templates/Uwp/_composition/CaliburnMicro/Feature.DeepLinking_Blank/Views/SchemeActivationSamplePage_postaction.xaml
- templates/Uwp/_composition/CodeBehind/Feature.DeepLinking_Blank/Views/SchemeActivationSamplePage_postaction.xaml
- templates/Uwp/_composition/CodeBehind/Feature.DeepLinking_Blank/Views/SchemeActivationSamplePage_searchreplace.xaml
- templates/Uwp/_composition/CodeBehind/Feature.DeepLinking_BlankVB/Views/SchemeActivationSamplePage_postaction.xaml
- templates/Uwp/_composition/CodeBehind/Feature.DeepLinking_BlankVB/Views/SchemeActivationSamplePage_searchreplace.xaml
- templates/Uwp/_composition/MVVMBasic/Feature.DeepLinking_Blank/Views/SchemeActivationSamplePage_postaction.xaml
- templates/Uwp/_composition/MVVMBasic/Feature.DeepLinking_Blank/Views/SchemeActivationSamplePage_searchreplace.xaml
- templates/Uwp/_composition/MVVMBasic/Feature.DeepLinking_BlankVB/Views/SchemeActivationSamplePage_postaction.xaml
- templates/Uwp/_composition/MVVMBasic/Feature.DeepLinking_BlankVB/Views/SchemeActivationSamplePage_searchreplace.xaml
- templates/Uwp/_composition/MVVMLight/Feature.DeepLinking_Blank/Views/SchemeActivationSamplePage_postaction.xaml
- templates/Uwp/_composition/MVVMLight/Feature.DeepLinking_Blank/Views/SchemeActivationSamplePage_searchreplace.xaml
- templates/Uwp/_composition/MVVMLight/Feature.DeepLinking_BlankVB/Views/SchemeActivationSamplePage_postaction.xaml
- templates/Uwp/_composition/MVVMLight/Feature.DeepLinking_BlankVB/Views/SchemeActivationSamplePage_searchreplace.xaml
- templates/Uwp/_composition/Prism/Feature.DeepLinking_Blank/Views/SchemeActivationSamplePage_postaction.xaml
- templates/Uwp/_composition/Prism/Feature.DeepLinking_Blank/Views/SchemeActivationSamplePage_searchreplace.xaml
Correct Scheme Activation Page alignment
#1229 Review generated pages redlines and guidance as per design team requests
> Correct SchemeActivation alignment

- code/src/Installer.2017/source.extension.vsixmanifest
- templates/Uwp/Features/ShareTarget.CodeBehindVB/Views/ShareTargetFeaturePage.xaml
- templates/Uwp/_composition/MVVMLight/Feature.ShareTargetVB/Views/wts.ItemNamePage.xaml
- templates/Uwp/_composition/_shared/Page.Ink.Blank.AddTitle/Strings/en-us/Resources_postaction.resw
- templates/Uwp/_composition/_shared/Page.Ink.Blank.AddTitleVB/Strings/en-us/Resources_postaction.resw
- templates/Uwp/_composition/_shared/Page.InkDraw.StringsVB/Strings/en-us/Resources_postaction.resw
- templates/Uwp/_composition/_shared/Page.InkDrawPicture.StringsVB/Strings/en-us/Resources_postaction.resw
- templates/Uwp/_composition/_shared/Page.InkSmartCanvas.StringsVB/Strings/en-us/Resources_postaction.resw
- Changed pre-requisites to UWP component shared between VS2017 and VS2019
- Added missing resources
- Synced VB templates
> Fix for VS2019 support and fixes from executing manual tests

- templates/Uwp/Projects/Default/Styles/_Thickness.xaml
- templates/Uwp/Projects/DefaultPrism/Styles/_Thickness.xaml
- templates/Uwp/Projects/DefaultVB/Styles/_Thickness.xaml
-Quick summary of changes
Correct Left margin used in ink pages in Blank project
#1229 Review generated pages redlines and guidance as per design team requests
> Correct Left margin used in ink pages in Blank project

- templates/Uwp/_composition/CaliburnMicro/Project.SplitView.Page.Settings/ViewModels/ShellViewModel_postaction.cs
- templates/Uwp/_composition/CaliburnMicro/Project.SplitView/ViewModels/ShellViewModel.cs
- templates/Uwp/_composition/CaliburnMicro/Project.SplitView/Views/ShellPage.xaml
- templates/Uwp/_composition/CaliburnMicro/Project.SplitView/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/MVVMBasic/Project.SplitView/Views/ShellPage.xaml
- templates/Uwp/_composition/MVVMBasic/Project.SplitView/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/MVVMBasic/Project.SplitViewVB/Views/ShellPage.xaml
- templates/Uwp/_composition/MVVMBasic/Project.SplitViewVB/Views/ShellPage.xaml.vb
- templates/Uwp/_composition/MVVMLight/Project.SplitView/Views/ShellPage.xaml
- templates/Uwp/_composition/MVVMLight/Project.SplitView/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/MVVMLight/Project.SplitViewVB/Views/ShellPage.xaml
- templates/Uwp/_composition/MVVMLight/Project.SplitViewVB/Views/ShellPage.xaml.vb
- templates/Uwp/_composition/Prism/Project.SplitView/Views/ShellPage.xaml
- templates/Uwp/_composition/Prism/Project.SplitView/Views/ShellPage.xaml.cs
Hotfix for Issue
WinUI:NavigationView does not navigate in Release Mode #2774
> Hotfix commit for Issue #2774

- docs/roadmap.md
#2740 Update Roadmap to reflect milestones
> Updated roadmap.md

- code/tools/Vsts2git/PublishBuildResult.cs
Get repo and owner from build info, to enable vsts2git function for rxt
> Get repo and owner from build info

- templates/Uwp/Pages/ImageGallery.Prism/Param_ProjectName.Core/Services/ISampleDataService$ImageGalleryView_gpostaction.cs
- templates/Uwp/Pages/ImageGallery.Prism/Param_ProjectName.Core/Services/SampleDataService$ImageGalleryView_gpostaction.cs
- templates/Uwp/Pages/ImageGallery.Prism/Param_ProjectName/App$ImageGalleryView_gpostaction.xaml.cs
- templates/Uwp/_composition/_shared/Page.ImageGallery/Param_ProjectName.Core/Services/SampleDataService$wts.ItemName_gpostaction.cs
- templates/Uwp/_composition/_shared/Page.ImageGallery/Param_ProjectName/Services/ActivationService$wts.ItemName_gpostaction.cs
Review Sample Images location and SampleDataService #2561
> Review Sample Images location

- code/test/Templates.Test/RestoreAndBuildAppx.bat
-Quick summary of changes
Add platform to compile wack test projects
#2797 Wack tests failed
> Add platform to compile wack test projects

- templates/Uwp/Features/FirstUsePrompt.Prism/Strings/en-us/Resources_postaction.resw
- templates/Uwp/Features/FirstUsePrompt.Prism/Views/FirstRunDialog.xaml
- templates/Uwp/Features/FirstUsePrompt/Strings/en-us/Resources_postaction.resw
- templates/Uwp/Features/FirstUsePrompt/Views/FirstRunDialog.xaml
- templates/Uwp/Features/FirstUsePromptVB/Strings/en-us/Resources_postaction.resw
- templates/Uwp/Features/FirstUsePromptVB/Views/FirstRunDialog.xaml
- templates/Uwp/Features/WhatsNewPrompt.Prism/Strings/en-us/Resources_postaction.resw
- templates/Uwp/Features/WhatsNewPrompt.Prism/Views/WhatsNewDialog.xaml
- templates/Uwp/Features/WhatsNewPrompt/Strings/en-us/Resources_postaction.resw
- templates/Uwp/Features/WhatsNewPrompt/Views/WhatsNewDialog.xaml
- templates/Uwp/Features/WhatsNewPromptVB/Strings/en-us/Resources_postaction.resw
- templates/Uwp/Features/WhatsNewPromptVB/Views/WhatsNewDialog.xaml
What's New and First Run Prompts are setting the title two times #2805
> Fix String and Bindings in FirstUse and WhatsNew Promts

- templates/Uwp/Features/DeepLinking.MVVMLight/ViewModels/ViewModelLocator_postaction.cs
- templates/Uwp/Features/DeepLinking.MVVMLightVB/ViewModels/ViewModelLocator_postaction.vb
- templates/Uwp/_composition/MVVMLight/Feature.DeepLinking_BlankVB/Activation/SchemeActivationHandler_postaction.vb
- templates/Uwp/_composition/MVVMLight/Feature.DeepLinking_SplitView.TabbedNavVB/Activation/SchemeActivationHandler_postaction.vb
- templates/Uwp/_composition/MVVMLight/Feature.ShareTarget/ViewModels/ViewModelLocator_postaction.cs
- templates/Uwp/_composition/MVVMLight/Feature.ShareTargetVB/ViewModels/ViewModelLocator_postaction.vb
- templates/Uwp/_composition/MVVMLight/Feature.SuspendAndResume.AddNavigation/Services/SuspendAndResumeService_postaction.cs
- templates/Uwp/_composition/MVVMLight/Feature.SuspendAndResume.AddNavigationVB/Services/SuspendAndResumeService_postaction.vb
- templates/Uwp/_composition/MVVMLight/Page.AddViewModel/ViewModels/ViewModelLocator_postaction.cs
- templates/Uwp/_composition/MVVMLight/Page.AddViewModelVB/ViewModels/ViewModelLocator_postaction.vb
- templates/Uwp/_composition/MVVMLight/Page.ContentGrid/ViewModels/ViewModelLocator_postaction.cs
- templates/Uwp/_composition/MVVMLight/Page.ContentGridVB/ViewModels/ViewModelLocator_postaction.vb
- templates/Uwp/_composition/MVVMLight/Page.ContentGridVB/ViewModels/wts.ItemNameViewModel_postaction.vb
- templates/Uwp/_composition/MVVMLight/Page.ContentGridVB/Views/wts.ItemNameDetailPage_postaction.xaml.vb
- templates/Uwp/_composition/MVVMLight/Page.ImageGallery/ViewModels/ViewModelLocator_postaction.cs
- templates/Uwp/_composition/MVVMLight/Page.ImageGalleryVB/ViewModels/ViewModelLocator_postaction.vb
- templates/Uwp/_composition/MVVMLight/Page.ImageGalleryVB/ViewModels/wts.ItemNameViewModel_postaction.vb
- templates/Uwp/_composition/MVVMLight/Page.ImageGalleryVB/Views/wts.ItemNameDetailPage_postaction.xaml.vb
- templates/Uwp/_composition/MVVMLight/Page.MediaPlayer.AddViewModel/ViewModels/ViewModelLocator_postaction.cs
- templates/Uwp/_composition/MVVMLight/Page.MediaPlayer.AddViewModelVB/ViewModels/ViewModelLocator_postaction.vb
- templates/Uwp/_composition/MVVMLight/Project.SplitView.TabbedNav/ViewModels/ShellViewModel.cs
- templates/Uwp/_composition/MVVMLight/Project.SplitView.TabbedNav/ViewModels/ViewModelLocator_postaction.cs
- templates/Uwp/_composition/MVVMLight/Project.SplitView.TabbedNavVB/ViewModels/ShellViewModel.vb
- templates/Uwp/_composition/MVVMLight/Project.SplitView.TabbedNavVB/ViewModels/ViewModelLocator_postaction.vb
- templates/Uwp/_composition/MVVMLight/Project/.template.config/template.json
- templates/Uwp/_composition/MVVMLight/Project/ViewModels/ViewModelLocator.cs
- templates/Uwp/_composition/MVVMLight/ProjectVB/.template.config/template.json
- templates/Uwp/_composition/MVVMLight/ProjectVB/Activation/DefaultLaunchActivationHandler_postaction.vb
- templates/Uwp/_composition/MVVMLight/ProjectVB/ViewModels/ViewModelLocator.vb
- templates/_catalog/frameworks.json
mvvmlight - .net standard #2333
> Update MVVMLight nuget reference to dotnet standard version

- code/tools/WtsTelemetry/WtsTelemetry/Helpers/StringHelper.cs
- templates/Uwp/Pages/Grid.CodeBehind/.template.config/template.json
- templates/Uwp/Pages/Grid.CodeBehindVB/.template.config/template.json
- templates/Uwp/Pages/Grid.Prism/.template.config/template.json
- templates/Uwp/Pages/Grid/.template.config/template.json
- templates/Uwp/Pages/GridVB/.template.config/template.json
Set "Horizontal Navigation View" telemetry name to TabbedNav project type.
#2819 - https://github.com/Microsoft/WindowsTemplateStudio/issues/2819
> Remove telemetry name in telerik datagrid template. Set telemetry name to TabbedNav project type.

- templates/Uwp/Pages/MediaPlayer.CodeBehind/Views/MediaPlayerViewPage.xaml.cs
- templates/Uwp/Pages/MediaPlayer.CodeBehindVB/Views/MediaPlayerViewPage.xaml.vb
- templates/Uwp/Pages/MediaPlayer.Prism/ViewModels/MediaPlayerViewViewModel.cs
- templates/Uwp/Pages/MediaPlayer/ViewModels/MediaPlayerViewViewModel.cs
- templates/Uwp/Pages/MediaPlayer/Views/MediaPlayerViewPage.xaml.cs
- templates/Uwp/Pages/MediaPlayerVB/ViewModels/MediaPlayerViewViewModel.vb
- templates/Uwp/Pages/MediaPlayerVB/Views/MediaPlayerViewPage.xaml.vb
Page Navigation - Memory Leak #2785
> Add MediaElement Dispose in MediaPlayer page template

- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
- templates/Uwp/Pages/ContentGrid.CaliburnMicro/.template.config/description.md
- templates/Uwp/Pages/ContentGrid.CodeBehind/.template.config/description.md
- templates/Uwp/Pages/ContentGrid.CodeBehindVB/.template.config/description.md
- templates/Uwp/Pages/ContentGrid.Prism/.template.config/description.md
- templates/Uwp/Pages/ContentGrid/.template.config/description.md
- templates/Uwp/Pages/ContentGridVB/.template.config/description.md
- Correct content grid description 
- add strings for multiproject breaking change message
- Remove unused strings 
#2619 , #405
> Prepare for localization

- code/src/Core/Core.csproj
- code/src/Core/Extensions/PathExtensions.cs
- code/src/Core/Gen/GenController.cs
- code/src/Core/Gen/NewItemGenController.cs
- code/src/Core/Gen/NewProjectGenController.cs
- code/src/Core/PostActions/Catalog/Merge/GenerateMergeInfoPostAction.cs
- code/src/Core/PostActions/Catalog/Merge/GetMergeFilesFromProjectPostAction.cs
- code/src/Core/PostActions/Catalog/Merge/MergeConfiguration.cs
- code/src/Core/PostActions/Catalog/Merge/MergePostAction.cs
- code/src/Core/PostActions/Catalog/Merge/MergeResourceDictionaryPostAction.cs
- code/src/Core/PostActions/Catalog/Merge/PostactionFormatter.cs
- code/src/Core/PostActions/Catalog/Merge/SearchAndReplacePostAction.cs
- code/src/Core/PostActions/PostActionFactory.cs
- code/src/UI/VisualStudio/VsGenShell.cs
- Add extension methods for common path operations
- Verify paths before starting generation
#2396 IContextProvider and GenContext improvements
> Issue2396 improvegencontext

- code/test/Templates.Test/CodeStyleEnforcementTests.cs
- templates/Uwp/_composition/_shared/Page.Camera.AddResource/Controls/CameraControl.xaml.cs
- templates/Uwp/_composition/_shared/Page.Camera.AddResource/Strings/en-us/Resources_postaction.resw
- templates/Uwp/_composition/_shared/Page.Camera.AddResourceVB/Controls/CameraControl.xaml.vb
- templates/Uwp/_composition/_shared/Page.Camera.AddResourceVB/Strings/en-us/Resources_postaction.resw
#2813 - CameraControl could throw exceptions
> Capture camera control exceptions

- templates/Uwp/Features/SuspendAndResume/Services/SuspendAndResumeService.cs
- templates/Uwp/Features/SuspendAndResumeVB/Services/SuspendAndResumeService.vb
#2794 - Exception closing app using unmodified SuspendAndResumeService - Unable to remove the file to be replaced
> Fix Suspend and Resume Service

- templates/Uwp/Projects/Default/wts.DefaultProject.csproj
- templates/Uwp/Projects/DefaultPrism/wts.DefaultProject.csproj
- templates/Uwp/Projects/DefaultVB/wts.DefaultProject.vbproj
- templates/Uwp/_composition/_shared/Project.AddCoreProject/Param_ProjectName.Core/Param_ProjectName.Core.csproj
- templates/Uwp/_composition/_shared/Project.AddCoreProjectVB/Param_ProjectName.Core/Param_ProjectName.Core.vbproj
Always add model folder to core project
#2252 Change basic output to generate multiple projects in a solution
> Always add model folder to core project

- templates/Uwp/Features/FeedbackHub.CaliburnMicro/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.CodeBehind/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.CodeBehindVB/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.MVVMBasic/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.MVVMBasicVB/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.MVVMLight/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.MVVMLightVB/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.Prism/.template.config/template.json
- templates/Uwp/Features/SettingsStorage/.template.config/template.json
- templates/Uwp/Features/SettingsStorageVB/.template.config/template.json
- templates/Uwp/Features/UserActivity.MVVMLight/.template.config/template.json
- templates/Uwp/Features/UserActivity.MVVMLight/Services/UserActivityService.Sample.cs
- templates/Uwp/Features/UserActivity.MVVMLightVB/.template.config/template.json
- templates/Uwp/Features/UserActivity.MVVMLightVB/Services/UserActivityService.Sample.vb
- templates/Uwp/Features/UserActivity.Prism/.template.config/template.json
- templates/Uwp/Features/UserActivity.Prism/Services/UserActivityService.Sample.cs
- templates/Uwp/Features/UserActivity/.template.config/template.json
- templates/Uwp/Features/UserActivity/Services/UserActivityService.Sample.cs
- templates/Uwp/Features/UserActivityVB/.template.config/template.json
- templates/Uwp/Features/UserActivityVB/Services/UserActivityService.Sample.vb
- templates/Uwp/Features/VSAppCenterAnalytics/.template.config/template.json
- templates/Uwp/Features/VSAppCenterAnalyticsVB/.template.config/template.json
- templates/Uwp/_composition/CaliburnMicro/Project.SplitView.TabbedNav/.template.config/template.json
- templates/Uwp/_composition/CodeBehind/Project.SplitView.TabbedNav/.template.config/template.json
- templates/Uwp/_composition/CodeBehind/Project.SplitView.TabbedNavVB/.template.config/template.json
- templates/Uwp/_composition/MVVMBasic/Project.SplitView.TabbedNav/.template.config/template.json
- templates/Uwp/_composition/MVVMBasic/Project.SplitView.TabbedNavVB/.template.config/template.json
- templates/Uwp/_composition/MVVMLight/Project.SplitView.TabbedNav/.template.config/template.json
- templates/Uwp/_composition/MVVMLight/Project.SplitView.TabbedNavVB/.template.config/template.json
- templates/Uwp/_composition/Prism/Project.SplitView.TabbedNav/.template.config/template.json
#2850 - Update nuget packages in generated projects to latest version
> Update nuget packages in generated projects to latest version

- templates/Uwp/_composition/MVVMLight/Page.MediaPlayer.AddViewModel/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/Uwp/_composition/MVVMLight/Page.MediaPlayer.AddViewModelVB/Views/wts.ItemNamePage_postaction.xaml.vb
#2785 -Page Navigation - Memory Leak
> Fix memory leak to Media Player Page in MVVMLight framework

- templates/Uwp/Features/UserActivity.MVVMLight/.template.config/template.json
- templates/Uwp/Features/UserActivity.MVVMLightVB/.template.config/template.json
- templates/Uwp/Features/UserActivity.Prism/.template.config/template.json
- templates/Uwp/Features/UserActivity/.template.config/template.json
- templates/Uwp/Features/UserActivityVB/.template.config/template.json
- templates/Uwp/Pages/Chart.CodeBehind/.template.config/template.json
- templates/Uwp/Pages/Chart.CodeBehindVB/.template.config/template.json
- templates/Uwp/Pages/Chart.Prism/.template.config/template.json
- templates/Uwp/Pages/Chart/.template.config/template.json
- templates/Uwp/Pages/ChartVB/.template.config/template.json
- templates/Uwp/Pages/Grid.CodeBehind/.template.config/template.json
- templates/Uwp/Pages/Grid.CodeBehindVB/.template.config/template.json
- templates/Uwp/Pages/Grid.Prism/.template.config/template.json
- templates/Uwp/Pages/Grid/.template.config/template.json
- templates/Uwp/Pages/GridVB/.template.config/template.json
#2850 - Update nuget packages in generated projects to latest version
> Update package version to AdaptiveCards and Telerik.UI

- templates/Uwp/Features/VSAppCenterAnalytics/.template.config/template.json
- templates/Uwp/Features/VSAppCenterAnalyticsVB/.template.config/template.json
Update AppCenter nugets to latest version
#2850 Update nuget packages in generated projects to latest version
> Update AppCenter nugets

- code/test/Templates.Test/App.config
- code/test/Templates.Test/Templates.Test.csproj
- docs/templates.md
- templates/Uwp/Features/SampleData.Prism/.template.config/template.json
- templates/Uwp/Features/SampleData/.template.config/template.json
- templates/Uwp/Features/SampleDataVB/.template.config/template.json
- templates/Uwp/Pages/Grid.Prism/.template.config/template.json
- templates/Uwp/Pages/ImageGallery.CodeBehindVB/Views/ImageGalleryViewPage.xaml.vb
- templates/Uwp/_composition/_shared/Page.Chart.SampleDataService/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.Chart.SampleDataServiceVB/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.ImageGallery/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.ImageGalleryVB/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.MasterDetail.SampleData/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.MasterDetail.SampleDataVB/.template.config/template.json
- Added documentation
- Fixed failing language comparison tests
#2252 Change basic output to multiproject
> Update documentation +  vb tests fixes

- templates/Uwp/_composition/_shared/Page.Blank.MasterDetail/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.Blank.MasterDetail/Views/wts.ItemNamePage_postaction.xaml
- templates/Uwp/_composition/_shared/Page.Blank.MasterDetailVB/.template.config/template.json
- templates/Uwp/_composition/_shared/Page.Blank.MasterDetailVB/Views/wts.ItemNamePage_postaction.xaml
Use inline back button on master detail page in blank project type #2873
> Inline back button on master detail page in blank project type

- code/src/Core/Gen/GenShell.cs
Report errors on missing core project in right click addition on 2.x projects
#2619 Support right click on 2.x projects
> Report errors on failing Right click addition on 2.x projects

- templates/Uwp/Projects/Default/wts.DefaultProject.csproj
- templates/Uwp/Projects/DefaultPrism/wts.DefaultProject.csproj
- templates/Uwp/Projects/DefaultVB/wts.DefaultProject.vbproj
> Fix wack tests

- specs/client-authentication-msal-example.md
Update and move Identity in apps specs doc
> Update and move Identity in apps specs doc

- code/src/Core/PostActions/Catalog/GenerateTestCertificatePostAction.cs
- code/test/Templates.Test/RunTests.bat
- Correct else syntax in batch file 
- Correct test certificate's path, when concatenating with relative path
#2931 Full test build failed
#2933 Dev-nightly: Addition of Test App features fails due to invalid path on TestCertificate
> Fixes for test features

- code/src/UI/VisualStudio/VsGenShell.cs
#2942 - dev-nightly: cannot add Core Test Feature
> Fix restore more that one nuget package in core project when generating.

- templates/Uwp/_composition/MVVMLight/Project._VB/Services/NavigationServiceEx.vb
- templates/Uwp/_composition/MVVMLight/Project._VB/Strings/en-us/Resources_postaction.resw
- templates/Uwp/_composition/MVVMLight/Project/Services/NavigationServiceEx.cs
- templates/Uwp/_composition/MVVMLight/Project/Strings/en-us/Resources_postaction.resw
Typo ExceptionNavigationServiceExPageUnknow -> ExceptionNavigationServiceExPageUnknown
> Typo correction

- code/src/UI/VisualStudio/RightClickActions.cs
- code/src/UI/VisualStudio/SolutionWizard.cs
#2934 - Prepare the extensions core project for migration to .net standard
> Update RemoteTemplatesSource call in release mode

- code/src/Core/Gen/GenComposer.cs
- docs/getting-started-endusers.md
- docs/projectTypes/menubar.md
- templates/Uwp/_composition/CodeBehind/Project.MenuBar/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/MVVMBasic/Project.MenuBar/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/MVVMLight/Project.MenuBar/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/Prism/Project.MenuBar/Views/ShellPage.xaml.cs
Add traditional Menu project type #2292
> MenuBar documentation

- code/src/Installer.2017/Installer.2017.csproj
Readd newtonsoft.json to vsix
#2934 Prepare the extensions core project for migration to .net standard
> Readd newtonsoft.json to vsix

- templates/Uwp/Features/FeedbackHub.CaliburnMicro/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.CodeBehind._VB/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.CodeBehind/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.MVVMBasic._VB/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.MVVMBasic/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.MVVMLight._VB/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.MVVMLight/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.Prism/.template.config/template.json
For #2971
Update to new version of NuGet package. Changes include a fix that was causing a crash for some users on 1809
> Update Microsoft.Services.Store.Engagement version

- code/tools/WtsTelemetry/WtsTelemetry/Services/QueryService.cs
- code/tools/WtsTelemetry/WtsTelemetry/WtsTelemetry.cs
#2953 - Update Telemetry report to include VB / C# usage
> Add programming languages to query

- templates/Uwp/Features/WinAppDriver._VB/Param_ProjectName.Tests.WinAppDriver/Param_ProjectName.Tests.WinAppDriver.vbproj
- templates/Uwp/Features/WinAppDriver/Param_ProjectName.Tests.WinAppDriver/Param_ProjectName.Tests.WinAppDriver.csproj
Fix namespace in winappdriver templates
#2980 Build dev.tests.full
> Fix build.tests.full

- templates/Uwp/Features/MultiView._VB/Services/ViewLifetimeControl.vb
- templates/Uwp/Features/MultiView._VB/Services/WindowManagerService.vb
- templates/Uwp/Features/MultiView/Services/ViewLifetimeControl.cs
- templates/Uwp/Features/MultiView/Services/WindowManagerService.cs
- templates/Uwp/_composition/_shared/Page.Ink.AddBasicInkServices._VB/Services/Ink/InkFileService.vb
- templates/Uwp/_composition/_shared/Page.Ink.AddBasicInkServices/Services/Ink/InkFileService.cs
Code smells in generated code #2871
> Unused local variables

- code/test/Templates.Test/BaseGenAndBuildFixture.cs
- code/tools/Localization/Logic/Routes.cs
#2958 - Split frameworks in frontendframeworks and backendframeworks
> Update localization tool to get frontendframeworks routes.

- templates/Uwp/_composition/CodeBehind/Project.MenuBar/Views/ShellPage.xaml
- templates/Uwp/_composition/CodeBehind/Project.MenuBar/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/MVVMBasic/Project.MenuBar/Views/ShellPage.xaml
- templates/Uwp/_composition/MVVMBasic/Project.MenuBar/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/MVVMLight/Project.MenuBar/Views/ShellPage.xaml
- templates/Uwp/_composition/MVVMLight/Project.MenuBar/Views/ShellPage.xaml.cs
Add traditional Menu project type #2292
> Fix Back tooltip

- templates/Uwp/Features/FirstUsePrompt._VB/.template.config/template.json
- templates/Uwp/Features/LiveTile._VB/.template.config/template.json
- templates/Uwp/Features/ToastNotifications._VB/.template.config/template.json
- templates/Uwp/Features/WhatsNewPrompt._VB/.template.config/template.json
- templates/Uwp/Pages/DataGrid.CodeBehind._VB/.template.config/template.json
- templates/Uwp/Pages/DataGrid._VB/.template.config/template.json
- templates/Uwp/Pages/MasterDetail.CodeBehind._VB/.template.config/template.json
- templates/Uwp/Pages/MasterDetail._VB/.template.config/template.json
Build dev.templates.tests.full_20190308.1 failed #2997
> tests fixes

- code/src/Core/Composition/QueryableProperty.cs
#2994 - Composition query $feature and $page always return false when no features/pages added
> Fix compare method in QueryableProperty

- code/src/UI/Launcher/WizardLauncher.cs
Correct NewFeature Telemetry report
#2983 NewFeature entry point is not reported correctly in telemetry
> Correct NewFeature Telemetry report

- code/test/Core.Test/Composition/CompositionQueryTest.cs
- code/test/Core.Test/Naming/NamingTests.cs
Add tests for latest core changes
#2994 Composition query $feature and $page always return false when no features/pages added
#1784 Some project names cause generated apps to not work
> Add tests for latest core changes

- code/src/Core/Gen/UserSelection.cs
#3001 - Refactor Core to return complete TemplateInfo when retrieving templates and light TemplateInfo on generation
> Remove Add UserSelectionItem method

- code/src/Core/Templates/TemplatesRepository.cs
- code/test/Core.Test/Localization/LocalizationTest.cs
- code/test/Core.Test/TestData/Templates/ProjectTemplate_FrontAndBack/.template.config/template.json
#3001 - Refactor Core to return complete TemplateInfo when retrieving templates and light TemplateInfo on generation
> Fix TemplatesRepository and templates test.

- code/src/Core/Gen/GenComposer.cs
- code/src/Core/Templates/TemplatesRepository.cs
#3001 - Refactor Core to return complete TemplateInfo when retrieving templates and light TemplateInfo on generation
> Support multiple project templates.

- code/test/Templates.Test/BuildTemplatesTests/BuildCaliburnMicroProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/BuildCodeBehindProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/BuildMVVMBasicProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/BuildMVVMLightProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/BuildPrismProjectTests.cs
- Separates OneByOne tests into its own execution set
- #3041 Execute OneByOne Tests in separate build
> Separate OneByOne Tests

- templates/Uwp/_composition/MVVMBasic/Project.MenuBar.AddMenuBarItem._VB/ViewModels/ShellViewModel_postaction.vb
- templates/Uwp/_composition/MVVMLight/Project.MenuBar.AddMenuBarItem._VB/ViewModels/ShellViewModel_postaction.vb
- Add missing whitelines to VB composition templates
- #3044 Build dev.tests.full failed
> Fix failed build

- templates/Uwp/_comp/CodeBehind/Feat.IdentityForcedLogin.SplitView.TabbedNav/Views/ShellPage$CleanOnLoaded_gpostaction.xaml.cs
- templates/Uwp/_comp/CodeBehind/Feat.IdentityOptionalLogin.MenuBar/.template.config/template.json
- templates/Uwp/_comp/CodeBehind/Feat.IdentityOptionalLogin.MenuBar/Views/ShellPage_postaction.xaml.cs
- templates/Uwp/_comp/CodeBehind/Feat.IdentityOptionalLogin.SplitView.TabbedNav/Views/ShellPage$CleanOnLoaded_gpostaction.xaml.cs
- templates/Uwp/_comp/CodeBehind/Feat.IdentityOptionalLogin.SplitView.TabbedNav/Views/ShellPage_postaction.xaml.cs
- templates/Uwp/_comp/MVVMBasic/Feat.IdentityForcedLogin.SplitView.TabbedNav/ViewModels/ShellViewModel$CleanOnLoaded_gpostaction.cs
- templates/Uwp/_comp/MVVMBasic/Feat.IdentityOptionalLogin.MenuBar/.template.config/template.json
- templates/Uwp/_comp/MVVMBasic/Feat.IdentityOptionalLogin.MenuBar/ViewModels/ShellViewModel_postaction.cs
- templates/Uwp/_comp/MVVMBasic/Feat.IdentityOptionalLogin.SplitView.TabbedNav/ViewModels/ShellViewModel$CleanOnLoaded_gpostaction.cs
- templates/Uwp/_comp/MVVMBasic/Feat.IdentityOptionalLogin.SplitView.TabbedNav/ViewModels/ShellViewModel_postaction.cs
- templates/Uwp/_comp/MVVMLight/Feat.IdentityForcedLogin.SplitView.TabbedNav/ViewModels/ShellViewModel$CleanOnLoaded_gpostaction.cs
- templates/Uwp/_comp/MVVMLight/Feat.IdentityOptionalLogin.MenuBar/.template.config/template.json
- templates/Uwp/_comp/MVVMLight/Feat.IdentityOptionalLogin.MenuBar/ViewModels/ShellViewModel_postaction.cs
- templates/Uwp/_comp/MVVMLight/Feat.IdentityOptionalLogin.SplitView.TabbedNav/ViewModels/ShellViewModel$CleanOnLoaded_gpostaction.cs
- templates/Uwp/_comp/MVVMLight/Feat.IdentityOptionalLogin.SplitView.TabbedNav/ViewModels/ShellViewModel_postaction.cs
- templates/Uwp/_comp/MVVMLight/Project.MenuBar/ViewModels/ShellViewModel.cs
Updates on Optional Login for MenuBar
Issue #292
> Updates on Optional Login for MenuBar

- templates/Uwp/Projects/Default._VB/Services/ActivationService.vb
- Renamed DefaultLaunchActivationHandler in vb project
- #3118 Template tests failed
> Fix failed tests

- templates/Uwp/Pages/ImageGallery.CodeBehind._VB/Views/ImageGalleryViewPage.xaml
It looks like this was my error when manually fixing some merge conflicts.
For #3126 #3127 & #3129
> Fix invalid xaml

- templates/Uwp/Features/SuspendAndResume._VB/Services/ActivationService_postaction.vb
> Fix VB error in Activation changes

- code/src/Installer/Installer.csproj
- Include System.IO.Packaging in vsix
- #3128 Vsix has to include System.IO.Packaging
> Include System.IO.Packaging in vsix

- docs/getting-started-developers.md
also changed the formatting on the relative code path to avoid it looking like a broken link
> fix broken image path

- docs/navigation-advanced.md
Update documentation for Navigation #3150
> Advanced Doc Updates for 3.3 version

- templates/Uwp/Features/ShareTarget.CodeBehind._VB/Views/ShareTargetFeaturePage.xaml.vb
- templates/Uwp/Features/ShareTarget.CodeBehind/Views/ShareTargetFeaturePage.xaml.cs
- templates/Uwp/Features/ShareTarget.Prism/ViewModels/ShareTargetFeatureViewModel.cs
- templates/Uwp/_comp/CaliburnMicro/Feat.ShareTarget/App_postaction.xaml.cs
- templates/Uwp/_comp/CaliburnMicro/Feat.ShareTarget/ViewModels/wts.ItemNameViewModel.cs
- templates/Uwp/_comp/MVVMBasic/Feat.ShareTarget._VB/ViewModels/wts.ItemNameViewModel.vb
- templates/Uwp/_comp/MVVMBasic/Feat.ShareTarget/ViewModels/wts.ItemNameViewModel.cs
- templates/Uwp/_comp/MVVMLight/Feat.ShareTarget._VB/ViewModels/wts.ItemNameViewModel.vb
- templates/Uwp/_comp/MVVMLight/Feat.ShareTarget/ViewModels/wts.ItemNameViewModel.cs
Change size of Share target window #2996
> ShareTarget doc url update

- _utils/code-snippets.json
- docs/templates.md
> VS Code Snippets

- code/src/UI/Views/Common/ErrorDialog.xaml
- code/src/UI/Views/Common/QuestionDialogWindow.xaml
- code/src/UI/Views/Common/TemplateInfoPage.xaml
Review steps in the wizard #2841
> Fixes on Wizard

- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
- code/src/UI/ViewModels/NewItem/MainViewModel.cs
Review steps in the wizard #2841
> New String Resources

- code/tools/Localization/Extensions/JsonExtensions.cs
- code/tools/Localization/Localization.csproj
- code/tools/Localization/Logic/LocalizableItemsExtractor.cs
- code/tools/Localization/Logic/LocalizableItemsGenerator.cs
- code/tools/Localization/Logic/LocalizableItemsVerificator.cs
- code/tools/Localization/Logic/LocalizationTool.cs
- code/tools/Localization/Logic/OriginalLocalizableItemsExtractor.cs
- code/tools/Localization/Logic/RightClickCommandGenerator.cs
- code/tools/Localization/Logic/Routes.cs
- code/tools/Localization/Logic/ValidateLocalizableExtractor.cs
#2841 - Review steps in the wizard
> Update localization tool

- templates/Uwp/Services/IdentityForcedLogin._VB/.template.config/template.json
- templates/Uwp/Services/IdentityForcedLogin/.template.config/template.json
Add missing dependency to AppDotConfig
#3218 One by one tests failed
> Add dependency on AppDotConfig

- code/tools/WtsTelemetry/WtsTelemetry/Helpers/StringHelper.cs
- code/tools/WtsTelemetry/WtsTelemetry/Services/QueryService.cs
- code/tools/WtsTelemetry/WtsTelemetry/WtsTelemetry.cs
#2841 - Review steps in the wizard
> Update telemetry tool to get Services and Testing steps info

- templates/Uwp/Features/VSAppCenterAnalytics._VB/.template.config/template.json
- templates/Uwp/Features/VSAppCenterAnalytics/.template.config/template.json
- templates/Uwp/Testing/UnitTests.Core.MSTest._VB/.template.config/template.json
- templates/Uwp/Testing/UnitTests.Core.MSTest/.template.config/template.json
- templates/Uwp/Testing/UnitTests.Core.NUnit._VB/.template.config/template.json
- templates/Uwp/Testing/UnitTests.Core.NUnit/.template.config/template.json
- templates/Uwp/Testing/UnitTests.Core.xUnit._VB/.template.config/template.json
- templates/Uwp/Testing/UnitTests.Core.xUnit/.template.config/template.json
Update nuget packages in generated code
#3104 Update nuget packages
> Update nuget packages in generated code

- templates/Uwp/Services/HttpDataService._VB/Param_ProjectName.Core/Services/HttpDataService.vb
- templates/Uwp/Services/HttpDataService/Param_ProjectName.Core/Services/HttpDataService.cs
for #3182 (Http Data Service enhancements)
- Add comments (with link)
- Add extra method variants
- Add VB & C# versions of changes
> Add PostAsync and PutAsJsonAsync to HttpDataService

- code/src/UI/ViewModels/NewProject/UserSelectionViewModel.cs
- templates/Uwp/Features/AppDotConfig._VB/.template.config/icon.xaml
- templates/Uwp/Features/AppDotConfig/.template.config/icon.xaml
Dev-nightly: When switching between Identity templates dependencies are not added in again #3232
> Issue3232 dependencies

- templates/Uwp/Pages/TreeView.CodeBehind._VB/Views/wts.ItemNamePage.xaml
- templates/Uwp/Pages/TreeView.CodeBehind/Views/wts.ItemNamePage.xaml
- templates/Uwp/Pages/TreeView.Prism/Param_ProjectName/Views/wts.ItemNamePage.xaml
- templates/Uwp/Pages/TreeView._VB/Views/wts.ItemNamePage.xaml
- templates/Uwp/Pages/TreeView/Views/wts.ItemNamePage.xaml
- templates/Uwp/Services/SampleData.Prism/Param_ProjectName.Core/Models/SampleCompany.cs
- templates/Uwp/Services/SampleData.Prism/Param_ProjectName.Core/Models/SampleOrder.cs
- templates/Uwp/Services/SampleData.Prism/Param_ProjectName.Core/Models/SampleOrderDetail.cs
- templates/Uwp/Services/SampleData.Prism/Param_ProjectName.Core/Services/SampleDataService.cs
- templates/Uwp/Services/SampleData._VB/Param_ProjectName.Core/Models/SampleCompany.vb
- templates/Uwp/Services/SampleData._VB/Param_ProjectName.Core/Models/SampleOrder.vb
- templates/Uwp/Services/SampleData._VB/Param_ProjectName.Core/Models/SampleOrderDetail.vb
- templates/Uwp/Services/SampleData._VB/Param_ProjectName.Core/Services/SampleDataService.vb
- templates/Uwp/Services/SampleData/Param_ProjectName.Core/Models/SampleCompany.cs
- templates/Uwp/Services/SampleData/Param_ProjectName.Core/Models/SampleOrder.cs
- templates/Uwp/Services/SampleData/Param_ProjectName.Core/Models/SampleOrderDetail.cs
- templates/Uwp/Services/SampleData/Param_ProjectName.Core/Services/SampleDataService.cs
- templates/Uwp/Services/SqlServerDataService.Prism/Param_ProjectName.Core/Services/SqlServerDataService.cs
- templates/Uwp/Services/SqlServerDataService._VB/Param_ProjectName.Core/Services/SqlServerDataService.vb
- templates/Uwp/Services/SqlServerDataService/Param_ProjectName.Core/Services/SqlServerDataService.cs
- templates/Uwp/_comp/_shared/Page.ImageGallery._VB/Param_ProjectName.Core/Services/SampleDataService$wts.ItemName_gpostaction.vb
- templates/Uwp/_comp/_shared/Test.UnitTests.Core.SampleData.ImageGallery.MSTest._VB/Param_ProjectName.Core.Tests.MSTest/Tests_postaction.vb
- templates/Uwp/_comp/_shared/Test.UnitTests.Core.SampleData.ImageGallery.NUnit._VB/Param_ProjectName.Core.Tests.NUnit/Tests_postaction.vb
- templates/Uwp/_comp/_shared/Test.UnitTests.Core.SampleData.ImageGallery.xUnit._VB/Param_ProjectName.Core.Tests.xUnit/Tests_postaction.vb
Issues
Treeview based on master/detail Page #1246
SQL Server Support #900
> SQL Data with companies, orders and products

- templates/Uwp/Services/WebApi.Prism/Param_ProjectName.Core/Services/ISampleDataService$MasterDetailView_gpostaction.cs
- templates/Uwp/Services/WebApi.Prism/Param_ProjectName.Core/Services/SampleDataService$MasterDetailView_gpostaction.cs
- templates/Uwp/Services/WebApi.Prism/Param_ProjectName.WebApi/Models/ItemRepository.cs
- templates/Uwp/Services/WebApi/Param_ProjectName.Core/Services/SampleDataService$wts.ItemName_gpostaction.cs
- templates/Uwp/Services/WebApi/Param_ProjectName.WebApi/Models/ItemRepository.cs
- templates/Uwp/_comp/_shared/Services.WebApi/Param_ProjectName.WebApi/Controllers/ItemController.cs
- templates/Uwp/_comp/_shared/Services.WebApi/Param_ProjectName.WebApi/Models/IItemRepository.cs
- Change webapi to work with SampleCompanies and add endpoint for getting SampleOrders
- #1246 TreeView page
> Changes to WebAPI to provide data for TreeView

- code/src/UI/Services/OrderingService.cs
Dev-nightly: Cannot reorder pages #3245
> Fix page ordering

- code/src/UI/ViewModels/NewProject/UserSelectionGroup.cs
- code/src/UI/ViewModels/NewProject/UserSelectionViewModel.cs
- code/src/UI/Views/NewProject/MainPage.xaml
Dev-nightly: Wizard fails when adding and removing WebAPI #3244
> Fix remove templates in wizard

- templates/Uwp/_comp/CodeBehind/Service.IdentityForcedLogin.SplitView._VB/Views/ShellPage_postaction.xaml
- templates/Uwp/_comp/CodeBehind/Service.IdentityForcedLogin.SplitView/Views/ShellPage_postaction.xaml
- templates/Uwp/_comp/CodeBehind/Service.IdentityOptionalLogin.SplitView._VB/Views/ShellPage_postaction.xaml
- templates/Uwp/_comp/CodeBehind/Service.IdentityOptionalLogin.SplitView/Views/ShellPage_postaction.xaml
- templates/Uwp/_comp/MVVMBasic/Service.IdentityForcedLogin.SplitView._VB/Views/ShellPage_postaction.xaml
- templates/Uwp/_comp/MVVMBasic/Service.IdentityForcedLogin.SplitView/Views/ShellPage_postaction.xaml
- templates/Uwp/_comp/MVVMBasic/Service.IdentityOptionalLogin.SplitView._VB/Views/ShellPage_postaction.xaml
- templates/Uwp/_comp/MVVMBasic/Service.IdentityOptionalLogin.SplitView/Views/ShellPage_postaction.xaml
- templates/Uwp/_comp/MVVMLight/Service.IdentityForcedLogin.SplitView._VB/Views/ShellPage_postaction.xaml
- templates/Uwp/_comp/MVVMLight/Service.IdentityForcedLogin.SplitView/Views/ShellPage_postaction.xaml
- templates/Uwp/_comp/MVVMLight/Service.IdentityOptionalLogin.SplitView._VB/Views/ShellPage_postaction.xaml
- templates/Uwp/_comp/MVVMLight/Service.IdentityOptionalLogin.SplitView/Views/ShellPage_postaction.xaml
- templates/Uwp/_comp/Prism/Service.IdentityForcedLogin.SplitView/Views/ShellPage_postaction.xaml
- templates/Uwp/_comp/Prism/Service.IdentityOptionalLogin.SplitView/Views/ShellPage_postaction.xaml
Dev-nightly: Username on NavView for identity features is misaligned #3248
> Fix Margin for Identity user in NavView

- templates/Uwp/Pages/TreeView.Prism/Param_ProjectName/Properties/Default_postaction.rd.xml
- templates/Uwp/Pages/TreeView._VB/My Project/Default_postaction.rd.xml
- templates/Uwp/Pages/TreeView/Properties/Default_postaction.rd.xml
Treeview based on master/detail Page #1246
> Add Directive into Default.rd.xml for TreeView page templates

- templates/Uwp/_comp/CaliburnMicro/Project.SplitView.TabbedNav/Helpers/NavHelper.cs
- templates/Uwp/_comp/CodeBehind/Project.SplitView.TabbedNav._VB/Helpers/NavHelper.vb
- templates/Uwp/_comp/CodeBehind/Project.SplitView.TabbedNav/Helpers/NavHelper.cs
- templates/Uwp/_comp/MVVMBasic/Project.SplitView.TabbedNav._VB/Helpers/NavHelper.vb
- templates/Uwp/_comp/MVVMBasic/Project.SplitView.TabbedNav/Helpers/NavHelper.cs
- templates/Uwp/_comp/MVVMLight/Project.SplitView.TabbedNav._VB/Helpers/NavHelper.vb
- templates/Uwp/_comp/MVVMLight/Project.SplitView.TabbedNav/Helpers/NavHelper.cs
- templates/Uwp/_comp/Prism/Project.SplitView.TabbedNav/Helpers/NavHelper.cs
How to invoke NavigationView.MenuItems added dynamically #3112
> Add comments to explain how to call NavHelper from Xaml and Code

- code/test/UI.Test/NewProjectTest.cs
Add test for
Dev-nightly: Wizard fails when adding and removing WebAPI #3244
> Issue3244 tests

- templates/Uwp/_comp/_shared/Page.SplitView.TreeView._VB/.template.config/template.json
- templates/Uwp/_comp/_shared/Page.SplitView.TreeView/.template.config/template.json
Treeview based on master/detail Page #1246
> Fix prism treeview on SplitView

- templates/Uwp/Features/FeedbackHub.CaliburnMicro/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.CodeBehind._VB/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.CodeBehind/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.MVVMBasic._VB/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.MVVMBasic/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.MVVMLight._VB/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.MVVMLight/.template.config/template.json
- templates/Uwp/Features/FeedbackHub.Prism/.template.config/template.json
- templates/Uwp/Features/StoreNotifications.Prism/.template.config/template.json
- templates/Uwp/Features/StoreNotifications._VB/.template.config/template.json
- templates/Uwp/Features/StoreNotifications/.template.config/template.json
For #3206
This is an issue that effects any app including the `Feedback Hub Link` or `Dev Center Notifications` features and are submitted to the store.
Marking for milestone 3.3 as this is a potentially critical bug with generated code.
> Fix casing issue in SDKReferences

- docs/PULL_REQUEST_TEMPLATE.md
Added note about updating important documentation.
Prompted by #3286
> Add note for updating the 'getting started' doc

- templates/Uwp/Projects/Default.CaliburnMicro/wts.DefaultProject.csproj
- templates/Uwp/Projects/Default._VB/wts.DefaultProject.vbproj
- templates/Uwp/Projects/Default/wts.DefaultProject.csproj
- templates/Uwp/Projects/DefaultPrism/wts.DefaultProject.csproj
- templates/Uwp/Testing/UnitTests.App.MSTest._VB/Param_ProjectName.Tests.MSTest/Param_ProjectName.Tests.MSTest.vbproj
- templates/Uwp/Testing/UnitTests.App.MSTest/Param_ProjectName.Tests.MSTest/Param_ProjectName.Tests.MSTest.csproj
- templates/Uwp/Testing/UnitTests.App.xUnit._VB/Param_ProjectName.Tests.xUnit/Param_ProjectName.Tests.xUnit.vbproj
- templates/Uwp/Testing/UnitTests.App.xUnit/Param_ProjectName.Tests.xUnit/Param_ProjectName.Tests.xUnit.csproj
Update TargetPlatformVersion to 18362 #3259
> Set target version to 10.0.18362.0

- code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyTests.cs
As this requires Target Platform Version 10.0.18362.0
> Exclude TreeView from Legacy Tests

- templates/Uwp/Features/3DLauncher._VB/.template.config/template.json
- templates/Uwp/Features/3DLauncher/.template.config/template.json
- Add right click enabled for 3D Launcher
#3095 3D Launcher not available for right click
> Add right click enabled for 3D Launcher

- code/test/Fakes/Solution/FakeSolution.cs
- code/test/Fakes/Solution/UwpSolutionTemplate.txt
- Set build and deploy actions for 'Any CPU' config
#2880 Set build and deploy actions for 'Any CPU' config
> Set build and deploy actions for 'Any CPU' config

- code/src/Installer/cs-CZ/Extension.vsixlangpack
- code/src/Installer/de-DE/Extension.vsixlangpack
- code/src/Installer/es-ES/Extension.vsixlangpack
- code/src/Installer/fr-FR/Extension.vsixlangpack
- code/src/Installer/it-IT/Extension.vsixlangpack
- code/src/Installer/ja-JP/Extension.vsixlangpack
- code/src/Installer/ko-KR/Extension.vsixlangpack
- code/src/Installer/pl-PL/Extension.vsixlangpack
- code/src/Installer/pt-BR/Extension.vsixlangpack
- code/src/Installer/ru-RU/Extension.vsixlangpack
- code/src/Installer/source.extension.vsixmanifest
- code/src/Installer/tr-TR/Extension.vsixlangpack
- code/src/Installer/zh-CN/Extension.vsixlangpack
- code/src/Installer/zh-TW/Extension.vsixlangpack
- Updated vsix description
- #3292 Update description shown in extension gallery
> Updated vsix description

- templates/Uwp/Pages/TabView.CodeBehind._VB/My Project/Default_postaction.rd.xml
- templates/Uwp/Pages/TabView.CodeBehind/Properties/Default_postaction.rd.xml
- templates/Uwp/Pages/TabView.Prism/Properties/Default_postaction.rd.xml
- templates/Uwp/Pages/TabView._VB/My Project/Default_postaction.rd.xml
- templates/Uwp/Pages/TabView/Properties/Default_postaction.rd.xml
> Add release execution directives

- .github/ISSUE_TEMPLATE/feature_request.md
For https://github.com/microsoft/WindowsTemplateStudio/issues/3289
> Update issue templates (feature proposal)

- .github/ISSUE_TEMPLATE/bug_report.md
> Update issue templates (bug report)

- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
- code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyFixture.cs
- code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyTests.cs
- templates/Uwp/Services/SqlServerDataService.Prism/Param_ProjectName/Properties/Default_postaction.rd.xml
- templates/Uwp/Services/SqlServerDataService._VB/Param_ProjectName/My Project/Default_postaction.rd.xml
- templates/Uwp/Services/SqlServerDataService/Param_ProjectName/Properties/Default_postaction.rd.xml
- templates/Uwp/_comp/_shared/Service.IdentityCommon._VB/Param_ProjectName/My Project/Default_postaction.rd.xml
- templates/Uwp/_comp/_shared/Service.IdentityCommon/Param_ProjectName/Properties/Default_postaction.rd.xml
-  Change runtime directives for System.Configuration.ConfigurationManager Version 4.6
- Add missing resource language variations 
- Fixed LegacyTests to sync VB templates
- #3328 Update nuget packages to latest version
> Issue3328 systemconfiguration

- code/test/Templates.Test/BuildTemplatesTests/BuildCaliburnMicroProjectTests.cs
> Fix caliburn micro tests

- templates/Uwp/Projects/Default.CaliburnMicro/wts.DefaultProject.csproj
- templates/Uwp/Projects/Default._VB/wts.DefaultProject.vbproj
- templates/Uwp/Projects/Default/wts.DefaultProject.csproj
- templates/Uwp/Projects/DefaultPrism/wts.DefaultProject.csproj
- templates/Uwp/Testing/UnitTests.App.MSTest._VB/Param_ProjectName.Tests.MSTest/Param_ProjectName.Tests.MSTest.vbproj
- templates/Uwp/Testing/UnitTests.App.MSTest/Param_ProjectName.Tests.MSTest/Param_ProjectName.Tests.MSTest.csproj
- templates/Uwp/Testing/UnitTests.App.xUnit._VB/Param_ProjectName.Tests.xUnit/Param_ProjectName.Tests.xUnit.vbproj
- templates/Uwp/Testing/UnitTests.App.xUnit/Param_ProjectName.Tests.xUnit/Param_ProjectName.Tests.xUnit.csproj
- Updated Microsoft.NETCore.UniversalWindowsPlatform to version 6.2.9
- #3355 Updated Microsoft.NETCore.UniversalWindowsPlatform to version 6.2.9
> Updated Microsoft.NETCore.UniversalWindowsPlatform to version 6.2.9

- code/src/UI/ViewModels/Common/WizardStatus.cs
- Updated issue template in wizard
- #3289 Have separate templates for bugs and new features
> Updated issue template in wizard

- docs/getting-started-endusers.md
- docs/services/readme.md
- docs/services/secured-web-api.md
- templates/Uwp/Services/SecuredWebAPI/.template.config/template.json
- templates/Uwp/Services/SecuredWebApi.CodeBehind/.template.config/template.json
- templates/Uwp/Services/SecuredWebApi.Prism/.template.config/template.json
- templates/Uwp/Services/SqlServerDataService.Prism/.template.config/template.json
- templates/Uwp/Services/SqlServerDataService/.template.config/template.json
- templates/Uwp/_comp/_shared/Services.SecuredWebApi/Param_ProjectName.WebApi/Extensions/ServiceCollectionExtensions.cs
- Added secured web api docs
- Added missing links to overview pages
- #3313 Review docs before release
> Issue3313 review docs

- templates/Uwp/Services/SecuredWebAPI/.template.config/template.json
- templates/Uwp/Services/SecuredWebApi.CodeBehind/.template.config/template.json
- templates/Uwp/Services/SecuredWebApi.Prism/.template.config/template.json
Requirements of Secured Web API were accidentially overridden by translated files, 
adding them back in now.
#3397 Dev version build failed
> Add requirements back in

- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
- code/src/UI/ViewModels/Common/BaseMainViewModel.cs
- code/src/UI/ViewModels/Common/WizardStatus.cs
- code/src/UI/Views/NewProject/MainPage.xaml
Error message for WPF entry point in VS 2017 #3372
> Error message for WPF entry point in VS 2017

- code/src/UI/VisualStudio/RightClickActions.cs
- code/src/UI/VisualStudio/VsGenShell.cs
- code/test/Fakes/FakeGenShell.cs
- code/test/VsEmulator/Main/GeneratedProjectInfo.cs
Get main project guid by name
Update submodule to add platform to project related events
#3429 WPF telemetry
> Issue3429 wpftelemetry

- docs/features/suspend-and-resume.md
- If you've changed the UI:
- If you've included a new template:
- Be sure it's included in the list on [this getting started doc](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/getting-started-endusers.md).
- Have docs been …
> typo(?) Data.xaml.cs changed to DataPage.xaml.cs

- code/AzFunc.sln
- code/tools/WtsTelemetry/WtsTelemetry/Services/MarkdownBuilder.cs
- code/tools/WtsTelemetry/WtsTelemetry/Services/QueryService.cs
- code/tools/WtsTelemetry/WtsTelemetry/WtsTelemetry.cs
- Change telemetry service to report project related telemetry by platform
- #3429 Review telemetry for WPF
> Report project related telemetry by platform

- templates/Wpf/Projects/Default.Prism/.template.config/template.json
- templates/Wpf/Projects/Default/.template.config/template.json
Update MahApps.Metro NuGet version
Create WPF Templates #3370
> Update MahApps.Metro NuGet version

- templates/Wpf/Features/MSIXPackaging/.template.config/template.json
- templates/Wpf/Features/MSIXPackaging/Param_ProjectName.Packaging/Package.appxmanifest
#3370 WPF Templates
Add GenInfo to MSIX App Manifest
> Add GenInfo to MSIX App Manifest

- templates/Uwp/Features/3DLauncher._VB/Package_postaction.appxmanifest
- templates/Uwp/Features/3DLauncher/Package_postaction.appxmanifest
- templates/Uwp/Features/CommandLine.Prism/Package_postaction.appxmanifest
- templates/Uwp/Features/CommandLine._VB/Package_postaction.appxmanifest
- templates/Uwp/Features/CommandLine/Package_postaction.appxmanifest
- templates/Uwp/Features/MultiInstanceBasic._VB/Package_postaction.appxmanifest
- templates/Uwp/Features/MultiInstanceBasic/Package_postaction.appxmanifest
- templates/Uwp/Features/WebToAppLink.Prism/Package_postaction.appxmanifest
- templates/Uwp/Features/WebToAppLink._VB/Package_postaction.appxmanifest
- templates/Uwp/Features/WebToAppLink/Package_postaction.appxmanifest
- templates/Uwp/_comp/Prism/Service.IdentityCommon/Param_ProjectName/Package_postaction.appxmanifest
- templates/Uwp/_comp/_shared/Feat.DeepLinking.AddLogoTextsAndAppxManifest._VB/Package_postaction.appxmanifest
- templates/Uwp/_comp/_shared/Feat.DeepLinking.AddLogoTextsAndAppxManifest/Package_postaction.appxmanifest
- templates/Uwp/_comp/_shared/Service.IdentityCommon._VB/Param_ProjectName/Package_postaction.appxmanifest
- templates/Uwp/_comp/_shared/Service.IdentityCommon/Param_ProjectName/Package_postaction.appxmanifest
Add Ignorable Namespaces in Manifest.appxpackage postactions.
Postaction refactor #3256
> Ignorable Namespaces

- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
- code/src/UI/ViewModels/Common/BaseMainViewModel.cs
Create WPF Entry Point for vsix #3372
> Update .NetCore on VS2017 error message

- templates/Wpf/Features/MSIXPackaging/Param_ProjectName.Packaging/Package.appxmanifest
- templates/Wpf/_comp/Prism/Project.MenuBar.AddMenuItem.Settings/ViewModels/ShellViewModel_postaction.cs
- templates/Wpf/_comp/Prism/Project.MenuBar.AddMenuItem.Settings/Views/ShellWindow_postaction.xaml
- templates/Wpf/_comp/Prism/Project.MenuBar.AddMenuItem/Views/ShellWindow_postaction.xaml
- templates/Wpf/_comp/Prism/Project.MenuBar/.template.config/template.json
- templates/Wpf/_comp/Prism/Project.MenuBar/App_postaction.xaml.cs
- templates/Wpf/_comp/Prism/Project.MenuBar/Contracts/Services/IRightPaneService.cs
- templates/Wpf/_comp/Prism/Project.MenuBar/Services/RightPaneService.cs
- templates/Wpf/_comp/Prism/Project.MenuBar/Views/ShellWindow.xaml
- templates/Wpf/_comp/Prism/Project.MenuBar/Views/ShellWindow.xaml.cs
- templates/Wpf/_comp/Prism/Project.Ribbon/.template.config/template.json
- templates/Wpf/_comp/Prism/Project.Ribbon/App_postaction.xaml.cs
- templates/Wpf/_comp/Prism/Project.Ribbon/Contracts/Services/IRightPaneService.cs
- templates/Wpf/_comp/Prism/Project.Ribbon/Services/RightPaneService.cs
- templates/Wpf/_comp/Prism/Project.Ribbon/Views/ShellWindow.xaml.cs
- templates/Wpf/_comp/_shared/Page.WebView.MenuBar/.template.config/template.json
- templates/Wpf/_comp/_shared/Page.WebView.MenuBar/ViewModels/wts.ItemNameViewModel_postaction.cs
- templates/Wpf/_comp/_shared/Project.MenuBar.AddMenuItem.Settings/Views/ShellWindow_postaction.xaml
- templates/Wpf/_comp/_shared/Project.MenuBar.AddMenuItem/Views/ShellWindow_postaction.xaml
- templates/Wpf/_comp/_shared/Project.MenuBar/Services/RightPaneService.cs
- templates/Wpf/_comp/_shared/Project.MenuBar/Views/ShellWindow.xaml
- templates/Wpf/_comp/_shared/Project.Ribbon/Contracts/Services/IRightPaneService.cs
- templates/Wpf/_comp/_shared/Project.Ribbon/Services/RightPaneService.cs
Dev-nightly: Settings page is not closed hitting menu item in WPF MenuBar project #3450
> RightPane over the MenuBar

- README.md
> Correct supported version in README.md

- docs/getting-started-extension.md
> Update min target version in docs

- templates/Wpf/_comp/MVVMBasic/Project/Views/ShellWindow_postaction.xaml.cs
- templates/Wpf/_comp/Prism/Project.Ribbon.AddBackstageTabItem.Settings/Views/ShellWindow_postaction.xaml
- templates/Wpf/_comp/Prism/Project.Ribbon/.template.config/template.json
- templates/Wpf/_comp/Prism/Project.Ribbon/Behaviors/RibbonTabsBehavior.cs
- templates/Wpf/_comp/Prism/Project.Ribbon/Views/ShellWindow.xaml
- templates/Wpf/_comp/Prism/Project.Ribbon/Views/ShellWindow.xaml.cs
- templates/Wpf/_comp/_shared/Project.Ribbon.AddBackstageTabItem.Settings/Views/ShellWindow_postaction.xaml
- templates/Wpf/_comp/_shared/Project.Ribbon/.template.config/template.json
- templates/Wpf/_comp/_shared/Project.Ribbon/Behaviors/RibbonTabsBehavior.cs
- templates/Wpf/_comp/_shared/Project.Ribbon/Views/ShellWindow.xaml
- templates/Wpf/_comp/_shared/Project.Ribbon/Views/ShellWindow.xaml.cs
Feedback requested for WPF mockup (MMVMBasic + Ribbon) #3364
> Add Ribbon team feedback

- docs/templates.md
- Correct spelling errors
- Add more info to naming config docs
> Add more info to naming config docs

- templates/Wpf/Features/MSIXPackaging/.template.config/template.json
- templates/Wpf/Pages/MasterDetail/Param_ProjectName/Views/wts.ItemNamePage.xaml
- templates/Wpf/Pages/Settings/Views/wts.ItemNamePage.xaml
- templates/Wpf/Pages/WebView/Strings/Resources_postaction.resx
- templates/Wpf/Pages/WebView/Views/wts.ItemNamePage.xaml
- templates/Wpf/_comp/Prism/Project.Blank/Views/ShellWindow.xaml
- templates/Wpf/_comp/Prism/Project.MenuBar.AddMenuItem.Settings/Views/ShellWindow_postaction.xaml
- templates/Wpf/_comp/Prism/Project.MenuBar.AddMenuItem/Views/ShellWindow_postaction.xaml
- templates/Wpf/_comp/Prism/Project.MenuBar/Strings/Resources_postaction.resx
- templates/Wpf/_comp/Prism/Project.MenuBar/Views/ShellWindow.xaml
- templates/Wpf/_comp/Prism/Project.Ribbon/Views/ShellWindow.xaml
- templates/Wpf/_comp/Prism/Project.SplitView/Views/ShellWindow.xaml
- templates/Wpf/_comp/_shared/Project.Blank/Views/ShellWindow.xaml
- templates/Wpf/_comp/_shared/Project.MenuBar.AddMenuItem.Settings/Views/ShellWindow_postaction.xaml
- templates/Wpf/_comp/_shared/Project.MenuBar.AddMenuItem/Views/ShellWindow_postaction.xaml
- templates/Wpf/_comp/_shared/Project.MenuBar.AddMenuItemResources.Settings/Strings/Resources_postaction.resx
- templates/Wpf/_comp/_shared/Project.MenuBar/Strings/Resources_postaction.resx
- templates/Wpf/_comp/_shared/Project.MenuBar/Views/ShellWindow.xaml
- templates/Wpf/_comp/_shared/Project.Ribbon/Views/ShellWindow.xaml
- templates/Wpf/_comp/_shared/Project.SplitView/Views/ShellWindow.xaml
> Accessibility for WPF

- code/src/Installer/source.extension.vsixmanifest
Add WPF to VSIX description
#3372 Create WPF entry point for VSIX
> Add WPF to VSIX description

- docs/UWP/getting-started-endusers.md
- Fix broken link
- #3428 Docs for WPF
> fix broken links in docs

- code/src/UI/ViewModels/Common/BaseMainViewModel.cs
- code/src/UI/ViewModels/Common/WizardStatus.cs
Do not sync WPF templates on VS2017
#3372 Create VSIX entry point for WPF
> Do not sync WPF templates on VS2017

- code/test/Fakes/MSBuild/FakeMsBuildProject.cs
- code/test/Templates.Test/BaseGenAndBuildTests.cs
- code/test/Templates.Test/BuildRightClickWithLegacy/Uwp/BuildRightClickWithLegacyCSharpCollection.cs
- code/test/Templates.Test/BuildRightClickWithLegacy/Uwp/BuildRightClickWithLegacyCSharpFixture.cs
- code/test/Templates.Test/BuildRightClickWithLegacy/Uwp/BuildRightClickWithLegacyCSharpTests.cs
- code/test/Templates.Test/BuildRightClickWithLegacy/Uwp/BuildRightClickWithLegacyVBCollection.cs
- code/test/Templates.Test/BuildRightClickWithLegacy/Uwp/BuildRightClickWithLegacyVBFixture.cs
- code/test/Templates.Test/BuildRightClickWithLegacy/Uwp/BuildRightClickWithLegacyVBTests.cs
- code/test/Templates.Test/Templates.Test.csproj
- Ensure newer nugets are added before others using the emulator
- #3525 dev.template.tests failed
> Issue3525 fixlegacytests

- templates/Uwp/Pages/ContentGrid.CaliburnMicro/Views/ContentGridViewDetailPage.xaml
- templates/Uwp/Pages/ContentGrid.CodeBehind._VB/Views/ContentGridViewDetailPage.xaml
- templates/Uwp/Pages/ContentGrid.CodeBehind/Views/ContentGridViewDetailPage.xaml
- templates/Uwp/Pages/ContentGrid.Prism/Param_ProjectName/Views/ContentGridViewDetailPage.xaml
- templates/Uwp/Pages/ContentGrid._VB/Views/ContentGridViewDetailPage.xaml
- templates/Uwp/Pages/ContentGrid/Views/ContentGridViewDetailPage.xaml
- templates/Uwp/_comp/CaliburnMicro/Page.ContentGrid.Blank/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/CaliburnMicro/Page.ContentGrid.SplitView.TabbedNav/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/CodeBehind/Page.ContentGrid.Blank.MenuBar._VB/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/CodeBehind/Page.ContentGrid.Blank.MenuBar/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/CodeBehind/Page.ContentGrid.SplitView.TabbedNav._VB/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/CodeBehind/Page.ContentGrid.SplitView.TabbedNav/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/Prism/Page.ContentGrid.Blank.MenuBar/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/Prism/Page.ContentGrid.SplitView.TabbedNav/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/_shared/Page.ContentGrid.Blank.MenuBar._VB/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/_shared/Page.ContentGrid.Blank.MenuBar/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/_shared/Page.ContentGrid.SplitView.TabbedNav._VB/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/_shared/Page.ContentGrid.SplitView.TabbedNav/Views/wts.ItemNameDetailPage_postaction.xaml
Generated Content Grid Page Does Not Scroll #3493
> Add Scroll in ContenGrid detail page

- code/src/Installer/Commands/RelayCommandPackage.cs
- code/src/UI/Services/ValidationService.cs
- code/src/UI/ViewModels/Common/DataItems/BasicInfoViewModel.cs
- code/src/UI/ViewModels/Common/DataItems/TemplateInfoViewModel.cs
- code/src/UI/ViewModels/NewItem/MainViewModel.cs
- code/src/UI/ViewModels/NewItem/TemplateSelectionViewModel.cs
- code/src/UI/VisualStudio/RightClickActions.cs
- code/src/UI/VisualStudio/VsGenShell.cs
- code/test/VsEmulator/Main/GeneratedProjectInfo.cs
- Ensure ContextInitialization for right click in VSIX and emulator
- Fix name validation in right click 
- Fix required sdk check in right click
#3375 Fix right click
> Issue3375 fixrightclick

- code/src/UI/Services/BreakingChangesValidatorService.cs
- code/src/UI/Services/ProjectConfigInfoService.cs
- code/src/UI/Validators/HasHamburgerMenuValidator.cs
- code/src/UI/Validators/HasOldMvvmLightLocatorValidator.cs
- code/src/UI/Validators/HasOldNavigationViewValidator.cs
- code/src/UI/Validators/HasPivotValidator.cs
- code/src/UI/ViewModels/NewItem/MainViewModel.cs
- code/src/UI/VisualStudio/RightClickActions.cs
- Get project platform before bootstrapping context
- #3375 Add right click support for WPF
> Get project platform before bootstrapping context

- templates/Wpf/_catalog/frontendframeworks.json
- templates/Wpf/_catalog/projectTypes.json
Adjust framework and project type order for WPF
#3530 Split catalog for WPF
> Adjust framework and project type order for WPF

- docs/telemetry.md
Update telemetry docs to separate whats logged on wints and on corets
https://github.com/microsoft/CoreTemplateStudio/issues/218
> Update telemetry docs to separate whats logged on wints and on corets

- code/src/UI/Services/OrderingService.cs
- code/src/UI/ViewModels/Common/DataItems/SavedTemplateViewModel.cs
Add edit summary items telemetry back in
#3538 Add WinTS edit summary items telemetry
> Add edit summary items telemetry back in

- code/test/Templates.Test/CodeStyleEnforcementTests.cs
- templates/Uwp/Pages/ContentGrid.CaliburnMicro/Views/ContentGridViewDetailPage.xaml
- templates/Uwp/Pages/ContentGrid.CaliburnMicro/Views/ContentGridViewDetailPage.xaml.cs
- templates/Uwp/Pages/ContentGrid.CodeBehind._VB/Views/ContentGridViewDetailPage.xaml
- templates/Uwp/Pages/ContentGrid.CodeBehind._VB/Views/ContentGridViewDetailPage.xaml.vb
- templates/Uwp/Pages/ContentGrid.CodeBehind/Views/ContentGridViewDetailPage.xaml
- templates/Uwp/Pages/ContentGrid.CodeBehind/Views/ContentGridViewDetailPage.xaml.cs
- templates/Uwp/Pages/ContentGrid.Prism/Param_ProjectName/Views/ContentGridViewDetailPage.xaml
- templates/Uwp/Pages/ContentGrid.Prism/Param_ProjectName/Views/ContentGridViewDetailPage.xaml.cs
- templates/Uwp/Pages/ContentGrid._VB/Views/ContentGridViewDetailPage.xaml
- templates/Uwp/Pages/ContentGrid._VB/Views/ContentGridViewDetailPage.xaml.vb
- templates/Uwp/Pages/ContentGrid/Views/ContentGridViewDetailPage.xaml
- templates/Uwp/Pages/ContentGrid/Views/ContentGridViewDetailPage.xaml.cs
- templates/Uwp/_comp/CaliburnMicro/Page.ContentGrid.Blank/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/CaliburnMicro/Page.ContentGrid.SplitView.TabbedNav/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/CodeBehind/Page.ContentGrid.Blank.MenuBar._VB/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/CodeBehind/Page.ContentGrid.Blank.MenuBar/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/CodeBehind/Page.ContentGrid.SplitView.TabbedNav._VB/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/CodeBehind/Page.ContentGrid.SplitView.TabbedNav/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/Prism/Page.ContentGrid.Blank.MenuBar/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/Prism/Page.ContentGrid.SplitView.TabbedNav/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/_shared/Page.ContentGrid.Blank.MenuBar._VB/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/_shared/Page.ContentGrid.Blank.MenuBar/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/_shared/Page.ContentGrid.SplitView.TabbedNav._VB/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Uwp/_comp/_shared/Page.ContentGrid.SplitView.TabbedNav/Views/wts.ItemNameDetailPage_postaction.xaml
Generated Content Grid Page Does Not Scroll #3493
> Fix ContentGrid connected animation

- templates/Uwp/Services/SqlServerDataService.Prism/Param_ProjectName.Core/Services/SqlServerDataService.cs
- templates/Uwp/Services/SqlServerDataService._VB/Param_ProjectName.Core/Services/SqlServerDataService.vb
- templates/Uwp/Services/SqlServerDataService/Param_ProjectName.Core/Services/SqlServerDataService.cs
- templates/Uwp/_comp/Prism/Service.IdentityCommon/Param_ProjectName.Core/Services/IdentityService.cs
- templates/Uwp/_comp/_shared/Service.IdentityForcedLogin._VB/Param_ProjectName.Core/Services/IdentityService.vb
- templates/Uwp/_comp/_shared/Service.IdentityForcedLogin/Param_ProjectName.Core/Services/IdentityService.cs
- templates/Uwp/_comp/_shared/Service.IdentityOptionalLogin._VB/Param_ProjectName.Core/Services/IdentityService.vb
- templates/Uwp/_comp/_shared/Service.IdentityOptionalLogin/Param_ProjectName.Core/Services/IdentityService.cs
- templates/Wpf/Features/SampleData/Param_ProjectName.Core/Services/SampleDataService.cs
- templates/Wpf/Pages/Settings/ViewModels/wts.ItemNameViewModel.cs
- templates/Wpf/Pages/WebView/ViewModels/wts.ItemNameViewModel.cs
- templates/Wpf/_comp/_shared/Project.MenuBar/ViewModels/ShellViewModel.cs
- Fix services links for uwp
- Add missing links
- #3428 Docs for WPF
> Issue3428 updatedocsforwpf

- templates/Wpf/Features/MSIXPackaging/.template.config/template.json
- templates/Wpf/Features/MSIXPackaging/Param_ProjectName.Core/Param_ProjectName.Core_postaction.csproj
- templates/Wpf/Features/MSIXPackaging/Param_ProjectName.Packaging/Param_ProjectName.Packaging.wapproj
- templates/Wpf/Features/MSIXPackaging/Param_ProjectName/Param_ProjectName_postaction.csproj
- templates/Wpf/Projects/Default.Prism/wts.ProjectName/wts.ProjectName.csproj
- Configure msix project for desktop apps
- Replace Identity name guid
- #3559 Dev-nightly: Identity name is not getting replaced correctly
- #3557 New WPF project Packaging 'mismatch between the processor architecture'
> Issue3559 fix msix templates

- templates/Wpf/_comp/Prism/Feature.SystemService/App_postaction.xaml.cs
fixes failing [onebyone tests](https://winappstudio.visualstudio.com/DefaultCollection/WTS/_build/results?buildId=32914&view=results)
> Fix composition template

- code/test/Templates.Test/bat/RestoreAndBuildXamarin.bat
- code/test/Templates.Test/bat/Uwp/RestoreAndBuild.bat
- code/test/Templates.Test/bat/Uwp/RestoreAndBuildAppx.bat
- code/test/Templates.Test/bat/Uwp/RunTests.bat
- code/test/Templates.Test/bat/Wpf/RestoreAndBuild.bat
- code/test/Templates.Test/bat/Wpf/RestoreAndBuildAppx.bat
- code/test/Templates.Test/bat/Wpf/RestoreAndBuildWithMsix.bat
- templates/Wpf/Projects/Default.Prism/wts.ProjectName/App.xaml.cs
- templates/Wpf/_comp/Prism/Feature.PersistAndRestore/App_postaction.xaml.cs
- templates/Wpf/_comp/Prism/Feature.SampleData/App_postaction.xaml.cs
- templates/Wpf/_comp/Prism/Feature.SystemService/App_postaction.xaml.cs
- templates/Wpf/_comp/Prism/Feature.ThemeSelection/App_postaction.xaml.cs
- templates/Wpf/_comp/Prism/Page.AddViewModel/App_postaction.xaml.cs
- templates/Wpf/_comp/Prism/Project.MenuBar/App_postaction.xaml.cs
- templates/Wpf/_comp/Prism/Project.Ribbon/App_postaction.xaml.cs
Feedback requested for WPF mockup (Prism+ NavigationView) #3337
> Issue3337 prism feedback

- templates/Wpf/Projects/Default.Prism/wts.ProjectName.Core/readme.txt
- templates/Wpf/Projects/Default.Prism/wts.ProjectName.Core/wts.ProjectName.Core.csproj
- templates/Wpf/Projects/Default/wts.ProjectName.Core/readme.txt
- templates/Wpf/Projects/Default/wts.ProjectName.Core/wts.ProjectName.Core.csproj
- Add readme.txt file to core project
- Add models folder to core project
#3578
> Add models folder to core project

- templates/Uwp/_comp/Prism/Service.IdentityCommon/Param_ProjectName.Core/Services/IdentityService.cs
- templates/Uwp/_comp/_shared/Service.IdentityCommon._VB/Param_ProjectName/App_postaction.config
- templates/Uwp/_comp/_shared/Service.IdentityCommon/Param_ProjectName/App_postaction.config
- templates/Uwp/_comp/_shared/Service.IdentityForcedLogin._VB/Param_ProjectName.Core/Services/IdentityService.vb
- templates/Uwp/_comp/_shared/Service.IdentityForcedLogin/Param_ProjectName.Core/Services/IdentityService.cs
- templates/Uwp/_comp/_shared/Service.IdentityOptionalLogin._VB/Param_ProjectName.Core/Services/IdentityService.vb
- templates/Uwp/_comp/_shared/Service.IdentityOptionalLogin/Param_ProjectName.Core/Services/IdentityService.cs
- Remove clientid from uwp templates
- #3577
> Remove clientId

- templates/Wpf/Features/MSIXPackaging/Param_ProjectName.Packaging/Package.appinstaller
- templates/Wpf/Features/MSIXPackaging/Param_ProjectName.Packaging/Param_ProjectName.Packaging.wapproj
Add .appInstaller file to WPF MSIX project #3589
> Add Paclage.appinstaller to WPF MSIX feature

- templates/Wpf/Features/ThemeSelection/App_postaction.xaml
- templates/Wpf/Projects/Default.Prism/wts.ProjectName/App.xaml
- templates/Wpf/Projects/Default.Prism/wts.ProjectName/Styles/UserControl.xaml
- templates/Wpf/_comp/Prism/Page.AddViewModel/Views/wts.ItemNamePage_postaction.xaml
> Prism UserControls style

- docs/WPF/frameworks/mvvmbasic.md
> Doc update

- templates/Uwp/Pages/TwoPaneView.CodeBehind/.template.config/template.json
- templates/Uwp/Pages/TwoPaneView.Prism/.template.config/template.json
- templates/Uwp/Pages/TwoPaneView/.template.config/template.json
#3596 TwoPaneView UWP Page
Update WinUI in TwoPaneView templates
https://winappstudio.visualstudio.com/WTS/_build/results?buildId=33447&view=results
> Update WinUI in TwoPaneView templates

- templates/Wpf/Features/MSIXPackaging/Param_ProjectName.Packaging/Package.appxmanifest
WPF Msix package version should be 1.0.0.0 #3626
> Fix MSIX package version

- code/src/UI/Services/ProjectConfigInfoService.cs
- code/src/UI/Views/NewItem/ProjectConfigurationDialog.xaml
- code/test/Fakes/FakeGenShell.cs
- code/test/Fakes/MSBuild/FakeMsBuildProject.cs
- code/test/Fakes/Solution/FakeSolution.cs
- code/test/VsEmulator/Main/GeneratedProjectInfo.cs
- code/test/VsEmulator/Main/MainView.xaml
- code/test/VsEmulator/Main/MainViewModel.cs
- code/test/VsEmulator/NewProject/NewProjectViewModel.cs
Issues:
- Emulator LoadProject does not work in WPF #3604
- VS Emulator: Recreate app #3571
> Issue3604 vsemulator

- code/tools/TemplateValidator/TemplateJsonVerifier.cs
- templates/Uwp/Pages/TwoPaneView.Prism/.template.config/template.json
New TwoPaneView UWP Page Template #3596
> Fix TwoPaneView postaction project path and add tests

- templates/Wpf/Features/MSIXPackaging/.template.config/template.json
- templates/Wpf/_comp/_shared/Feature.MSIXPackaging.UpdateApplicationInfoService/.template.config/template.json
- templates/Wpf/_comp/_shared/Feature.MSIXPackaging.UpdateApplicationInfoService/Services/ApplicationInfoService_postaction.cs
WPF ApplicationInfoService fails during debug (GetVersion exception) #3630
> Use OSVersionHelper ApplicationInfoService

- code/test/Templates.Test/WACK/Uwp/WindowsAppCertKitTests.cs
- code/test/Templates.Test/WACK/Wpf/WindowsAppCertKitTests.cs
- templates/Wpf/Projects/Default.Prism/wts.ProjectName/app.manifest
- templates/Wpf/Projects/Default.Prism/wts.ProjectName/wts.ProjectName.csproj
- templates/Wpf/Projects/Default/wts.ProjectName/app.manifest
- templates/Wpf/Projects/Default/wts.ProjectName/wts.ProjectName.csproj
- Add DPI support for WPF
- Removed Identity templates from wack tests, as they don't work out of the box after removing the ClientID
- #3648 WPF projects are missing DPI support
> Issue3648 add dpi support

- templates/Wpf/Features/ThemeSelection/Services/ThemeSelectorService.cs
- templates/Wpf/Pages/WebView/.template.config/template.json
- templates/Wpf/Projects/Default.Prism/.template.config/template.json
- templates/Wpf/Projects/Default/.template.config/template.json
- templates/Wpf/_comp/Prism/Service.IdentityForcedLogin/.template.config/template.json
- templates/Wpf/_comp/Prism/Service.IdentityOptionalLogin/.template.config/template.json
- templates/Wpf/_comp/_shared/Service.IdentityCommon/.template.config/template.json
#3490 Update Nuget Packages in WPF Templates
> Update Nuget Packages in WPF Templates

- code/test/VsEmulator/Main/MainView.xaml
- code/test/VsEmulator/Main/MainViewModel.cs
#3571 Recreate App in VS Emulator
> VSEmulator Re-create App

- code/test/VsEmulator/Main/MainView.xaml
- code/test/VsEmulator/Main/MainViewModel.cs
#3571 Recreate App in VS Emulator
> updates in vs emulator recreate app

- _build/ProjectTemplate-SetPublishingData.ps1
> Fix vstemplate replacement script

- code/src/Installer/source.extension.vsixmanifest
> Remove wpf from description

- templates/Wpf/Projects/Default.Prism/.template.config/template.json
- templates/Wpf/Projects/Default/.template.config/template.json
- templates/Wpf/_comp/_shared/Feature.MSIXPackaging.UpdateApplicationInfoService/.template.config/template.json
- templates/Wpf/_comp/_shared/Service.IdentityCommon/.template.config/template.json
Update nugets in WPF Templates to latest version #3490
> Update WPF Nuget packages

- templates/Uwp/_comp/CaliburnMicro/Project.SplitView.TabbedNav/ViewModels/ShellViewModel.cs
- templates/Uwp/_comp/CodeBehind/Project.SplitView.TabbedNav.Page.Settings._VB/Views/ShellPage_postaction.xaml.vb
- templates/Uwp/_comp/CodeBehind/Project.SplitView.TabbedNav.Page.Settings/Views/ShellPage_postaction.xaml.cs
- templates/Uwp/_comp/CodeBehind/Project.SplitView.TabbedNav._VB/Views/ShellPage.xaml.vb
- templates/Uwp/_comp/CodeBehind/Project.SplitView.TabbedNav/Views/ShellPage.xaml.cs
- templates/Uwp/_comp/MVVMBasic/Project.SplitView.TabbedNav.Page.Settings._VB/ViewModels/ShellViewModel_postaction.vb
- templates/Uwp/_comp/MVVMBasic/Project.SplitView.TabbedNav.Page.Settings/ViewModels/ShellViewModel_postaction.cs
- templates/Uwp/_comp/MVVMBasic/Project.SplitView.TabbedNav._VB/ViewModels/ShellViewModel.vb
- templates/Uwp/_comp/MVVMBasic/Project.SplitView.TabbedNav/ViewModels/ShellViewModel.cs
- templates/Uwp/_comp/MVVMLight/Project.SplitView.TabbedNav.Page.Settings._VB/ViewModels/ShellViewModel_postaction.vb
- templates/Uwp/_comp/MVVMLight/Project.SplitView.TabbedNav.Page.Settings/ViewModels/ShellViewModel_postaction.cs
- templates/Uwp/_comp/MVVMLight/Project.SplitView.TabbedNav._VB/ViewModels/ShellViewModel.vb
- templates/Uwp/_comp/MVVMLight/Project.SplitView.TabbedNav/ViewModels/ShellViewModel.cs
- templates/Uwp/_comp/Prism/Project.SplitView.TabbedNav/ViewModels/ShellViewModel.cs
Nested NavigationViewItem.MenuItems Aren't Found OnItemInvoked #3657
> Nested NavigationView MenuItems

- code/test/Fakes/FakeGenShell.cs
Fix add reference on FakeGenShell
Failing wack tests: https://winappstudio.visualstudio.com/DefaultCollection/WTS/_build/results?buildId=33826&view=results
> Fix failing wack tests

- templates/Wpf/Projects/Default.Prism/.template.config/template.json
- templates/Wpf/Projects/Default.Prism/wts.ProjectName/App.xaml
- templates/Wpf/Projects/Default/.template.config/template.json
- templates/Wpf/Projects/Default/wts.ProjectName/App.xaml
Update nugets in WPF Templates to latest version #3490
> Update Mahapps to 2.0.0 release version

- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
> Do not translate command line.

- code/src/UI/VisualStudio/VsGenShell.cs
Set packaging project as startup project if available
#3631 WPF: MSIX project should be marked as startup project if it is added
> Set packaging project as startup project if available

- code/src/Installer/Installer.csproj
- code/src/Installer/source.extension.vsixmanifest
- code/src/ProjectTemplates/CSharp.UWP.Solution/CSharp.UWP.Solution.csproj
- code/src/ProjectTemplates/CSharp.UWP.Solution/packages.config
- code/src/ProjectTemplates/CSharp.WPF.Solution/CSharp.WPF.Solution.csproj
- code/src/ProjectTemplates/CSharp.WPF.Solution/packages.config
- code/src/ProjectTemplates/VBNet.UWP.Solution/VBNet.UWP.Solution.csproj
- code/src/ProjectTemplates/VBNet.UWP.Solution/packages.config
- code/src/UI/UI.csproj
Set VS 16.2 as minimum required version
#3699 Dev-nightly: WTS fails on VS 16.0 and 16.1
> Set VS 16.2 as minimum required version

- templates/Uwp/Features/HubNotifications.Prism/App_postaction.xaml.cs
- templates/Uwp/Features/LiveTile.Prism/App_postaction.xaml.cs
- templates/Uwp/Features/StoreNotifications.Prism/App_postaction.xaml.cs
- templates/Uwp/Features/ToastNotifications.Prism/App_postaction.xaml.cs
- templates/Uwp/Features/UserActivity.Prism/App_postaction.xaml.cs
Remove unneeded await Task.CompletedTask; line
#3697 ToastNotification fails on right click using Prism
> Fix ToastNotification addition on right click for prism

- templates/Wpf/Pages/MasterDetail/Param_ProjectName/Views/wts.ItemNamePage.xaml
- templates/Wpf/Pages/Settings/Views/wts.ItemNamePage.xaml
- templates/Wpf/Pages/WebView/Views/wts.ItemNamePage.xaml
- templates/Wpf/Services/IdentityForcedLogin/Views/LogInWindow.xaml
- templates/Wpf/Services/IdentityForcedLogin/Views/SettingsPage_postaction.xaml
- templates/Wpf/Services/IdentityOptionalLogin/Views/SettingsPage_postaction.xaml
- templates/Wpf/_comp/Prism/Project.Blank/Properties/Resources.Designer_postaction.cs
- templates/Wpf/_comp/Prism/Project.Blank/Properties/Resources_postaction.resx
- templates/Wpf/_comp/Prism/Project.Blank/Views/ShellWindow.xaml
- templates/Wpf/_comp/Prism/Project.MenuBar/Properties/Resources.Designer_postaction.cs
- templates/Wpf/_comp/Prism/Project.MenuBar/Properties/Resources_postaction.resx
- templates/Wpf/_comp/Prism/Project.MenuBar/Views/ShellWindow.xaml
- templates/Wpf/_comp/Prism/Project.SplitView/Properties/Resources.Designer_postaction.cs
- templates/Wpf/_comp/Prism/Project.SplitView/Properties/Resources_postaction.resx
- templates/Wpf/_comp/Prism/Project.SplitView/Views/ShellWindow.xaml
- templates/Wpf/_comp/_shared/Project.Blank/Properties/Resources.Designer_postaction.cs
- templates/Wpf/_comp/_shared/Project.Blank/Properties/Resources_postaction.resx
- templates/Wpf/_comp/_shared/Project.Blank/Views/ShellWindow.xaml
- templates/Wpf/_comp/_shared/Project.MenuBar/Properties/Resources.Designer_postaction.cs
- templates/Wpf/_comp/_shared/Project.MenuBar/Properties/Resources_postaction.resx
- templates/Wpf/_comp/_shared/Project.MenuBar/Views/ShellWindow.xaml
- templates/Wpf/_comp/_shared/Project.SplitView/Properties/Resources.Designer_postaction.cs
- templates/Wpf/_comp/_shared/Project.SplitView/Properties/Resources_postaction.resx
- templates/Wpf/_comp/_shared/Project.SplitView/Views/ShellWindow.xaml
> Issue3459 accessibility

- code/src/Installer/source.extension.vsixmanifest
Fix dependency and pre-requisits versions
#3699 Dev-nightly: WTS fails on VS 16.0 and 16.1
> Fix dependency and pre-requisits versions

- code/test/Templates.Test/CodeStyleEnforcementTests.cs
- templates/Uwp/_comp/Prism/Service.IdentityCommon/Param_ProjectName.Core/Services/IdentityService.cs
- templates/Uwp/_comp/_shared/Service.IdentityForcedLogin._VB/Param_ProjectName.Core/Services/IdentityService.vb
- templates/Uwp/_comp/_shared/Service.IdentityForcedLogin/Param_ProjectName.Core/Services/IdentityService.cs
- templates/Uwp/_comp/_shared/Service.IdentityOptionalLogin._VB/Param_ProjectName.Core/Services/IdentityService.vb
- templates/Uwp/_comp/_shared/Service.IdentityOptionalLogin/Param_ProjectName.Core/Services/IdentityService.cs
- templates/Uwp/_comp/_shared/Services.SecuredWebApi/Param_ProjectName.WebApi/Extensions/ServiceCollectionExtensions.cs
- templates/Wpf/_comp/_shared/Service.IdentityCommon/Param_ProjectName.Core/Services/IdentityService.cs
Correct TODO's
#3698 Login failure
> Correct TODO's

- templates/Uwp/Projects/Default.CaliburnMicro/App.xaml.cs
- templates/Uwp/Projects/Default._VB/App.xaml.vb
- templates/Uwp/Projects/Default/App.xaml.cs
- templates/Uwp/Projects/DefaultPrism/App.xaml.cs
- templates/Wpf/Projects/Default.Prism/wts.ProjectName/App.xaml.cs
- templates/Wpf/Projects/Default/wts.ProjectName/App.xaml.cs
Add a global exception handler for UWP applications #3709
> Add global exception handling in UWP Templates

- templates/Wpf/Features/PersistAndRestore/Param_ProjectName/appsettings_postaction.json
- templates/Wpf/Projects/Default.Prism/wts.ProjectName/app.manifest
- templates/Wpf/Projects/Default.Prism/wts.ProjectName/appsettings.json
- templates/Wpf/Projects/Default/wts.ProjectName/app.manifest
- templates/Wpf/Projects/Default/wts.ProjectName/appsettings.json
- templates/Wpf/_comp/Prism/Project.MenuBar/appsettings_postaction.json
- templates/Wpf/_comp/_shared/Service.IdentityCommon/Param_ProjectName/appsettings_postaction.json
Dev-nightly: Fix indentation in appSettings.json and app.manifest files #3719
> Fix indentation in appSettings.json and app.manifest files

- templates/Wpf/Features/ThemeSelection/Services/ThemeSelectorService.cs
- templates/Wpf/Pages/WebView/ViewModels/wts.ItemNameViewModel.cs
- templates/Wpf/Projects/Default.Prism/wts.ProjectName/App.xaml
- templates/Wpf/Projects/Default/wts.ProjectName/App.xaml
- templates/Wpf/_comp/MVVMBasic/Project/Services/ApplicationHostService.cs
- templates/Wpf/_comp/MVVMBasic/Service.IdentityForcedLogin/Services/ApplicationHostService_postaction.cs
- templates/Wpf/_comp/MVVMLight/Project/Services/ApplicationHostService.cs
- templates/Wpf/_comp/MVVMLight/Service.IdentityForcedLogin/Services/ApplicationHostService_postaction.cs
- templates/Wpf/_comp/_shared/Feature.ApplicationInfoService.AddGetVersion/Services/ApplicationInfoService_postaction.cs
- templates/Wpf/_comp/_shared/Feature.MSIXPackaging.UpdateApplicationInfoService/Services/ApplicationInfoService_postaction.cs
- templates/Wpf/_comp/_shared/Project.Ribbon/Views/ShellWindow.xaml
- templates/Wpf/_comp/_shared/Service.IdentityCommon/Param_ProjectName.Core/Services/IdentityService.cs
- templates/Wpf/_comp/_shared/Service.IdentityCommon/Param_ProjectName.Core/Services/MicrosoftGraphService.cs
- Added comment to mark the place in code where the default start page is set 
- Added reference to docs on how to implement a custom High Contrast Theme for MahApps
- Adjusted wording/format in some other comments in WPF templates
- #3683 WPF Default page setting (minor)
> Review WPF Comments

- code/test/Fakes/Fakes.csproj
- code/test/Fakes/app.config
- code/tools/Localization/App.config
- code/tools/Localization/Localization.csproj
- code/tools/Localization/Resources/HelpMessages.Designer.cs
- code/tools/TemplateValidator/TemplateValidator.csproj
- code/tools/TemplateValidator/app.config
- Update TargetFrameworkVersion to 4.7.2
- #3701 Update TargetFrameworkVersion to 4.7.2
Anything that requires particular review or attention?
- Contains Submodule update to update CoreTS projects
> Update TargetFrameworkVersion to 4.7.2

- templates/Uwp/SC/VBStyleAnalysis/.template.config/template.json
- templates/Uwp/SC/_comp/T.SC.A.MSTest._VB/.template.config/template.json
- templates/Uwp/SC/_comp/T.SC.A.xUnit._VB/.template.config/template.json
- templates/Uwp/SC/_comp/T.SC.C.MSTest._VB/.template.config/template.json
- templates/Uwp/SC/_comp/T.SC.C.NUnit._VB/.template.config/template.json
- templates/Uwp/SC/_comp/T.SC.C.xUnit._VB/.template.config/template.json
- templates/Uwp/SC/_comp/T.SC.WinAD._VB/.template.config/template.json
for #3728
update license link locations
> Fix license file location

- docs/getting-started-extension.md
- templates/Wpf/Projects/Default.Prism/wts.ProjectName/wts.ProjectName.csproj
- templates/Wpf/Projects/Default/wts.ProjectName/wts.ProjectName.csproj
- templates/Wpf/SC/StyleCop/Param_ProjectName/Param_ProjectName_searchreplace.csproj
Update WPF templates to use .net core 3.1
#3490 Update nugets in WPF templates
> Update WPF templates to use .net core 3.1

- templates/Wpf/Pages/MasterDetail/Param_ProjectName/Views/wts.ItemNamePage.xaml
- templates/Wpf/_comp/Prism/Project.Blank/Views/ShellWindow.xaml
- templates/Wpf/_comp/Prism/Project.MenuBar/Views/ShellWindow.xaml
- templates/Wpf/_comp/_shared/Project.Blank/Views/ShellWindow.xaml
- templates/Wpf/_comp/_shared/Project.MenuBar/Views/ShellWindow.xaml
Dev-nightly: WPF MasterDetail Status Binding wrong on Detail page #3734
> Fix Data Binding

- templates/Uwp/_comp/_shared/Page.Camera.AddResource._VB/Controls/CameraControl.xaml.vb
- templates/Uwp/_comp/_shared/Page.Camera.AddResource/Controls/CameraControl.xaml.cs
Back camera is rotated - and it should not be #3733
> Fix camera rotation

- .gitmodules
- Update submodule to point to release branch
- microsoft/CoreTemplateStudio#229
> Update submodule to point to release branch

- templates/Uwp/_comp/_shared/Page.TreeView.AddStringResources._VB/.template.config/template.json
- templates/Uwp/_comp/_shared/Page.TreeView.AddStringResources._VB/Strings/en-us/Resources_postaction.resw
- templates/Uwp/_comp/_shared/Page.TreeView.AddStringResources/.template.config/template.json
- templates/Uwp/_comp/_shared/Page.TreeView.AddStringResources/Strings/en-us/Resources_postaction.resw
Unused Uid TreeView_CollapseAllButton in TreeViewPage #3744
> Fix CollapseAllButton Tooltip and AutomationName in TreeViewPage

- templates/Uwp/Pages/TabbedPivot.CaliburnMicro/Views/TabbedPivotPagePage.xaml
Wrong binding on TabbedPivot Page for Caliburn.Micro #3739
> Fix Binding

- templates/Uwp/Services/SqlServerDataService.Prism/.template.config/template.json
- templates/Uwp/Services/SqlServerDataService._VB/.template.config/template.json
- templates/Uwp/Services/SqlServerDataService/.template.config/template.json
- templates/Uwp/Testing/UnitTests.App.MSTest._VB/.template.config/template.json
- templates/Uwp/Testing/UnitTests.App.MSTest/.template.config/template.json
- templates/Uwp/Testing/UnitTests.Core.MSTest._VB/.template.config/template.json
- templates/Uwp/Testing/UnitTests.Core.MSTest/.template.config/template.json
- templates/Uwp/Testing/WinAppDriver._VB/.template.config/template.json
- templates/Uwp/Testing/WinAppDriver/.template.config/template.json
- templates/Uwp/_comp/_shared/Service.IdentityCommon._VB/.template.config/template.json
- templates/Uwp/_comp/_shared/Service.IdentityCommon/.template.config/template.json
- templates/Uwp/_comp/_shared/Services.WebApi/.template.config/template.json
- templates/Wpf/Pages/WebView/.template.config/template.json
- templates/Wpf/Projects/Default.Prism/.template.config/template.json
- templates/Wpf/Projects/Default/.template.config/template.json
- templates/Wpf/_comp/_shared/Feature.MSIXPackaging.UpdateApplicationInfoService/.template.config/template.json
- templates/Wpf/_comp/_shared/Service.IdentityCommon/.template.config/template.json
- Update nuget packages to latest version for WPF and UWP
- #3490 Update nugets in WPF templates
- #3670 Update nugets in UWP templates
> Issue3490 updatenugetpackages

- templates/Uwp/Services/SqlServerDataService.Prism/.template.config/template.json
- templates/Uwp/Services/SqlServerDataService.Prism/Param_ProjectName.Core/Services/SqlServerDataService.cs
- templates/Uwp/Services/SqlServerDataService._VB/.template.config/template.json
- templates/Uwp/Services/SqlServerDataService._VB/Param_ProjectName.Core/Services/SqlServerDataService.vb
- templates/Uwp/Services/SqlServerDataService/.template.config/template.json
- templates/Uwp/Services/SqlServerDataService/Param_ProjectName.Core/Services/SqlServerDataService.cs
- Go back to System.Data.SqlClient
- #3756 Dev-nightly: Wack test failure caused by Microsoft.Data.SQLClient
> Go back to System.Data.SqlClient

- templates/Wpf/Services/IdentityForcedLogin/Views/LogInWindow.xaml
- templates/Wpf/_comp/Prism/Project.Blank/Views/ShellWindow.xaml
- templates/Wpf/_comp/Prism/Project.MenuBar/Views/ShellWindow.xaml
- templates/Wpf/_comp/Prism/Project.Ribbon/Views/ShellWindow.xaml
- templates/Wpf/_comp/Prism/Project.SplitView/Views/ShellWindow.xaml
- templates/Wpf/_comp/_shared/Project.Blank/Views/ShellWindow.xaml
- templates/Wpf/_comp/_shared/Project.MenuBar/Views/ShellWindow.xaml
- templates/Wpf/_comp/_shared/Project.Ribbon/Views/ShellWindow.xaml
- templates/Wpf/_comp/_shared/Project.SplitView/Views/ShellWindow.xaml
Set WPF MinWidth and MinHeight to ShellWindow #3757
> Set WPF MinWidth and MinHeight to ShellWindow

- templates/Wpf/Projects/Default.Prism/wts.ProjectName/App.xaml.cs
- templates/Wpf/Projects/Default/wts.ProjectName/App.xaml.cs
- Add comment for WPF UI elements defaulting to en-US issue
- #3667 WPF Automatic culture setting
> Add comment for WPF UI elements defaulting to en-US issue

- templates/Uwp/Projects/Default.CaliburnMicro/App.xaml.cs
- templates/Uwp/Projects/Default._VB/App.xaml.vb
- templates/Uwp/Projects/Default/App.xaml.cs
- templates/Uwp/_comp/_shared/Page.Camera.AddResource._VB/Controls/CameraControl.xaml.vb
- templates/Uwp/_comp/_shared/Page.Camera.AddResource/Controls/CameraControl.xaml.cs
Fix links that have redirects from msdn to docs (detected by ExternalLinksTests)
> Fix links that have redirects from msdn to docs

- code/src/UI/VisualStudio/VsGenShell.cs
- code/test/Fakes/FakeGenShell.cs
- Update CoreTS
- Change solution configuration based on configured project configurations
- #3740 Add postaction to unset "Deploy" in Configuration Manager
>  Add postaction to unset "Deploy" in Configuration Manager

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- docs/PULL_REQUEST_TEMPLATE.md
Add platform to issue and pr templates
#3793 issue and PR templates to include indication of related platform(s)
> Add platform to issue and pr templates

- code/src/UI/ViewModels/NewProject/UserSelectionGroup.cs
Include count of pages in wizard summary #3803
> Add count for pages, features, services and testing

- .gitignore
> Add Code folder to gitignore file

- code/test/Templates.Test/ExternalLinksTests.cs
Check links in comment blocks
#3769 Include links in block comments in ExternalLinkTests
> Check links in comment blocks

- templates/Wpf/Features/ThemeSelection/Services/ThemeSelectorService.cs
- templates/Wpf/Features/XamlIslandUwpApp/.template.config/template.json
- templates/Wpf/Pages/XamlIsland/.template.config/template.json
- templates/Wpf/_comp/_shared/Feature.XamlIsland.Theming/Services/ThemeSelectorService_postaction.cs
Fix available frontendframeworks for xaml island
Fix ThemeSelector postaction
#3624 Xaml Island Page
> Fix available frontendframeworks for XAML Island

- code/test/Templates.Test/CodeStyleEnforcementTests.cs
Add test to ensure exception messages are not localized
#3792 Exception messages should not be localized
> Add test to ensure exception messages are not localized

- templates/Wpf/_comp/Prism/Project.SplitView/Views/ShellWindow.xaml
Add x:Name on HamburgerMenu
#3845 Binding failures
| No | Yes |
> Fix Binding issues in Prism

- docs/WPF/frameworks/codebehind.md
- docs/WPF/frameworks/readme.md
- docs/WPF/pages/readme.md
- docs/WPF/pages/xamlisland.md
- docs/getting-started-developers.md
Add docs for CodeBehind and XamlIsland
#3774, #3624
| no | yes |
> Add docs for CodeBehind and XamlIsland

- docs/UWP/services/secured-web-api.md
- templates/Uwp/_comp/_shared/Service.IdentityForcedLogin._VB/Param_ProjectName.Core/Services/IdentityService.vb
- templates/Uwp/_comp/_shared/Service.IdentityForcedLogin/Param_ProjectName.Core/Services/IdentityService.cs
- templates/Uwp/_comp/_shared/Service.IdentityOptionalLogin._VB/Param_ProjectName.Core/Services/IdentityService.vb
- templates/Uwp/_comp/_shared/Service.IdentityOptionalLogin/Param_ProjectName.Core/Services/IdentityService.cs
- templates/Uwp/_comp/_shared/Services.SecuredWebApi/Param_ProjectName.WebApi/Extensions/ServiceCollectionExtensions.cs
Add link to role and redirect uri configuration
#3625 Add AppclientID and scopes login wts 
| yes | no |
> Add link to role and redirect uri configuration

- templates/Wpf/Pages/ContentGrid.CodeBehind/.template.config/template.json
- templates/Wpf/Pages/ContentGrid/.template.config/template.json
- templates/Wpf/Pages/DataGrid.CodeBehind/.template.config/template.json
- templates/Wpf/Pages/DataGrid/.template.config/template.json
- templates/Wpf/Pages/MasterDetail.CodeBehind/.template.config/template.json
- templates/Wpf/Pages/WebView.CodeBehind/.template.config/template.json
- templates/Wpf/Pages/WebView/.template.config/template.json
- templates/Wpf/Pages/XamlIsland.CodeBehind/.template.config/template.json
- templates/Wpf/Pages/XamlIsland/.template.config/template.json
Reorder pages in WPF to match UWP order
#3818 Unify pages, features, and services order between UWP and WPF
| No | Yes |
> Reorder pages in WPF to match UWP order

- templates/Wpf/_comp/CodeBehind/Project.MenuBar/Views/ShellWindow.xaml.cs
Fix codebehind ContentGrid GoBack navigation
#3774 Add codebehind as a framework option for WPF
| No | Yes |
> Fix ContentGrid GoBack navigation

- templates/Wpf/Pages/XamlIsland.CodeBehind/Param_ProjectName.XamlIsland/wts.ItemNameControlUniversal.xaml
- templates/Wpf/Pages/XamlIsland.CodeBehind/Param_ProjectName.XamlIsland/wts.ItemNameControlUniversal.xaml.cs
- templates/Wpf/Pages/XamlIsland.CodeBehind/Param_ProjectName/Controls/wts.ItemNameControl.xaml.cs
- templates/Wpf/Pages/XamlIsland/Param_ProjectName.XamlIsland/wts.ItemNameControlUniversal.xaml
- templates/Wpf/Pages/XamlIsland/Param_ProjectName.XamlIsland/wts.ItemNameControlUniversal.xaml.cs
- templates/Wpf/Pages/XamlIsland/Param_ProjectName/Controls/wts.ItemNameControl.xaml.cs
Add WTS TODO on XAMLIslandControlUniversal
#3624 WPF Page with XAML Island
| No | Yes |
> Add TODO WTS to XAMLIsland

- code/src/UI/Services/RequiredVersionValidation/RequiredVersionService.cs
- code/src/UI/Services/RequiredVersionValidation/Validators/DotNetValidator.cs
- code/tools/Localization/Extensions/RoutesManager.cs
- code/tools/TemplateValidator/TemplateJsonVerifier.cs
Fixes some warnings from recently added code
> Fix warnings 

- templates/WinUI/Features/MSIXPackaging/Param_ProjectName.Packaging/build/Microsoft.WinUI.AppX.targets
Avoid evaluation of conditionals on Microsoft.WinUI.AppX.targets 
#3810 WinUI templates
| UWP              | WPF              | WinUI
| No  | No |Yes|
> Avoid evaluation of conditionals on Microsoft.WinUI.AppX.targets 

- code/tools/TemplateValidator/TemplateJsonVerifier.cs
Fix message in template validation tests
#3874 Template validation of RequiredSDK has the wrong error message
> Fix message in template tests

- docs/how-to.md
- docs/newitem.md
- docs/readme.md
- docs/third-party-libraries.md
Move thirdparty libraries and howto to docs
#3775 Review and update wiki
> Move thirdparty libraries and howto to docs

- README.md
- docs/roadmap.md
Update roadmap after releasing 3.8
> Update roadmap after releasing 3.8

- WpfMockup/DotNetCoreWpfApp.Tests.WinAppDriver/BasicTests.cs
Fix labels
#3613 WPF Testing Templates
| No | Yes |
> Mockup wpf patch

- templates/WinUI/Pages/Form/.template.config/icon.xaml
- templates/WinUI/Projects/Default/nuget.config
Change Form icon and add nuget.config
> Change Form icon and add nuget.config

- code/test/Templates.Test/VisualTests/VisualComparisonTests.cs
Adjusted tests to be more robust
**Which issue does this PR relate to?** #3776 
| Yes | Yes |
no
yes
n/a
n/a
- Be sure it's included in the list …
> Increase reliability of EnsureCanNavigateToEveryPageWithMenuBarWithoutErrorAsync tests

- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
- code/test/Templates.Test/BuildTemplatesTests/WinUI/BuildMVVMToolkitProjectTests.cs
Fix WinUI StyleCop tests to build with correct bat script
> Fix WinUI StyleCop tests

- code/src/UI/Styles/DataTemplate.xaml
Wizard. Fix AutomationProperties.Name binding
#3899
> Accessibility - Wizard - Template details hiperlink Layout

- code/src/UI/Views/Common/TemplateInfoPage.xaml
Wizard. Set Button with custom template on GoBack details
#3896
> Accessibility - Wizard - Back button Hyperlink

- code/src/UI/AutomationPeers/ExpanderButtonAutomationPeer.cs
- code/src/UI/Controls/ExpanderButtonAutomationPeerControl.cs
- code/src/UI/Styles/DataTemplate.xaml
- code/src/UI/UI.csproj
Create custom Expander to override AutomationControlType to Button
#3891
> Accessibility - Wizard - Expander incorrect announcement

- code/src/UI/Controls/SequentialFlow.xaml
- code/src/UI/Controls/SequentialFlow.xaml.cs
- code/src/UI/Views/NewProject/MainPage.xaml
- code/src/UI/Views/NewProject/MainPage.xaml.cs
Apply previous focus when GoBack from template details
#3898
> Accessibility - Wizard - keep keyboard focus

- code/src/UI/Controls/Markdown.cs
- code/src/UI/Views/Common/TemplateInfoPage.xaml
- code/src/UI/Views/Common/TemplateInfoPage.xaml.cs
On TeplateInfo apply RaiseAutomationEvent when Hyperlink Inline is selected.
#3897
> Accessibility - Wizard - Hyperlink template detail

- code/src/UI/Controls/MarkdownBlock.xaml
- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
- code/src/UI/Styles/Button.xaml
- code/src/UI/Styles/MarkdownBlock.xaml
- code/src/UI/Views/Common/TemplateInfoPage.xaml
- code/src/UI/Views/NewItem/WizardShell.xaml
Fix accessibility issues Fast Pass
#3838
#3835
#3834
#3830
> Accessibility - Wizard - Fast Pass

- mockup/WinUI3/WinUIDesktopApp.Core/Services/SampleDataService.cs
- mockup/WinUI3/WinUIDesktopApp/Activation/DefaultActivationHandler.cs
- mockup/WinUI3/WinUIDesktopApp/App.xaml.cs
- mockup/WinUI3/WinUIDesktopApp/Contracts/Services/IThemeSelectorService.cs
Add updates in mockup to be aligned with generated apps
> Add updates in mockup to be aligned with generated apps

- code/src/UI/Styles/DataTemplate.xaml
- code/src/UI/Styles/ListView.xaml
Wizard. Make description TextBlock focusable to be accessible by screen reader
#3892
> Accessibility - Wizard - Make Card description accessible

- templates/Wpf/Features/ThemeSelection/.template.config/template.json
- templates/Wpf/Features/ThemeSelection/Contracts/Services/IThemeSelectorService.cs
- templates/Wpf/Features/ThemeSelection/Models/AppTheme.cs
- templates/Wpf/Features/ThemeSelection/Services/ThemeSelectorService.cs
- templates/Wpf/Features/ThemeSelection/Styles/Themes/HC.Dark.Blue.xaml
- templates/Wpf/Features/ThemeSelection/Styles/Themes/HC.Light.Blue.xaml
- templates/Wpf/Pages/Settings.CodeBehind/Properties/Resources.Designer_postaction.cs
- templates/Wpf/Pages/Settings.CodeBehind/Properties/Resources_postaction.resx
- templates/Wpf/Pages/Settings.CodeBehind/Views/wts.ItemNamePage.xaml
- templates/Wpf/Pages/Settings.CodeBehind/Views/wts.ItemNamePage.xaml.cs
- templates/Wpf/Pages/Settings/Properties/Resources.Designer_postaction.cs
- templates/Wpf/Pages/Settings/Properties/Resources_postaction.resx
- templates/Wpf/Pages/Settings/Views/wts.ItemNamePage.xaml
- templates/Wpf/Projects/Default.Prism/.template.config/template.json
- templates/Wpf/Projects/Default/.template.config/template.json
- templates/Wpf/_comp/CodeBehind/Feature.ThemeSelection/Services/ApplicationHostService_postaction.cs
- templates/Wpf/_comp/MVVMBasic/Feature.ThemeSelection/Services/ApplicationHostService_postaction.cs
- templates/Wpf/_comp/MVVMLight/Feature.ThemeSelection/Services/ApplicationHostService_postaction.cs
- templates/Wpf/_comp/Prism/Feature.ThemeSelection/App_postaction.xaml.cs
- templates/Wpf/_comp/_shared/Feature.XamlIsland.Theming/Services/ThemeSelectorService_postaction.cs
- templates/Wpf/_comp/_shared/Project.Ribbon.ThemeSelection/Services/ThemeSelectorService_postaction.cs
Add Windows Default Theme and High Contrast compatibility to WPF Templates.
Accessibility for WPF #3459
> WPF Default Theme and High Contrast support

- templates/Uwp/Testing/UnitTests.App.MSTest._VB/.template.config/template.json
- templates/Uwp/Testing/UnitTests.App.MSTest/.template.config/template.json
- templates/Uwp/Testing/UnitTests.App.xUnit._VB/.template.config/template.json
- templates/Uwp/Testing/UnitTests.App.xUnit/.template.config/template.json
- templates/Uwp/Testing/UnitTests.App.xUnit/Param_ProjectName.Tests.xUnit/Param_ProjectName.Tests.xUnit.csproj
- templates/Uwp/Testing/UnitTests.Core.MSTest._VB/.template.config/template.json
- templates/Uwp/Testing/UnitTests.Core.MSTest/.template.config/template.json
- templates/Uwp/Testing/UnitTests.Core.NUnit._VB/.template.config/template.json
- templates/Uwp/Testing/UnitTests.Core.NUnit/.template.config/template.json
- templates/Uwp/Testing/UnitTests.Core.xUnit._VB/.template.config/template.json
- templates/Uwp/Testing/UnitTests.Core.xUnit/.template.config/template.json
- templates/Uwp/Testing/WinAppDriver._VB/.template.config/template.json
- templates/Uwp/Testing/WinAppDriver/.template.config/template.json
Add reference to Microsoft.NET.Test.Sdk.
**Which issue does this PR relate to?** 3940
| Yes | ? |? |
**Have automated tests been added for new features?** No
**If you've changed the UI:** No
**If you've included a new template:** No …
> Update Param_ProjectName.Tests.xUnit.csproj - Add reference to Microsoft.NET.Test.Sdk

- mockup/WinUI3/WinUIDesktopApp/App.xaml.cs
- mockup/WinUI3/WinUIDesktopApp/Contracts/Services/INavigationService.cs
- mockup/WinUI3/WinUIDesktopApp/Contracts/Services/INavigationViewService.cs
- mockup/WinUI3/WinUIDesktopApp/Contracts/Services/IWebViewService.cs
- mockup/WinUI3/WinUIDesktopApp/Helpers/FrameExtensions.cs
- mockup/WinUI3/WinUIDesktopApp/Services/NavigationService.cs
- mockup/WinUI3/WinUIDesktopApp/Services/NavigationViewService.cs
- mockup/WinUI3/WinUIDesktopApp/Services/WebViewService.cs
- mockup/WinUI3/WinUIDesktopApp/ViewModels/ContentGridViewModel.cs
- mockup/WinUI3/WinUIDesktopApp/ViewModels/MasterDetailViewModel.cs
- mockup/WinUI3/WinUIDesktopApp/ViewModels/ShellViewModel.cs
- mockup/WinUI3/WinUIDesktopApp/ViewModels/WebViewViewModel.cs
- mockup/WinUI3/WinUIDesktopApp/Views/ContentGridDetailPage.xaml.cs
- mockup/WinUI3/WinUIDesktopApp/Views/MasterDetailPage.xaml
- mockup/WinUI3/WinUIDesktopApp/Views/MasterDetailPage.xaml.cs
- mockup/WinUI3/WinUIDesktopApp/Views/ShellWindow.xaml
- mockup/WinUI3/WinUIDesktopApp/Views/ShellWindow.xaml.cs
- mockup/WinUI3/WinUIDesktopApp/Views/WebViewPage.xaml
- mockup/WinUI3/WinUIDesktopApp/Views/WebViewPage.xaml.cs
- mockup/WinUI3/WinUIDesktopApp/WinUIDesktopApp.csproj
Decouple Views and ViewModels in WinUI3 Mockup
Review and decouple VM from Views in Winui 3 #3908
> Decouple Views and ViewModels in WinUI 3 Mockup

- mockup/WinUI3/WinUIDesktopApp/App.xaml.cs
- mockup/WinUI3/WinUIDesktopApp/Services/PageService.cs
- mockup/WinUI3/WinUIDesktopApp/ViewModels/FormWCTViewModel.cs
- mockup/WinUI3/WinUIDesktopApp/Views/FormWCTPage.xaml
- mockup/WinUI3/WinUIDesktopApp/Views/FormWCTPage.xaml.cs
- mockup/WinUI3/WinUIDesktopApp/Views/ShellWindow.xaml
- mockup/WinUI3/WinUIDesktopApp/WinUIDesktopApp.csproj
Update Microsoft.Toolkit.Mvvm to Version 7.0.0-preview4
Add a duplicated Form Page trying to use ObservableValidator
> Update Microsoft.Toolkit.Mvvm to Version 7.0.0-preview4

- mockup/WinUI3/WinUIDesktopApp/Helpers/ObservableValidator.cs
- mockup/WinUI3/WinUIDesktopApp/ViewModels/FormViewModel.cs
> Rename ValidationObservableRecipient to ObservableValidator

- templates/WinUI/Pages/Form/.template.config/template.json
- templates/WinUI/Pages/Form/Param_ProjectName/Helpers/ObservableValidator.cs
- templates/WinUI/Pages/Form/Param_ProjectName/ViewModels/wts.ItemNameViewModel.cs
- templates/WinUI/_comp/MVVMToolkit/Feature.SampleData/App_postaction.xaml.cs
- templates/WinUI/_comp/MVVMToolkit/Feature.ThemeSelection/App_postaction.xaml.cs
- templates/WinUI/_comp/MVVMToolkit/Page.AddViewModel/App_postaction.xaml.cs
- templates/WinUI/_comp/MVVMToolkit/Page.AddViewModelDetail/App_postaction.xaml.cs
- templates/WinUI/_comp/MVVMToolkit/Project/.template.config/template.json
- templates/WinUI/_comp/MVVMToolkit/Project/App_postaction.xaml.cs
- templates/WinUI/_comp/MVVMToolkit/Project/Services/PageService.cs
Update WinUI 3 MVVM Toolkit to Preview 4
Proposal: C# Templates for WinUI 3 #3810
Microsoft.Toolkit.Mvvm to replace MVVMBasic, MVVMLight, & Caliburn.Micro templates #3753
> Update WinUI 3 MVVM Toolkit to Preview 4

- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
Improve warning message when trying to remove a readonly layout item
#3906
> Improve warning message when trying to remove a readonly layout item

- code/src/UI/Services/Styles/BaseStyleValuesProvider.cs
- code/src/UI/Services/Styles/UIStylesService.Styles.cs
- code/src/UI/Services/Styles/UIStylesService.cs
- code/src/UI/Services/Styles/VSStyleValuesProvider.cs
- code/src/UI/Services/Styles/WindowsTemplateStudioColors.xml
- code/src/UI/Styles/ListView.xaml
- code/src/UI/UI.csproj
- code/test/UI.Test/UITestStyleValuesProvider.cs
- code/test/VsEmulator/Services/FakeStyleValuesProvider.cs
- code/test/VsEmulator/Services/Styles.cs
- code/test/VsEmulator/Styles/Dark_Styles.xaml
- code/test/VsEmulator/Styles/HighContrast_Styles.xaml
- code/test/VsEmulator/Styles/Light_Styles.xaml
- code/test/VsEmulator/VsEmulator.csproj
Wizard: Steps sequential flow control accessibility enhacements
A11y_Windows Template Studio_Select a Project type_Keyboard: When we move to selected list Item Keyboard focus is not visible on it. #3900
> Wizard: Steps sequential flow control accessibility enhacements

- docs/getting-started-developers.md
- templates/Wpf/_comp/MVVMToolkit/Feature.ThemeSelection/Services/ApplicationHostService_postaction.cs
- Fix theme initialization for MVVMToolkit
-  Add MVVMToolkit test execution to build pipelines and updated docs
#3753 Microsoft.Toolkit.Mvvm to replace MVVMBasic, MVVMLight, & Caliburn.Micro templates
> Fix wpftests

- code/src/UI/VisualStudio/RightClickActions.cs
Add testing templates entry point for wpf on right click
#3613 WPF Testing Templates
|No | Yes | No|
> Add testing templates entry point for wpf on right click

- templates/Uwp/Pages/ImageGallery.CaliburnMicro/ViewModels/ImageGalleryViewDetailViewModel.cs
- templates/Uwp/Pages/ImageGallery.CodeBehind._VB/Views/ImageGalleryViewDetailPage.xaml.vb
- templates/Uwp/Pages/ImageGallery.CodeBehind/Views/ImageGalleryViewDetailPage.xaml.cs
- templates/Uwp/Pages/ImageGallery.Prism/Param_ProjectName/ViewModels/ImageGalleryViewDetailViewModel.cs
- templates/Uwp/Pages/ImageGallery._VB/ViewModels/ImageGalleryViewDetailViewModel.vb
- templates/Uwp/Pages/ImageGallery/ViewModels/ImageGalleryViewDetailViewModel.cs
Fix ImageGallery navigation issue
Application crashes when click items in ImageGallery page twice #3965
| Yes | No | No |
> Fix ImageGallery navigation issue

- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
Add machine tranlations for new texts in 3.9
#3977 Localize new texts
> Add machine tranlations for new texts in 3.9

- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
Fix swapped translations + formatting
#3977 Localize new texts
> Fix swapped translations + formatting

- templates/Uwp/Pages/ImageGallery.Prism/Param_ProjectName/ViewModels/ImageGalleryViewViewModel.cs
- templates/Uwp/Pages/ImageGallery._VB/ViewModels/ImageGalleryViewViewModel.vb
- templates/Uwp/Pages/ImageGallery/ViewModels/ImageGalleryViewViewModel.cs
- templates/Uwp/_comp/MVVMBasic/Page.ImageGallery._VB/ViewModels/wts.ItemNameViewModel_postaction.vb
- templates/Uwp/_comp/MVVMBasic/Page.ImageGallery/ViewModels/wts.ItemNameViewModel_postaction.cs
- templates/Uwp/_comp/MVVMLight/Page.ImageGallery._VB/ViewModels/wts.ItemNameViewModel_postaction.vb
- templates/Uwp/_comp/MVVMLight/Page.ImageGallery/ViewModels/wts.ItemNameViewModel_postaction.cs
- templates/Uwp/_comp/MVVMToolkit/Page.ImageGallery._VB/ViewModels/wts.ItemNameViewModel_postaction.vb
- templates/Uwp/_comp/MVVMToolkit/Page.ImageGallery/ViewModels/wts.ItemNameViewModel_postaction.cs
Simply change `OnsItemSelected` to `OnItemSelected`
No issue related
|Yes| Yes| Yes |
No
Yes
No new features
- Be sure you reviewed the [Template Verification Checklist](https://github.com/microsoft/WindowsTemplateStudio/w …
> Fix code style

- docs/WinUI/readme.md
> Update winui docs with known issues

- code/src/UI/Services/Styles/UIStylesService.ThemedDialog.cs
- code/src/UI/Services/Styles/UIStylesService.cs
- code/src/UI/Services/Styles/VSStyleValuesProvider.cs
- code/src/UI/Styles/ListView.xaml
- code/src/UI/UI.csproj
- code/test/VsEmulator/Services/FakeStyleValuesProvider.cs
- code/test/VsEmulator/Services/ThemedDialog.cs
- code/test/VsEmulator/Styles/Dark_ThemedDialog.xaml
- code/test/VsEmulator/Styles/HighContrast_ThemedDialog.xaml
- code/test/VsEmulator/Styles/Light_ThemedDialog.xaml
- code/test/VsEmulator/VsEmulator.csproj
Update sequential flow control colors using themed dialog theme colors
A11y_Windows Template Studio_Select a Project type_Keyboard: When we move to selected list Item Keyboard focus is not visible on it. #3900
> Wizard accessibility updates: Sequential flow colors

- templates/WinUI/Features/ThemeSelection/Services/ThemeSelectorService.cs
- templates/WinUI/Projects/Default/wts.ProjectName/App.xaml.cs
- templates/WinUI/_comp/MVVMToolkit/Project/Services/ActivationService.cs
Rename CurrentWindow to MainWindow in WinUI Templates
Rename CurrentWindow to MainWindow in generated WinUI Code #3993
> Rename CurrentWindow to MainWindow in WinUI Templates

- templates/WinUI/Features/ThemeSelection/Services/ThemeSelectorService.cs
Comment out read/save theme as workaround for issue 3984
#3984 Comment persisting theme as workaround for issue 3984
> Comment out persisting theme as workaround for issue 3984

- code/test/Fakes/Fakes.csproj
- templates/Wpf/_comp/_shared/Test.Core.SampleData.Grids.MSTest/.template.config/template.json
- templates/Wpf/_comp/_shared/Test.Core.SampleData.Grids.NUnit/.template.config/template.json
- templates/Wpf/_comp/_shared/Test.Core.SampleData.Grids.xUnit/.template.config/template.json
- Fix error in DataGrid Tests (WPF)
- Remove TemplateInterface reference
#4015
> Fix error in DataGrid Tests (WPF) + Remove TemplateInterface reference

- code/test/Fakes/Fakes.csproj
- templates/Wpf/_comp/_shared/Test.Core.SampleData.Grids.MSTest/.template.config/template.json
- templates/Wpf/_comp/_shared/Test.Core.SampleData.Grids.NUnit/.template.config/template.json
- templates/Wpf/_comp/_shared/Test.Core.SampleData.Grids.xUnit/.template.config/template.json
Fix error in DataGrid Tests (WPF)
Remove TemplateInterface reference
#4015
> Issue4015 fixwpftests

- templates/WinUI/Projects/Default/wts.ProjectName/Helpers/ResourceExtensions.cs
- templates/WinUI/Projects/Default/wts.ProjectName/Strings/en-us/Resources.resw
- templates/WinUI/_comp/MVVMToolkit/Project.SplitView/Views/ShellWindow.xaml.cs
Add AppTitle and Resw file to WinUI3 Apps
Set Title on ShellWindow for WinUI3 generated apps #3999
> Add AppTitle and Resw file to WinUI3 Apps

- templates/WinUI/_comp/MVVMToolkit/AddConnectedAnimation/Contracts/Services/INavigationService_postaction.cs
Fix StyleCop in WinUI3 Templates
Review and decouple VM from Views in Winui 3 #3908
> Fix StyleCop in WinUI3 Templates

- templates/WinUI/Features/SampleData/Param_ProjectName.Core/Contracts/Services/ISampleDataService.cs
- templates/WinUI/Features/SampleData/Param_ProjectName.Core/Models/SampleCompany.cs
- templates/WinUI/Features/SampleData/Param_ProjectName.Core/Models/SampleOrder.cs
- templates/WinUI/Features/SampleData/Param_ProjectName.Core/Models/SampleOrderDetail.cs
- templates/WinUI/Features/SampleData/Param_ProjectName.Core/Services/SampleDataService.cs
- templates/WinUI/Pages/ContentGrid/Param_ProjectName.Core/Services/SampleDataService$wts.ItemName_gpostaction.cs
- templates/WinUI/Pages/ContentGrid/Param_ProjectName/ViewModels/wts.ItemNameViewModel.cs
- templates/WinUI/Pages/DataGrid/Param_ProjectName.Core/Services/SampleDataService$wts.ItemName_gpostaction.cs
- templates/WinUI/Pages/DataGrid/Param_ProjectName/ViewModels/wts.ItemNameViewModel.cs
- templates/WinUI/Pages/DataGrid/Param_ProjectName/Views/wts.ItemNamePage.xaml.cs
- templates/WinUI/Pages/Form/Param_ProjectName.Core/Services/SampleDataService$wts.ItemName_gpostaction.cs
- templates/WinUI/Pages/MasterDetail/Param_ProjectName.Core/Services/SampleDataService$wts.ItemName_gpostaction.cs
- templates/WinUI/Pages/MasterDetail/Param_ProjectName/ViewModels/wts.ItemNameViewModel.cs
- templates/WinUI/Pages/Settings/Views/wts.ItemNamePage.xaml.cs
- templates/WinUI/Pages/WebView/Views/wts.ItemNamePage.xaml.cs
- templates/WinUI/Projects/Default/wts.ProjectName/App.xaml.cs
- templates/WinUI/_comp/MVVMToolkit/Project.SplitView/Views/ShellWindow.xaml.cs
- templates/WinUI/_comp/MVVMToolkit/Project/App_postaction.xaml.cs
WinUI3 apps comments review
Review comments in generated WinUI code #3996
> WinUI3 Apps Comments Review

- docs/roadmap.md
just updating the roadmap based on recent planning meeting
> Add MVVM Toolkit to the 3.10 milestone

- templates/WinUI/Projects/Default/wts.ProjectName/README.md
Add Readme.md to generated WinUI 3 projects
Add Readme.md to generated WinUI project #3995
> Issue3995 readme

- docs/WinUI/readme.md
- templates/WinUI/Pages/Form/Param_ProjectName/Strings/en-us/Resources_postaction.resw
- templates/WinUI/Pages/Form/Param_ProjectName/Views/wts.ItemNamePage.xaml
- templates/WinUI/Pages/MasterDetail/Param_ProjectName/Strings/en-us/Resources_postaction.resw
- templates/WinUI/Pages/MasterDetail/Param_ProjectName/Views/wts.ItemNamePage.xaml
- templates/WinUI/Pages/Settings/Strings/en-us/Resources_postaction.resw
- templates/WinUI/Pages/Settings/Views/wts.ItemNamePage.xaml
- templates/WinUI/Pages/WebView/Strings/en-us/Resources_postaction.resw
- templates/WinUI/Pages/WebView/Views/wts.ItemNamePage.xaml
- templates/WinUI/Projects/Default/wts.ProjectName/wts.ProjectName.csproj
- templates/WinUI/_comp/MVVMToolkit/Project.SplitView.AddNavigationViewItem/Strings/en-us/Resources_postaction.resw
- templates/WinUI/_comp/MVVMToolkit/Project.SplitView.AddNavigationViewItem/Views/ShellWindow_postaction.xaml
WinUI 3 Templates: Localized Resources with Resw
Use localized resources in generated WinUI projects #3994
MasterDetail page does not adapt the header with VisualStateManager in WinUI3 #4035
> WinUI 3 Templates: Localized Resources with Resw

- templates/WinUI/Pages/Settings/Strings/en-us/Resources_postaction.resw
- templates/WinUI/Pages/Settings/Views/wts.ItemNamePage.xaml
Add localized resources privacy statement URL in settings page templates WinUI 3
Use localized resources in generated WinUI projects #3994
> Add localized resources privacy statement URL

- mockup/WinUI3/WinUIDesktopApp (Package)/build/Microsoft.WinUI.AppX.targets
- mockup/WinUI3/WinUIDesktopApp/Contracts/Services/IWebViewService.cs
- mockup/WinUI3/WinUIDesktopApp/Properties/PublishProfiles/win10-arm64.pubxml
- mockup/WinUI3/WinUIDesktopApp/Properties/PublishProfiles/win10-x64.pubxml
- mockup/WinUI3/WinUIDesktopApp/Properties/PublishProfiles/win10-x86.pubxml
- mockup/WinUI3/WinUIDesktopApp/Services/ThemeSelectorService.cs
- mockup/WinUI3/WinUIDesktopApp/Services/WebViewService.cs
- mockup/WinUI3/WinUIDesktopApp/Strings/en-us/Resources.resw
- mockup/WinUI3/WinUIDesktopApp/ViewModels/ContentGridViewModel.cs
- mockup/WinUI3/WinUIDesktopApp/ViewModels/DataGridViewModel.cs
- mockup/WinUI3/WinUIDesktopApp/ViewModels/SettingsViewModel.cs
- mockup/WinUI3/WinUIDesktopApp/ViewModels/ShellViewModel.cs
- mockup/WinUI3/WinUIDesktopApp/ViewModels/WebViewViewModel.cs
- mockup/WinUI3/WinUIDesktopApp/Views/SettingsPage.xaml
- mockup/WinUI3/WinUIDesktopApp/WinUIDesktopApp.csproj
- mockup/WinUI3/WinUIDesktopApp/app.manifest
- mockup/WinUI3/nuget.config
Update WinUI 3 Mockup to Preview 4
Update WinUI3 Templates to Preview 4 #4064
> Update WinUI 3 Mockup to Preview 4

- mockup/WinUI3/WinUIDesktopApp (Package)/WinUIDesktopApp (Package).wapproj
Update WinUI 3 Mockup
Remove unnecesary SDKReference from winui packaging project
> Update WinUI 3 Mockup

- docs/WinUI/readme.md
Adding known issue to WinUI Docs
[WinUI 3384](https://github.com/microsoft/microsoft-ui-xaml/issues/3384)
> Adding known issue to WinUI Docs

- templates/WinUI/Features/MSIXPackaging/Param_ProjectName (Package)/Package.appinstaller
- templates/WinUI/Features/MSIXPackaging/Param_ProjectName (Package)/Param_ProjectName (Package).wapproj
Add Package.appinstaller to WinUI 3 MSIX project
WinUI 3 add Package.appinstaller in MSIX project #4078
> Add Package.appinstaller to WinUI 3 MSIX project

- templates/WinUI/Pages/WebView/Strings/en-us/Resources_postaction.resw
- templates/WinUI/Pages/WebView/Views/wts.ItemNamePage.xaml
- templates/WinUI/Pages/WebView/Views/wts.ItemNamePage.xaml.cs
Add Automation properties in WinUI 3 WebView page
Add localized automation name properties in WinUI #4066
> Add Automation properties in WinUI 3 WebView page

- docs/WinUI/readme.md
Add missing known issues to WinUI 3 docs
> Add missing known issues to WinUI 3 docs

- _build/ProjectTemplate-SetPublishingData.ps1
- code/src/ProjectTemplates/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.cs-CZ.vstemplate
- code/src/ProjectTemplates/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.de-DE.vstemplate
- code/src/ProjectTemplates/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.es-ES.vstemplate
- code/src/ProjectTemplates/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.fr-FR.vstemplate
- code/src/ProjectTemplates/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.it-IT.vstemplate
- code/src/ProjectTemplates/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.ja-JP.vstemplate
- code/src/ProjectTemplates/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.ko-KR.vstemplate
- code/src/ProjectTemplates/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.pl-PL.vstemplate
- code/src/ProjectTemplates/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.pt-BR.vstemplate
- code/src/ProjectTemplates/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.ru-RU.vstemplate
- code/src/ProjectTemplates/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.tr-TR.vstemplate
- code/src/ProjectTemplates/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.vstemplate
- code/src/ProjectTemplates/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.zh-CN.vstemplate
- code/src/ProjectTemplates/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.zh-TW.vstemplate
- docs/WinUI/readme.md
- Fix description and tags for WinUI C++ vstemplate 
- Update WinUI Docs
#4011 WinUI 3 C++ Templates (UWP and Desktop)
> Fix description and tags for WinUI C++ vstemplate and update WinUI Docs

- README.md
- Corrects grammar issue
- Use generic "documentation" term (rather than "Docs") to better indicate that links go to various documentation sources/sites
- Removes reference to StackOverflow as there are no links to it in any generated code
- Remove specific reference to "blogs" as there is only [a single link](https://blogs.windows.com/buildingapps/2016/10/14/web-to-app-linking-with-appurihandlers/) that is to a blog.
n/a - just a quick docs improvement while viewing docs
n/a - just docs
|  |  | |
no
**Do all …
> Update information about the generated code

- templates/WinUI/_comp/MVVMToolkit/Project/.template.config/template.json
Update Microsoft.Toolkit.Mvvm to Preview 5 in WinUI 3 Templates
Update WinUI MVVM Toolkit templates to Preview 5 #4104
> Update Microsoft.Toolkit.Mvvm to Preview 5 in WinUI 3 Templates

- code/src/UI/Extensions/UserSelectionContextExtensions.cs
- code/src/UI/Launcher/WizardLauncher.cs
- code/src/UI/UI.csproj
- code/src/UI/ViewModels/NewItem/ProjectConfigurationViewModel.cs
- code/src/UI/ViewModels/NewProject/MainViewModel.cs
- code/src/UI/VisualStudio/SolutionWizard.cs
- code/test/Templates.Test/BuildTemplatesTests/WinUI/BuildMVVMToolkitProjectTests.cs
- code/test/VsEmulator/Main/GeneratedProjectInfo.cs
- code/test/VsEmulator/Main/MainViewModel.cs
Add UserSelectionContextExtensions to simplify appmodel usage
Add support for AppModel filter in templates and composition queries
https://github.com/microsoft/CoreTemplateStudio/issues/287
> Add UserSelectionContextExtensions to simplify appmodel usage

- templates/WinUI/Projects/Default/wts.ProjectName/README.md
Improve Readme readability 
#3995 Add Readme.md to generated WinUI project
| No | No|Yes |
> Improve Readme readability 

- templates/Wpf/Pages/Settings.CodeBehind/Views/wts.ItemNamePage.xaml.cs
- templates/Wpf/Pages/Settings/ViewModels/wts.ItemNameViewModel.cs
Use localized version of the app name on the settings page.
#4128 
no
yes
n/a
n/a
- Be sure you reviewed the [Template Verification Checklist](https://github.com/microsoft/WindowsTemplateStudio/wiki/Checkl …
> Use localized app name on settings page [WPF]

- templates/WinUI/Pages/Settings/ViewModels/wts.ItemNameViewModel.cs
Use correctly localized application name on settings page (C#, WinUI3 Desktop)
For #4129 
| No | No| Yes |
no
yes
n/a
n/a
- Be sure you reviewed the [Template Verification …
> Correctly localize app name on settings page [WinUI3]

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Put the issue template instructions in comments so the person raising the issue is not forced to manually remove them to stop them being rendered as part of the text of an issue.
For #4134
n/a
|  |  | |
no
n/a
n/a
n/a
- …
> Put issue template instructions in comments

- templates/WinUI/Features/MSIX.Cpp/.template.config/template.json
- templates/WinUI/Features/MSIX/.template.config/template.json
- templates/WinUI/Features/MSIX/Param_ProjectName (Package)/Param_ProjectName (Package).wapproj
- templates/WinUI/Projects/Default.UWP/.template.config/template.json
- templates/WinUI/Projects/Default.UWP/wts.ProjectName/wts.ProjectName.csproj
Remove postactions generate test certificates from WinUI
Remove Certificate generation from WinUI3 templates #4112
> Remove Certificate generation from WinUI3 templates

- templates/WinUI/_comp/MVVMToolkit/Project/Contracts/Services/INavigationService.cs
- templates/WinUI/_comp/MVVMToolkit/Project/Services/NavigationService.cs
GoBack method in NavigationService should return true if the operation is done and false if not
NavigationService.GoBack should return bool #4076
> NavigationService.GoBack should return bool

- code/test/Templates.Test/BaseGenAndBuildTests.cs
- code/test/Templates.Test/BuildTemplatesTests/Uwp/BuildCaliburnMicroProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/Uwp/BuildCodeBehindProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/Uwp/BuildMVVMBasicProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/Uwp/BuildMVVMLightProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/Uwp/BuildPrismProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/Uwp/BuildToolkitMVVMProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/WinUI/BuildCodeBehindProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/WinUI/BuildMVVMToolkitProjectTests.cs
- code/test/Templates.Test/bat/WinUI/RestoreAndBuild.bat
- docs/getting-started-developers.md
- Run tests using VS 2019 (not preview)
- Update docs
- Add EnsureCanInferConfigInfo to WinUI tests
#4045 Review testing for WinUI3 templates
> Review WinUI testing

- docs/WinUI/readme.md
- templates/WinUI/Projects/Default/wts.ProjectName/README.md
Update docs for Project Reunion 0.5 Preview
#4148 Update WinUI Templates to use Project Reunion Nugets
> Update docs for Project Reunion 0.5 Preview

- templates/WinUI/Pages/WebView/Strings/en-us/Resources_postaction.resw
- templates/WinUI/Pages/WebView/Views/wts.ItemNamePage.xaml
- templates/WinUI/Pages/WebView/Views/wts.ItemNamePage.xaml.cs
Set AutomationProperties and Tooltip content using resw
Fix Tooltips + Automation Names in WinUI #4039
> Fix Tooltips + Automation Names in WinUI

- _build/ProjectTemplate-SetPublishingData.ps1
Fix ProjectTemplate script for class library templates
#4144
> Fix ProjectTemplate script for class library templates

- code/src/ProjectTemplates/WinUI/CS/CSharp.WinUI.Uwp.ClassLibrary/CSharp.WinUI.Uwp.ClassLibrary.vstemplate
- code/src/ProjectTemplates/WinUI/CS/CSharp.WinUI.Uwp.RuntimeComponent/CSharp.WinUI.Uwp.RuntimeComponent.vstemplate
- code/src/ProjectTemplates/WinUI/CS/CSharp.WinUI.Uwp.Solution/CSharp.WinUI.Uwp.Solution.cs-CZ.vstemplate
- code/src/ProjectTemplates/WinUI/CS/CSharp.WinUI.Uwp.Solution/CSharp.WinUI.Uwp.Solution.de-DE.vstemplate
- code/src/ProjectTemplates/WinUI/CS/CSharp.WinUI.Uwp.Solution/CSharp.WinUI.Uwp.Solution.es-ES.vstemplate
- code/src/ProjectTemplates/WinUI/CS/CSharp.WinUI.Uwp.Solution/CSharp.WinUI.Uwp.Solution.fr-FR.vstemplate
- code/src/ProjectTemplates/WinUI/CS/CSharp.WinUI.Uwp.Solution/CSharp.WinUI.Uwp.Solution.it-IT.vstemplate
- code/src/ProjectTemplates/WinUI/CS/CSharp.WinUI.Uwp.Solution/CSharp.WinUI.Uwp.Solution.ja-JP.vstemplate
- code/src/ProjectTemplates/WinUI/CS/CSharp.WinUI.Uwp.Solution/CSharp.WinUI.Uwp.Solution.ko-KR.vstemplate
- code/src/ProjectTemplates/WinUI/CS/CSharp.WinUI.Uwp.Solution/CSharp.WinUI.Uwp.Solution.pl-PL.vstemplate
- code/src/ProjectTemplates/WinUI/CS/CSharp.WinUI.Uwp.Solution/CSharp.WinUI.Uwp.Solution.pt-BR.vstemplate
- code/src/ProjectTemplates/WinUI/CS/CSharp.WinUI.Uwp.Solution/CSharp.WinUI.Uwp.Solution.ru-RU.vstemplate
- code/src/ProjectTemplates/WinUI/CS/CSharp.WinUI.Uwp.Solution/CSharp.WinUI.Uwp.Solution.tr-TR.vstemplate
- code/src/ProjectTemplates/WinUI/CS/CSharp.WinUI.Uwp.Solution/CSharp.WinUI.Uwp.Solution.vstemplate
- code/src/ProjectTemplates/WinUI/CS/CSharp.WinUI.Uwp.Solution/CSharp.WinUI.Uwp.Solution.zh-CN.vstemplate
- code/src/ProjectTemplates/WinUI/CS/CSharp.WinUI.Uwp.Solution/CSharp.WinUI.Uwp.Solution.zh-TW.vstemplate
- code/src/ProjectTemplates/WinUI/Cpp/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.cs-CZ.vstemplate
- code/src/ProjectTemplates/WinUI/Cpp/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.de-DE.vstemplate
- code/src/ProjectTemplates/WinUI/Cpp/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.es-ES.vstemplate
- code/src/ProjectTemplates/WinUI/Cpp/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.fr-FR.vstemplate
- code/src/ProjectTemplates/WinUI/Cpp/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.it-IT.vstemplate
- code/src/ProjectTemplates/WinUI/Cpp/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.ja-JP.vstemplate
- code/src/ProjectTemplates/WinUI/Cpp/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.ko-KR.vstemplate
- code/src/ProjectTemplates/WinUI/Cpp/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.pl-PL.vstemplate
- code/src/ProjectTemplates/WinUI/Cpp/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.pt-BR.vstemplate
- code/src/ProjectTemplates/WinUI/Cpp/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.ru-RU.vstemplate
- code/src/ProjectTemplates/WinUI/Cpp/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.tr-TR.vstemplate
- code/src/ProjectTemplates/WinUI/Cpp/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.vstemplate
- code/src/ProjectTemplates/WinUI/Cpp/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.zh-CN.vstemplate
- code/src/ProjectTemplates/WinUI/Cpp/Cpp.WinUI.UWP.Solution/Cpp.WinUI.UWP.Solution.zh-TW.vstemplate
Add PREVIEW flag to WinUI UWP entry points
> Add PREVIEW to WinUI UWP entry points

- templates/WinUI/Projects/Default/wts.ProjectName/README.md
Remove pfx reference from readme
#4112 Remove Certificate generation from WinUI3 templates
> Remove pfx reference from readme

- templates/Wpf/_comp/MVVMToolkit/Page.XamlIsland/Controls/wts.ItemNameControl_postaction.xaml.cs
Fix XAML Island MVVMToolkit template
XAML Island now throws error from generated code #4140
> Fix XAML Island MVVMToolkit

- code/test/UI.Test/VisualTests/AutomatedWizardTestingBase.cs
- code/test/UI.Test/VisualTests/CaptureWizardScreenshots.cs
- code/test/VsEmulator/Main/MainViewModel.cs
- Limit visualtest execution to VB and C#
- Automatically refresh cache when starting the emulator
> Smaller fixes after executing manualtests

- docs/telemetryData.md
> Update telemetry data for march

- templates/WinUI/Projects/Default/.template.config/template.json
Update Microsoft.Xaml.Behaviors.WinUI.Managed nuget package to release version
Update WinUI 3 templates to final WinUI version #4095
> Update WinUI Behaviors Nuget

- templates/Wpf/Projects/Default.Prism/.template.config/template.json
- templates/Wpf/_comp/Prism/Page.AddViewModel/Views/wts.ItemNamePage_postaction.xaml
- templates/Wpf/_comp/Prism/Page.AddViewModelDetail/Views/wts.ItemNameDetailPage_postaction.xaml
- templates/Wpf/_comp/Prism/Page.WebView/Views/wts.ItemNamePage_postaction.xaml
- templates/Wpf/_comp/Prism/Page.WebView/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/Wpf/_comp/Prism/Project.Blank/Views/ShellWindow.xaml
- templates/Wpf/_comp/Prism/Project.MenuBar/Views/ShellWindow.xaml
- templates/Wpf/_comp/Prism/Project.Ribbon/Views/ShellWindow.xaml
- templates/Wpf/_comp/Prism/Project.SplitView/Views/ShellWindow.xaml
- templates/Wpf/_comp/Prism/Service.IdentityForcedLogin/.template.config/template.json
- templates/Wpf/_comp/Prism/Service.IdentityForcedLogin/App_postaction.xaml.cs
- templates/Wpf/_comp/Prism/Service.IdentityOptionalLogin/.template.config/template.json
- templates/Wpf/_comp/Prism/Service.IdentityOptionalLogin/App_postaction.xaml.cs
Update current Prism Wpf templates to last version (8.0.0.1909).
Update Prism Wpf templates to version 8.0 #4006
> Update Prism Wpf templates to version 8.0

- templates/Uwp/Pages/Chart.CodeBehind/Views/ChartViewPage.xaml.cs
- templates/Uwp/Pages/Chart.Prism/Param_ProjectName/ViewModels/ChartViewViewModel.cs
- templates/Uwp/Pages/Chart/ViewModels/ChartViewViewModel.cs
- templates/Uwp/Pages/ImageGallery.CaliburnMicro/ViewModels/ImageGalleryViewDetailViewModel.cs
- templates/Uwp/Pages/ImageGallery.CaliburnMicro/ViewModels/ImageGalleryViewViewModel.cs
- templates/Uwp/Pages/ImageGallery.CodeBehind/Views/ImageGalleryViewDetailPage.xaml.cs
- templates/Uwp/Pages/ImageGallery.CodeBehind/Views/ImageGalleryViewPage.xaml.cs
- templates/Uwp/Pages/ImageGallery.Prism/Param_ProjectName/ViewModels/ImageGalleryViewDetailViewModel.cs
- templates/Uwp/Pages/ImageGallery.Prism/Param_ProjectName/ViewModels/ImageGalleryViewViewModel.cs
- templates/Uwp/Pages/ImageGallery/ViewModels/ImageGalleryViewDetailViewModel.cs
- templates/Uwp/Pages/ImageGallery/ViewModels/ImageGalleryViewViewModel.cs
- templates/Uwp/_comp/Prism/Page.ContentGrid.Blank.MenuBar/ViewModels/wts.ItemNameDetailViewModel_postaction.cs
- templates/Uwp/_comp/Prism/Page.ContentGrid.SplitView.TabbedNav/ViewModels/wts.ItemNameDetailViewModel_postaction.cs
- Remove remaining TODOS on ContentGrid, ImageGallery and ChartPage
#4038 Reduce instructions on removal of SampleData
UWP | WPF | WinUI
-- | -- | --
Yes | No| No
> Reduced TODOs for removing sample data

- templates/Wpf/Features/PersistAndRestore/.template.config/template.json
- templates/Wpf/Projects/Default.Prism/.template.config/template.json
- templates/Wpf/Projects/Default/.template.config/template.json
- templates/Wpf/Testing/UnitTests.App.MSTest/.template.config/template.json
- templates/Wpf/Testing/UnitTests.App.NUnit/.template.config/template.json
- templates/Wpf/Testing/UnitTests.App.xUnit/.template.config/template.json
- templates/Wpf/Testing/UnitTests.Core.MSTest/.template.config/template.json
- templates/Wpf/Testing/UnitTests.Core.NUnit/.template.config/template.json
- templates/Wpf/Testing/UnitTests.Core.xUnit/.template.config/template.json
- templates/Wpf/Testing/WinAppDriver/.template.config/template.json
- templates/Wpf/_comp/MVVMToolkit/Project/.template.config/template.json
- templates/Wpf/_comp/_shared/Service.IdentityCommon/.template.config/template.json
Update WPF nuget packages to latests versions
Update nuget packages in generated code #4187
_Updated packages_
Appium.WebDriver 4.3.1
coverlet.collector 3.0.3
MahApps.Metro 2.4.4
Microsoft.Extensions.Hosting 3.1.14
Microsoft.Extensions.Http 3.1.14
Microsoft.Extensions.Configuration 3.1.14
Microsoft.Extensions.Configuration.Binder 3.1.14
Microsoft.Extensions.Configuration.CommandLine 3.1.14
Microsoft.Extensions.Configuration.Json 3.1.14
Microsoft.Identity.Client 4.29.0
Microsoft.NET.Test.Sdk …
> [WPF] Update nuget packages in generated code

- docs/WPF/features/toast-notifications.md
Update docs adding App Life Cycle changes
WPF Feature: Toast Notifications #3614
> Update ToastNotification docs adding App Life Cycle changes

- templates/WinUI/_catalog/projectTypes.json
Set Blank project as default
Add Blank Project Type and CodeBehind Design Pattern to WinUI 3 Desktop Templates #4172
> WinUI [C#] Set Blank project as default

- templates/Uwp/_comp/_shared/Service.IdentityForcedLogin._VB/Param_ProjectName.Core/Services/IdentityService.vb
- templates/Uwp/_comp/_shared/Service.IdentityForcedLogin/Param_ProjectName.Core/Services/IdentityService.cs
- templates/Uwp/_comp/_shared/Service.IdentityOptionalLogin._VB/Param_ProjectName.Core/Services/IdentityService.vb
- templates/Uwp/_comp/_shared/Service.IdentityOptionalLogin/Param_ProjectName.Core/Services/IdentityService.cs
- templates/Wpf/_comp/_shared/Service.IdentityCommon/Param_ProjectName.Core/Contracts/Services/IIdentityService.cs
- templates/Wpf/_comp/_shared/Service.IdentityCommon/Param_ProjectName.Core/Services/IdentityService.cs
Update current Login service template to apply current Azure Active Directory changes
- Set Redirect Uri
- Add PersonalMicrosoftAccount type
https://docs.microsoft.com/azure/active-directory/develop/quickstart-register-app
Optional Login pair a Uwp crash #4211
| Yes | Yes |No |
> Fix Login personal account

- code/test/Templates.Test/BaseGenAndBuildFixture.cs
- code/test/Templates.Test/BuildTemplatesTests/BuildTemplatesTestFixture.cs
Avoid returning duplicated test setup for platforms that do not use appmodel
#4223 Duplicated test execution on build pipeline
> Avoid returning duplicated test setup for platforms that do not use appmodel

- templates/WinUI/Pages/Blank.Cpp/.template.config/template.json
- templates/WinUI/Projects/Default.Desktop._Cpp/.template.config/Layout.json
Remove option to add Blank pages on WinUI Destop C++ project
WinUI 3 C++ Templates (UWP and Desktop) #4011
> WinUI C++ Desktop remove Blank page

- code/test/Templates.Test/GenTests/LanguageComparisonTests.cs
- docs/UWP/services/identity.md
- docs/WPF/features/toast-notifications.md
- docs/WPF/services/identity.md
- templates/Uwp/Features/LiveTile._VB/Services/LiveTileFeatureService.Samples.vb
- templates/Uwp/Pages/Chart.CodeBehind._VB/Views/ChartViewPage.xaml.vb
- templates/Uwp/Pages/Chart._VB/ViewModels/ChartViewViewModel.vb
- templates/Uwp/Pages/ImageGallery.CodeBehind._VB/Views/ImageGalleryViewDetailPage.xaml.vb
- templates/Uwp/Pages/ImageGallery.CodeBehind._VB/Views/ImageGalleryViewPage.xaml.vb
- templates/Uwp/Pages/ImageGallery._VB/ViewModels/ImageGalleryViewDetailViewModel.vb
- templates/Uwp/Pages/ImageGallery._VB/ViewModels/ImageGalleryViewViewModel.vb
- Remove comments from VB files that were removed from C# files
- Remove invalid links
- Add new method to identity docs
> Fixes from executing manualtests

- mockup/WinUI3/WinUIDesktopApp/WinUIDesktopApp/WinUIDesktopApp.vcxproj
- mockup/WinUI3/WinUIDesktopApp/WinUIDesktopApp/packages.config
Update branch WinUI cpp Mockup to Reunion 0.5.5
> Update WinUI cpp Mockup to Reunion 0.5.5

- templates/Wpf/_catalog/cs-CZ.frontendframeworks.json
> Fix cs-CZ.frontendframeworks.json

- code/tools/Localization/Logic/LocalizableItemsExtractor.cs
- code/tools/Localization/Logic/LocalizableItemsVerificator.cs
- code/tools/Localization/Logic/OriginalLocalizableItemsExtractor.cs
- code/tools/Localization/Logic/Routes.cs
- templates/WinUI/_catalog/projectTypes/pl-PL.Blank.md
- Update Localization Tool to support WinUI templates
- Update missing templates translations in WinUI templates
#4046 - Include WinUI3 in tooling
> Add win UI support to localization tool

- docs/WinUI/readme.md
- List all entry points for WinUI
- Remove closed issues
#4217 Update WinUI Docs after update to reunion 0.5.5
> Update readme.md after update to reunion 0.5.5

- code/src/Installer/Installer.csproj
- code/src/Installer/source.extension.vsixmanifest
Disable UWP templates for WinUI3 on .vsix
- C#/C++ UWP Solution
- UWP Class Library
- UWP Runtime Component
Disable UWP templates for WinUI3 #4239
> Disable UWP templates for WinUI3

- code/src/UI/VisualStudio/RightClickActions.cs
- code/test/VsEmulator/Main/GeneratedProjectInfo.cs
- code/test/VsEmulator/Main/MainViewModel.cs
- Disable rightclick on Blank WinUI projects
- #4042 Review right click support on WinUI
> Disable rightclick on Blank WinUI projects

- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
- code/src/UI/Styles/Button.xaml
- code/src/UI/Styles/Image.xaml
- code/src/UI/Styles/_DrawingImage.xaml
- code/src/UI/ViewModels/Common/BaseMainViewModel.cs
- code/src/UI/ViewModels/Common/WizardNavigation.cs
- code/src/UI/Views/Common/ErrorDialog.xaml
- code/src/UI/Views/Common/InfoDialog.xaml
- code/src/UI/Views/Common/QuestionDialogWindow.xaml
- code/src/UI/Views/NewItem/MainPage.xaml.cs
- code/src/UI/Views/NewItem/ProjectConfigurationDialog.xaml
- code/src/UI/Views/NewItem/WizardShell.xaml
- code/src/UI/Views/NewProject/MainPage.xaml.cs
- code/src/UI/Views/NewProject/WizardShell.xaml
Add Maximize-Restore window button in wizard
Wizard stuck in full screen when magnetizing with top of screen #4185
|  Yes | Yes | Yes |
> Add Maximize-Restore window button in wizard

- templates/WinUI/projectNameValidation.config.json
Remove reservedNames from WinUI project names validation rules
Review WinUI name validation rules #4043
> Review WinUI validation rules

- mockup/WinUI3/WinUIDesktopApp (Package)/WinUIDesktopApp (Package).wapproj
- mockup/WinUI3/WinUIDesktopApp/WinUIDesktopApp.csproj
Update Mockup WinUI3 to Reunion 0.5.6
Update WinUI templates to Project Reunion 0.5.6 #4250
| No|No |Yes |
> Update Mockup WinUI3 to Reunion 0.5.6

- mockup/WinUI3/WinUIDesktopApp/WinUIDesktopApp (Package)/WinUIDesktopApp (Package).wapproj
- mockup/WinUI3/WinUIDesktopApp/WinUIDesktopApp/WinUIDesktopApp.vcxproj
- mockup/WinUI3/WinUIDesktopApp/WinUIDesktopApp/packages.config
Update Mockup WinUI Cpp to reunion 0.5.6
Update WinUI templates to Project Reunion 0.5.6 #4250
> Update Mockup WinUI Cpp to reunion 0.5.6

- templates/WinUI/Pages/Form/.template.config/template.json
Hide WinUI FormPage from WTS wizard
Add a page that uses form validation #2293
> Hidde WinUI FormPage

- code/src/ProjectTemplates/WinUI/CS/CSharp.WinUI.Uwp.ClassLibrary/CSharp.WinUI.Uwp.ClassLibrary.vstemplate
- code/src/ProjectTemplates/WinUI/CS/CSharp.WinUI.Uwp.ClassLibrary/ProjectTemplate.csproj
WinUI 3 Runtime Component remove target framework and certificate
WinUI 3 UWP and Desktop Class Libraries #4144
> WinUI 3 Class Librariy remove target framework

- README.md
- docs/roadmap.md
- Add MVVMToolkit to main readme
- Update roadmap
> Update docs after 3.10 release

- templates/WinUI/Projects/Default/wts.ProjectName/README.md
> Update README.md with latest changes on WinUI templates

- code/src/Installer/source.extension.vsixmanifest
Add WinUI3 to vsix description and tags
#3810
> Add WinUI3 to vsix description and tags

- code/src/ItemTemplates/WinUI/Cpp/Cpp.WinUI.BlankPage/BlankPage.xaml
- code/src/ItemTemplates/WinUI/Cpp/Cpp.WinUI.Desktop.BlankWindow/BlankWindow.xaml
- code/src/ItemTemplates/WinUI/Cpp/Cpp.WinUI.UserControl/UserControl.xaml
- templates/WinUI/Pages/Blank.Cpp/wts.ItemNamePage.xaml
- templates/WinUI/Pages/Blank.Cpp/wts.ItemNamePage.xaml.cpp
- templates/WinUI/Pages/Blank.Cpp/wts.ItemNamePage.xaml.h
- templates/WinUI/Pages/Blank.UWP/wts.ItemNamePage.xaml
- templates/WinUI/Pages/Blank.UWP/wts.ItemNamePage.xaml.cs
- templates/WinUI/Projects/Default.Blank/wts.ProjectName/MainWindow.xaml
- templates/WinUI/Projects/Default.Desktop._Cpp/wts.ProjectName/MainWindow.xaml
- templates/WinUI/_comp/_shared/Page.AddClickMeButton.Cpp/.template.config/template.json
- templates/WinUI/_comp/_shared/Page.AddClickMeButton.Cpp/wts.ItemNamePage_postaction.xaml
- templates/WinUI/_comp/_shared/Page.AddClickMeButton.Cpp/wts.ItemNamePage_postaction.xaml.cpp
- templates/WinUI/_comp/_shared/Page.AddClickMeButton.Cpp/wts.ItemNamePage_postaction.xaml.h
- templates/WinUI/_comp/_shared/Page.AddClickMeButton/.template.config/template.json
- templates/WinUI/_comp/_shared/Page.AddClickMeButton/wts.ItemNamePage_postaction.xaml
- templates/WinUI/_comp/_shared/Page.AddClickMeButton/wts.ItemNamePage_postaction.xaml.cs
- Update Xaml code in Blank page and Blank window for C# and C++ projects
- Update Xaml code from item templates
- Add "ClickMe" button to a composition template in order to only have this button in the home page, having less code to remove.
Review generated code for BlankWindow on Blank/None project #4275
> Review blank window code

- code/test/Templates.Test/BaseGenAndBuildTests.cs
- code/test/Templates.Test/Templates.Test.csproj
- code/test/Templates.Test/WACK/WinUI/WindowsAppCertKitTests.cs
- code/test/Templates.Test/bat/WinUI/RestoreAndBuildAppx.bat
- Add wack tests to WinUI C# projects
- #4276 - Add WACK tests for WinUI
> Add wack tests to WinUI C# projects

- code/src/UI/Services/ProjectConfigInfoService.cs
- code/test/Templates.Test/BaseGenAndBuildFixture.cs
- code/test/Templates.Test/BaseGenAndBuildTests.cs
- code/test/Templates.Test/BuildTemplatesTests/WinUI/BuildNoneProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/Wpf/BuildCodeBehindProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/Wpf/BuildMVVMBasicProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/Wpf/BuildMVVMLightProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/Wpf/BuildPrismProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/Wpf/BuildToolkitMVVMProjectTests.cs
- code/test/Templates.Test/Templates.Test.csproj
- code/test/Templates.Test/WACK/WinUI/WindowsAppCertKitTests.cs
- code/test/Templates.Test/bat/WinUI/RestoreAndBuildCpp.bat
- code/test/Templates.Test/bat/WinUI/RestoreAndBuildCppAppx.bat
- Added template test to C++ WinUI projects
- Added wack test to C++ WinUI projects
- Update nuget.exe in tools
#4099 - Add template tests for WinUI C++ projects
> Added tests to C++ WinUI projects

- templates/WinUI/Projects/Default.Blank/wts.ProjectName/App.xaml.cs
- templates/WinUI/Projects/Default.Blank/wts.ProjectName/wts.ProjectName.csproj
- templates/WinUI/Projects/Default/wts.ProjectName/App.xaml.cs
- templates/WinUI/Projects/Default/wts.ProjectName/wts.ProjectName.csproj
Fix grammar in TODO comment
#4307 Fix grammar in TODO comment
> Fix grammar in TODO comment

- code/test/VsEmulator/Main/MainViewModel.cs
Remove force refresh templates when VsEmulator starts
Remove force refresh templates when emulator starts #4324
> Remove force refresh when emulator starts

- code/src/UI/Styles/DataTemplate.xaml
- code/src/UI/Styles/ImageEx.xaml
- code/src/UI/Styles/TextBlock.xaml
- code/src/UI/Views/NewProject/MainPage.xaml
Remove unnecessary bindings that generate Binding Failures
Review Binding Failures on Wizard #4299
> Fix Wizard Binding Failures

- code/src/UI/VisualStudio/RightClickActions.cs
- code/src/UI/VisualStudio/SolutionWizard.cs
Add usings for release configuration
#4301 Review Code suggestions on Wizard
> Fix release build

- code/src/UI/VisualStudio/SolutionWizard.cs
Fix variable name
#4304 Unify SolutionWizard files
> Fix variable name

- CONTRIBUTING.md
- docs/UWP/getting-started-endusers.md
- docs/WTSNaming.md
- docs/getting-started-extension.md
> Last doc update

- code/src/UI/Services/ProjectConfigInfoService.cs
Add infer for WinUI Menubar project type
https://winappstudio.visualstudio.com/WTS/_build/results?buildId=37648&view=results
> Add infer for WinUI Menubar project type

- docs/getting-started-developers.md
- docs/templates.md
* Add entry points
* Add item templates folder
* Add important folder for troubleshooting
* Fix links
> Doc updates

- templates/WinUI/Pages/ContentGrid/.template.config/template.json
- templates/WinUI/Pages/ListDetails/.template.config/template.json
Fix pages order in WinUI Templates
Unify page order in WinUI #4331
> Fix pages order in WinUI Templates

- templates/WinUI/_comp/MVVMToolkit/Project.MenuBar/Views/ShellPage.xaml
Fix renaming HomePage
Add MenuBar project type for WinUI #4338
> WinUI MenuBar - fix renaming HomePage

- templates/Wpf/Features/XamlIslandUwpApp/Param_ProjectName.XamlIsland/Param_ProjectName.XamlIsland.csproj
- templates/Wpf/Features/XamlIslandUwpApp/Param_ProjectName.XamlIslandApp/Param_ProjectName.XamlIslandApp.csproj
- templates/Wpf/_comp/_shared/Service.IdentityCommon/.template.config/template.json
Update nuget packages in generated code for WPF
_Updated packages_
Microsoft.Identity.Client 4.33.0
Microsoft.Extensions.Http 3.1.16
Microsoft.NETCore.UniversalWindowsPlatform 6.2.12
Update nuget packages in generated code #4346
> Fix update nugets wpf

- README.md
- docs/WinUI/projectTypes/blankadvanced.md
- docs/WinUI/projectTypes/menubar.md
- templates/WinUI/_catalog/projectTypes/BlankAdvanced.md
Add missing WinUI MenuBar docs
> Add WinUI MenuBar docs

- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
- templates/WinUI/_catalog/es-ES.projectTypes.json
- templates/WinUI/_catalog/projectTypes/es-ES.Blank.md
- templates/WinUI/_catalog/projectTypes/es-ES.BlankAdvanced.md
- Fix spanish translations in WinUI Templates
- Fix Wizard title translations for WinUI 3 apps
Review texts before 4.1. Release #4362
> Review Texts

- code/test/UI.Test/ProjectConfigurationTests/ProjectTemplateConfigurationTest.cs
- code/test/UI.Test/TestData/Templates/test/Pages/TestPageTemplate/.template.config/template.json
- code/test/UI.Test/TestData/Templates/test/Projects/TestProjectTemplate/.template.config/template.json
- code/test/UI.Test/TestData/Templates/test/Projects/TestSecondProjectType/.template.config/template.json
- code/test/UI.Test/TestData/Templates/test/_catalog/frontendframeworks.json
- code/test/UI.Test/TestData/Templates/test/_catalog/frontendframeworks/TestSecondFramework.md
- code/test/UI.Test/UI.Test.csproj
Add UI.Test to check selected updated Framework
Review and update UI.Tests #4332
> UI.Tests - Add test update Framework

- templates/Wpf/Projects/Default.Prism/wts.ProjectName/App.xaml.cs
- templates/Wpf/Projects/Default/wts.ProjectName/App.xaml.cs
* Fixed typo's in App.xaml.cs for the wpf templates
|  No  | Yes  | No |
> Minor typo corrections in WPF templates

- _build/pipelines/ci.yml
- _build/pipelines/pr.yml
- _build/pipelines/templates.tests.full.yml
- _build/pipelines/templates.tests.onebyone.yml
- _build/pipelines/templates.tests.wack.yml
Checked in existing CI pipelines as YAML so we have a baseline to work from going forward.
> Converted ADO Pipelines to YAML

- docs/roadmap.md
Quick doc fix to clarify the year in the roadmap
> Clarify which year this refers to ;)

- code/SharedFunctionality.Core/Templates/ITemplateInfoExtensions.cs
this is just a bit of tidying up in the code, so I can make a PR and see the new checks being run against it. :)
> remove some old commented out code

- _utils/Set-All-Text-File-Template-Encodings.ps1
> Update /_utils/Set-All-Text-File-Template-Encodings.ps1 to support PowerShell Core

- code/SharedFunctionality.UI/ViewModels/Common/WizardStatus.cs
Benefits from latest form templates and removes stale WTS references.
#4426
ALL
- Be sure it's included in the list on this [UWP](https://github.com/microsoft/WindowsTemplateStudio/blob/ …
> Link to issue chooser for report issue.

- _build/CodeSign_ExtractFilesToSign.ps1
- _build/CodeSign_IncludeSignedFiles.ps1
- _build/pipelines/release.yml
- code/Nuget.Config
The pipeline produces production signed release builds of the extensions.
It does not run any tests right now.
> Updated the release pipeline

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Moved the PR template to .github and added checkboxes for platforms.
|  |  |  |
- Be sure you reviewed the [Template Verification Checklist](https://github.com/microsoft/WindowsTemplateStudio/wiki/Checklist:-Template-Ver …
> PR template changes

- _build/pipelines/ci.yml
- code/TemplateStudio.SharedTests.CI.slnf
to be used in the PR pipeline
For #4438 …
> Add solution filter for shared tests

- README.md
> Updated the Build Status section for the new pipelines.

- code/TemplateStudioForWinUICs/Templates/Proj/Default/Param_ProjectName/README.md
> Updated wts URL in README.md.

- code/test/SharedFunctionality.Tests/TemplateValidator/TemplateJsonVerifier.cs
- code/tools/Localization/Logic/LocalizableItemsVerificator.cs
Internal only references but further reduces the noise when you search for "wts" in the repo. …
> Renamed all VerifyWts references.

- code/SharedFunctionality.UI/Controls/MarkdownBlock.xaml
- code/SharedFunctionality.UI/Controls/MarkdownBlock.xaml.cs
- code/SharedFunctionality.UI/Controls/NotificationMarkdownBlock.xaml
- code/SharedFunctionality.UI/Controls/NotificationMarkdownBlock.xaml.cs
- code/SharedFunctionality.UI/Controls/NotificationsControl.xaml
- code/SharedFunctionality.UI/Controls/SequentialFlow.xaml
- code/SharedFunctionality.UI/Converters/SavedTemplateGridConverter.cs
- code/SharedFunctionality.UI/Views/Common/CompositionToolWindow.xaml
- code/SharedFunctionality.UI/Views/Common/ErrorDialog.xaml
- code/SharedFunctionality.UI/Views/Common/InfoDialog.xaml
- code/SharedFunctionality.UI/Views/Common/QuestionDialogWindow.xaml
- code/SharedFunctionality.UI/Views/Common/TemplateInfoPage.xaml
- code/SharedFunctionality.UI/Views/NewItem/ChangesSummaryPage.xaml
- code/SharedFunctionality.UI/Views/NewItem/NewItemMainPage.xaml
- code/SharedFunctionality.UI/Views/NewItem/NewItemWizardShell.xaml
- code/SharedFunctionality.UI/Views/NewItem/ProjectConfigurationDialog.xaml
- code/SharedFunctionality.UI/Views/NewItem/TemplateSelectionPage.xaml
- code/SharedFunctionality.UI/Views/NewProject/FrameworkPage.xaml
- code/SharedFunctionality.UI/Views/NewProject/NewProjectMainPage.xaml
- code/SharedFunctionality.UI/Views/NewProject/NewProjectWizardShell.xaml
- code/SharedFunctionality.UI/Views/NewProject/ProjectTypePage.xaml
- code/SharedFunctionality.UI/Views/NewProject/TemplatesStepPage.xaml
- code/SharedStyles/TemplateStudioStyles.xaml
Renamed Wts style names to TS and all references.
#4396 
- Be sure it's included in the list on this [UWP](https://github.com/microsoft/TemplateStudio/blob/main/docs/UWP/getting-started-enduser …
> Updated Wts references in SharedStyles

- _build/pipelines/release.yml
- code/TemplateStudioForUWP/CoreTemplateStudio.config.json
- code/TemplateStudioForUWP/TemplateStudioForUWP.csproj
- code/TemplateStudioForWPF/CoreTemplateStudio.config.json
- code/TemplateStudioForWPF/TemplateStudioForWPF.csproj
- code/TemplateStudioForWinUICpp/CoreTemplateStudio.config.json
- code/TemplateStudioForWinUICpp/TemplateStudioForWinUICpp.csproj
- code/TemplateStudioForWinUICs/CoreTemplateStudio.config.json
- code/TemplateStudioForWinUICs/TemplateStudioForWinUICs.csproj
> Configure telemetry service as part of the release pipeline

- CONTRIBUTING.md
just docs
#4468 
nope
assume so - just a docs change without links
n/a - just a docs change 
n/a - just a docs change  …
> Add note about working with the shared extension code

- code/TemplateStudioForWinUICs/Templates/Pg/WebView/Views/Param_ItemNamePage.xaml
Changed the FontFamily to SymbolThemeFontFamily so it will pick up Fluent Icons on Win11.
#4463
Check if the CI pipelines behave as expected. Only the WinUI (C#) and Shared pipelines should be run for this change.
- Be sure you reviewed the [Template Verification Checklist](https://github.com/microsoft/TemplateStudio/wiki/Checklist:-Tem …
> Updated the FontFamily in WebView pages.

- code/TemplateStudioForWinUICs/TemplateStudioForWinUICs.csproj
- code/TemplateStudioForWinUICs/Templates/Proj/Default/.vsconfig
> Add .vsconfig to install missing VS components

- README.md
As nightly builds are no longer created …
> Remove known issue about nightly builds

- CONTRIBUTING.md
- _utils/Set-All-Text-File-Template-Encodings.ps1
- code/SharedResources/StringRes.Designer.cs
- code/SharedResources/StringRes.resx
- code/TemplateStudioForWinUICs/TemplateStudioForWinUICs.csproj
- code/TemplateStudioForWinUICs/Templates/Ft/SelfContained/.template.config/description.md
- code/TemplateStudioForWinUICs/Templates/Ft/SelfContained/.template.config/icon.xaml
- code/TemplateStudioForWinUICs/Templates/Ft/SelfContained/.template.config/template.json
- code/TemplateStudioForWinUICs/Templates/Ft/SelfContained/Param_ProjectName_postaction.csproj
- code/TemplateStudioForWinUICs/Templates/Proj/Default/.template.config/template.json
Temporarily referencing WinAppSDK 1.1-preview3 until 1.1 ships.
#4476
Notice that all CI pipelines were triggered by the change to SharedResources. …
> Added self-contained deployment

- code/TemplateStudioForWinUICs/Templates/Ft/SelfContained/Param_ProjectName_postaction.csproj
There's a bug in 1.1 that requires this additional target. Once the bug is fixed, this will still work, though we can remove it in a future update. …
> Added self-contained target that's required for 1.1.

- code/TemplateStudioForWinUICs/TemplateStudioForWinUICs.csproj
- code/TemplateStudioForWinUICs/Templates/Pg/WebView/Views/Param_ItemNamePage.xaml.cs
- code/TemplateStudioForWinUICs/Templates/Proj/Default/.template.config/template.json
- code/TemplateStudioForWinUICs/Templates/Proj/Default/Param_ProjectName/App.xaml.cs
- code/TemplateStudioForWinUICs/Templates/Proj/Default/Param_ProjectName/Usings.cs
- code/TemplateStudioForWinUICs/Templates/_comp/MT/Project.MenuBar/Views/ShellPage.xaml
- code/TemplateStudioForWinUICs/Templates/_comp/MT/Project.NavView/Views/ShellPage.xaml
- code/TemplateStudioForWinUICs/Templates/_comp/MT/Project/App_postaction.xaml.cs
Integrated WinUIEx to address gaps in Windowing:
* Adds Mica support just by setting the Backdrop property
* Persist window size and position for MSIX apps by setting PersistenceId (see https://github.com/dotMorten/WinUIEx/issues/61 for unpackaged)
* Convenience properties for setting things like MinWidth/Height, IsAlwaysOnTop, IsResizable, etc.
* Extension methods added to MainWindow that wrap P/Invokes to commonly needed APIs
#4529 
#4368 
@dotmorten please review. Based on https://github.com/dotMorten/WinUIEx/issues/62#issuecomment-1175627509, I added a global using for WinUIEx so the extension methods are available …
> Integrated WinUIEx

- code/TemplateStudioForWinUICs/fr-FR/Extension.vsixlangpack
Finish translation of Extension name & description for French language.
Any
Nothing
Didn't tested
No …
> Translate name of extension in French

- code/TemplateStudioForWinUICs/Templates/Proj/Default/.template.config/template.json
This PR update WindowsAppSDK to 1.2.230217.4 (https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.2.230217.4)
> Update WindowsAppSDK to 1.2.230217.4

- code/SharedFunctionality.UI/Services/BreakingChangesValidatorService.cs
- code/SharedFunctionality.UI/SharedFunctionality.UI.projitems
- code/SharedFunctionality.UI/Validators/UsesVersionSevenOfMvvmToolkitValidator.cs
- code/SharedResources/Resources.Designer.cs
- code/SharedResources/Resources.resx
- code/SharedStyles/AllStylesDictionary.cs
- code/TemplateStudioForWinUICs/CoreTemplateStudio.config.json
- code/TemplateStudioForWinUICs/Templates/Pg/Blank/ViewModels/Param_ItemNameViewModel.cs
- code/TemplateStudioForWinUICs/Templates/Pg/CGrid/Param_ProjectName.Core/Services/SampleDataService$Param_ItemName_gpostaction.cs
- code/TemplateStudioForWinUICs/Templates/Pg/CGrid/Param_ProjectName/ViewModels/Param_ItemNameDetailViewModel.cs
- code/TemplateStudioForWinUICs/Templates/Pg/CGrid/Param_ProjectName/ViewModels/Param_ItemNameViewModel.cs
- code/TemplateStudioForWinUICs/Templates/Pg/DGrid/Param_ProjectName.Core/Services/SampleDataService$Param_ItemName_gpostaction.cs
- code/TemplateStudioForWinUICs/Templates/Pg/DGrid/Param_ProjectName/ViewModels/Param_ItemNameViewModel.cs
- code/TemplateStudioForWinUICs/Templates/Pg/Form/Param_ProjectName.Core/Services/SampleDataService$Param_ItemName_gpostaction.cs
- code/TemplateStudioForWinUICs/Templates/Pg/List/Param_ProjectName.Core/Services/SampleDataService$Param_ItemName_gpostaction.cs
- code/TemplateStudioForWinUICs/Templates/Pg/List/Param_ProjectName/ViewModels/Param_ItemNameViewModel.cs
- code/TemplateStudioForWinUICs/Templates/Pg/Settings/ViewModels/Param_ItemNameViewModel.cs
- code/TemplateStudioForWinUICs/Templates/Pg/WebView/ViewModels/Param_ItemNameViewModel.cs
- code/TemplateStudioForWinUICs/Templates/_catalog/FrontendFrameworks/FrontendFrameworks.json
- code/TemplateStudioForWinUICs/Templates/_comp/MT/Page.AddBackCommand/ViewModels/Param_ItemNameDetailViewModel_postaction.cs
- code/TemplateStudioForWinUICs/Templates/_comp/MT/Project.MenuBar.AddMenuItem.Settings/ViewModels/ShellViewModel_postaction.cs
- code/TemplateStudioForWinUICs/Templates/_comp/MT/Project.MenuBar.AddMenuItem/ViewModels/ShellViewModel_postaction.cs
- code/TemplateStudioForWinUICs/Templates/_comp/MT/Project.MenuBar/ViewModels/ShellViewModel.cs
- code/TemplateStudioForWinUICs/Templates/_comp/MT/Project.NavView.AddNavViewItem.Settings/ViewModels/ShellViewModel_postaction.cs
- code/TemplateStudioForWinUICs/Templates/_comp/MT/Project.NavView/ViewModels/ShellViewModel.cs
- code/TemplateStudioForWinUICs/Templates/_comp/MT/Project/.template.config/template.json
- code/test/VsEmulator/CoreTemplateStudio.config.json
- code/test/VsEmulator/Main/MainViewModel.cs
- docs/WinUI/frameworks/mvvmtoolkit-upgrate-to-version8.md
- Update MVVM Toolkit to v8.1.0
- Update templates to take advantage of SourceGenerator capabilities in the new version
- Added breaking change detector
fixes #4640
I haven't changed the use of ICommands in the Settings, and WebView pages, as these use lambdas rather than named methods.
Breaking changes displayed using the built-in breaking change UI:
yes
No new features, just changes to existing ones.
Breaking change update manually tested by creating an app with the current public release and then using VSEmulator to trigger the Add …
> Update to CommunityToolkit.MVVM v 8.1.0

- code/TemplateStudioForWinUICs/Templates/Pg/WebView/ViewModels/Param_ItemNameViewModel.cs
> using community toolkit mvvm in viewmodel of webview

- code/TemplateStudioForWinUICs/Templates/Proj/Default/.template.config/template.json
This PR update WindowsAppSDK to 1.2.230217.4 (https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.2.230313.1)
> Update WindowsAppSDK to 1.2.230313.1

- code/TemplateStudioForWinUICs/Templates/Proj/Default/.template.config/template.json
https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.3.230331000
If someone has an error with the compiler (manual tests) it is normal ^^.
https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#known-issue
> Update Windows App SDK to 1.3.230331000

- code/TemplateStudioForWinUICpp/Templates/Projects/Default/.template.config/template.json
https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.3.230331000
> Update Windows App SDK to 1.3.230331000 for WinUICpp

- README.md
- code/TemplateStudioForWinUICs/TemplateStudioForWinUICs.csproj
- code/TemplateStudioForWinUICs/Templates/Ft/ThemeSelection/Services/ThemeSelectorService.cs
- code/TemplateStudioForWinUICs/Templates/Proj/Default/Param_ProjectName/App.xaml
- code/TemplateStudioForWinUICs/Templates/Proj/Default/Param_ProjectName/Helpers/TitleBarHelper.cs
- code/TemplateStudioForWinUICs/Templates/_comp/MT/Project.MenuBar/Views/ShellPage.xaml.cs
- code/TemplateStudioForWinUICs/Templates/_comp/MT/Project.NavView/Views/ShellPage.xaml.cs
Reverts microsoft/TemplateStudio#4621
> Revert "Removes workaround theming code for WinUI 3 custom titlebar"  => solving title bar problem when changing theme

- code/TemplateStudioForWinUICs/Templates/Proj/Default/.template.config/template.json
All is in the title ^^.
This should be merged after #4666 ^^.
> Update to WinUIEx 2.2

- code/TemplateStudioForWinUICs/Templates/Proj/Default/.template.config/template.json
All is in the title ^^.
https://www.nuget.org/packages/WinUIEx/
> Fix WinUIEx License
