- templates/Features/HubNotifications/Services/ActivationService_postaction.cs
- templates/Features/SuspendAndResume/Services/SuspendAndResumeService.cs
> Fix comment case inconsistency

- code/src/Core/PostActions/Catalog/SortUsings/IEnumerableExtensions.cs
- code/test/Core.Test/PostActions/Catalog/SortUsingsTest.cs
> Ensure that generated code file won't contain repeated using statements

- templates/_composition/MVVMBasic/Page.AddViewModel/ViewModels/wts.ItemNameViewModel_postaction.cs
> Remove duplicate using statement

- docs/getting-started-extension.md
> Updated prereqs to state VS2017 v15.1 or higher

- code/src/UI/Styles/StyleTextBlock.xaml
> ensure author text is fully visible

- templates/Pages/WebView.CodeBehind/.template.config/template.json
- templates/Pages/WebView/.template.config/template.json
> update WebView page version No. to indicate that it's changed

- code/src/UI/VisualStudio/SolutionWizard.cs
> Delete created folder only on WizardBackoutException

- code/src/Core/Extensions/VersionExtensions.cs
- code/src/Core/Locations/LocalTemplatesSource.cs
- code/src/Core/Locations/TemplatesSynchronization.cs
- code/src/Installer.2017/app.config
- code/src/UI/app.config
- code/test/Core.Test/Locations/UnitTestTemplatesSource.cs
- code/test/Templates.Test/App.config
- code/test/VsEmulator/App.config
> Ensure no colision while updating local templates

- templates/_composition/CodeBehind/Project.SplitView/Views/ShellPage.xaml
- templates/_composition/MVVMBasic/Project.SplitView/Views/ShellPage.xaml
- templates/_composition/MVVMLight/Project.SplitView/Views/ShellPage.xaml
Changes based on January redlines
#364
> Fix styling of Nav Menu items

- docs/changelog.md
- docs/roadmap.md
- docs/templates.md
Simple link fix in the documentation.
> Fix broken link to _composition folder.

- templates/_composition/MVVMLight/Feature.SuspendAndResume.AddNavigation/Services/SuspendAndResumeService_postaction.cs
- templates/_composition/_shared/Feature.SuspendAndResume.AddNavigation/Services/SuspendAndResumeService_postaction.cs
> Fix New application crash on resume #422

- code/src/UI/VisualStudio/VsGenShell.cs
This avoid to let the solution with errors and not building as described in #418
> Avoid automatic nuget restore if no internet connection available

- templates/Projects/Default/.template.config/template.json
> Include dataType definition for wts.wizardVersion Symbol definition. 

- templates/Features/StoreNotifications/Services/StoreNotificationsFeatureService.cs
> Fix async warning

- templates/_composition/CodeBehind/Project.SplitView/Views/ShellPage.xaml.cs
- templates/_composition/MVVMBasic/Project.SplitView/ViewModels/ShellViewModel.cs
- templates/_composition/MVVMLight/Project.SplitView/ViewModels/ShellViewModel.cs
Add adaptative trigger state initialization.
> Add adaptative trigger state initialization.

- templates/Features/SettingsStorage/Helpers/SettingsStorageExtensions.cs
> Added missing using

- templates/Features/StoreNotifications/_postaction.csproj
#442 Fixed Microsoft.VCLibs dependency warning
> Fix Microsoft.VCLibs dependency warning

- templates/Pages/Chart.CodeBehind/.template.config/description.md
- templates/Pages/Chart/.template.config/description.md
- templates/Pages/Grid.CodeBehind/.template.config/description.md
- templates/Pages/Grid/.template.config/description.md
- templates/Pages/MediaPlayer.CodeBehind/.template.config/description.md
- templates/Pages/MediaPlayer/.template.config/description.md
#509
Submitting this against /dev but would be good to get this fix out in an updated template ASAP, rather than wait for the next VSIX update.
> Fix markdown description links

- docs/features/whats-new-prompt.md
- templates/Features/WhatsNewPrompt/.template.config/description.md
- templates/Features/WhatsNewPrompt/.template.config/icon.xaml
- templates/Features/WhatsNewPrompt/.template.config/template.json
- templates/Features/WhatsNewPrompt/Services/ActivationService_postaction.cs
- templates/Features/WhatsNewPrompt/Services/WhatsNewDisplayService.cs
- templates/Features/WhatsNewPrompt/Views/WhatsNewDialog.xaml
- templates/Features/WhatsNewPrompt/Views/WhatsNewDialog.xaml.cs
> Display dialog after app update

- templates/Features/FirstUsePrompt/.template.config/description.md
- templates/Features/FirstUsePrompt/.template.config/icon.xaml
- templates/Features/FirstUsePrompt/.template.config/template.json
- templates/Features/FirstUsePrompt/Services/ActivationService_postaction.cs
- templates/Features/FirstUsePrompt/Services/FirstRunDisplayService.cs
- templates/Features/FirstUsePrompt/Views/FirstRunDialog.xaml
- templates/Features/FirstUsePrompt/Views/FirstRunDialog.xaml.cs
> Add OOBE message prompt

- templates/Features/FirstUsePrompt/Strings/en-us/Resources_postaction.resw
- templates/Features/FirstUsePrompt/Views/FirstRunDialog.xaml
> OOBE dialog localization

- templates/Features/WhatsNewPrompt/Strings/en-us/Resources_postaction.resw
- templates/Features/WhatsNewPrompt/Views/WhatsNewDialog.xaml
> added localization

- templates/Pages/Chart.CodeBehind/_postaction.csproj
- templates/Pages/Chart/_postaction.csproj
- templates/Pages/Grid.CodeBehind/Views/GridViewPage.xaml
- templates/Pages/Grid.CodeBehind/Views/GridViewPage.xaml.cs
- templates/Pages/Grid.CodeBehind/_postaction.csproj
- templates/Pages/Grid/Views/GridViewPage.xaml
- templates/Pages/Grid/_postaction.csproj
Also updated Chart page Nuget version so both are using the same version
#496
> Update Telerik reference to avoid workaround for Binding issue

- templates/Pages/Grid/Views/GridViewPage.xaml
> Fixed binding in GridViewPage

- code/src/UI/Controls/OverlayBox.xaml
> breaking shadow from border as it caused text rendering issue before

- code/src/Core/PostActions/Catalog/SortUsings/IEnumerableExtensions.cs
- code/test/Core.Test/PostActions/Catalog/SortUsingsTest.cs
Modified sortusing postaction to remove unnecessary blank lines before usings
Solves #573
> Modified sortusing postaction 

- code/src/Core/PostActions/Catalog/Merge/MergePostAction.cs
(not in temp generation folder)
Fixes issue #600
> Refresh project only when modifing csproj in proj folder 

- templates/Features/FirstUsePrompt/.template.config/template.json
- templates/Features/HubNotifications/.template.config/template.json
- templates/Features/LiveTile/.template.config/template.json
- templates/Features/StoreNotifications/.template.config/template.json
- templates/Features/SuspendAndResume/.template.config/template.json
- templates/Features/WhatsNewPrompt/.template.config/template.json
- templates/Pages/Chart.CodeBehind/.template.config/template.json
- templates/Pages/Chart/.template.config/template.json
- templates/Pages/Grid.CodeBehind/.template.config/template.json
- templates/Pages/Grid/.template.config/template.json
- templates/Pages/Map.CodeBehind/.template.config/template.json
- templates/Pages/Map/.template.config/template.json
- templates/Pages/MasterDetail.CodeBehind/.template.config/template.json
- templates/Pages/MasterDetail/.template.config/template.json
- templates/Pages/MediaPlayer.CodeBehind/.template.config/template.json
- templates/Pages/MediaPlayer/.template.config/template.json
- templates/Pages/Settings.CodeBehind/.template.config/template.json
- templates/Pages/Settings/.template.config/template.json
- templates/Pages/TabbedPivot.CodeBehind/.template.config/template.json
- templates/Pages/TabbedPivot/.template.config/template.json
- templates/Pages/WebView.CodeBehind/.template.config/template.json
- templates/Pages/WebView/.template.config/template.json
> Issue479 reordering

- code/src/UI/VisualStudio/RightClickActions.cs
- code/test/VsEmulator/Main/MainViewModel.cs
> Ensure Temp Directory is there

- code/src/UI/VisualStudio/RightClickActions.cs
- code/test/Templates.Test/NewItemGenerationTests.cs
- code/test/VsEmulator/Main/MainViewModel.cs
> Included timestamp in temp folder

- code/src/Installer.2017/Commands/RelayCommandPackage.cs-CZ.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.de-DE.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.en-US.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.es-ES.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.fr-FR.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.it-IT.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.ja-JP.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.ko-KR.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.pl-PL.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.pt-BR.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.ru-RU.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.tr-TR.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.zh-CN.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.zh-TW.vsct
> Add hidden command to place icon

- code/src/Core/Diagnostics/FileHealthWriter.cs
- code/src/Core/Diagnostics/FormattedWriterMessages.cs
- code/src/Core/Diagnostics/ShellHealthWriter.cs
- code/test/Templates.Test/GenerationFixture.cs
> format datetime to use 24 hour format hours

- templates/_composition/CodeBehind/Project.SplitView/Views/ShellPage.xaml
- templates/_composition/MVVMBasic/Project.SplitView/Views/ShellPage.xaml
- templates/_composition/MVVMLight/Project.SplitView/Views/ShellPage.xaml
To reflect updated guidance based on NavigationView control
#597
> Remove vertical margin from hamburger button

- code/src/Core/PostActions/Catalog/NewItemGeneration/CreateSyncSummaryPostAction.cs
> Changed link format to open in recommended editor

- docs/roadmap.md
- docs/templates.md
Added right click enabled documentation.
Referenced updated documentation in roadmap.md
@crutkas: In #683, you referred to including the changed documentation in the roadmap, didn't you?
> Documentation updates

- code/src/UI/Controls/CodeViewer.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryViewModel.cs
- code/src/UI/Views/NewItem/ChangesSummaryView.xaml
- code/src/UI/Views/NewItem/ChangesSummaryView.xaml.cs
> Set header background to light blue in changes summary file.

- code/src/UI/ViewModels/NewItem/ChangesSummaryViewModel.cs
- code/src/UI/Views/NewItem/ChangesSummaryView.xaml.cs
> Fix compiler warnings

- _build/Extension-SetIdentityAndVersion.ps1
> Issue700 vsix localized name

- templates/Features/BackgroundTask/.template.config/description.md
- templates/Features/BackgroundTask/.template.config/template.json
- templates/Features/HubNotifications/.template.config/template.json
- templates/Features/LiveTile/.template.config/template.json
- templates/Features/LiveTile/Services/LiveTileFeatureService.cs
- templates/Features/StoreNotifications/.template.config/template.json
- templates/Features/SuspendAndResume/.template.config/description.md
- templates/Features/SuspendAndResume/.template.config/template.json
- templates/Features/ToastNotifications/.template.config/description.md
- templates/Features/ToastNotifications/.template.config/template.json
Also changed to explain what adding the feature does to the generated project, not explaining the service or functionality it relates to.
#627
> simplified some feature descriptions

- code/src/Core/Gen/GenShell.cs
- code/src/UI/Generation/GenComposer.cs
- code/src/UI/VisualStudio/VsGenShell.cs
- code/test/Artifacts/FakeGenShell.cs
> Get namespace from active project instead from active item

- code/src/Installer.2017/Commands/PackageIds.cs
- code/src/Installer.2017/Commands/RelayCommandPackage.cs
- code/src/Installer.2017/Commands/RelayCommandPackage.en-US.vsct
> Fix invalid menu in non WTS projects

- templates/Pages/MasterDetail.CodeBehind/Views/MasterDetailDetailPage.xaml
- templates/Pages/MasterDetail/Views/MasterDetailDetailPage.xaml
> No white border when in dark theme on Master/detail page

- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Views/NewItem/ChangesSummaryView.xaml
- code/src/UI/Views/NewProject/ProjectSetupView.xaml
- code/src/UI/Views/NewProject/ProjectTemplatesView.xaml
issue #738 
- added in tooltip in other "i" areas.
- changed ? to i
- simplified XAML tree
> changing ? to i

- code/src/UI/Assets/Html/Compare.html
- code/src/UI/Assets/Html/Document.html
Rolling back #721 due to normal screen it blows text up far too big.
> Issue721 fontsize

- docs/newitem.md
Add examples to make clearer what's the difference between conflicting file and failed merge. Fixes #753
> New item documentation enhancements

- code/src/Installer.2017/cs-CZ/Extension.vsixlangpack
- code/src/Installer.2017/de-DE/Extension.vsixlangpack
- code/src/Installer.2017/es-ES/Extension.vsixlangpack
- code/src/Installer.2017/fr-FR/Extension.vsixlangpack
- code/src/Installer.2017/it-IT/Extension.vsixlangpack
- code/src/Installer.2017/ja-JP/Extension.vsixlangpack
- code/src/Installer.2017/ko-KR/Extension.vsixlangpack
- code/src/Installer.2017/pl-PL/Extension.vsixlangpack
- code/src/Installer.2017/pt-BR/Extension.vsixlangpack
- code/src/Installer.2017/ru-RU/Extension.vsixlangpack
- code/src/Installer.2017/tr-TR/Extension.vsixlangpack
- code/src/Installer.2017/zh-CN/Extension.vsixlangpack
- code/src/Installer.2017/zh-TW/Extension.vsixlangpack
Corrected paths to eula files for localized vsix
Fixes #656
> Adjust eulas

- code/src/Installer.2017/Commands/PackageIds.cs
- code/src/Installer.2017/Commands/RelayCommandPackage.cs
- code/src/Installer.2017/Commands/RelayCommandPackage.cs-CZ.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.de-DE.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.en-US.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.es-ES.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.fr-FR.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.it-IT.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.ja-JP.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.ko-KR.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.pl-PL.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.pt-BR.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.ru-RU.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.tr-TR.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.zh-CN.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.zh-TW.vsct
@crutkas: This fixes #728  
Also see #620, we are the only ones with an icon on a menu as far as I can see.
> Remove hidden command and WTS icon

- templates/Features/LiveTile/.template.config/template.json
- templates/Features/ToastNotifications/.template.config/template.json
- templates/_catalog/projectTypes.json
- templates/_composition/CodeBehind/Project.SplitView/.template.config/template.json
- templates/_composition/MVVMBasic/Project.SplitView/.template.config/template.json
- templates/_composition/MVVMLight/Project.SplitView/.template.config/template.json
> Standardising Community Toolkit license labels

- code/src/Core/Diagnostics/TelemetryTracker.cs
- code/src/Core/Diagnostics/WizardActionEnum.cs
- code/src/UI/Generation/NewItemGenController.cs
- code/src/UI/Generation/NewProjectGenController.cs
> Changed WizardActions to include GenerateProject action

- code/src/Installer.2017/Commands/RelayCommandPackage.cs-CZ.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.de-DE.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.en-US.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.es-ES.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.fr-FR.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.it-IT.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.ja-JP.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.ko-KR.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.pl-PL.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.pt-BR.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.ru-RU.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.tr-TR.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.zh-CN.vsct
- code/src/Installer.2017/Commands/RelayCommandPackage.zh-TW.vsct
> Bring folder icon back

- code/src/UI/Generation/ProjectConfigInfo.cs
> Fix file name typo

- templates/Pages/Chart.CodeBehind/Views/ChartViewPage.xaml
- templates/Pages/Chart/Views/ChartViewPage.xaml
> Ensure Chart axis, ticks & labels visible in light and dark theme

- code/src/Core/Gen/GenContext.cs
- code/src/UI/VisualStudio/RightClickActions.cs
- code/test/Templates.Test/NewItemGenerationTests.cs
- code/test/VsEmulator/Main/MainViewModel.cs
#666 
Yes
- If you've changed the UI are you including screenshots to show the changes
- If breaking changes or different ways of doing things have been introduced, have they been communicated widely.
> Moved GetTempGenerationPath to GenContext 

- code/src/Core/Configuration/Configuration.cs
- code/src/Core/Configuration/WindowsTemplateStudio.tokenized.config.json
- code/src/Installer.2017/WindowsTemplateStudio.config.json
- code/src/UI/ViewModels/NewItem/ChangesSummaryViewModel.cs
- code/test/Core.Test/Config/ConfigurationTests.cs
Added a configuration value GitHubDocsUrl to the config file, that points to the root of the documentation folder so we can configure master branch for pre and pro, and dev branch for dev.
#681 
Yes
Adapted existing tests
#836
> Issue681 configurablegithuburl

- templates/Features/FirstUsePrompt/Services/ActivationService_postaction.cs
- templates/Features/FirstUsePrompt/Services/FirstRunDisplayService.cs
- templates/Features/LiveTile/Services/LiveTileFeatureService.Samples.cs
- templates/Features/WhatsNewPrompt/Services/ActivationService_postaction.cs
- templates/Features/WhatsNewPrompt/Services/WhatsNewDisplayService.cs
> Async methods returning a task should all have names ending "Async"

- code/test/Templates.Test/CodeStyleEnforcementTests.cs
- code/test/Templates.Test/Templates.Test.csproj
- templates/Features/FirstUsePrompt/Views/FirstRunDialog.xaml.cs
- templates/Features/WhatsNewPrompt/Views/WhatsNewDialog.xaml.cs
- templates/_composition/CodeBehind/Page.Settings.AddShellThemeSupport_SplitView/Views/ShellNavigationItem_postaction.cs
- templates/_composition/CodeBehind/Project.SplitView/Views/ShellNavigationItem.cs
- templates/_composition/MVVMBasic/Page.Settings.AddShellThemeSupport_SplitView/ViewModels/ShellNavigationItem_postaction.cs
- templates/_composition/MVVMBasic/Project.SplitView/ViewModels/ShellNavigationItem.cs
- templates/_composition/MVVMBasic/Project/Helpers/RelayCommand.cs
- templates/_composition/MVVMLight/Page.Settings.AddShellThemeSupport_SplitView/ViewModels/ShellNavigationItem_postaction.cs
- templates/_composition/MVVMLight/Project.SplitView/ViewModels/ShellNavigationItem.cs
-Removed use of `this.` from generated project code
#847
Yes 😄
> Issue847 use of this

- templates/Features/FirstUsePrompt/Services/ActivationService_postaction.cs
- templates/Features/FirstUsePrompt/Services/FirstRunDisplayService.cs
- templates/Features/LiveTile/Services/LiveTileFeatureService.Samples.cs
- templates/Features/WhatsNewPrompt/Services/ActivationService_postaction.cs
- templates/Features/WhatsNewPrompt/Services/WhatsNewDisplayService.cs
- If you've changed the UI are you including screenshots to show the changes
- If breaking changes or different ways of doing things have been introduced, have they been communicated widely.
> Hotfix patch for 841

- templates/_composition/CodeBehind/Project.SplitView/Views/ShellNavigationItem.cs
- templates/_composition/MVVMBasic/Project.SplitView/ViewModels/ShellNavigationItem.cs
- templates/_composition/MVVMLight/Project.SplitView/ViewModels/ShellNavigationItem.cs
Just removed some whitespaces in templatefiles that made stylecop tests fail.
> Removed whitespaces

- code/test/Templates.Test/GenerationFixture.cs
style cop adjustment for #869 
does the () actually correct
yes
> Fix for #869

- templates/Features/SampleData/Models/Order.cs
#870 with a comment
does my adjustment make sense :)
> adjustment on comment

- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
- code/src/UI/Views/NewProject/InformationWindow.xaml.cs
> fixing spelling mistake for #755

- templates/Features/SampleData/Models/Order.cs
> Fix for SA1028.  comments had trailing spaces

- code/src/Core/Diagnostics/ShellHealthWriter.cs
- code/src/Installer.2017/Commands/RelayCommand.cs
- code/src/Installer.2017/Commands/RelayCommandPackage.cs
- code/src/UI/Services/DragAndDropService/DragAndDropService.Members.cs
- code/src/UI/Services/DragAndDropService/DragAndDropService.cs
- code/src/UI/ViewModels/NewItem/MainViewModel.cs
- code/test/Core.Test/Localization/LocalizationTest.cs
- code/tools/Localization/ClientInterface/ToolCommandHandler.cs
- code/tools/Localization/ClientInterface/ToolCommandInfo.cs
- code/tools/Localization/Logic/LocalizableItemsExtractor.cs
- code/tools/Localization/Logic/ProjectTemplateGenerator.cs
- code/tools/Localization/Logic/RightClickCommandGenerator.cs
> audit of "this" keyword in main code base

- _utils/Set-All-Text-File-Template-Encodings.ps1
- code/tools/Localization/Program.cs
> Issue841 copyrights

- code/src/UI/Controls/CodeViewer.cs
- code/src/UI/TemplateSelectors/FileExtensionTemplateSelector.cs
- code/src/UI/TemplateSelectors/FileStatusTemplateSelector.cs
- code/src/UI/ViewModels/NewItem/NewItemSetupViewModel.cs
> fixing IDE0019

- code/test/Fakes/MSBuild/FakeMsBuildProject.cs
#873 change to switch statement
that i did the flip correctly
yup
> adjusted to switch statement

- code/src/UI/Controls/CodeViewer.cs
- code/src/UI/TemplateSelectors/FileExtensionTemplateSelector.cs
- code/src/UI/TemplateSelectors/FileStatusTemplateSelector.cs
- code/src/UI/UI.csproj
- code/src/UI/ViewModels/Common/FileExtension.cs
- code/src/UI/ViewModels/Common/FileStatus.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/BaseFileViewModel.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/ConflictingFileViewModel.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/FailedMergesFileViewModel.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/ModifiedFileViewModel.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/NewFileViewModel.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/UnchangedFileViewModel.cs
> migrated two enums out

- docs/getting-started-developers.md
- docs/getting-started-extension.md
- docs/templates.md
Deliberately making this PR to master as the issue in is the public docs which exist on master.
This change should also then be resubmitted to or merged to dev.
#910
> Fix contribution links in docs

- templates/Pages/Settings.CodeBehind/Views/SettingsPagePage.xaml.cs
- templates/Pages/Settings/Views/SettingsPagePage.xaml.cs
> Improve wording of TODO message

- code/src/UI/Controls/CodeViewer.cs
> Tidy long `if` statement as a `switch` in code/src/UI/Controls/CodeViewer.cs

- templates/_composition/CodeBehind/Project.SplitView/Views/ShellPage.xaml
- templates/_composition/MVVMBasic/Project.SplitView/Views/ShellPage.xaml
- templates/_composition/MVVMLight/Project.SplitView/Views/ShellPage.xaml
#885
deliberately against master for hotfix
> Ensure native Hamburger selection highlight is hidden

- templates/Features/SettingsStorage/_postaction.csproj
- templates/Features/SettingsStorageVB/_postaction.vbproj
> Update to latest version of json.net

- templates/Pages/Chart.CodeBehind/_postaction.csproj
- templates/Pages/Chart/_postaction.csproj
- templates/Pages/Grid.CodeBehind/_postaction.csproj
- templates/Pages/Grid/_postaction.csproj
#622 
nope
yup
- If you've changed the UI are you including screenshots to show the changes
- If breaking changes or different ways of doing things have been introduced, have they been communicated widely.
> Updating to 1005 for telerik (#622)

- templates/Pages/Chart.CodeBehind/_postaction.csproj
- templates/Pages/Chart/_postaction.csproj
- templates/Pages/Grid.CodeBehind/_postaction.csproj
- templates/Pages/Grid/_postaction.csproj
Deliberately against master
Hot fix for #622.  PR #927 is against Dev branch
> Hot fix for #622 designer fix (against master)

- templates/Features/SampleData/.template.config/template.json
- templates/Features/SampleData/Models/SampleOrder.cs
- templates/Features/SampleData/Services/SampleDataService.cs
- templates/Pages/Grid.CodeBehind/Views/GridViewPage.xaml.cs
- templates/Pages/Grid/ViewModels/GridViewViewModel.cs
- templates/Pages/MasterDetail.CodeBehind/Views/MasterDetailDetailControl.xaml.cs
- templates/Pages/MasterDetail.CodeBehind/Views/MasterDetailDetailPage.xaml.cs
- templates/Pages/MasterDetail.CodeBehind/Views/MasterDetailPage.xaml
- templates/Pages/MasterDetail.CodeBehind/Views/MasterDetailPage.xaml.cs
- templates/Pages/MasterDetail/ViewModels/MasterDetailDetailViewModel.cs
- templates/Pages/MasterDetail/ViewModels/MasterDetailViewModel.cs
- templates/Pages/MasterDetail/Views/MasterDetailDetailControl.xaml.cs
- templates/Pages/MasterDetail/Views/MasterDetailDetailPage.xaml.cs
- templates/Pages/MasterDetail/Views/MasterDetailPage.xaml
- templates/_composition/MVVMBasic/Page.MasterDetail.AddViewModel/ViewModels/wts.ItemNameViewModel_postaction.cs
- templates/_composition/MVVMLight/Page.MasterDetail.AddViewModel/ViewModels/wts.ItemNameViewModel_postaction.cs
- templates/_composition/_shared/Page.Grid.SampleDataService/Services/SampleDataService$wts.ItemName_gpostaction.cs
- templates/_composition/_shared/Page.MasterDetail.SampleDataService/Services/SampleDataService$wts.ItemName_gpostaction.cs
> Rename Order[.cs] to SampleOrder[.cs]

- templates/Pages/Settings.CodeBehind/Views/SettingsPagePage.xaml
- templates/Pages/Settings.CodeBehind/Views/SettingsPagePage.xaml.cs
- templates/Pages/Settings/ViewModels/SettingsPageViewModel.cs
- templates/Pages/Settings/Views/SettingsPagePage.xaml
#350
Pivot fix
can't run full tests since something in dev branch broke core.test
> Fix for pivot life cycle.

- code/src/Installer.2017/Commands/GenContextBootstrapService.cs
- code/src/Installer.2017/Commands/RelayCommandPackage.cs
> Fix RightClick>Add

- code/src/Core/Core.csproj
weird this didn't fail on my desktop.
> adjusting app insights again

- templates/_composition/CodeBehind/Project.SplitView/Views/ShellPage.xaml
- templates/_composition/MVVMBasic/Project.SplitView/Views/ShellPage.xaml
- templates/_composition/MVVMLight/Project.SplitView/Views/ShellPage.xaml
Fix for NavMenu showing incorrect highlight after back button click  ( #885 )
Previously merged in to master for hotfix - this PR is to get this also applied to dev branch
> Issue885 nav menu issue

- code/src/Core/Core.csproj
- code/src/Core/Diagnostics/FileHealthWriter.cs
- code/src/Core/Diagnostics/FormattedWriterMessages.cs
- code/src/Core/Diagnostics/ShellHealthWriter.cs
- code/src/Core/Extensions/DateTimeExtensions.cs
- code/src/Core/Gen/GenContext.cs
- code/src/UI/VisualStudio/VsOutputPane.cs
- code/test/Templates.Test/GenerationFixture.cs
- code/test/Templates.Test/NewItemGenerationTests.cs
- code/test/Templates.Test/StyleCopGenerationTestsFixture.cs
For #692
Also ensures that Hours are in 24 hour format (for #674)
> centralize datetime tostring writing

- code/src/Core/Gen/GenContext.cs
- code/src/Core/Naming/DirectoryExistsValidator.cs
- code/test/Core.Test/Naming/NamingTest.cs
- code/test/Templates.Test/NewItemGenerationTests.cs
- templates/Pages/MasterDetail/ViewModels/MasterDetailDetailViewModel.cs
- templates/Pages/MasterDetail/ViewModels/MasterDetailViewModel.cs
- templates/Pages/Settings/ViewModels/SettingsPageViewModel.cs
#897 and #963 
nope
yup
yup for #963
> Issue897 and 963

- code/src/UI/Controls/ImageEx.cs
- code/src/UI/UI.csproj
- code/src/UI/ViewModels/NewItem/MainViewModel.cs
- code/src/UI/packages.config
> enable bitmap effects

- templates/Pages/MasterDetail/ViewModels/MasterDetailDetailViewModel.cs
- templates/Pages/MasterDetail/ViewModels/MasterDetailViewModel.cs
- templates/Pages/Settings/ViewModels/SettingsPageViewModel.cs
> Fixes due to trailing whitespace

- code/UI.sln
- code/src/UI/ViewModels/NewProject/ProjectTemplatesViewModel.cs
- code/src/UI/ViewModels/NewProject/TemplateInfoViewModel.cs
- code/src/UI/Views/NewItem/MainView.xaml
- code/src/UI/Views/NewItem/MainView.xaml.cs
- code/src/UI/Views/NewProject/MainView.xaml
- code/src/UI/Views/NewProject/MainView.xaml.cs
- code/test/VsEmulator/LoadProject/LoadProjectView.xaml
- code/test/VsEmulator/LoadProject/LoadProjectView.xaml.cs
- code/test/VsEmulator/Main/MainView.xaml
- code/test/VsEmulator/Main/MainView.xaml.cs
- code/test/VsEmulator/NewProject/NewProjectView.xaml
- code/test/VsEmulator/NewProject/NewProjectView.xaml.cs
- If you've changed the UI are you including screenshots to show the changes
- If breaking changes or different ways of doing things have been introduced, have they been communicated widely.
> Fix Escape key handlers in wizard

- code/src/UI/Styles/_Colors.xaml
> Update WTS Blue color

- code/src/UI/Styles/StyleMarkdown.xaml
> Set underline style to hyperlink in markdown text.

- code/src/UI/Converters/FixedWidthConverter.cs
#951 
The Visual Studio Output Console not display binding warnings.
> Change FixedWidthConverter to return valid values.

- code/test/Templates.Test/StyleCopPlusLocalTemplatesSource.cs
- code/tools/Localization/Logic/ProjectTemplateGeneratorBase.cs
> Ignore CA2214 until further review

- templates/_composition/CodeBehind/Project.SplitView/Views/ShellPage.xaml
- templates/_composition/CodeBehind/Project.SplitViewVB/Views/ShellPage.xaml
- templates/_composition/MVVMBasic/Project.SplitView/Views/ShellPage.xaml
- templates/_composition/MVVMBasic/Project.SplitViewVB/Views/ShellPage.xaml
- templates/_composition/MVVMLight/Project.SplitView/Views/ShellPage.xaml
- templates/_composition/MVVMLight/Project.SplitViewVB/Views/ShellPage.xaml
> Add tooltip to icons in split view projects

- code/src/UI/Styles/StyleExpander.xaml
- code/src/UI/Views/NewItem/ChangesSummaryView.xaml
Fix margins related to issue #786
> Fix margins

- code/src/UI/Controls/TogglePane.cs
- code/src/UI/Controls/TogglePane.xaml
- code/src/UI/Styles/StyleButton.xaml
- code/src/UI/ViewModels/NewProject/MainViewModel.cs
- code/src/UI/Views/NewProject/MainView.xaml.cs
> Allow short saved pages from keyboard

- code/src/UI/Controls/OverlayBox.xaml
- code/src/UI/Styles/StyleButton.xaml
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/BaseFileViewModel.cs
- code/src/UI/Views/NewItem/ChangesSummaryView.xaml
- code/src/UI/Views/NewItem/MainView.xaml
- code/src/UI/Views/NewProject/ProjectSetupView.xaml
- code/src/UI/Views/NewProject/ProjectTemplatesView.xaml
> Add AutomationProperties.Name on controls for accesibility.

- code/GlobalSuppressions.cs
audit was for #851
follow up task #868 already planned
> Temporarily suppressing issues found in async audit

- templates/Pages/Map.CodeBehind/Services/LocationService.cs
- templates/Pages/Map.CodeBehind/Views/MapPagePage.xaml.cs
- templates/Pages/Map/Services/LocationService.cs
- templates/Pages/Map/ViewModels/MapPageViewModel.cs
- templates/Projects/Default/Services/ActivationService.cs
- templates/_composition/CodeBehind/Page.Map.AddInitialization_TabbedPivot/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/_composition/CodeBehind/Page.MasterDetail.AddInitialization_TabbedPivot/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/_composition/CodeBehind/Page.Settings.AddInitialization_TabbedPivot/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/_composition/CodeBehind/Project.SplitView/Views/ShellPage.xaml.cs
- templates/_composition/CodeBehind/Project.SplitViewVB/Views/ShellPage.xaml.vb
- templates/_composition/MVVMBasic/Page.Map.AddCleanUp/ViewModels/wts.ItemNameViewModel_postaction.cs
- templates/_composition/MVVMBasic/Project.SplitView/ViewModels/ShellViewModel.cs
- templates/_composition/MVVMBasic/Project.SplitViewVB/ViewModels/ShellViewModel.vb
- templates/_composition/MVVMLight/Page.Map.AddCleanUp/ViewModels/wts.ItemNameViewModel_postaction.cs
- templates/_composition/MVVMLight/Project.SplitView/ViewModels/ShellViewModel.cs
- templates/_composition/MVVMLight/Project.SplitViewVB/ViewModels/ShellViewModel.vb
- templates/_composition/_shared/Page.Map.AddInitialization_TabbedPivot/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/_composition/_shared/Page.MasterDetail.AddInitialization_TabbedPivot/Views/wts.ItemNamePage_postaction.xaml.cs
Normalize event handler method names in templates #857
> Normalize event handler mehtod names in templates #857

- code/src/UI/Extensions/AnimationExtensions.cs
- code/test/Templates.Test/GenerationFixture.cs
- code/test/Templates.Test/ProjectGenerationTests.cs
- code/test/Templates.Test/StyleCopGenerationTestsFixture.cs
Quick summary of changes:
Remove some Async issues warned:
#851 
Required to enable build properly
> Remove Async Analyzer issues

- code/src/UI/Views/NewItem/ChangesSummaryView.xaml
> #736 - Fix scroll in changes summary view

- code/src/Core/Core.csproj
- code/src/Core/app.config
- code/src/Core/packages.config
- code/src/Installer.2017/Installer.2017.csproj
- code/src/Installer.2017/app.config
- code/src/Installer.2017/packages.config
- code/src/Installer.2017/source.extension.vsixmanifest
- code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.csproj
- code/src/ProjectTemplates/CSharp.UWP.2017.Solution/packages.config
- code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.csproj
- code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/packages.config
- code/src/UI/UI.csproj
- code/src/UI/app.config
- code/src/UI/packages.config
- code/test/Core.Test/App.config
- code/test/Core.Test/Core.Test.csproj
- code/test/Core.Test/packages.config
- code/test/Fakes/app.config
- code/test/Templates.Test/App.config
- code/test/Templates.Test/Templates.Test.csproj
- code/test/Templates.Test/packages.config
- code/test/VsEmulator/App.config
- code/test/VsEmulator/VsEmulator.csproj
- code/test/VsEmulator/packages.config
- code/tools/Localization/App.config
- code/tools/Localization/Localization.csproj
- code/tools/Localization/packages.config
Consolidate references and remove conflicts caused by previous update to v15.3 of Microsoft.VisualStudio.Threading / Imaging / Validation
843
Nop
Yes
> Consolidate references among projects

- code/src/UI/VisualStudio/SolutionWizard.cs
> Delete solution directory to cancel button click, only if directory is empy.

- code/src/UI/Styles/StyleExpander.xaml
> Issue725-expanders

- code/src/Core/Gen/GenShell.cs
- code/src/Installer.2017/Commands/RelayCommandPackage.cs
- code/src/UI/VisualStudio/RightClickActions.cs
- code/src/UI/VisualStudio/VsGenShell.cs
- code/test/Fakes/FakeGenShell.cs
> Right click disabled on debugging

- code/src/UI/Controls/OverlayBox.cs
- code/src/UI/Controls/OverlayBox.xaml
- code/src/UI/Styles/StyleTextBox.xaml
Issue #723
Make wizard and templates versions as a select target.
> Make wizard and templates versions as select target

- _build/PackAndSign-Content.ps1
> Issue1032 fix PackAndSign-Content.ps1 script

- code/test/Templates.Test/GenerationFixture.cs
- code/test/Templates.Test/StyleCopGenerationTestsFixture.cs
- templates/_composition/MVVMLight/Project/Services/ActivationService_postaction.cs
> Fix integration test execution issues and generated code StyleCop violations

- code/src/UI/Views/NewItem/MainView.xaml
- code/src/UI/Views/NewItem/MainView.xaml.cs
> Fix open md file when close wizard using the X in the top right-hand corner of the window

- code/src/UI/ViewModels/NewProject/ProjectTemplatesViewModel.cs
- code/src/UI/ViewModels/NewProject/SavedTemplateViewModel.cs
Remove hidden templates if no one templates depends on it.
Issue #810
> Remove hidden templates if no one templates depends on it

- code/test/Core.Test/Naming/NamingTest.cs
> adjustment of names and breaking functions out

- code/test/Templates.Test/BaseGenAndBuildTests.cs
- code/test/Templates.Test/BuildProjectsTests.cs
> Avoid clean up generations when building solutions

- templates/Features/SuspendAndResumeVB/.template.config/template.json
> Fix Suspend and Resume feature template

- code/test/Templates.Test/BaseGenAndBuildTests.cs
- code/test/Templates.Test/BuildProjectsTests.cs
> Fix builds and rename test methods

- templates/Pages/Settings/Views/SettingsPagePage.xaml.cs
#921
Adding missing comment. Related to PR #1046
> Adding missing comment

- templates/Features/FirstUsePrompt/Strings/en-us/Resources_postaction.resw
- templates/Features/WhatsNewPrompt/Strings/en-us/Resources_postaction.resw
- templates/Pages/Blank.CodeBehind/Strings/en-us/Resources_postaction.resw
- templates/Pages/Blank.CodeBehindVB/Strings/en-us/Resources_postaction.resw
- templates/Pages/Blank/Strings/en-us/Resources_postaction.resw
- templates/Pages/BlankVB/Strings/en-us/Resources_postaction.resw
- templates/Pages/Chart.CodeBehind/Strings/en-us/Resources_postaction.resw
- templates/Pages/Chart/Strings/en-us/Resources_postaction.resw
- templates/Pages/Grid.CodeBehind/Strings/en-us/Resources_postaction.resw
- templates/Pages/Grid/Strings/en-us/Resources_postaction.resw
- templates/Pages/Map.CodeBehind/Strings/en-us/Resources_postaction.resw
- templates/Pages/Map/Strings/en-us/Resources_postaction.resw
- templates/Pages/MasterDetail.CodeBehind/Strings/en-us/Resources_postaction.resw
- templates/Pages/MasterDetail/Strings/en-us/Resources_postaction.resw
- templates/Pages/Settings.CodeBehind/Strings/en-us/Resources_postaction.resw
- templates/Pages/Settings/Strings/en-us/Resources_postaction.resw
- templates/Pages/TabbedPivot.CodeBehind/Strings/en-us/Resources_postaction.resw
- templates/Pages/TabbedPivot/Strings/en-us/Resources_postaction.resw
- templates/Pages/WebView.CodeBehind/Strings/en-us/Resources_postaction.resw
- templates/Pages/WebView/Strings/en-us/Resources_postaction.resw
- templates/_composition/_shared/Project.SplitView.AddNavigationPaneResources/Strings/en-us/Resources_postaction.resw
- templates/_composition/_shared/Project.SplitView.AddNavigationPaneResourcesVB/Strings/en-us/Resources_postaction.resw
- templates/_composition/_shared/Project.TabbedPivot.AddTabbedPivotItems/Strings/en-us/Resources_postaction.resw
- templates/_composition/_shared/Project.TabbedPivot.AddTabbedPivotItemsVB/Strings/en-us/Resources_postaction.resw
> Add comments for Resx string resources

- templates/Pages/Settings/Views/SettingsPagePage.xaml.cs
> Comment already in the ViewModel

- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
#756
Add comments to resx files and remove not unreferenced resources.
> Add comments to resx files and remove not unreferences resources.

- templates/Pages/Settings/Views/SettingsPagePage.xaml
> Add binding on SettingsPage as a woraround for #1053

- code/src/UI/Generation/UserSelection.cs
- code/src/UI/ViewModels/NewItem/MainViewModel.cs
- code/src/UI/Views/NewItem/MainView.xaml.cs
#797
The right click generation works corretly.
Yes
> #797 - Fix problem when finalize generation in right click.

- _build/signconfig.xml
> Add sign config file

- _build/PackAndSign-Content.ps1
Update the script for packaging templates to avoid mandatory signingCertificate
> Allow pack without sign

- docs/roadmap.md
- docs/telemetryData.md
New data, intentionally going to master, will do another back to Dev
> Updated telem data for August [master branch]

- docs/PULL_REQUEST_TEMPLATE.md
- docs/accessibility.md
> Accessibility document

- code/src/UI/ViewModels/NewProject/MainViewModel.cs
> Fix a bug on #537

- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Views/NewItem/ChangesSummaryView.xaml
> Fix and comment zoom buttons

- templates/Features/UriScheme/Strings/en-us/Resources_postaction.resw
> Add comment to resources

- code/src/UI/Views/NewItem/NewItemSetupView.xaml
> Fix author on new item information window

- CONTRIBUTING.md
- docs/getting-started-developers.md
> Update accessibility links.

- templates/_composition/CodeBehind/Project.SplitView/Views/ShellNavigationItem.cs
- templates/_composition/MVVMBasic/Project.SplitView/ViewModels/ShellNavigationItem.cs
- templates/_composition/MVVMLight/Project.SplitView/ViewModels/ShellNavigationItem.cs
> Update selected item foreground on ShellNavigationItem

- code/src/Core/Core.csproj
- code/src/Core/Diagnostics/PerformanceCounterEnum.cs
- code/src/Core/Diagnostics/TelemetryMetrics.cs
- code/src/Core/Diagnostics/TelemetryTracker.cs
- code/src/Core/Gen/IContextProvider.cs
- code/src/Core/PostActions/Catalog/AddContextItemsToProjectPostAction.cs
- code/src/Core/PostActions/Catalog/AddProjectToSolutionPostAction.cs
- code/src/UI/Generation/GenController.cs
- code/src/UI/Generation/NewProjectGenController.cs
- code/src/UI/VisualStudio/RightClickActions.cs
- code/src/UI/VisualStudio/SolutionWizard.cs
- code/test/Core.Test/PostActions/Catalog/GenerateTestCertificatePostActionTest.cs
- code/test/Templates.Test/BaseTestContextProvider.cs
- code/test/VsEmulator/Main/MainViewModel.cs
Added performance counters to track total time of generation vs time it takes to generate, add files to project and add project to solution
#307
> Added performance counters

- code/src/UI/Controls/InformationButton.xaml
> Fix info button automation name

- templates/Features/StoreNotifications/_postaction.csproj
Removed whitespaces that caused issue #1101
#1101
> Removed extra whitespaces

- docs/navigation.md
Quick revision of the new navigation documentation as a "native speaker" for #775
> Issue775 nav doc wording

- code/test/Templates.Test/BaseGenAndBuildTests.cs
- code/test/Templates.Test/GenerationFixture.cs
Add homepage with random name in random tests
#1106
> Add homepage with random name in random tests

- templates/Pages/Settings.CodeBehind/Strings/en-us/Resources_postaction.resw
- templates/Pages/Settings.CodeBehind/Views/SettingsPagePage.xaml
- templates/Pages/Settings.MVVMLight/Strings/en-us/Resources_postaction.resw
- templates/Pages/Settings.MVVMLight/Views/SettingsPagePage.xaml
- templates/Pages/Settings/Strings/en-us/Resources_postaction.resw
- templates/Pages/Settings/Views/SettingsPagePage.xaml
Using SettingsPage on resources and xaml to support renaming of the page correctly
#1112
> Use SourceName for Settings page ressources

- templates/Features/UriScheme/.template.config/template.json
Fix #1114
Add default name on Uri Scheme feature
> Add default name on Uri Scheme feature

- templates/Features/UriScheme/.template.config/cs-CZ.description.md
- templates/Features/UriScheme/.template.config/cs-CZ.template.json
- templates/Features/UriScheme/.template.config/de-DE.description.md
- templates/Features/UriScheme/.template.config/de-DE.template.json
- templates/Features/UriScheme/.template.config/es-ES.description.md
- templates/Features/UriScheme/.template.config/es-ES.template.json
- templates/Features/UriScheme/.template.config/fr-FR.description.md
- templates/Features/UriScheme/.template.config/fr-FR.template.json
- templates/Features/UriScheme/.template.config/it-IT.description.md
- templates/Features/UriScheme/.template.config/it-IT.template.json
- templates/Features/UriScheme/.template.config/ja-JP.description.md
- templates/Features/UriScheme/.template.config/ja-JP.template.json
- templates/Features/UriScheme/.template.config/ko-KR.description.md
- templates/Features/UriScheme/.template.config/ko-KR.template.json
- templates/Features/UriScheme/.template.config/pl-PL.description.md
- templates/Features/UriScheme/.template.config/pl-PL.template.json
- templates/Features/UriScheme/.template.config/pt-BR.description.md
- templates/Features/UriScheme/.template.config/pt-BR.template.json
- templates/Features/UriScheme/.template.config/ru-RU.description.md
- templates/Features/UriScheme/.template.config/ru-RU.template.json
- templates/Features/UriScheme/.template.config/tr-TR.description.md
- templates/Features/UriScheme/.template.config/tr-TR.template.json
- templates/Features/UriScheme/.template.config/zh-CN.description.md
- templates/Features/UriScheme/.template.config/zh-CN.template.json
- templates/Features/UriScheme/.template.config/zh-TW.description.md
- templates/Features/UriScheme/.template.config/zh-TW.template.json
> Added localized files for urischeme feature

- templates/Pages/Grid.CodeBehind/Views/GridViewPage.xaml
- templates/Pages/Grid/Views/GridViewPage.xaml
#1131
Set Uid to match the value in the resources file
> Set Grid Page title correctly

- code/test/Templates.Test/BaseGenAndBuildTests.cs
- code/test/Templates.Test/BuildProjectsTests.cs
- code/test/Templates.Test/GenProjectsTests.cs
- code/test/Templates.Test/GenerationFixture.cs
1. Review of the projects generated by all test categories. 
2. Added in a test that generates a project with all features and pages and then adds in everything again. 
#1108, #1097 
No
Yes
> Issue1108 testaudit

- code/src/UI/Controls/WizardHeader.xaml
- code/src/UI/Controls/WizardHeader.xaml.cs
- code/src/UI/UI.csproj
- code/src/UI/ViewModels/Common/BaseMainViewModel.cs
- code/src/UI/Views/NewItem/MainView.xaml
- code/src/UI/Views/NewProject/MainView.xaml
Issue #669
Share code between new project and new item views:
- Add WizardHeader control
> Control sharing code

- code/test/Templates.Test/CodeStyleEnforcementTests.cs
Enforce no tab usage in templates
#1126
> Enforce no tab usage in templates

- templates/Features/BackgroundTask/Helpers/TaskExtensions.cs
- templates/Features/BackgroundTask/Services/BackgroundTaskService.cs
- templates/Features/FirstUsePrompt/Services/FirstRunDisplayService.cs
- templates/Features/HubNotifications/Services/ActivationService_postaction.cs
- templates/Features/HubNotifications/Services/HubNotificationsFeatureService.cs
- templates/Features/SettingsStorage/Helpers/SettingsStorageExtensions.cs
- templates/Features/SettingsStorageVB/Helpers/SettingsStorageExtensions.vb
- templates/Features/StoreNotifications/Services/StoreNotificationsFeatureService.cs
- templates/Features/SuspendAndResume/Services/OnBackgroundEnteringEventArgs.cs
- templates/Features/SuspendAndResumeVB/Services/OnBackgroundEnteringEventArgs.vb
- templates/Features/ToastNotifications/Services/ToastNotificationsFeatureService.Samples.cs
- templates/Features/WhatsNewPrompt/Services/WhatsNewDisplayService.cs
- templates/Pages/WebView.CodeBehind/Views/WebViewPagePage.xaml.cs
- templates/Pages/WebView/ViewModels/WebViewPageViewModel.cs
- templates/Projects/Default/Activation/DefaultLaunchActivationHandler.cs
- templates/Projects/Default/App.xaml.cs
- templates/Projects/Default/Services/ActivationService.cs
- templates/Projects/DefaultVB/App.xaml.vb
- templates/Projects/DefaultVB/Services/ActivationService.vb
- templates/_composition/CodeBehind/Project.SplitView/Views/ShellNavigationItem.cs
- templates/_composition/CodeBehind/Project.SplitViewVB/Views/ShellNavigationItem.vb
- templates/_composition/MVVMBasic/Project.SplitView/ViewModels/ShellNavigationItem.cs
- templates/_composition/MVVMBasic/Project.SplitViewVB/ViewModels/ShellNavigationItem.vb
- templates/_composition/MVVMBasic/Project/Helpers/RelayCommand.cs
- templates/_composition/MVVMBasic/ProjectVB/Helpers/RelayCommand.vb
- templates/_composition/MVVMLight/Project.SplitView/ViewModels/ShellNavigationItem.cs
- templates/_composition/MVVMLight/Project.SplitViewVB/ViewModels/ShellNavigationItem.vb
- templates/_composition/MVVMLight/Project/Services/NavigationServiceEx.cs
- templates/_composition/MVVMLight/ProjectVB/Services/NavigationServiceEx.vb
For #1152
+ also updated the wording in some of the generated comments
> Tidy up generated code

- code/test/Templates.Test/CodeStyleEnforcementTests.cs
- templates/Pages/Chart.CodeBehind/Views/ChartViewPage.xaml.cs
- templates/Pages/Chart/Views/ChartViewPage.xaml.cs
#1149
just a minor tweak to comments in generated code
> changing to standard comment format

- code/src/Core/Diagnostics/TelemetryService.cs
Added vs properties to context before returning result
#1154
> Added VS Properties to context

- code/tools/Localization/Localization.csproj
- code/tools/Localization/Logic/ExtractorMode.cs
- code/tools/Localization/Logic/LocalizableItemsExtractor.cs
- code/tools/Localization/Logic/LocalizationTool.cs
- code/tools/Localization/Logic/Routes.cs
- code/tools/Localization/Logic/ValidateLocalizableExtractor.cs
- code/tools/Localization/Program.cs
- code/tools/Localization/packages.config
> Issue1123 review localization tool

- docs/projectTypes/navigationpane.md
Documentation to show how to have a menu item in the SplitView menu run code rather than navigate
For #1137
Just a doc change
> Doc run code from nav menu item

- templates/Features/SettingsStorage/Helpers/SettingsStorageExtensions.cs
- templates/Features/SettingsStorage/Strings/en-us/Resources_postaction.resw
- templates/Pages/Map.CodeBehind/Services/LocationService.cs
- templates/Pages/Map.CodeBehind/Strings/en-us/Resources_postaction.resw
- templates/Pages/Map/Services/LocationService.cs
- templates/Pages/Map/Strings/en-us/Resources_postaction.resw
- templates/Pages/Settings.CodeBehind/Helpers/EnumToBooleanConverter.cs
- templates/Pages/Settings.CodeBehind/Strings/en-us/Resources_postaction.resw
- templates/Pages/Settings.MVVMLight/Helpers/EnumToBooleanConverter.cs
- templates/Pages/Settings.MVVMLight/Strings/en-us/Resources_postaction.resw
- templates/Pages/Settings/Helpers/EnumToBooleanConverter.cs
- templates/Pages/Settings/Strings/en-us/Resources_postaction.resw
- templates/_composition/MVVMLight/Project/Services/NavigationServiceEx.cs
- templates/_composition/MVVMLight/Project/Strings/en-us/Resources_postaction.resw
> Localize exception messages

- code/src/Core/Configuration/Configuration.cs
- code/src/UI/ViewModels/NewProject/MainViewModel.cs
- code/src/UI/ViewModels/NewProject/ProjectSetupViewModel.cs
> Fix new project reset selection

- code/src/UI/Generation/ProjectConfigInfo.cs
- code/test/Templates.Test/BaseGenAndBuildTests.cs
- code/test/Templates.Test/GenTests/GenProjectsTests.cs
Added validations to verify correct use of ProjectConfigInfo
#607
Nop.
Yes.
> Include tests to validate project config info query / infer

- _build/ParallelTestExecution.ps1
- code/test/Templates.Test/BuildCaliburnMicroTests/BuildCaliburnMicroProjectTests.cs
- code/test/Templates.Test/BuildCodeBehindTests/BuildCodeBehindProjectsTests.cs
- code/test/Templates.Test/BuildMVVMBasic/BuildMVVMBasicProjectsTests.cs
- code/test/Templates.Test/BuildMVVMLightTests/BuildMVVMLightProjectsTests.cs
- code/test/Templates.Test/CodeStyleEnforcementTests.cs
- code/test/Templates.Test/FileEncodingTests.cs
- code/test/Templates.Test/StyleCopProjectGenerationTests.cs
- code/test/Templates.Test/TemplateJsonValidationTests.cs
Added script to allow parallel test execution on build server
#1156
> Parallel test execution

- code/AppVeyorCI.sln
Changed build config of UI.Tests
> Changed build config for UI.Tests

- code/test/Templates.Test/WindowsAppCertKitTests.cs
Enabled wack tests to set up wack test execution in build
#1148
> Enabling wack tests to set up wack test execution in daily build

- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.resx
- code/src/UI/ViewModels/NewItem/ChangesSummaryViewModel.cs
- code/src/UI/ViewModels/NewItem/MainViewModel.cs
- code/src/UI/Views/NewItem/ChangesSummaryView.xaml.cs
Show warning when there are no changes after generation of new item
#785
> Issue785 no changes warning

- code/src/UI/ViewModels/NewProject/ProjectTemplatesViewModel.cs
Fixed features header bug
#1172
> Fixed features header bug

- code/src/UI/Controls/CodeViewer.xaml.cs
- code/src/UI/Services/SystemService.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/BaseFileViewModel.cs
Fixed bug on codeviewer not showing first file on changes summary
#785
> Fixed bug on codeviewer showing first file on changes summary

- templates/Pages/MasterDetail.CaliburnMicro/Views/MasterDetailsItemDetail/DetailsView.xaml
- templates/Pages/MasterDetail.CaliburnMicro/Views/MasterDetailsItemDetail/MasterView.xaml
- templates/Pages/MasterDetail.CaliburnMicro/Views/MasterDetailsItemPage.xaml
Adapted Caliburn.Micro MasterDetail to new designs. Pending revision in #1183 and extraction of styles to resource dictionary.
#1184
> Adapted Caliburn.Micro MasterDetail to new designs

- CONTRIBUTING.md
Trying to better set expectations about contributing and avoid anyone charging in with a PR that we weren't expecting and can't accept.
> Add "Before you begin" section to contributing.md

- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/ConflictingFileViewModel.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/FailedMergesFileViewModel.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/ModifiedFileViewModel.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/NewFileViewModel.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/UnchangedFileViewModel.cs
- code/src/UI/Views/NewItem/ChangesSummaryView.xaml
> Update file changes layout

- templates/Pages/Map.CaliburnMicro/Services/LocationService.cs
- templates/Pages/Map.CodeBehind/Services/LocationService.cs
- templates/Pages/Map/Services/LocationService.cs
- templates/Projects/Default/App.xaml.cs
- templates/_composition/CaliburnMicro/Project/App.xaml.cs
> Remove XmlDoc style comments.

- README.md
- docs/getting-started-developers.md
Added wack tests and build output to docs
#1148
> Added wack tests and build output to docs

- code/test/Core.Test/Core.Test.csproj
- code/test/Core.Test/PostActions/Catalog/MergeResourceDictionaryPostactionTest.cs
- code/test/Core.Test/TestData/Merge/Style_expected.xaml
> Issue1179 resourcedictionarypostaction

- code/test/Core.Test/PostActions/Catalog/MergeResourceDictionaryPostactionTest.cs
- templates/_composition/_shared/Page.EnsureMergedDictionaries/.template.config/template.json
- templates/_composition/_shared/Page.EnsureMergedDictionaries/App_postaction.xaml
-Added template to ensure merged dictionaries
-Fixed appveyor tests
> Added template  to ensure merged dictionaries

- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/BaseFileViewModel.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/ConflictingFileViewModel.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/FailedMergesFileViewModel.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/FailedStyleMergesFileViewModel.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/ModifiedFileViewModel.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/NewFileViewModel.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/UnchangedFileViewModel.cs
- code/tools/Localization/Localization.csproj
- code/tools/Localization/Logic/CSharpProjectTemplateGenerator.cs
- code/tools/Localization/Logic/ProjectTemplateGeneratorBase.cs
- code/tools/Localization/Logic/ProjectTemplateGeneratorConfig.cs
- code/tools/Localization/Logic/VisualBasicProjectTemplateGenerator.cs
> Fix StyleCop rule CA2214 violation

- code/src/Core/Gen/GenShell.cs
- code/src/Core/PostActions/Catalog/NewItemGeneration/CopyFilesToProjectPostAction.cs
- code/src/UI/VisualStudio/VsGenShell.cs
- code/test/Fakes/FakeGenShell.cs
> Issue1215 - Right-Click needing double compile

- templates/Features/WhatsNewPrompt/.template.config/icon.xaml
For #1052
Fixes blurry off center exclamation mark
Now looks like this
> new icon for WhatsNewPrompt features

- templates/Features/SampleData/Models/SampleOrder.cs
> Add sample order data ToString for narrator information

- code/src/UI/Controls/StatusBox.xaml.cs
- code/src/UI/ViewModels/NewProject/MainViewModel.cs
> Fix Issue 757

- templates/Pages/MasterDetail.CaliburnMicro/ViewModels/MasterDetailViewViewModel.cs
- templates/Pages/MasterDetail.CaliburnMicro/Views/MasterDetailViewPage.xaml
- templates/Pages/MasterDetail.CaliburnMicro/Views/MasterDetailViewPage.xaml.cs
Issue #1184
I've fixed ActiveItem initialization on Caliburn.Micro.
Could @nigel-sampson please review that? I don't know if this is the best approach to do that on Caliburn.Micro Framework.
> Fix ActiveItem initialization in Caliburn.Micro

- code/src/Core/Locations/RemoteTemplatesSource.cs
- code/test/Templates.Test/BuildRightClickWithLegacy/LegacyTemplatesSource.cs
Changed ForcedAcquisition back to false on RemoteTemplateSource
#1165
> Changed ForcedAcquisition back to false on RemoteTemplateSource

- code/test/UI.Test/NewProjectTest.cs
> Fixed UI tests

- code/src/UI/Services/LicensesService.cs
- code/src/UI/Services/OrderingService.cs
- code/src/UI/Services/ResourceService.cs
- code/src/UI/Services/UserSelectionService.cs
- code/src/UI/UI.csproj
- code/src/UI/ViewModels/Common/BaseMainViewModel.cs
- code/src/UI/ViewModels/NewItem/ChangesSummaryFiles/BaseFileViewModel.cs
- code/src/UI/ViewModels/NewItem/MainViewModel.cs
- code/src/UI/ViewModels/NewProject/MainViewModel.cs
- code/src/UI/ViewModels/NewProject/ProjectSetupViewModel.cs
- code/src/UI/ViewModels/NewProject/ProjectTemplatesViewModel.cs
- code/src/UI/ViewModels/NewProject/SavedTemplateViewModel.cs
- code/src/UI/ViewModels/NewProject/TemplateInfoViewModel.cs
- code/test/UI.Test/NewProjectTest.cs
> UI project refactors and tests improovements

- templates/Pages/MasterDetail.CaliburnMicro/_postaction.csproj
- templates/_composition/CaliburnMicro/Project.SplitView/_postaction.csproj
- templates/_composition/CodeBehind/Project.SplitView/_postaction.csproj
- templates/_composition/MVVMBasic/Project.SplitView/_postaction.csproj
- templates/_composition/MVVMLight/Project.SplitView/_postaction.csproj
- templates/_composition/_shared/Page.MasterDetail/_postaction.csproj
Update community toolkit to 2.0.0, corrected indent on postactions
#1045 
Yes
> Update community toolkit to 2.0.0, corrected indent on postactions

- templates/Pages/MasterDetail.CaliburnMicro/Views/MasterDetailViewDetail/DetailsView.xaml
- templates/Pages/MasterDetail.CaliburnMicro/Views/MasterDetailViewDetail/MasterView.xaml
- templates/_composition/_shared/Page.AddPageStyle/.template.config/template.json
- templates/_composition/_shared/Page.AddPageStyle/Styles/Control_postaction.xaml
- templates/_composition/_shared/Page.AddPageStyle/Views/wts.ItemNamePage_postaction.xaml
- templates/_composition/_shared/Page.Camera.AddResource/Controls/CameraControl.xaml
- templates/_composition/_shared/Page.MasterDetail/Views/wts.ItemNameDetailControl.xaml
#1175
Add style and background to all pages and controls
> Issue1252 backgroundcolor

- code/src/Installer.2017/Commands/RelayCommandPackage.cs
- code/src/UI/Threading/SafeThreading.cs
- code/src/UI/UI.csproj
- code/src/UI/ViewModels/Common/BaseMainViewModel.cs
- code/src/UI/ViewModels/NewItem/MainViewModel.cs
- code/src/UI/ViewModels/NewProject/MainViewModel.cs
- code/src/UI/VisualStudio/SolutionWizard.cs
- code/src/UI/VisualStudio/VsGenShell.cs
- code/src/UI/VisualStudio/VsOutputPane.cs
- code/test/VsEmulator/Main/MainViewModel.cs
Update the way we ensure safety in threading to avoid errors when no VS instance is available
#1265 
Nop
Yes
> Review the way we handle safety in threading

- code/test/Templates.Test/FileEncodingTests.cs
Added check for nonbreakingwhitespaces to file encoding test
#1202
> Added check for nonbreakingwhitespaces to file encoding test

- templates/_composition/_shared/Page.Camera.AddResource/Controls/CameraControl.xaml.cs
- templates/_composition/_shared/Page.Camera.AddResource/Helpers/CameraOrientationExtensions.cs
> Fix camera snapshot rotation

- templates/Pages/MasterDetail.CaliburnMicro/Views/MasterDetailViewDetail/DetailsView.xaml
- templates/Pages/MasterDetail.CaliburnMicro/Views/MasterDetailViewDetail/MasterView.xaml
- templates/_composition/_shared/Page.AddPageStyle/Styles/Page_postaction.xaml
- templates/_composition/_shared/Page.AddPageStyle/Views/wts.ItemNamePage_postaction.xaml
- templates/_composition/_shared/Page.Camera.AddResource/Controls/CameraControl.xaml
- templates/_composition/_shared/Page.MasterDetail/Views/wts.ItemNameDetailControl.xaml
Update Page.AddStyle position to add one single page style instead of control style. Discussion on #1255
> Update Page.AddStyle postaction

- code/tools/Localization/Logic/Routes.cs
#1123
Fix indentation to vsix files.
> Fix vsixlangpack file format.

- templates/Pages/Map.CaliburnMicro/Services/LocationService.cs
- templates/Pages/Map.CaliburnMicro/Strings/en-us/Resources_postaction.resw
- templates/Pages/Settings.CaliburnMicro/Helpers/EnumToBooleanConverter.cs
- templates/Pages/Settings.CaliburnMicro/Strings/en-us/Resources_postaction.resw
- templates/_composition/CaliburnMicro/Project/Services/ActivationService.cs
> Localize exception messages in Caliburn.Micro

- code/src/UI/ViewModels/NewProject/MainViewModel.cs
> Fix reset selection in Wizard

- code/src/Core/Locations/LocalTemplatesSource.cs
- code/test/Core.Test/Locations/UnitTestsTemplatesSource.cs
- code/test/Templates.Test/BuildRightClickWithLegacy/LegacyTemplatesSource.cs
> Include AGENT_NAME if exists in template source id for tests

- code/test/Core.Test/Packaging/TemplatePackageTests.cs
> Avoid error when run multiple agents at the same time

- code/test/Core.Test/TestData/TestProject/Test.csproj
- samples/activation/MarkdownViewer/MarkdownViewer.csproj
- samples/navigation/MixedNavigationSample.CodeBehind/MixedNavigationSample.CodeBehind/MixedNavigationSample.CodeBehind.csproj
- samples/navigation/MixedNavigationSample.MVVMBasic/MixedNavigationSample.MVVMBasic/MixedNavigationSample.MVVMBasic.csproj
- samples/navigation/MixedNavigationSample.MVVMLight/MixedNavigationSample.MVVMLight/MixedNavigationSample.MVVMLight.csproj
- samples/suspendandresume/TasksApp/TasksApp/TasksApp.csproj
- samples/suspendandresume/VideoResume/VideoResume.MVVMBasic/VideoResume.MVVMBasic/VideoResume.MVVMBasic.csproj
- samples/suspendandresume/VideoResume/VideoResume.MVVMLight/VideoResume.MVVMLight/VideoResume.MVVMLight.csproj
- templates/Projects/Default/wts.DefaultProject.csproj
- templates/Projects/DefaultVB/wts.DefaultProject.vbproj
#1185, #1223 
From this commit, the generated code will target FCU SDK
YES
> Update TargetPlatformVersion to 10.0.16299.0 and NETCore.uwp to 6.0.1

- code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyTests.cs
Changed test name to show correctly in test results
> Changed legacy test name

- templates/Pages/ImageGallery.CodeBehind/Views/ImageGalleryViewDetailPage.xaml.cs
> Start ShowFlipView animation on CodeBehind ImageGallery

- code/src/Core/Diagnostics/TelemetryProperties.cs
- code/src/Core/Diagnostics/TelemetryService.cs
- code/src/Core/Diagnostics/TelemetryTracker.cs
- code/src/Core/Gen/GenContext.cs
- code/src/Core/Gen/GenShell.cs
- code/src/UI/Generation/NewItemGenController.cs
- code/src/UI/Generation/NewProjectGenController.cs
- code/src/UI/VisualStudio/VsGenShell.cs
- code/test/Core.Test/Core.Test.csproj
- code/test/Core.Test/packages.config
- code/test/Templates.Test/Templates.Test.csproj
- code/test/Templates.Test/packages.config
- code/test/UI.Test/UI.Test.csproj
- code/test/UI.Test/packages.config
We currently have the exe version tracked but not the product version (15.4.xxxx)
#1154
No
> Add vs product version to telemetry

- templates/_composition/CaliburnMicro/Project.SplitView/ViewModels/ShellNavigationItem.cs
> Update SplitView selection foreground in Caliburn.Micro

- templates/Pages/ImageGallery.CaliburnMicro/.template.config/template.json
- templates/Pages/ImageGallery.CodeBehind/.template.config/template.json
- templates/Pages/ImageGallery/.template.config/template.json
> Make image gallery as hidden

- templates/Pages/Map.CaliburnMicro/ViewModels/MapPageViewModel.cs
> Move map page load logic to OnInitialize Caliburn.Micro method

- templates/_composition/_shared/Page.Camera.AddResource/Controls/CameraControl.xaml.cs
> Issue519 camera page caliburn micro

- templates/Pages/ImageGallery.CaliburnMicro/Views/ImageGalleryViewDetailPage.xaml
- templates/Pages/ImageGallery.CodeBehind/Views/ImageGalleryViewDetailPage.xaml
- templates/Pages/ImageGallery/Views/ImageGalleryViewDetailPage.xaml
- templates/Pages/MasterDetail.CaliburnMicro/Views/MasterDetailViewPage.xaml
- templates/Pages/MasterDetail.CodeBehind/Views/MasterDetailViewPage.xaml
- templates/Pages/MasterDetail/Views/MasterDetailViewPage.xaml
- templates/Pages/Settings.CaliburnMicro/Views/SettingsPagePage.xaml
- templates/Pages/Settings.CodeBehind/Views/SettingsPagePage.xaml
> Review binding modes in generated code.

- templates/Pages/ImageGallery.CaliburnMicro/Views/ImageGalleryViewDetailPage.xaml.cs
- templates/Pages/ImageGallery.CodeBehind/Views/ImageGalleryViewDetailPage.xaml.cs
- templates/Pages/ImageGallery/Views/ImageGalleryViewDetailPage.xaml.cs
#1164
Check Back NavigationMode before call SetAnimation
> Check Back NavigationMode before call SetAnimation

- templates/Features/ShareTarget.CaliburnMicro/App_postaction.xaml.cs
- templates/Features/ShareTarget/App_postaction.xaml.cs
> StyleCop fixes

- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.resx
- code/tools/TemplateValidator/TemplateJsonVerifier.cs
- templates/Features/ShareTarget.CaliburnMicro/.template.config/template.json
- templates/Features/ShareTarget.CaliburnMicro/App_postaction.xaml.cs
- templates/Features/ShareTarget/.template.config/template.json
- templates/Features/ShareTarget/App_postaction.xaml.cs
- templates/_composition/CaliburnMicro/Feature.ShareTargetExamplePage/ViewModels/wts.ItemNameExampleViewModel.cs
- templates/_composition/CodeBehind/Feature.ShareTargetExamplePage/Views/wts.ItemNameExamplePage.xaml.cs
- templates/_composition/MVVMBasic/Feature.ShareTargetExamplePage/ViewModels/wts.ItemNameExampleViewModel.cs
- templates/_composition/MVVMBasic/Feature.ShareTargetExamplePage/Views/wts.ItemNameExamplePage.xaml.cs
- templates/_composition/MVVMLight/Feature.ShareTargetExamplePage/ViewModels/wts.ItemNameExampleViewModel.cs
- templates/_composition/MVVMLight/Feature.ShareTargetExamplePage/Views/wts.ItemNameExamplePage.xaml.cs
- templates/_composition/_shared/Feature.ShareTarget/.template.config/template.json
- templates/_composition/_shared/Feature.ShareTarget/Activation/ShareTargetActivationHandler.cs
- templates/_composition/_shared/Feature.ShareTarget/Helpers/ShareOperationExtensions.cs
- templates/_composition/_shared/Feature.ShareTarget/Services/ActivationService_postaction.cs
#365
Updates on Share Target Feature
> Updates on Share Target Feature

- code/Test.sln
Added localizationtool to Test.sln to integrate localization verification in build
#1273
> Added localizationtool to test.sln

- CONTRIBUTING.md
- docs/PULL_REQUEST_TEMPLATE.md
> Added Links to template checklist from contribution guidelines and PR template

- templates/Features/UriScheme/.template.config/template.json
- templates/Features/UriSchemeVB/.template.config/template.json
> Changed UriSheme category to AppToApp

- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
- code/src/UI/ViewModels/NewItem/MainViewModel.cs
> Update new page/feature wizard title

- code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyTests.cs
- code/test/Templates.Test/BuildRightClickWithLegacy/LegacyTemplatesSource.cs
Added comment to ManualOnly tests, changed legacy template source version 
#1165
> Added comment to legacy tests, changed legacy template source version

- templates/Features/ShareSource/.template.config/template.json
- templates/Features/ShareTarget.CodeBehind/.template.config/template.json
- templates/Features/ShareTarget/.template.config/template.json
- templates/Features/UriScheme/.template.config/template.json
- templates/Features/UriSchemeVB/.template.config/template.json
- templates/Features/WebToAppLink/.template.config/template.json
Reordered templates within App To App category 
#827
> Reordered templates within App To App category

- templates/Features/ShareSource/.template.config/template.json
- templates/Features/ShareSource/Services/ShareSourceFeatureService.cs
> ShareSource updates

- templates/Features/ShareTarget.CodeBehind/Views/ShareTargetFeaturePage.xaml.cs
- templates/_composition/CaliburnMicro/Feature.ShareTarget/ViewModels/wts.ItemNameViewModel.cs
- templates/_composition/CodeBehind/Feature.UriSchemeExamplePage/Views/wts.ItemNameExamplePage.xaml.cs
- templates/_composition/CodeBehind/Feature.UriSchemeExamplePageVB/Views/wts.ItemNameExamplePage.xaml.vb
- templates/_composition/MVVMBasic/Feature.ShareTarget/ViewModels/wts.ItemNameViewModel.cs
- templates/_composition/MVVMBasic/Feature.ShareTarget/Views/wts.ItemNamePage.xaml.cs
- templates/_composition/MVVMBasic/Feature.UriSchemeExamplePage/Views/wts.ItemNameExamplePage.xaml.cs
- templates/_composition/MVVMBasic/Feature.UriSchemeExamplePageVB/Views/wts.ItemNameExamplePage.xaml.vb
- templates/_composition/MVVMLight/Feature.ShareTarget/ViewModels/wts.ItemNameViewModel.cs
- templates/_composition/MVVMLight/Feature.ShareTarget/Views/wts.ItemNamePage.xaml.cs
- templates/_composition/MVVMLight/Feature.UriSchemeExamplePage/Views/wts.ItemNameExamplePage.xaml.cs
- templates/_composition/MVVMLight/Feature.UriSchemeExamplePageVB/Views/wts.ItemNameExamplePage.xaml.vb
> ShareTarget updates

- code/src/UI/Controls/WizardHeader.xaml
- code/src/UI/ViewModels/Common/WizardStatus.cs
- code/src/UI/Views/NewItem/MainView.xaml.cs
- code/src/UI/Views/NewProject/MainView.xaml.cs
Fix behavior on show more info button in Wizard
> Show Info button updates

- code/src/Core/PostActions/Catalog/NewItemGeneration/CopyFilesToProjectPostAction.cs
Do not open generated image files
#1410
> Do not open generated image files

- code/src/UI/ViewModels/Common/ErrorViewModel.cs
> Fix error message window heght

- code/src/UI/Generation/NewItemGenController.cs
CleanUp ProjectItems as there could be files added due to ResourceDictionaryPostactions
#1411
> CleanUp ProjectItems when changing selection

- code/src/UI/Services/SystemService.cs
> Fix High contrast issue #1431

- code/src/UI/Services/DataService.cs
> Set category ordet by name instead of title

- CONTRIBUTING.md
- README.md
- docs/PULL_REQUEST_TEMPLATE.md
- Two typos I noticed creating my PR for Prism
- Consistent line endings for bullet lists
> Fixing markdown typos and consistent punctuation

- poc/MultiViewFeaturePoC/MultiViewFeaturePoC/MultiViewFeaturePoC.csproj
- poc/MultiViewFeaturePoC/MultiViewFeaturePoC/Services/ActivationService.cs
- poc/MultiViewFeaturePoC/MultiViewFeaturePoC/Services/ViewLifetimeControl.cs
- poc/MultiViewFeaturePoC/MultiViewFeaturePoC/Services/WindowManagerService.cs
- poc/MultiViewFeaturePoC/MultiViewFeaturePoC/Strings/en-us/Resources.resw
- poc/MultiViewFeaturePoC/MultiViewFeaturePoC/ViewModels/Scenario1SecondaryViewModel.cs
- poc/MultiViewFeaturePoC/MultiViewFeaturePoC/ViewModels/Scenario1ViewModel.cs
- poc/MultiViewFeaturePoC/MultiViewFeaturePoC/ViewModels/Scenario2ViewModel.cs
- poc/MultiViewFeaturePoC/MultiViewFeaturePoC/ViewModels/Scenario3SecondaryViewModel.cs
- poc/MultiViewFeaturePoC/MultiViewFeaturePoC/ViewModels/Scenario3ViewModel.cs
- poc/MultiViewFeaturePoC/MultiViewFeaturePoC/Views/PivotPage.xaml
- poc/MultiViewFeaturePoC/MultiViewFeaturePoC/Views/Scenario1SecondaryPage.xaml.cs
- poc/MultiViewFeaturePoC/MultiViewFeaturePoC/Views/Scenario3SecondaryPage.xaml
- poc/MultiViewFeaturePoC/MultiViewFeaturePoC/Views/Scenario3SecondaryPage.xaml.cs
Memory leak fixed on MultiView PoC
> Fix in MultiView PoC

- code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.csproj
- code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.Xamarin.VS2017.Solution.vstemplate
Added projectTemplate for Xamarin
> Added projecttemplate for xamarin

- poc/MultiViewFeaturePoC/MultiViewFeaturePoC/Services/ViewLifetimeControl.cs
- poc/MultiViewFeaturePoC/MultiViewFeaturePoC/Services/WindowManagerService.cs
- templates/Features/MultiView/.template.config/icon.xaml
- templates/Features/MultiView/.template.config/template.json
- templates/Features/MultiView/Services/ViewLifetimeControl.cs
- templates/Features/MultiView/Services/WindowManagerService.cs
Add MultiView feature Template #241
> MultiView feature template

- templates/Features/MultiView/.template.config/description.md
- templates/Features/MultiView/.template.config/template.json
- templates/Features/ShareSource/.template.config/description.md
- templates/Features/ShareTarget/.template.config/description.md
Adjusting text for multi-view and shared source
> adding / adjusting text

- templates/Features/MultiView/.template.config/cs-CZ.description.md
- templates/Features/MultiView/.template.config/cs-CZ.template.json
- templates/Features/MultiView/.template.config/de-DE.description.md
- templates/Features/MultiView/.template.config/de-DE.template.json
- templates/Features/MultiView/.template.config/es-ES.description.md
- templates/Features/MultiView/.template.config/es-ES.template.json
- templates/Features/MultiView/.template.config/fr-FR.description.md
- templates/Features/MultiView/.template.config/fr-FR.template.json
- templates/Features/MultiView/.template.config/it-IT.description.md
- templates/Features/MultiView/.template.config/it-IT.template.json
- templates/Features/MultiView/.template.config/ja-JP.description.md
- templates/Features/MultiView/.template.config/ja-JP.template.json
- templates/Features/MultiView/.template.config/ko-KR.description.md
- templates/Features/MultiView/.template.config/ko-KR.template.json
- templates/Features/MultiView/.template.config/pl-PL.description.md
- templates/Features/MultiView/.template.config/pl-PL.template.json
- templates/Features/MultiView/.template.config/pt-BR.description.md
- templates/Features/MultiView/.template.config/pt-BR.template.json
- templates/Features/MultiView/.template.config/ru-RU.description.md
- templates/Features/MultiView/.template.config/ru-RU.template.json
- templates/Features/MultiView/.template.config/tr-TR.description.md
- templates/Features/MultiView/.template.config/tr-TR.template.json
- templates/Features/MultiView/.template.config/zh-CN.description.md
- templates/Features/MultiView/.template.config/zh-CN.template.json
- templates/Features/MultiView/.template.config/zh-TW.description.md
- templates/Features/MultiView/.template.config/zh-TW.template.json
> Add localization resources to MultiViewTemplate

- code/test/Templates.Test/BaseGenAndBuildTests.cs
- code/test/Templates.Test/BuildCaliburnMicroTests/BuildCaliburnMicroProjectTests.cs
- code/test/Templates.Test/BuildCodeBehindTests/BuildCodeBehindProjectTests.cs
- code/test/Templates.Test/BuildMVVMBasic/BuildMVVMBasicProjectTests.cs
- code/test/Templates.Test/BuildMVVMLightTests/BuildMVVMLightProjectTests.cs
-Quick summary of changes
Include platform filter for rightclick templates in tests.
Set SolutionPath for OneByOneTests
Shortened some names
#1471
> Fixed some tests

- code/tools/Localization/Logic/LocalizableItemsExtractor.cs
- code/tools/Localization/Logic/LocalizableItemsVerificator.cs
- code/tools/Localization/Logic/Routes.cs
- code/tools/Localization/Logic/ValidateLocalizableExtractor.cs
- Filter localization resources: not VB resources.
- Get commits from date of commit sha
- Change validation and extract templates resources to work with subdirectories of xamarin and uwp
> Changes in localization tool

- code/Test.sln
Added tool to Test.sln to use from build
#1488
> Added tool to test.sln

- templates/Features/HubNotifications/Services/HubNotificationsFeatureService.cs
- templates/Features/HubNotificationsVB/Services/HubNotificationsFeatureService.vb
Add comments in HubNotification template suggested on #1461
> Add comment aditions in HubNotification template

- code/test/Templates.Test/CodeStyleEnforcementTests.cs
- templates/Features/WhatsNewPromptVB/Services/WhatsNewDisplayService.vb
- templates/_composition/_shared/Page.ImageGalleryVB/Services/SampleDataService$wts.ItemName_gpostaction.vb
For #1339
+ add appropriate test
and fix the issue that test found
> Fix sampledata template for VB ImageGallery

- code/tools/WtsTool/CommandOptions/PackageOptions.cs
- code/tools/WtsTool/PackageWorker.cs
- code/tools/WtsTool/RemoteSourceWorker.cs
- code/tools/WtsTool/RunCommand.cs
Related to #1488 and #1476
Allow builds to prepare the templates to be shipped.
> Include package-task prepare option

- code/tools/WtsTool/PackageWorker.cs
- code/tools/WtsTool/RunCommand.cs
> Fix issues in filtering

- code/tools/WtsTool/RunCommand.cs
> Avoid console error if not present

- code/tools/WtsTool/PackageWorker.cs
> Avoid error due to the version number

- code/tools/WtsTool/ConsoleHelper.cs
- code/tools/WtsTool/PackageWorker.cs
- code/tools/WtsTool/Program.cs
- code/tools/WtsTool/TextWriterExtensions.cs
- code/tools/WtsTool/WtsTool.csproj
> Ensure source path is replaced

- docs/notifications.md
- Mispelling
- No
- No
- No
- No
- No
- No
> Minor fix (capital issue)

- templates/Pages/ImageGallery.CodeBehindVB/.template.config/template.json
Added another missing parameter 
#1535
> Another missing parameter

- _build/Execute-LocalTestsInParallel.ps1
- code/test/Templates.Test/BuildPrismTests/BuildPrismFixture.cs
Fixed a path in prism tests to allow correct concurrent execution. 
Included prism in local test execution set.
#304
> Fix prism tests, include to local test script

- templates/Features/StoreNotifications/Services/ActivationService_postaction.cs
> Initialize StoreNotifications on ActivationService StartupAsync method

- code/test/Templates.Test/BuildRightClickWithLegacy/LegacyTemplatesSource.cs
updated legacy tests to run against 1.5 version
> Updated legacy tests

- code/src/UI/ViewModels/NewItem/NewItemSetupViewModel.cs
Order groups by name instead of title like in New Project Wizard
#1421 
No
Yes
> Order groups by name instead of title like in New Project Wizard

- templates/_composition/Prism/Project.SplitView.AddToSecondaryNavigationItems/ViewModels/ShellViewModel_postaction.cs
For Issue #1625, simple fix to set correct icon for settings page when using Prism framework.
> Changed icon for Settings page to Symbol.Settings

- templates/Features/BackgroundTaskVB/Services/ActivationService_postaction.vb
- templates/Features/HubNotificationsVB/Services/ActivationService_postaction.vb
- templates/Features/LiveTileVB/Services/ActivationService_postaction.vb
- templates/Features/StoreNotificationsVB/Services/ActivationService_postaction.vb
- templates/Features/ToastNotificationsVB/Services/ActivationService_postaction.vb
- templates/_composition/_shared/Feature.ShareTargetVB/Services/ActivationService_postaction.vb
To match previous C# template change
(for #1580)
> Update store notification service caching

- templates/Features/FirstUsePrompt.Prism/.template.config/template.json
- templates/Features/FirstUsePrompt.Prism/Services/FirstRunDisplayService.cs
- templates/Features/FirstUsePrompt.Prism/_postaction.csproj
- templates/Features/FirstUsePrompt/.template.config/template.json
- templates/Features/FirstUsePrompt/Services/FirstRunDisplayService.cs
- templates/Features/FirstUsePrompt/_postaction.csproj
- templates/Features/WhatsNewPrompt.Prism/.template.config/template.json
- templates/Features/WhatsNewPrompt.Prism/Services/WhatsNewDisplayService.cs
- templates/Features/WhatsNewPrompt.Prism/_postaction.csproj
- templates/Features/WhatsNewPrompt/.template.config/template.json
- templates/Features/WhatsNewPrompt/Services/WhatsNewDisplayService.cs
- templates/Features/WhatsNewPrompt/_postaction.csproj
> Issue1304 update first run and whats news features

- templates/Features/FirstUsePromptVB/.template.config/template.json
- templates/Features/FirstUsePromptVB/Services/FirstRunDisplayService.vb
- templates/Features/FirstUsePromptVB/_postaction.vbproj
- templates/Features/WhatsNewPromptVB/.template.config/template.json
- templates/Features/WhatsNewPromptVB/Services/WhatsNewDisplayService.vb
- templates/Features/WhatsNewPromptVB/_postaction.vbproj
> VB equiv of #1631

- templates/Pages/MediaPlayer.CodeBehind/Views/MediaPlayerViewPage.xaml.cs
- templates/Pages/MediaPlayer/Views/MediaPlayerViewPage.xaml.cs
- templates/_composition/CodeBehind/Page.MediaPlayer.AddNavigation_Blank_SplitView/.template.config/template.json
- templates/_composition/CodeBehind/Page.MediaPlayer.AddNavigation_Blank_SplitView/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/_composition/CodeBehind/Page.MediaPlayer.AddNavigation_TabbedPivot/.template.config/template.json
- templates/_composition/CodeBehind/Page.MediaPlayer.AddNavigation_TabbedPivot/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/_composition/CodeBehind/Page.MediaPlayer.AddNavigation_TabbedPivot/_postaction.csproj
- templates/_composition/_shared/Page.MediaPlayer.AddNavigation_Blank_SplitView/.template.config/template.json
- templates/_composition/_shared/Page.MediaPlayer.AddNavigation_Blank_SplitView/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/_composition/_shared/Page.MediaPlayer.AddNavigation_TabbedPivot/.template.config/template.json
- templates/_composition/_shared/Page.MediaPlayer.AddNavigation_TabbedPivot/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/_composition/_shared/Page.MediaPlayer.AddNavigation_TabbedPivot/_postaction.csproj
> Issue1504 pivot and media player page

- templates/Pages/MediaPlayer.CodeBehindVB/Views/MediaPlayerViewPage.xaml.vb
- templates/Pages/MediaPlayerVB/Views/MediaPlayerViewPage.xaml.vb
- templates/_composition/CodeBehind/Page.MediaPlayer.AddNavigation_Blank_SplitViewVB/.template.config/template.json
- templates/_composition/CodeBehind/Page.MediaPlayer.AddNavigation_Blank_SplitViewVB/Views/wts.ItemNamePage_postaction.xaml.vb
- templates/_composition/CodeBehind/Page.MediaPlayer.AddNavigation_TabbedPivotVB/.template.config/template.json
- templates/_composition/CodeBehind/Page.MediaPlayer.AddNavigation_TabbedPivotVB/Views/wts.ItemNamePage_postaction.xaml.vb
- templates/_composition/CodeBehind/Page.MediaPlayer.AddNavigation_TabbedPivotVB/_postaction.vbproj
- templates/_composition/_shared/Page.MediaPlayer.AddNavigation_Blank_SplitViewVB/.template.config/template.json
- templates/_composition/_shared/Page.MediaPlayer.AddNavigation_Blank_SplitViewVB/Views/wts.ItemNamePage_postaction.xaml.vb
- templates/_composition/_shared/Page.MediaPlayer.AddNavigation_TabbedPivotVB/.template.config/template.json
- templates/_composition/_shared/Page.MediaPlayer.AddNavigation_TabbedPivotVB/Views/wts.ItemNamePage_postaction.xaml.vb
- templates/_composition/_shared/Page.MediaPlayer.AddNavigation_TabbedPivotVB/_postaction.vbproj
For #1639 
The VB equivalent of #1638
> media player page now pauses on pivot change (VB template version)

- templates/Features/LiveTile.Prism/Services/LiveTileFeatureService.cs
- templates/Features/LiveTile/Services/LiveTileFeatureService.cs
- templates/Features/LiveTileVB/Services/LiveTileFeatureService.vb
- templates/Features/SuspendAndResume/Services/SuspendAndResumeService.cs
- templates/Features/SuspendAndResumeVB/Services/SuspendAndResumeService.vb
- templates/Pages/Settings.CaliburnMicro/Services/ThemeSelectorService.cs
- templates/Pages/Settings.CodeBehind/Services/ThemeSelectorService.cs
- templates/Pages/Settings.CodeBehindVB/Services/ThemeSelectorService.vb
- templates/Pages/Settings.Prism/Services/ThemeSelectorService.cs
- templates/Pages/Settings/Services/ThemeSelectorService.cs
- templates/Pages/SettingsVB/Services/ThemeSelectorService.vb
> Rename settings keys.

- code/src/Core/Locations/SyncStatusEventArgs.cs
- code/src/Core/Locations/TemplatesContent.cs
- code/src/Core/Locations/TemplatesSynchronization.cs
- code/src/UI/Extensions/SyncStatusExtensions.cs
- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
- code/src/UI/ViewModels/Common/BaseMainViewModel.cs
- code/src/UI/ViewModels/Common/StatusViewModel.cs
Add version to sync status event and sync message review 
#1376 
No
Yes
> Review sync messages

- templates/Pages/ImageGallery.CaliburnMicro/ViewModels/ImageGalleryViewDetailViewModel.cs
- templates/Pages/ImageGallery.CaliburnMicro/ViewModels/ImageGalleryViewViewModel.cs
- templates/Pages/ImageGallery.CodeBehind/Views/ImageGalleryViewDetailPage.xaml.cs
- templates/Pages/ImageGallery.CodeBehind/Views/ImageGalleryViewPage.xaml.cs
- templates/Pages/ImageGallery.CodeBehindVB/Views/ImageGalleryViewDetailPage.xaml.vb
- templates/Pages/ImageGallery.CodeBehindVB/Views/ImageGalleryViewPage.xaml.vb
- templates/Pages/ImageGallery.Prism/ViewModels/ImageGalleryViewDetailViewModel.cs
- templates/Pages/ImageGallery.Prism/ViewModels/ImageGalleryViewViewModel.cs
- templates/Pages/ImageGallery/ViewModels/ImageGalleryViewDetailViewModel.cs
- templates/Pages/ImageGallery/ViewModels/ImageGalleryViewViewModel.cs
- templates/Pages/ImageGalleryVB/ViewModels/ImageGalleryViewDetailViewModel.vb
- templates/Pages/ImageGalleryVB/ViewModels/ImageGalleryViewViewModel.vb
> Rename Image gallery page settings keys.

- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
Reset to english changed status messages until translated translated resources are back.
#1376 
No
Yes
> Reset to english changed status messages

- templates/_composition/CaliburnMicro/Page.MediaPlayer.AddNavigation_TabbedPivot/.template.config/template.json
- templates/_composition/CaliburnMicro/Page.MediaPlayer.AddNavigation_TabbedPivot/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/_composition/CaliburnMicro/Page.MediaPlayer.AddNavigation_TabbedPivot/_postaction.csproj
- templates/_composition/CodeBehind/Page.MediaPlayer.AddNavigation_TabbedPivot/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/_composition/CodeBehind/Page.MediaPlayer.AddNavigation_TabbedPivotVB/Views/wts.ItemNamePage_postaction.xaml.vb
- templates/_composition/_shared/Page.MediaPlayer.AddNavigation_TabbedPivotVB/Views/wts.ItemNamePage_postaction.xaml.vb
> Fix Media Player page in Caliburn Micro Framework and Pivot project.

- templates/Features/SampleDataVB/Models/SampleOrder.vb
For #1706
Just a small VB template UI issue (see issue for before and after screenshots)
> Fix MasterDetail symbol display issue

- code/src/Core/Resources/StringRes.cs-CZ.resx
- code/src/Core/Resources/StringRes.de-DE.resx
- code/src/Core/Resources/StringRes.es-ES.resx
- code/src/Core/Resources/StringRes.fr-FR.resx
- code/src/Core/Resources/StringRes.it-IT.resx
- code/src/Core/Resources/StringRes.ja-JP.resx
- code/src/Core/Resources/StringRes.ko-KR.resx
- code/src/Core/Resources/StringRes.pl-PL.resx
- code/src/Core/Resources/StringRes.pt-BR.resx
- code/src/Core/Resources/StringRes.ru-RU.resx
- code/src/Core/Resources/StringRes.tr-TR.resx
- code/src/Core/Resources/StringRes.zh-CN.resx
- code/src/Core/Resources/StringRes.zh-TW.resx
- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
Include localized resources for status messages
#1688 
No
Yes
> Include localized ressources for status messages

- code/src/UI/ViewModels/Common/BaseMainViewModel.cs
- code/src/UI/ViewModels/NewProject/MainViewModel.cs
Reset current step to 0 when new templates are available
#1709
No
Yes
> Reset currentstep to 0 when new templates are available

- docs/roadmap.md
For #1593
Updated with discussed areas for future development.
@crutkas feel free to modify as you feel necessary. Just raised this to make sure it doesn't get forgotten or overlooked.
> Updated roadmap (& standardized formatting)

- code/Installer.sln
- code/src/Installer.2017/Installer.2017.csproj
- code/src/Installer.2017/source.extension.vsixmanifest
- templates/_catalog/en-US.frameworks.json
- templates/_catalog/frameworks.json
Added prism and vb back into master
> Add prism and vb back into master

- templates/Pages/Map.Prism/Services/LocationService.cs
- templates/_composition/Prism/Project.Blank.AddNavigation/App_postaction.xaml.cs
- templates/_composition/Prism/Project.TabbedPivot/App_postaction.xaml.cs
> Remove XmlDoc style comments to Prism framework templates.

- code/src/UI/Controls/CodeViewer.xaml.cs
> Add highlight vb syntax to file viewer in vb projects

- code/src/UI/V2Controls/ImageEx.cs
- code/src/UI/V2Resources/StringRes.Designer.cs
- code/src/UI/V2Resources/StringRes.resx
- code/src/UI/V2Styles/ComboBox.xaml
- code/src/UI/V2Styles/DataTemplate.xaml
- code/src/UI/V2Styles/ListView.xaml
- code/src/UI/V2Styles/TextBlock.xaml
- code/src/UI/V2Styles/TextBox.xaml
- code/src/UI/V2Styles/_thickness.xaml
- code/src/UI/V2ViewModels/Common/BaseMainViewModel.cs
- code/src/UI/V2ViewModels/Common/DataItems/SavedTemplateViewModel.cs
- code/src/UI/V2ViewModels/Common/WizardStatus.cs
- code/src/UI/V2Views/NewProject/MainPage.xaml
- code/src/UI/V2Views/NewProject/PageToRemove.xaml
> Wizard redesign

- templates/Features/FirstUsePrompt.Prism/Services/FirstRunDisplayService.cs
- templates/Features/FirstUsePrompt/Services/FirstRunDisplayService.cs
- templates/Features/FirstUsePromptVB/Services/FirstRunDisplayService.vb
- templates/Features/WhatsNewPrompt.Prism/Services/WhatsNewDisplayService.cs
- templates/Features/WhatsNewPrompt/Services/WhatsNewDisplayService.cs
- templates/Features/WhatsNewPromptVB/Services/WhatsNewDisplayService.vb
> Create flag to whats new and first run first display

- templates/Features/FirstUsePromptVB/Services/FirstRunDisplayService.vb
- templates/Features/WhatsNewPromptVB/Services/WhatsNewDisplayService.vb
> Fix vb tests

- code/src/Core/Locations/TemplatesSynchronization.cs
> Update cache when currentcontent folder is out of date

- code/src/Core/Locations/TemplatesContent.cs
Added check if content directory physically exists
#1729
> Check if content directory exists

- code/src/UI/V2Styles/ComboBox.xaml
- code/src/UI/V2Styles/ListView.xaml.cs
- code/src/UI/V2ViewModels/Common/BaseMainViewModel.cs
- code/src/UI/V2ViewModels/NewItem/MainViewModel.cs
- code/src/UI/V2ViewModels/NewProject/FrameworkViewModel.cs
- code/src/UI/V2ViewModels/NewProject/MainViewModel.cs
- code/src/UI/V2ViewModels/NewProject/ProjectTypeViewModel.cs
- code/src/UI/V2Views/NewItem/WizardShell.xaml.cs
- code/src/UI/V2Views/NewProject/MainPage.xaml
- code/src/UI/V2Views/NewProject/WizardShell.xaml.cs
> Updates on combobox and templates selection

- code/src/Core/Mvvm/Observable.cs
- code/src/UI/UI.csproj
- code/src/UI/V2Services/DispatcherService.cs
- code/src/UI/V2ViewModels/Common/DataItems/BasicInfoViewModel.cs
- code/src/UI/V2ViewModels/Common/DataItems/MetadataInfoViewModel.cs
- code/src/UI/V2ViewModels/Common/Selectable.cs
- code/src/UI/V2ViewModels/Common/SelectableGroup`1.cs
- code/src/UI/V2ViewModels/NewProject/FrameworkViewModel.cs
- code/src/UI/V2ViewModels/NewProject/MainViewModel.cs
- code/src/UI/V2ViewModels/NewProject/ProjectTypeViewModel.cs
- code/src/UI/V2Views/NewProject/MainPage.xaml
- code/src/UI/V2Views/NewProject/MainPage.xaml.cs
> Updates on project type and framework selection

- code/src/Core/Locations/TemplatesContent.cs
Ensure config is not null in version checks
#1729
> Ensure config is not null in version checks

- CHANGELOG.md
For #1755
Adding the file for standardization of discovery.
It just links to other files to reduce maintenance overhead and ensure a single point of truth.
> Adding a changelog file

- templates/_composition/MVVMLight/Page.MediaPlayer.AddViewModel/.template.config/template.json
- templates/_composition/MVVMLight/Page.MediaPlayer.AddViewModel/ViewModels/ViewModelLocator_postaction.cs
- templates/_composition/MVVMLight/Page.MediaPlayer.AddViewModel/ViewModels/wts.ItemNameViewModel_postaction.cs
- templates/_composition/MVVMLight/Page.MediaPlayer.AddViewModel/Views/wts.ItemNamePage_postaction.xaml
- templates/_composition/MVVMLight/Page.MediaPlayer.AddViewModel/Views/wts.ItemNamePage_postaction.xaml.cs
- templates/_composition/MVVMLight/Page.MediaPlayer.AddViewModelVB/.template.config/template.json
- templates/_composition/MVVMLight/Page.MediaPlayer.AddViewModelVB/ViewModels/ViewModelLocator_postaction.vb
- templates/_composition/MVVMLight/Page.MediaPlayer.AddViewModelVB/ViewModels/wts.ItemNameViewModel_postaction.vb
- templates/_composition/MVVMLight/Page.MediaPlayer.AddViewModelVB/Views/wts.ItemNamePage_postaction.xaml
- templates/_composition/MVVMLight/Page.MediaPlayer.AddViewModelVB/Views/wts.ItemNamePage_postaction.xaml.vb
Problem was that when opening the media player page multiple times it would only work on the first. Single instance VM wasn't "playing nicely" with the player control.
Issue #1757
only affects MVVMLight apps with the NavigationView
Fix for C# & VB
> Fix for MediaPlayer page issue when using MVVMLight

- code/test/Templates.Test/FileEncodingTests.cs
- code/test/Templates.Test/LanguageSyncTests.cs
- code/test/Templates.Test/Templates.Test.csproj
> Detect VB templates with missing description localizations

- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
- code/src/UI/UI.csproj
> Added localized resources

- code/tools/WtsTool/PackageWorker.cs
- code/tools/WtsTool/RunCommand.cs
> Fixed wts tool

- code/src/UI/Styles/ListView.xaml.cs
- code/src/UI/ViewModels/Common/DataItems/BasicInfoViewModel.cs
- code/src/UI/ViewModels/NewProject/UserSelectionViewModel.cs
> Clear naming notifications on template deleting

- code/src/Core/Locations/TemplatesSynchronization.cs
Update extraction progress when extracting local package
#1756
> Subscribe to GetContentProgress when extracting local package

- code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyFixture.cs
- code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyTests.cs
> Include VB templates in RightClick Legacy tests

- code/src/UI/Styles/DataTemplate.xaml
- code/src/UI/ViewModels/Common/DataItems/BasicInfoViewModel.cs
- code/src/UI/ViewModels/Common/DataItems/MetadataInfoViewModel.cs
- code/src/UI/ViewModels/Common/DataItems/TemplateInfoViewModel.cs
> Issue1849 cardtexts

- code/src/UI/Generation/GenComposer.cs
- code/src/UI/ViewModels/NewProject/UserSelectionViewModel.cs
> Fix licenses building

- code/src/UI/ViewModels/Common/SelectableGroup`1.cs
- code/src/UI/ViewModels/NewProject/FrameworkViewModel.cs
- code/src/UI/ViewModels/NewProject/MainViewModel.cs
- code/src/UI/ViewModels/NewProject/ProjectTypeViewModel.cs
> Update reset project code

- code/src/UI/Services/DataService.cs
Order templates by displayOrder
#1834
> Order pages by displayorder

- code/src/UI/ViewModels/NewItem/MainViewModel.cs
- code/src/UI/ViewModels/NewItem/TemplateSelectionViewModel.cs
> Clear error naming on new item template selection

- code/src/UI/Styles/ImageEx.xaml
> Center images on project details templates

- code/src/UI/Styles/TextBlock.xaml
- code/src/UI/Styles/_Thickness.xaml
- code/src/UI/Views/Common/TemplateInfoPage.xaml
> Redesign TemplateInfo page

- code/src/UI/Styles/DataTemplate.xaml
- code/src/UI/Styles/_Thickness.xaml
- code/src/UI/Views/Common/TemplateInfoPage.xaml
> Alignment updates

- code/src/UI/Extensions/TextBlockExtensions.cs
- code/src/UI/Styles/ListView.xaml
- code/src/UI/Styles/ListView.xaml.cs
- code/src/UI/Styles/TextBlock.xaml
> Fix 1852 and remove V2 namespace from Styles

- code/src/UI/Controls/ImageEx.cs
- code/test/VsEmulator/Main/MainViewModel.cs
> Fix icon foreground

- code/src/UI/Controls/ImageEx.cs
Apply foreground to bitmap images
#1695
> Apply foreground to bitmap images

- code/src/UI/Controls/Step.cs
- code/src/UI/Extensions/TextBlockExtensions.cs
> sequential workflow index updates

- code/src/UI/Styles/DataTemplate.xaml
- code/src/UI/Styles/Hyperlink.xaml
- code/src/UI/Styles/_Thickness.xaml
- code/src/UI/Views/Common/TemplateInfoPage.xaml
- code/src/UI/Views/NewItem/TemplateSelectionPage.xaml
- code/src/UI/Views/NewProject/MainPage.xaml
> Issue1841 links

- code/src/UI/Extensions/ImageExtensions.cs
- code/src/UI/Services/Styles/UIStylesService.Environment.cs
- code/src/UI/Services/Styles/UIStylesService.cs
- code/src/UI/Styles/DataTemplate.xaml
- code/src/UI/UI.csproj
- code/test/VsEmulator/Main/MainViewModel.cs
- code/test/VsEmulator/Services/FakeStyleValuesProvider.cs
> Issue1806 image

- code/src/UI/VisualStudio/RightClickActions.cs
- code/src/UI/VisualStudio/SolutionWizard.cs
Asynchronously restore packages and finish right click actions 
#1884
No
Yes
> Asynchronously restore packages and finish right click actions 

- code/src/UI/Services/SystemService.cs
- code/src/UI/Styles/DataTemplate.xaml
- code/src/UI/Styles/ListView.xaml
- code/src/UI/Styles/TextBlock.xaml
- code/src/UI/Views/NewItem/MainPage.xaml
- code/src/UI/Views/NewItem/TemplateSelectionPage.xaml
- code/src/UI/Views/NewProject/MainPage.xaml
> Card Design proposal

- code/src/UI/Services/Styles/UIStylesService.FontSizes.cs
- code/src/UI/Services/Styles/UIStylesService.cs
- code/src/UI/Services/Styles/VSStyleValuesProvider.cs
- code/src/UI/Styles/MarkdownBlock.xaml
- code/src/UI/Styles/TextBlock.xaml
- code/src/UI/Styles/TextBox.xaml
- code/test/VsEmulator/Services/FakeStyleValuesProvider.cs
Change 90 percent font size to 100 percent
#1896
> Change 90 percent font size to 100 percent

- templates/Features/DragAndDrop.CodeBehind/.template.config/template.json
- templates/Features/DragAndDrop.CodeBehindVB/.template.config/template.json
- templates/Features/StoreNotifications.Prism/.template.config/template.json
- templates/Features/StoreNotifications/.template.config/template.json
- templates/Features/StoreNotificationsVB/.template.config/template.json
- templates/Pages/WebView.CaliburnMicro/.template.config/template.json
- templates/Pages/WebView.CodeBehind/.template.config/template.json
- templates/Pages/WebView.CodeBehindVB/.template.config/template.json
- templates/Pages/WebView.Prism/.template.config/template.json
- templates/Pages/WebView/.template.config/template.json
- templates/Pages/WebViewVB/.template.config/template.json
- templates/_catalog/en-US.frameworks.json
- templates/_catalog/frameworks.json
Shortened texts on templates that are cropped on standard text size
#1849
> Shortened texts on templates that are cropped on standard text size

- code/src/UI/Controls/NotificationsControl.xaml
- code/src/UI/Controls/SequentialFlow.xaml
- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Styles/Button.xaml
- code/src/UI/Styles/DataTemplate.xaml
- code/src/UI/Styles/ListView.xaml
- code/src/UI/ViewModels/Common/DataItems/TemplateGroupViewModel.cs
- code/src/UI/Views/Common/TemplateInfoPage.xaml
- code/src/UI/Views/NewItem/TemplateSelectionPage.xaml
- code/src/UI/Views/NewProject/FrameworkPage.xaml
- code/src/UI/Views/NewProject/MainPage.xaml
- code/src/UI/Views/NewProject/ProjectTypePage.xaml
- code/src/UI/Views/NewProject/WizardShell.xaml
- code/test/VsEmulator/Main/MainView.xaml
- code/test/VsEmulator/NewProject/NewProjectView.xaml
> Issue1891 accessibility

- code/src/UI/Views/NewItem/ChangesSummaryPage.xaml
- code/src/UI/Views/NewItem/MainPage.xaml
- code/src/UI/Views/NewItem/TemplateSelectionPage.xaml
> Updates on right click layout

- code/src/UI/Styles/ComboBox.xaml
> Set border color to combobox when keyboard focused

- code/src/UI/ViewModels/Common/DataItems/TemplateInfoViewModel.cs
- code/src/UI/Views/NewItem/ChangesSummaryPage.xaml
- code/src/UI/Views/NewItem/MainPage.xaml
- code/src/UI/Views/NewItem/TemplateSelectionPage.xaml
> Issue1908 borders

- code/src/UI/Controls/Markdown.cs
- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Services/SystemService.cs
- code/src/UI/Styles/DataTemplate.xaml
- code/src/UI/ViewModels/Common/DataItems/NewItemFileViewModel.cs
> Add tooltip to external links.

- code/src/UI/Controls/CodeViewer.xaml.cs
- code/src/UI/Services/Styles/IStyleValuesProvider.cs
- code/src/UI/Services/Styles/UIStylesService.WindowsTemplateStudio.cs
- code/src/UI/Services/Styles/UIStylesService.cs
- code/src/UI/Services/Styles/VSStyleValuesProvider.cs
- code/test/VsEmulator/Services/FakeStyleValuesProvider.cs
- code/test/VsEmulator/VsEmulator.csproj
> Set monaco theme

- code/src/Core/Locations/TemplatesContent.cs
Do not download templates if it's the same version as wizard but extract them from vsix
#1928
> Do not download templates if it's the same version as wizard but extract them from vsix

- code/src/UI/Controls/SequentialFlow.xaml
- code/src/UI/ViewModels/Common/BaseMainViewModel.cs
- code/src/UI/ViewModels/Common/WizardStatus.cs
- code/src/UI/ViewModels/NewItem/MainViewModel.cs
- code/src/UI/Views/NewItem/MainPage.xaml
- code/src/UI/Views/NewProject/MainPage.xaml
> Issue1925 next

- code/src/UI/Controls/CodeViewer.xaml
- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Styles/DataTemplate.xaml
- code/src/UI/Styles/Image.xaml
- code/src/UI/Styles/TextBox.xaml
- code/src/UI/Styles/Viewbox.xaml
- code/src/UI/Views/Common/ErrorDialog.xaml
- code/src/UI/Views/Common/QuestionDialogWindow.xaml
- code/src/UI/Views/NewItem/ProjectConfigurationDialog.xaml
- code/src/UI/Views/NewItem/TemplateSelectionPage.xaml
- code/src/UI/Views/NewItem/WizardShell.xaml
> Issue1891 keros accessibility

- code/src/UI/Controls/Markdown.cs
- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Styles/DataTemplate.xaml
> Change external hyperlink tooltip message.

- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Styles/ListView.xaml
> Explain how to reorder page item with accessibility help text

- code/src/UI/Styles/ListView.xaml
> Fix drag and drop pages hover color.

- code/src/UI/Styles/Button.xaml
- code/src/UI/Styles/ListView.xaml
> Set delete button focusable and keep style item

- code/src/UI/VisualStudio/RightClickActions.cs
- code/src/UI/VisualStudio/SolutionWizard.cs
> Added long running option

- code/src/UI/Controls/Step.cs
- code/src/UI/Services/NavigationService.cs
- code/src/UI/ViewModels/Common/BaseMainViewModel.cs
- code/src/UI/ViewModels/NewItem/MainViewModel.cs
- code/src/UI/ViewModels/NewProject/MainViewModel.cs
> Update Steps on frame shortcut navigation

- templates/Features/FeedbackHub.CaliburnMicro/_postaction.csproj
- templates/Features/FeedbackHub.CodeBehind/_postaction.csproj
- templates/Features/FeedbackHub.CodeBehindVB/_postaction.vbproj
- templates/Features/FeedbackHub.MVVMBasic/_postaction.csproj
- templates/Features/FeedbackHub.MVVMBasicVB/_postaction.vbproj
- templates/Features/FeedbackHub.MVVMLight/_postaction.csproj
- templates/Features/FeedbackHub.MVVMLightVB/_postaction.vbproj
- templates/Features/FeedbackHub.Prism/_postaction.csproj
For #1920
Update to use the most recent version of the NuGet package
> Update version of Microsoft.Services.Store.Engagement

- code/src/UI/Views/NewItem/WizardShell.xaml.cs
- code/src/UI/Views/NewProject/WizardShell.xaml.cs
#1927 - Inconsistent backspace button behavior on details page
> Fix navigation back from info page

- templates/Pages/Chart.CodeBehind/_postaction.csproj
- templates/Pages/Chart.CodeBehindVB/_postaction.vbproj
- templates/Pages/Chart.Prism/_postaction.csproj
- templates/Pages/Chart/_postaction.csproj
- templates/Pages/ChartVB/_postaction.vbproj
- templates/Pages/Grid.CodeBehind/_postaction.csproj
- templates/Pages/Grid.CodeBehindVB/_postaction.vbproj
- templates/Pages/Grid.Prism/_postaction.csproj
- templates/Pages/Grid/_postaction.csproj
- templates/Pages/GridVB/_postaction.vbproj
> Update version of Telerik.UI library

- code/src/UI/Controls/Notification.cs
- code/src/UI/Controls/NotificationsControl.xaml.cs
- code/src/UI/Views/NewItem/WizardShell.xaml.cs
- code/src/UI/Views/NewProject/WizardShell.xaml.cs
#1950 Notification error when closing and opening wizard with notification
> Unregister notification events

- code/src/Core/CodeGen.cs
- code/src/Core/Resources/StringRes.cs-CZ.resx
- code/src/Core/Resources/StringRes.de-DE.resx
- code/src/Core/Resources/StringRes.es-ES.resx
- code/src/Core/Resources/StringRes.fr-FR.resx
- code/src/Core/Resources/StringRes.it-IT.resx
- code/src/Core/Resources/StringRes.ja-JP.resx
- code/src/Core/Resources/StringRes.ko-KR.resx
- code/src/Core/Resources/StringRes.pl-PL.resx
- code/src/Core/Resources/StringRes.pt-BR.resx
- code/src/Core/Resources/StringRes.ru-RU.resx
- code/src/Core/Resources/StringRes.tr-TR.resx
- code/src/Core/Resources/StringRes.zh-CN.resx
- code/src/Core/Resources/StringRes.zh-TW.resx
- code/src/Core/Templates/ITemplateInfoExtensions.cs
- code/src/Core/Templates/TemplatesRepository.cs
- code/src/UI/Resources/StringRes.cs-CZ.resx
- code/src/UI/Resources/StringRes.de-DE.resx
- code/src/UI/Resources/StringRes.es-ES.resx
- code/src/UI/Resources/StringRes.fr-FR.resx
- code/src/UI/Resources/StringRes.it-IT.resx
- code/src/UI/Resources/StringRes.ja-JP.resx
- code/src/UI/Resources/StringRes.ko-KR.resx
- code/src/UI/Resources/StringRes.pl-PL.resx
- code/src/UI/Resources/StringRes.pt-BR.resx
- code/src/UI/Resources/StringRes.ru-RU.resx
- code/src/UI/Resources/StringRes.tr-TR.resx
- code/src/UI/Resources/StringRes.zh-CN.resx
- code/src/UI/Resources/StringRes.zh-TW.resx
- code/test/Core.Test/Localization/LocalizationTest.cs
#1954 - Force wizard to show everything in english until localized files are back
> Force wizard to show everything in english

- code/src/UI/ViewModels/NewItem/TemplateSelectionViewModel.cs
- code/src/UI/ViewModels/NewProject/UserSelectionViewModel.cs
#1958 Navigation disabled after deleting page with error
> Clean validation error on template deleting if it has errors

- templates/Features/SampleData/Models/SampleOrder.cs
- templates/Features/SampleDataVB/Models/SampleOrder.vb
- templates/Pages/MasterDetail.CaliburnMicro/Views/MasterDetailViewDetail/MasterView.xaml
- templates/Pages/MasterDetail.CodeBehind/Views/MasterDetailViewPage.xaml
- templates/Pages/MasterDetail.CodeBehindVB/Views/MasterDetailViewPage.xaml
- templates/Pages/MasterDetail.Prism/Views/MasterDetailViewPage.xaml
- templates/Pages/MasterDetail/Views/MasterDetailViewPage.xaml
- templates/Pages/MasterDetailVB/Views/MasterDetailViewPage.xaml
> Remove HashIdentIcon and HashIdentTitle from SampleOrder

- code/src/UI/Views/Common/ErrorDialog.xaml
- code/src/UI/Views/Common/QuestionDialogWindow.xaml
- code/src/UI/Views/NewItem/ProjectConfigurationDialog.xaml
- code/src/UI/Views/NewItem/WizardShell.xaml
- code/src/UI/Views/NewProject/WizardShell.xaml
#1929 - Wizard shows white border on top
> Fix white border when resize window

- templates/Projects/Default/Styles/TextBlock.xaml
- templates/Projects/DefaultPrism/Styles/TextBlock.xaml
- templates/Projects/DefaultVB/Styles/TextBlock.xaml
Update TextBlock Styles in project templates
> Update TextBlock Styles in project templates

- code/src/UI/Styles/Button.xaml
#1965 Review and Fix Close Button alignments on Windows
> Fix margin

- code/src/UI/Styles/_Thickness.xaml
- code/src/UI/Views/Common/ErrorDialog.xaml
- code/src/UI/Views/Common/ErrorDialog.xaml.cs
- code/src/UI/Views/Common/QuestionDialogWindow.xaml
- code/src/UI/Views/Common/QuestionDialogWindow.xaml.cs
- code/src/UI/Views/NewItem/ProjectConfigurationDialog.xaml
- code/src/UI/Views/NewItem/ProjectConfigurationDialog.xaml.cs
- code/src/UI/Views/NewItem/WizardShell.xaml
> Refactor windows dialogs: size, margin and move.

- code/src/Core/Locations/TemplatesContent.cs
Fixed version comparison
#1978 Wrong update message
> Compare major and minor version

- code/src/UI/ViewModels/Common/BaseMainViewModel.cs
- code/src/UI/Views/NewProject/MainPage.xaml.cs
#1979 Wrong step shown when navigating back from details
> Initialize secondary frame to current Step Page

- code/src/UI/ViewModels/NewItem/MainViewModel.cs
- code/src/UI/ViewModels/NewProject/MainViewModel.cs
- code/src/UI/Views/Common/ErrorDialog.xaml
- code/src/UI/Views/Common/QuestionDialogWindow.xaml
- code/src/UI/Views/NewItem/ProjectConfigurationDialog.xaml
- code/src/UI/Views/NewItem/WizardShell.xaml
- code/src/UI/Views/NewProject/WizardShell.xaml
#1990  - Wizard shows in Taskbar
> Hide wizard icon in taskbar.

- code/src/UI/Styles/Styles.xaml
- code/src/UI/ViewModels/NewItem/ChangesSummaryViewModel.cs
- code/src/UI/ViewModels/NewItem/MainViewModel.cs
#1989 Code Viewer in right click sometimes does not show files
> Fix Code Viewer in right click sometimes does not show files

- templates/Pages/MasterDetail.CodeBehind/Views/MasterDetailViewPage.xaml
- templates/Pages/MasterDetail.CodeBehindVB/Views/MasterDetailViewPage.xaml
- templates/Pages/MasterDetail.Prism/Views/MasterDetailViewPage.xaml
- templates/Pages/MasterDetail/Views/MasterDetailViewPage.xaml
- templates/Pages/MasterDetailVB/Views/MasterDetailViewPage.xaml
> MasterDetail Selected Binding should be TwoWay

- code/src/UI/Styles/Button.xaml
#2007 Close notification button is not showing visual styles
> Update Close Notification Button Visual Style

- code/src/UI/ViewModels/NewProject/UserSelectionViewModel.cs
Home Page can not be removed. #2012
> Refresh can execute on delete template button

- code/src/UI/UI.csproj
- code/src/UI/packages.config
Delete unused nuger references.
No related Issue.
> Delete unused nuger references

- code/src/Core/Locations/LocalTemplatesSource.cs
> Rebuild entire junction (including version number)

- templates/Features/BackgroundTask.Prism/App_postaction.xaml.cs
- templates/Features/BackgroundTask.Prism/Services/BackgroundTaskService.cs
- templates/Features/BackgroundTask.Prism/Services/IBackgroundTaskService.cs
- templates/Features/BackgroundTask/Services/ActivationService_postaction.cs
- templates/Features/BackgroundTask/Services/BackgroundTaskService.cs
- templates/Features/BackgroundTaskVB/Services/ActivationService_postaction.vb
- templates/Features/BackgroundTaskVB/Services/BackgroundTaskService.vb
RequestAccessAsync missing from background task code #1994.
@mrlacey could you please review the VS sintaxis?
> Issue1994 backgroundtask

- templates/Pages/Settings.Prism/ViewModels/SettingsPageViewModel.cs
#2031 - Prism Settings page is not showing App Title and Version number
> Get name and version app in OnNavigatedTo event

- templates/Features/FirstUsePrompt/Services/ActivationService_postaction.cs
- templates/Features/HubNotifications/Services/ActivationService_postaction.cs
- templates/Features/LiveTile/Services/ActivationService_postaction.cs
- templates/Features/StoreNotifications/Services/ActivationService_postaction.cs
- templates/Features/WhatsNewPrompt/Services/ActivationService_postaction.cs
This PR is for 2.1 version. Do not merge at this moment.
App takes to much time to update the theme when there are many features added #1752
> Reorder ActivationService StartupAsync actions

- templates/Features/FirstUsePrompt.Prism/Views/FirstRunDialog.xaml.cs
- templates/Features/FirstUsePrompt/Views/FirstRunDialog.xaml.cs
- templates/Features/WhatsNewPrompt.Prism/Views/WhatsNewDialog.xaml.cs
- templates/Features/WhatsNewPrompt/Views/WhatsNewDialog.xaml.cs
#1998 - What's new dialog shown before theme is set
> Config theme in first run and whats new dialogs.

- templates/Features/FirstUsePrompt/Services/ActivationService_postaction.cs
- templates/Features/HubNotifications/Services/ActivationService_postaction.cs
- templates/Features/LiveTile/Services/ActivationService_postaction.cs
- templates/Features/StoreNotifications/Services/ActivationService_postaction.cs
- templates/Features/WhatsNewPrompt/Services/ActivationService_postaction.cs
App takes to much time to update the theme when there are many features added #1752
> Move await Task.CompletedTask; to the bottom of method

- templates/Features/FirstUsePromptVB/Services/ActivationService_postaction.vb
- templates/Features/HubNotificationsVB/Services/ActivationService_postaction.vb
- templates/Features/LiveTileVB/Services/ActivationService_postaction.vb
- templates/Features/StoreNotificationsVB/Services/ActivationService_postaction.vb
- templates/Features/WhatsNewPromptVB/Services/ActivationService_postaction.vb
Fix App takes to much time to update the theme when there are many features added #1752 in Visual Basic
> Update StartUp Async postaction in VB

- templates/Features/FirstUsePromptVB/Views/FirstRunDialog.xaml.vb
- templates/Features/WhatsNewPromptVB/Views/WhatsNewDialog.xaml.vb
#1998 - What's new dialog shown before theme is set
> Config theme to first run and whats new dialogs in VB templates.

- code/test/Core.Test/Localization/LocalizationTest.cs
- code/test/Core.Test/PostActions/Catalog/GenerateTestCertificatePostActionTest.cs
- code/test/Templates.Test/BaseGenAndBuildFixture.cs
- code/test/Templates.Test/BaseGenAndBuildTests.cs
- code/test/Templates.Test/BuildFixture.cs
- code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyFixture.cs
- code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyTests.cs
- code/test/Templates.Test/BuildTemplatesTests/BuildCaliburnMicroProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/BuildCodeBehindProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/BuildMVVMBasicProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/BuildMVVMLightProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/BuildPrismProjectTests.cs
- code/test/Templates.Test/BuildTemplatesTests/BuildTemplatesTestFixture.cs
- code/test/Templates.Test/FileEncodingTests.cs
- code/test/Templates.Test/GenTests/GenProjectTests.cs
- code/test/Templates.Test/GenTests/GenerationFixture.cs
- code/test/Templates.Test/GenTests/LanguageComparisonTests.cs
- code/test/Templates.Test/LanguageSyncTests.cs
- code/test/Templates.Test/TemplateFolderValidationTests.cs
- code/test/Templates.Test/TemplateJsonValidationTests.cs
- code/test/Templates.Test/VisualTests/VisualComparisonTests.cs
- code/test/Templates.Test/WindowsAppCertKitTests.cs
#2052 - Transitient test failures in builds
> Synchronously wait until templates are synchronized on test initialization

- code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyTests.cs
Correct memberdata method name
#2056 - Build dev.templates.tests.full_20180312.3 failed
> Fix failing tests

- _build/Extension-SetIdentityAndVersion.ps1
- code/src/Installer.2017/Installer.2017.csproj
Add IsProductComponent and make it configurable via build script
#2059 - Make csproj values configurable
> Make csproj values configurable

- docs/projectTypes/navigationpane.md
#904 Create an option to disable adaptive screen size triggers in the Navigation Pane Project Type
> NavigationPane project type documentation updates.

- code/src/UI/Views/Common/TemplateInfoPage.xaml
Back link text is cropped in some languages on details page #2071
> Fix TemplateInfoPage back button

- docs/projectTypes/navigationpane.md
> Fix typos in NavigationPane documentation

- code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.cs-CZ.vstemplate
- code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.de-DE.vstemplate
- code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.es-ES.vstemplate
- code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.fr-FR.vstemplate
- code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.it-IT.vstemplate
- code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.ja-JP.vstemplate
- code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.ko-KR.vstemplate
- code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.pl-PL.vstemplate
- code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.pt-BR.vstemplate
- code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.ru-RU.vstemplate
- code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.tr-TR.vstemplate
- code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.vstemplate
- code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.zh-CN.vstemplate
- code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.zh-TW.vstemplate
- code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.cs-CZ.vstemplate
- code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.csproj
- code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.de-DE.vstemplate
- code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.es-ES.vstemplate
- code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.fr-FR.vstemplate
- code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.it-IT.vstemplate
- code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.ja-JP.vstemplate
- code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.ko-KR.vstemplate
- code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.pl-PL.vstemplate
- code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.pt-BR.vstemplate
- code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.ru-RU.vstemplate
- code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.tr-TR.vstemplate
- code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.vstemplate
- code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.zh-CN.vstemplate
- code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.zh-TW.vstemplate
- Do not show wts templates on blend
- Correctly include russian vb template (found that whilst removing from blend)
- #2111  WTS theming in blend is messed up
> Do not show wts templates on blend

- templates/Uwp/Projects/Default/Properties/Default.rd.xml
- templates/Uwp/Projects/DefaultPrism/Properties/Default.rd.xml
- templates/Uwp/Projects/DefaultVB/My Project/Default.rd.xml
> Fix typo in default.rd.xml

- templates/Uwp/Projects/Default/wts.DefaultProject.csproj
- templates/Uwp/Projects/DefaultPrism/wts.DefaultProject.csproj
- templates/Uwp/Projects/DefaultVB/wts.DefaultProject.vbproj
> Update version of Microsoft.NETCore.UniversalWindowsPlatform

- templates/Projects/Default/wts.DefaultProject.csproj
- templates/Projects/DefaultPrism/wts.DefaultProject.csproj
- templates/Projects/DefaultVB/wts.DefaultProject.vbproj
For #2104 Update NetCore.Uwp reference
> Update NetCore.Uwp reference

- code/src/Core/Locations/JunctionNativeMethods.cs
- code/src/UI/Styles/TextBox.xaml
Fix accessibility issue 589481
> Issue accessibility 589481

- code/src/UI/Styles/Button.xaml
- code/src/UI/Styles/ComboBox.xaml
> Fix 589534

- code/src/UI/Styles/TextBlock.xaml
> Fix 589518

- code/src/UI/Styles/ComboBox.xaml
> Fix 589572

- code/src/UI/Controls/CodeViewer.xaml
- code/src/UI/Resources/StringRes.Designer.cs
- code/src/UI/Resources/StringRes.resx
- code/src/UI/Styles/ComboBox.xaml
- code/src/UI/Styles/DataTemplate.xaml
- code/src/UI/Styles/ListView.xaml
Fix Inspect accessibility issues:
587762
590400
589647
Fix keyboard accessibility issue:
591006
> V2.0.18093.1 accessibilityfixes

- templates/_composition/CaliburnMicro/Project.SplitView/ViewModels/ShellViewModel.cs
- templates/_composition/CodeBehind/Project.SplitViewVB/Views/ShellPage.xaml.vb
- templates/_composition/MVVMBasic/Project.SplitView/ViewModels/ShellViewModel.cs
- templates/_composition/MVVMBasic/Project.SplitViewVB/ViewModels/ShellViewModel.vb
- templates/_composition/MVVMLight/Project.SplitView/ViewModels/ShellViewModel.cs
- templates/_composition/MVVMLight/Project.SplitViewVB/ViewModels/ShellViewModel.vb
- templates/_composition/Prism/Project.SplitView/ViewModels/ShellViewModel.cs
Fix an issue when ImageGallery navigates on a nav pane project
> Fix Issue on NavigationView Frame Navigated

- templates/_composition/CaliburnMicro/Project.SplitView/Views/ShellPage.xaml
- templates/_composition/CodeBehind/Project.SplitView/Views/ShellPage.xaml
- templates/_composition/CodeBehind/Project.SplitViewVB/Views/ShellPage.xaml
- templates/_composition/MVVMBasic/Project.SplitView/Views/ShellPage.xaml
- templates/_composition/MVVMBasic/Project.SplitViewVB/Views/ShellPage.xaml
- templates/_composition/MVVMLight/Project.SplitView/Views/ShellPage.xaml
- templates/_composition/MVVMLight/Project.SplitViewVB/Views/ShellPage.xaml
- templates/_composition/Prism/Project.SplitView/Views/ShellPage.xaml
Fix Issue: hamburger icon not visible when in dark mode and small window size #2143
> Add Background to ShellPage in NavPane projects

- templates/Pages/ImageGalleryVB/ViewModels/ImageGalleryViewViewModel.vb
#2149 Build dev.templates.tests.full_20180409.2 failed
> Fixed build

- templates/_composition/CaliburnMicro/Project.SplitView/ViewModels/ShellViewModel.cs
- templates/_composition/CodeBehind/Project.SplitView/Views/ShellPage.xaml.cs
- templates/_composition/CodeBehind/Project.SplitViewVB/Views/ShellPage.xaml.vb
- templates/_composition/MVVMBasic/Project.SplitView/ViewModels/ShellViewModel.cs
- templates/_composition/MVVMBasic/Project.SplitViewVB/ViewModels/ShellViewModel.vb
- templates/_composition/MVVMLight/Project.SplitView/ViewModels/ShellViewModel.cs
- templates/_composition/MVVMLight/Project.SplitViewVB/ViewModels/ShellViewModel.vb
- templates/_composition/Prism/Project.SplitView/ViewModels/ShellViewModel.cs
> Standardize method names as IsMenuItemForPageType

- templates/Pages/MasterDetail.Prism/Styles/TextBlock_postaction.xaml
- templates/_composition/_shared/Page.MasterDetail.SampleData.Styles.Strings/Styles/TextBlock_postaction.xaml
- templates/_composition/_shared/Page.MasterDetail.SampleData.Styles.StringsVB/Styles/TextBlock_postaction.xaml
#1969 - Review XAML ResourceDictionary Styles
> Fix resource dictionary styles post-actions

- templates/Features/BackgroundTask.Prism/App_postaction.xaml.cs
- templates/Features/BackgroundTask.Prism/Services/BackgroundTaskService.cs
- templates/Features/BackgroundTask.Prism/Services/IBackgroundTaskService.cs
- templates/Features/BackgroundTask/Services/ActivationService_postaction.cs
- templates/Features/BackgroundTask/Services/BackgroundTaskService.cs
- templates/Features/BackgroundTaskVB/Services/ActivationService_postaction.vb
- templates/Features/BackgroundTaskVB/Services/BackgroundTaskService.vb
This reverts commit de93e4011fc63a4d33fb6e73a93a972a952d858b.
> RequestAccessAsync on Background Task

- templates/Pages/Settings.CaliburnMicro/ViewModels/SettingsPageViewModel.cs
- templates/Pages/Settings.CodeBehind/Views/SettingsPagePage.xaml.cs
- templates/Pages/Settings.CodeBehindVB/Views/SettingsPagePage.xaml.vb
- templates/Pages/Settings.Prism/ViewModels/SettingsPageViewModel.cs
- templates/Pages/Settings/ViewModels/SettingsPageViewModel.cs
- templates/Pages/SettingsVB/ViewModels/SettingsPageViewModel.vb
- templates/Projects/Default/Package.appxmanifest
- templates/Projects/Default/Strings/en-us/Resources.resw
- templates/Projects/DefaultPrism/Package.appxmanifest
- templates/Projects/DefaultPrism/Strings/en-us/Resources.resw
- templates/Projects/DefaultVB/Package.appxmanifest
- templates/Projects/DefaultVB/Strings/en-us/Resources.resw
#1859 - Generated projects to not include localization of app title
>  Add generated app display name and description to resources

- code/src/UI/ViewModels/Common/CompositionTool/CompositionFile.cs
- code/src/UI/ViewModels/Common/CompositionTool/CompositionToolViewModel.cs
> Fixed changed namespaces

- docs/features/setting-storage.md
- docs/features/setting-storage.vb.md
#962 - Add documentation of SettingsStorageExtensions
> Add c# and VB setting storage documentation.

- templates/Features/SettingsStorage/.template.config/description.md
- templates/Features/SettingsStorageVB/.template.config/description.md
#1923 - Update description of SettingsStorage feature
> Update description of SettingsStorage in C# and VB templates.

- templates/_catalog/projectTypes.json
Remove License from NavigationPane project type description
> Catalog Update

- templates/_composition/CodeBehind/Project/Services/NavigationService.cs
- templates/_composition/CodeBehind/ProjectVB/Services/NavigationService.vb
- templates/_composition/MVVMBasic/Project/Services/NavigationService.cs
- templates/_composition/MVVMBasic/ProjectVB/Services/NavigationService.vb
- templates/_composition/MVVMLight/Project/Services/NavigationServiceEx.cs
- templates/_composition/MVVMLight/ProjectVB/Services/NavigationServiceEx.vb
Navigate Method should be overriden to open same page multiple times. #2098 
@mrlacey can you review the Visual Basic implementation?
> Issue2098 navigation

- templates/_composition/CodeBehind/ProjectVB/Services/NavigationService.vb
- templates/_composition/MVVMBasic/ProjectVB/Services/NavigationService.vb
- templates/_composition/MVVMLight/ProjectVB/Services/NavigationServiceEx.vb
VB Fixes Navigate Method should be overriden to open same page multiple times. #2098
> Issue2098 navigation - VB Fixes

- docs/projectTypes/navigationpane.md
- docs/projectTypes/navigationpane.vb.md
Docs update Issue: Need documentation that explains how to update a previously generated project #2082
> Issue2082 navview update doc

- code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyFixture.cs
Re-enable RightClick-Legacy support for MVVMLight
#1985 Re-enable RightClick-Legacy support for MVVMLight
> Re-enable RightClick-Legacy support for MVVMLight

- code/src/Core/Locations/TemplatesSynchronization.cs
> Fix cancel exception in telemetry

- docs/getting-started-endusers.md
For #2094
Updated the Getting started for End Users document
- Expanded the description of each framework (design pattern) to help those not familiar with them
- Added entries for missing Features
A documentation only change
> Update framework & feature descriptions in docs

- docs/roadmap.md
As prompted by #2135
Just a doc change
> Updating roadmap

- templates/Uwp/Features/SampleData.Prism/Services/SampleDataService.cs
Fix wrong char in prism dataservice
#2093 Make sample data platform agnostic
> Fix wrong char

- code/src/Core/PostActions/Catalog/Merge/SearchAndReplacePostAction.cs
- code/src/UI/Generation/GenComposer.cs
Reviewing the string resources I found two missing parameters.
> Missing parameters for string resources

- templates/Uwp/Features/ShareTarget.Prism/Package_postaction.appxmanifest
- templates/Uwp/Features/ShareTarget.Prism/Strings/en-us/Resources_postaction.resw
Add missing extension to Package.appxmanifest and correction of sourceName in resource.resw
#1555 Prism: Reduce use of composition templates where not necessary
> Fix for 1555

- docs/features/uri-scheme.md
> Fix for Policheck

- templates/Uwp/Projects/Default/wts.DefaultProject.csproj
- templates/Uwp/Projects/DefaultPrism/wts.DefaultProject.csproj
- templates/Uwp/Projects/DefaultVB/wts.DefaultProject.vbproj
- templates/Uwp/_composition/CaliburnMicro/Project.SplitView/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/CodeBehind/Project.SplitView/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/CodeBehind/Project.SplitViewVB/Views/ShellPage.xaml.vb
- templates/Uwp/_composition/MVVMBasic/Project.SplitView/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/MVVMBasic/Project.SplitViewVB/Views/ShellPage.xaml.vb
- templates/Uwp/_composition/MVVMLight/Project.SplitView/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/MVVMLight/Project.SplitViewVB/Views/ShellPage.xaml.vb
- templates/Uwp/_composition/Prism/Project.SplitView/Views/ShellPage.xaml.cs
- Set tpv to april 2018 sdk
- Hide NavViews back button
#2221 Navigationview is showing extra back button on rs4
> Set tpv to april 2018 sdk

- templates/Uwp/Pages/Map.CaliburnMicro/ViewModels/MapPageViewModel.cs
- templates/Uwp/Pages/Map.CodeBehind/Views/MapPagePage.xaml.cs
- templates/Uwp/Pages/Map.CodeBehindVB/Views/MapPagePage.xaml.vb
- templates/Uwp/Pages/Map.Prism/ViewModels/MapPageViewModel.cs
- templates/Uwp/Pages/Map/ViewModels/MapPageViewModel.cs
- templates/Uwp/Pages/MapVB/ViewModels/MapPageViewModel.vb
Setting MapserviceToken to string.empty throws exception in machine with April2018 SDK #2231
> Comment map service tokken in all map page templates

- code/src/Core/Gen/GenShell.cs
- code/src/UI/VisualStudio/SolutionWizard.cs
- code/src/UI/VisualStudio/VsGenShell.cs
- code/test/Fakes/FakeGenShell.cs
Opens the project overview tab after project creation
#353 Open overview tab on project creation
> Open overview tab on project creation 

- templates/Uwp/Features/VSAppCenterAnalytics/App_postaction.xaml.cs
- templates/Uwp/Features/VSAppCenterAnalytics/_postaction.csproj
- templates/Uwp/Features/VSAppCenterAnalyticsVB/App_postaction.xaml.vb
- templates/Uwp/Features/VSAppCenterAnalyticsVB/_postaction.vbproj
For #2296
Update the referenced version of the SDK & add tracking of crashes as well as basic analytics
> Update App Center feature

- code/src/Installer.2017/Commands/RelayCommandPackage.cs
#2301 Add background load flag to RelayCommand
> Add background load flag

- docs/roadmap.md
Update to roadmap based on discussions at the post-build offsite meeting
> Updated roadmap based on plans from build/offsite

- code/tools/Localization/Program.cs
#2199 - Review extraction of files to localize
> Update help text to localization tool

- templates/Uwp/Features/BackgroundTaskVB/Services/ActivationService_postaction.vb
- templates/Uwp/Features/LiveTile/Services/ActivationService_postaction.cs
- templates/Uwp/Features/ToastNotificationsVB/Services/ActivationService_postaction.vb
- templates/Uwp/Features/WebToAppLink/Services/ActivationService_postaction.cs
- templates/Uwp/_composition/CaliburnMicro/Feature.UriSchemeExamplePage/Services/ActivationService_postaction.cs
- templates/Uwp/_composition/_shared/Feature.ShareTarget/Services/ActivationService_postaction.cs
- templates/Uwp/_composition/_shared/Feature.ShareTargetVB/Services/ActivationService_postaction.vb
- templates/Uwp/_composition/_shared/Feature.UriScheme/Services/ActivationService_postaction.cs
- templates/Uwp/_composition/_shared/Feature.UriSchemeVB/Services/ActivationService_postaction.vb
Deleted some extra whitelines found during tests
#2088 Deleting code in postaction deletes all occurences of that code
> Remove extra whitelines

- code/test/Templates.Test/ExternalLinksTests.cs
- docs/features/drag-and-drop.md
- docs/features/drag-and-drop.vb.md
- docs/projectTypes/navigationpane.md
- docs/projectTypes/navigationpane.vb.md
- docs/projectTypes/updatetonavigationview.md
Follow on from PR #2321 
For Issue #2248
> Check for broken links in docs

- code/test/Templates.Test/WACK/WindowsAppCertKitTests.cs
Issue Build dev.templates.tests.wack_20180227.4 failed #2001
> Updates on WACK Test

- _build/Extension-SetIdentityAndVersion.ps1
- code/src/Installer.2017/Commands/RelayCommandPackage.cs
- code/src/Installer.2017/Commands/VSPackage.cs-CZ.resx
- code/src/Installer.2017/Commands/VSPackage.de-DE.resx
- code/src/Installer.2017/Commands/VSPackage.en-US.resx
- code/src/Installer.2017/Commands/VSPackage.es-ES.resx
- code/src/Installer.2017/Commands/VSPackage.fr-FR.resx
- code/src/Installer.2017/Commands/VSPackage.it-IT.resx
- code/src/Installer.2017/Commands/VSPackage.ja-JP.resx
- code/src/Installer.2017/Commands/VSPackage.ko-KR.resx
- code/src/Installer.2017/Commands/VSPackage.pl-PL.resx
- code/src/Installer.2017/Commands/VSPackage.pt-BR.resx
- code/src/Installer.2017/Commands/VSPackage.ru-RU.resx
- code/src/Installer.2017/Commands/VSPackage.tr-TR.resx
- code/src/Installer.2017/Commands/VSPackage.zh-CN.resx
- code/src/Installer.2017/Commands/VSPackage.zh-TW.resx
Update to correct descriptions and set version in build script
#2332 Help/About details are incorrect.
> Issue2332 aboutdetails

- templates/Uwp/Features/ToastNotifications/Services/ToastNotificationsFeatureService.cs
- templates/Uwp/Features/ToastNotificationsVB/Services/ToastNotificationsFeatureService.vb
> Fix doc links in generated code

- templates/Uwp/Features/BackgroundTask.Prism/BackgroundTasks/BackgroundTaskFeature.cs
- templates/Uwp/Features/BackgroundTask/BackgroundTasks/BackgroundTaskFeature.cs
- templates/Uwp/Features/BackgroundTaskVB/BackgroundTasks/BackgroundTaskFeature.vb
Cancel the background task from the sample on cancel requested.
#2358
> Cancel background task execution

- templates/Uwp/Features/VSAppCenterAnalytics/_postaction.csproj
- templates/Uwp/Features/VSAppCenterAnalyticsVB/_postaction.vbproj
For #2380 - Updates to latest NuGet versions
> Update AppCenter references to latest SDK versions

- templates/Uwp/Projects/Default/Services/ActivationService.cs
- templates/Uwp/Projects/DefaultVB/Services/ActivationService.vb
- templates/Uwp/_composition/CaliburnMicro/Project.SplitView/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/CaliburnMicro/Project/Services/ActivationService.cs
- templates/Uwp/_composition/CodeBehind/Project.SplitView/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/CodeBehind/Project.SplitViewVB/Views/ShellPage.xaml.vb
- templates/Uwp/_composition/CodeBehind/Project/Services/NavigationService.cs
- templates/Uwp/_composition/CodeBehind/ProjectVB/Services/NavigationService.vb
- templates/Uwp/_composition/MVVMBasic/Project.SplitView/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/MVVMBasic/Project.SplitViewVB/Views/ShellPage.xaml.vb
- templates/Uwp/_composition/MVVMBasic/Project/Services/NavigationService.cs
- templates/Uwp/_composition/MVVMBasic/ProjectVB/Services/NavigationService.vb
- templates/Uwp/_composition/MVVMLight/Project.SplitView/Views/ShellPage.xaml.cs
- templates/Uwp/_composition/MVVMLight/Project.SplitViewVB/Views/ShellPage.xaml.vb
- templates/Uwp/_composition/MVVMLight/Project/Services/ActivationService_postaction.cs
- templates/Uwp/_composition/MVVMLight/Project/Services/NavigationServiceEx.cs
- templates/Uwp/_composition/MVVMLight/ProjectVB/Services/NavigationServiceEx.vb
App go back navigation: Add Alt+LeftArrow support #1770
> Add KeyboardAccelerators for back navigation using keyboard
