microsoft/TemplateStudio

templates/Pages/TabbedPivot/.template.config/description.md
Fix for issue #341.
Formatting the hyperlink in the Tabbed page correctly inline with other pages.
=> Issue #341 Formatting hyperlink in Tabbed Page Wizard

code/src/Core/Core.csproj, code/src/Core/app.config, code/src/Core/packages.config, code/test/Artifacts/app.config, code/test/Core.Test/App.config, code/test/Templates.Test/App.config
Fix for #328 for VS Preview.  Newer NuGet reference fixed it.  Unit tests didn't seem to catch this however.  Only release mode seemed to trigger it.
=> Fix for #328

templates/Pages/Settings.CodeBehind/Services/ThemeSelectorService.cs, templates/Pages/Settings.CodeBehind/Strings/en-us/Resources_postaction.resw, templates/Pages/Settings.CodeBehind/Views/SettingsPagePage.xaml, templates/Pages/Settings.CodeBehind/Views/SettingsPagePage.xaml.cs, templates/Pages/Settings/Services/ThemeSelectorService.cs, templates/Pages/Settings/Strings/en-us/Resources_postaction.resw, templates/Pages/Settings/ViewModels/SettingsPageViewModel.cs, templates/Pages/Settings/Views/SettingsPagePage.xaml, templates/Projects/Blank/App.xaml, templates/Projects/SplitView/App.xaml, templates/Projects/TabbedPivot/App.xaml, templates/_composition/CodeBehind/Page.Settings.AddShellThemeSupport_SplitView/Views/ShellNavigationItem_postaction.cs, templates/_composition/MVVMBasic/Page.Settings.AddShellThemeSupport_SplitView/ViewModels/ShellNavigationItem_postaction.cs, templates/_composition/MVVMLight/Page.Settings.AddShellThemeSupport_SplitView/ViewModels/ShellNavigationItem_postaction.cs, templates/_composition/MVVMLight/Project/App_postaction.xaml
PR for feature #350 to support **Windows Default theme** in addition to Light and Dark themes. This mode will set the app's theme as the default windows theme which can be controlled directly from 'Color Settings'. 
- Switching to `RadioButton` instead of `ToggleSwitch` since we have 3 modes: Light, Dark and Windows default
- Removed `RequestedTheme='Light'` from Application tag in `App.xaml` since XAML doesn't support a default mode so to respect the system's theme, this has to be removed.
- In `ShellNavigationItem`, brushes `SystemControlForegroundAltHighBrush` and `SystemControlForegroundBaseHighBrush` now behave based on the default windows setting since `RequestedTheme` isn't set to Light in the App.xaml. As a result, they can't be used when the theme is set to Light or Dark _in the …
=> Feature #350 Including support for default Windows Theme

code/src/UI/VisualStudio/SolutionWizard.cs
Delete empty folder created by Visual Studio when cancelling wizard  without project creation #84
=> Delete empty folder created by Visual Studio when cancelling wizard 

templates/Pages/Settings.CodeBehind/Services/ThemeSelectorService.cs, templates/Pages/Settings.CodeBehind/Views/SettingsPagePage.xaml, templates/Pages/Settings.CodeBehind/Views/SettingsPagePage.xaml.cs, templates/Pages/Settings/Services/ThemeSelectorService.cs, templates/Pages/Settings/ViewModels/SettingsPageViewModel.cs, templates/Pages/Settings/Views/SettingsPagePage.xaml
As per the discussion and comments on #360 by @crutkas and @mrlacey, changing to a drop-down instead of radio buttons. 
- Using `SelectedIndex` from `ComboBox` and converting that into `ElementTheme` and vice-versa while setting the theme. So there needs to be mapping to determine which index corresponds to which theme. Also the XAML needs to be in the same order. i.e since the drop-down is expected to have `Light`, `Dark` and then `Default`, index 0 should match with `ElementTheme.Light` and so on. Please take a look at `GetTheme()` and `SetThemeAsync(int themeId)` in `ThemeSelectorService.cs`
**Questions:**
- To avoid the above, could consider using a collection of theme class, where each theme class will have an order. The same class can then be used populate the xaml `ItemsSource` …
=> Issue350: Switching default theme from RadioButton to ComboBox

code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.vstemplate
The Project Template name is replaced at build time in order to change it for each environment (loca, dev-nightly, pre-release and pro).
Updated the name in the local template and changed the builds variables to include "Universal Windows" as part of the name.
=> Include  "Universal Windows" in VS Project Template name

code/src/Core/PostActions/Catalog/SortUsings/IEnumerableExtensions.cs, code/test/Core.Test/PostActions/Catalog/SortUsingsTest.cs
Small fix for an exception that appears only when a template file has content before its using statements (e.g. comments). In that case, LastIndexOfWhile can return a value that is less than startIndex, causing problems in the caller. (For existing templates, startIndex is always 0, so this problem doesn't arise).
=> bugfix for sort-usings exception

templates/Pages/Grid.CodeBehind/Views/GridViewPage.xaml, templates/Pages/Grid.CodeBehind/Views/GridViewPage.xaml.cs, templates/Pages/Grid/Views/GridViewPage.xaml
We will be moving away from x:Bind in the Grid Page until Telerik fix the issue described in #496
=> Workarround for issue #496

code/src/Core/Configuration/Configuration.cs, code/src/Core/Configuration/WindowsTemplateStudio.tokenized.config.json, code/src/Core/Diagnostics/TelemetryService.cs
Provides for optional custom telemetry endpoint in config file
Tagged AI iKeys won't fail parsing and report as unavailable or invalid
=> Allow for custom AI Endpoint in config file + tagged AI key GUID

code/src/Core/Diagnostics/TelemetryService.cs, code/src/Core/Diagnostics/VsTelemetryProperties.cs
Only add list of pages and fetaures to VSTelemetry not to our own (as logged seperately)
Fixed VSTelemetryPrefix
Fixes issue #708
=> Adjust NewItem Telemetry properties

_build/Extension-SetIdentityAndVersion.ps1, code/src/Installer.2017/Commands/PackageIds.cs, code/src/Installer.2017/Commands/RelayCommandPackage.cs-CZ.vsct, code/src/Installer.2017/Commands/RelayCommandPackage.de-DE.vsct, code/src/Installer.2017/Commands/RelayCommandPackage.en-US.vsct, code/src/Installer.2017/Commands/RelayCommandPackage.es-ES.vsct, code/src/Installer.2017/Commands/RelayCommandPackage.fr-FR.vsct, code/src/Installer.2017/Commands/RelayCommandPackage.it-IT.vsct, code/src/Installer.2017/Commands/RelayCommandPackage.ja-JP.vsct, code/src/Installer.2017/Commands/RelayCommandPackage.ko-KR.vsct, code/src/Installer.2017/Commands/RelayCommandPackage.pl-PL.vsct, code/src/Installer.2017/Commands/RelayCommandPackage.pt-BR.vsct, code/src/Installer.2017/Commands/RelayCommandPackage.ru-RU.vsct, code/src/Installer.2017/Commands/RelayCommandPackage.tr-TR.vsct, code/src/Installer.2017/Commands/RelayCommandPackage.zh-CN.vsct, code/src/Installer.2017/Commands/RelayCommandPackage.zh-TW.vsct, code/src/Installer.2017/Properties/AssemblyInfo.cs
With this PR we allow to have installed by environment the extension. Basically, allows to have multiple Right-Click menu.
#798 should remain open targeting 1.3 where we can review and solve the isolation issues.
Known issue having 2 extensions side by side (f.ex. local & nightly) and running it with in the same VS Instance: 
* The WTS extension wizard executed first will "win" and the other instance will not load the wizard xaml windows. 
* Would appear exceptions trying to delete temp folders in the output window.
With this workarround we at least will be able to have installed and differetiate between differente extension environment versions (f.ex. production & niglthly & local).
The solution implies to modify the guids at build time.
=> Issue798 configure right click per env

code/src/Core/Diagnostics/FileHealthWriter.cs, code/src/Installer.2017/Installer.2017.csproj, code/src/Installer.2017/app.config, code/src/Installer.2017/packages.config, code/src/UI/UI.csproj, code/src/UI/packages.config, code/test/VsEmulator/App.config, code/test/VsEmulator/VsEmulator.csproj, code/test/VsEmulator/packages.config
#955
& fixed build warnings
There are other nuget updates available and some opportunities for
consolidating versions but everything seems to to work as is.
=> Allow big.sln to run on VS15.3

docs/Fluent_PerspectiveParallax.md, templates/Features/SampleData/Models/Order.cs, templates/Features/SampleData/Services/SampleDataService.cs, templates/Pages/MasterDetail.CodeBehind/Views/MasterDetailDetailControl.xaml, templates/Pages/MasterDetail.CodeBehind/Views/MasterDetailDetailControl.xaml.cs, templates/Pages/MasterDetail.CodeBehind/Views/MasterDetailDetailPage.xaml, templates/Pages/MasterDetail.CodeBehind/Views/MasterDetailPage.xaml, templates/Pages/MasterDetail.CodeBehind/Views/MasterDetailPage.xaml.cs, templates/Pages/MasterDetail/Views/MasterDetailDetailControl.xaml, templates/Pages/MasterDetail/Views/MasterDetailDetailControl.xaml.cs, templates/Pages/MasterDetail/Views/MasterDetailPage.xaml, templates/Pages/MasterDetail/Views/MasterDetailPage.xaml.cs, templates/Pages/WebView.CodeBehind/Views/WebViewPagePage.xaml, templates/Pages/WebView.CodeBehind/Views/WebViewPagePage.xaml.cs
This PR serves to introduce fluent features in the WTS default templates for inclusion in the FCU update. 
1) It updates the Webview template with an acrylic control bar and the Master/Detail template with connected animation and an implicit show animation.
2) It adds new fields to the Order model in the SampleDataService so each order has a unique icon.
3) It serves to update the Master/Detail template closer to a Design reviewed style. 
4) It adds a documentation page detailing how to add Perspective Parallax to a template. 
Because this is utilizing features (Conditional XAML) that only become available in RS2 and later, compiled projects from these templates will not work in any version of Windows below RS2. There is also additional design review internally that should be done to …
=> Include explicit Fluent Design features in Webview and M/D templates

code/AppVeyorCI.sln, code/src/Installer.2017/Installer.2017.csproj, code/src/UI/Extensions/AnimationExtensions.cs, code/test/Core.Test/PostActions/Catalog/MergeTest.cs, code/test/Templates.Test/GenerationFixture.cs, code/test/Templates.Test/ProjectGenerationTests.cs, code/test/Templates.Test/StyleCopGenerationTestsFixture.cs
Create  a new solution without the Installer.2017 project to build all but the extension as looks like AppVeyor does not have Visual Studio Extensibility tools installed.
#843 
Not all things will be build but at least, developers will get build inputs from the most of the code as the Installer.2017.csproj contains basically the wrapper clasess to invoke the rest of the components.
=> Issue843 enable app veyor ci

_build/templates.signconfig.xml, _build/vsix.signconfig.xml
Config splited to allow sign templates before the vsix
=> Split signing config

code/src/Core/Fs.cs, code/src/Core/Locations/TemplatesContent.cs, code/src/Core/Packaging/Templatex.cs, code/test/Core.Test/Packaging/TemplatexTests.cs
Added share option when opening the package to allow concurrent read.
#1004
Nop.
Yes.
Yes.
=> Added share options to extract templates

templates/_composition/MVVMLight/Feature.UriSchemeExamplePage_Activation_Blank_SplitView/Activation/SchemeActivationHandler_postaction.cs
#1104
Fix bug where changes to the main/home page name were not respected by the UriScheme templates for SplitView + MvvmLight
=> Fix ViewModel name usage

code/src/Core/ProgrammingLanguages.cs, code/test/Templates.Test/BuildProjectsTests.cs
Included the Generation+Build of all project combinations (Frameworks and Project Types) with all features and pages in the Minimum execution set. This will increase the generation+build tests surface to catch more issues within the CI
#1104
The build time for CI will be increased to run the minimum execution set (expected 10-15 mins now).
Yes
=> Extend minimum test execution set

code/test/Templates.Test/BuildMVVMLightTests/BuildMVVMLightCollection.cs, code/test/Templates.Test/GenTests/GenerationCollection.cs, code/test/Templates.Test/Templates.Test.csproj
Fix for failing gen tests. I missed the generation collection when splitting up classes.
=> Fixed generation tests

_build/Execute-LocalTestsInParallel.ps1, code/test/Core.Test/Naming/NamingTests.cs, code/test/Templates.Test/BuildCaliburnMicroTests/BuildCaliburnMicroProjectTests.cs, code/test/Templates.Test/BuildCodeBehindTests/BuildCodeBehindProjectsTests.cs, code/test/Templates.Test/BuildMVVMBasic/BuildMVVMBasicProjectsTests.cs, code/test/Templates.Test/BuildMVVMLightTests/BuildMVVMLightProjectsTests.cs, code/test/Templates.Test/WindowsAppCertKitTests.cs, docs/getting-started-developers.md
Changed wack tests ExecutionSet to longrunning.
Removed ExecutionSet Build as not used.
Added script to execute tests locally in parallel
#1235
=> Review test ExecutionSets

code/src/Core/Locations/TemplatesSynchronization.cs
Ensure folder is created to avoid warning on first sync
#1249
=> Ensure folder is created to avoid warning on first sync

_build/Execute-LocalTestsInParallel.ps1, code/test/Core.Test/Core.Test.csproj, code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyTests.cs, templates/Pages/Camera.CodeBehind/Views/CameraViewPage.xaml, templates/Pages/Camera/Views/CameraViewPage.xaml, templates/_composition/_shared/Page.Camera.AddResource/Controls/CameraControl.xaml, templates/_composition/_shared/Page.Camera.AddResource/_postaction.csproj
Removed BoolToVisibilityConverter from Camera Page and dependency con UWP Community Toolkit
#1251
=> Remove BoolToVisibilityConverter from Camera Page

code/test/Templates.Test/BuildCaliburnMicroTests/BuildCaliburnMicroFixture.cs, code/test/Templates.Test/BuildCodeBehindTests/BuildCodeBehindFixture.cs, code/test/Templates.Test/BuildFixture.cs, code/test/Templates.Test/BuildMVVMBasic/BuildMVVMBasicFixture.cs, code/test/Templates.Test/BuildMVVMLightTests/BuildMVVMLightFixture.cs, code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyFixture.cs, code/test/Templates.Test/BuildRightClickWithLegacy/LegacyTemplatesSource.cs, code/test/Templates.Test/StyleCopPlusLocalTemplatesSource.cs
Some VSTS have source id created to loog for path combination.
No
Yes
=> Reduce SourceId names in tests to avoid path too long

code/src/Core/Diagnostics/AppHealth.cs, code/src/Core/Extensions/DateTimeExtensions.cs
Avoid side by side test execution issues
=> Include seconds to avoid collision when multiple tests run

templates/_composition/MVVMLight/Project/Services/NavigationServiceEx.cs, templates/_composition/MVVMLight/ProjectVB/Services/NavigationServiceEx.vb
Issue #1291 
Changes in files NavigationServiceEx.cs and NavigationServiceEx.vb.
All automated tests passed.
=> Fix Issue #1291. Review the use of lock {} in NavigationServiceEx

code/tools/Localization/Logic/LocalizableItemsExtractor.cs
It was not validated if the files in folder wtsFolder/templates\_catalog\projectTypes had been modified before the last commit or tag.
=> Fix error to validate wts template subfolder md files.

templates/Projects/DefaultVB/wts.DefaultProject.vbproj
Reviewing issue 1360 I noticed some extra whitespaces in .vbproj file. 
This is not causing any issues currently, still I'll correct this to avoid possible future issues. 
In _postaction files extra whitespaces can cause references to be added two times, as indentation is corrected when refreshing the project. 
#1360
=> Removed extra whitespaces in vbproj file

code/src/Core/Locations/TemplatesSynchronization.cs, code/src/Core/Resources/StringRes.Designer.cs, code/src/Core/Resources/StringRes.resx, code/src/UI/ViewModels/Common/BaseMainViewModel.cs
Handle and track if there is an exception acquiring content to avoid existing content to be loaded.
#1321 
Download and extract content (Templates Sources) will require a review as some of the intially assumptions are no longer valid (we distribute now content with each version. Issue #1376 reflect this.
Yes.
Yes, #1376
=> Avoid acquire exception preventing load existing content.

code/src/Core/PostActions/Catalog/Merge/IEnumerableExtensions.cs, code/test/Core.Test/PostActions/Catalog/HandleRemovalsTest.cs
Remove extra whitelines before/after closing/opening braces and add extra whiteline before comments where necessary
#1380
=> Avoid stylecop warnings caused by merge postactions

code/tools/TemplateValidator/TemplateFolderVerifier.cs, code/tools/TemplateValidator/TemplateJsonVerifier.cs
Added name verification for composition templates as this can lead to duplicate identities too. 
If there is no identity specified, template engine retrieves identity from name.
#1395
=> Added name verification for composition templates 

code/src/UI/Generation/GenComposer.cs
Add v to version number to avoid conversion to int
#1407
=> Add v to version number to avoid conversion to int

code/src/Core/Core.csproj, code/src/Core/Resources/StringRes.Designer.cs, code/test/Core.Test/Localization/LocalizationTest.cs, code/test/Core.Test/PostActions/Catalog/MergeResourceDictionaryPostactionTest.cs
- Ensure UICulture is reset to en-US after localization tests.
- Use resources to verify MergeResourceDictionary error text
#1435
Anything that requires particular review or attention?
No
Do all automated tests pass?
Yes
=> Ensure UICulture is reset to en-US after localization tests.

code/src/Core/PostActions/Catalog/GenerateTestCertificatePostAction.cs, code/src/Core/PostActions/PostActionFactory.cs, code/test/Core.Test/PostActions/Catalog/GenerateTestCertificatePostActionTest.cs
-Added replacement of parameters in primary output path to certificate generation postaction.
#1330, #1329 
Where the primaryoutput path is used, the fix for parameter replacemement has to be applied until template engine is updated
Yes
=> Fixed certificate generation postaction for multiproject solutions

code/src/UI/VisualStudio/VsGenShell.cs, code/test/Templates.Test/BaseGenAndBuildTests.cs, code/test/Templates.Test/BuildCaliburnMicroTests/BuildCaliburnMicroProjectTests.cs, code/test/Templates.Test/BuildCodeBehindTests/BuildCodeBehindFixture.cs, code/test/Templates.Test/BuildCodeBehindTests/BuildCodeBehindProjectTests.cs, code/test/Templates.Test/BuildMVVMBasic/BuildMVVMBasicFixture.cs, code/test/Templates.Test/BuildMVVMBasic/BuildMVVMBasicProjectTests.cs, code/test/Templates.Test/BuildMVVMLightTests/BuildMVVMLightFixture.cs, code/test/Templates.Test/BuildMVVMLightTests/BuildMVVMLightProjectTests.cs
Exlude xamarin templates from BuildMinimum ExecutionSet to avoid appveyor generation errors
#1471
=> Exlude xamarin templates from BuildMinimum ExecutionSet

code/test/Templates.Test/BuildCodeBehindTests/BuildCodeBehindProjectTests.cs
Reduce path length for tests
#1471
=> Remove framework from project names to avoid path too long errors

code/src/Core/Core.csproj
Exclude template engine dll s from vsix as they are distributed with Visual Studio
=> Do not distribute template.engine dlls

code/test/Templates.Test/Templates.Test.csproj, code/test/Templates.Test/TestData/StyleCop/_searchreplace.1.csproj
Suppress CS0618 warnings caused by UwpCommunityToolkit HamburgerMenu to ensure tests pass.
I added this as stylecop tests are not passing as warnings are treated as errors here.
=> Suppress CS0618 warnings caused by UwpCommunityToolkit HamburgerMenu 

templates/_composition/Prism/Project.SplitView/ViewModels/ShellNavigationItem.cs
For [#1547](https://github.com/Microsoft/WindowsTemplateStudio/issues/1547)
Modified Resource value to properly handle both light and dark themes.
=> Fix for Issue 1547.

templates/Features/BackgroundTask.Prism/App_postaction.xaml.cs
This PR resolves a crash condition for issue #1586.  The original crash condition reported in the issue was not encountered.  This change adds logic to invoke the appropriate methods in the base class to initialize the Container variable if it is null when a background task is launched.
=> Adds logic to init the Unity container.

code/src/Core/Locations/TemplatesSynchronization.cs, code/src/Core/Templates/TemplatesRepository.cs
Force re-loading initial content from template tests to avoid build failures on build servers where template directory changes depending on the working folder
#1710 
No
Yes
=> Force re-loading initial content from template tests

_build/Extension-SetIdentityAndVersion.ps1
In dev wizard version is 65000 + revision number, but templates just have revision number.
Removing this to align with other environments. 
#1729
=> Remove 65000 from dev wizard version

code/src/UI/Controls/ImageEx.cs, code/tools/TemplateValidator/TemplateFolderVerifier.cs
For #1764 
Enabled use of shape to specify either a stroke or a fill, but not both, when Binding the foreground to allow for different colors, such as when using high-contrast. Were previously overlooking Rectangle and Ellipse which set a Fill as the code only adjusted the StrokeProperty. Can now use either, but not both as some templates are using these shapes for outlines.
Also added a related check to the Template Validator code.
=> Handle use of filled Rectangles & Ellipses in template icon xaml

templates/_composition/CodeBehind/ProjectVB/Services/NavigationService.vb, templates/_composition/MVVMBasic/ProjectVB/Services/NavigationService.vb, templates/_composition/MVVMLight/Project/Services/NavigationServiceEx.cs, templates/_composition/MVVMLight/ProjectVB/Services/NavigationServiceEx.vb
For #1774 
Affects all VB frameworks and MVVMLight with C#
For MVVMLight based projects we did not have the check we do for the other frameworks. (If already showing that page, don't navigate again.)
The VB code had a bug in it for comparing types.
=> Prevent repeated navigation to the same page

code/src/UI/Controls/CodeViewer.xaml, code/src/UI/Controls/CodeViewer.xaml.cs
#1945 - Monaco Editor shows a white screen before render the dark theme colors
=> Fix code viewer background

code/test/Templates.Test/BuildTemplatesTests/BuildCodeBehindProjectTests.cs
Fix BuildAllPagesAndFeaturesRandomNamesVBAsync tests for codebehind
#2060 Build xamarininfra.templates.tests.full_20180313.1 failed
=> Fix BuildAllPagesAndFeaturesRandomNamesVBAsync tests for codebehind

code/src/Core/PostActions/Catalog/Merge/MergePostAction.cs
Corrected bug where failedfilename is missing a point in case a _postaction.xaml.cs fails
#2128
=> Fix full test build in dev

templates/Uwp/Features/BackgroundTask.Prism/Helpers/TaskExtensions.cs, templates/Uwp/Features/BackgroundTask/Helpers/TaskExtensions.cs, templates/Uwp/Features/BackgroundTaskVB/Helpers/TaskExtensions.vb
For #2202
`FireAndForget` method allows code to be called with**out** awaiting it.
=> Fix error in comments of FireAndForget method

_utils/Identify-CSharp-Template-Commits-Without-VisualBasic-Equivalents.ps1, _utils/Identify-CSharp-Templates-Changed-More-Recently-Than-VisualBasic-Equivalents.ps1, _utils/List-CSharp-Templates-Without-VisualBasic-Equivalents.ps1, _utils/Synchronize-Files-Used-By-VisualBasic-Templates.ps1, code/test/Templates.Test/GenTests/LanguageComparisonTests.cs, templates/Uwp/Features/MultiViewVB/.template.config/description.md, templates/Uwp/_composition/MVVMLight/Project.SplitViewVB/Views/ShellPage.xaml
Update PowerShell scripts to use paths that account for the differences in the template folder structure.
Also, fix a manual test that was reporting false negatives due to the changes for #1859
=> Fixing scripts & tests affected by template folder structure change

docs/roadmap.md
Added milestone 2.3
indicated 2.1 might now not ship until May
A documentation only change - just trying to be more proactive about keeping the roadmap up to date.
=> Update roadmap doc

code/src/Core/Locations/TemplatesContent.cs
- if there is no cached templatefolder, set current templates to latest valid version from working folder
- #2291 WTS is extracting templates after VSUpdate
=> Get latest (compatible) version from working folder in case of VS Update

templates/Uwp/_composition/Prism/Project.SplitView/ViewModels/ShellViewModel.cs
Page with "Page" suffix causes Header in NavigationView not to work #2362
=> Fix Issue on Prism NavigationView activation

code/tools/TemplateValidator/TemplateJsonVerifier.cs
This PR corrects the error message when an invalid wts.group value is encountered.  We added a new Telemetry group in our STS fork, and were seeing this error incorrectly reported when running the unit tests.  
This PR does not change or add any functionality.
=> Corrects error message.  I found this in our STS fork.

templates/Uwp/Pages/DataGrid.CodeBehind/Views/DataGridViewPage.xaml, templates/Uwp/Pages/DataGrid.CodeBehind/Views/DataGridViewPage.xaml.cs, templates/Uwp/Pages/DataGrid.CodeBehindVB/Views/DataGridViewPage.xaml, templates/Uwp/Pages/DataGrid.CodeBehindVB/Views/DataGridViewPage.xaml.vb, templates/Uwp/Pages/DataGrid.Prism/Views/DataGridViewPage.xaml, templates/Uwp/Pages/DataGrid.Prism/Views/DataGridViewPage.xaml.cs, templates/Uwp/Pages/DataGrid/Views/DataGridViewPage.xaml, templates/Uwp/Pages/DataGrid/Views/DataGridViewPage.xaml.cs, templates/Uwp/Pages/DataGridVB/Views/DataGridViewPage.xaml, templates/Uwp/Pages/DataGridVB/Views/DataGridViewPage.xaml.vb, templates/Uwp/Pages/Grid.CodeBehind/Views/GridViewPage.xaml, templates/Uwp/Pages/Grid.CodeBehind/Views/GridViewPage.xaml.cs, templates/Uwp/Pages/Grid.CodeBehindVB/Views/GridViewPage.xaml, templates/Uwp/Pages/Grid.CodeBehindVB/Views/GridViewPage.xaml.vb, templates/Uwp/Pages/Grid.Prism/Views/GridViewPage.xaml, templates/Uwp/Pages/Grid.Prism/Views/GridViewPage.xaml.cs, templates/Uwp/Pages/Grid/Views/GridViewPage.xaml, templates/Uwp/Pages/Grid/Views/GridViewPage.xaml.cs, templates/Uwp/Pages/GridVB/Views/GridViewPage.xaml, templates/Uwp/Pages/GridVB/Views/GridViewPage.xaml.vb
Added column definitions to datagrid to correctly show symbol column
#2351 DataGrid template does not display symbol icon
The DataGrid from the community toolkit does not allow x:bind yet, thats why I used binding for now. 
(https://github.com/Microsoft/WindowsCommunityToolkit/issues/2112)
=> Added columndefinitions to datagrids to correctly show symbol icon

code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyFixture.cs
Always use latest version from pro to do legacy tests
#2434 Use latest version from pro in legacy tests
=> Always use latest version from pro to do legacy tests

code/test/Core.Test/.codeclonesettings, code/test/Core.Test/Core.Test.csproj, code/test/Templates.Test/BaseGenAndBuildFixture.cs, code/test/Templates.Test/BaseGenAndBuildTests.cs, code/test/Templates.Test/BuildFixture.cs, code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyTests.cs, code/test/Templates.Test/BuildTemplatesTests/BuildCaliburnMicroProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/BuildCodeBehindProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/BuildMVVMBasicProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/BuildMVVMLightProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/BuildPrismProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/BuildTemplatesTestFixture.cs, code/test/Templates.Test/CodeAnalysis/SonarLintGenerationTestsFixture.cs, code/test/Templates.Test/CodeAnalysis/SonarLintProjectGenerationTests.cs, code/test/Templates.Test/CodeAnalysis/StyleCopGenerationTestsFixture.cs, code/test/Templates.Test/CodeAnalysis/StyleCopProjectGenerationTests.cs, code/test/Templates.Test/CodeAnalysis/VBStyleGenerationTestsFixture.cs, code/test/Templates.Test/CodeAnalysis/VBStyleProjectGenerationTests.cs, code/test/Templates.Test/GenTests/GenProjectTests.cs, code/test/Templates.Test/GenTests/GenerationFixture.cs, code/test/Templates.Test/WACK/WindowsAppCertKitTests.cs, code/tools/WtsTelemetry/WtsTelemetry/WtsTelemetry.cs
Started to look at this, and eliminated the following code clones:
- Exact match in StyleCop/VB Style tests: Changed to use BaseGenAndBuildFixture and BaseGenAndBuildTest
- Exact match in Generation and BuildFixture: Created common method for 
GetPageAndFeatureTemplates on BaseGenAndBuildFixture
- Added exception for two igual asserts in CompositionQueryTest
- #933 Address code clone results
=> Issue933 eliminatecodeclones

templates/Uwp/Features/BackgroundTask.Prism/App_postaction.xaml.cs, templates/Uwp/Features/HubNotifications.Prism/App_postaction.xaml.cs, templates/Uwp/Features/StoreNotifications.Prism/App_postaction.xaml.cs, templates/Uwp/Features/ToastNotifications.Prism/App_postaction.xaml.cs, templates/Uwp/Features/UriScheme.Prism/App_postaction.xaml.cs, templates/Uwp/Features/WebToAppLink.Prism/App_postaction.xaml.cs, templates/Uwp/Pages/Settings.Prism/App_postaction.xaml.cs, templates/Uwp/_composition/Prism/Project.Blank.AddNavigation/App_postaction.xaml.cs, templates/Uwp/_composition/Prism/Project.TabbedPivot/App_postaction.xaml.cs
- Change return Task.CompletedTask to await Task.CompletedTask
- Make async methods async 
#2316 Review Async Methods
=> Change return Task.CompletedTask to await Task.CompletedTask;

templates/Uwp/_composition/CaliburnMicro/Feature.MultiView/.template.config/template.json, templates/Uwp/_composition/CaliburnMicro/Feature.MultiView/Services/ViewLifetimeControl_postaction.cs, templates/Uwp/_composition/CaliburnMicro/Feature.MultiView/Services/WindowManagerService_postaction.cs
This resolves an issue raised in #2501 which is null reference when combining Caliburn.Micro and the MultiView feature.
=> Resolve null reference for MultiView and Caliburn.Micro

templates/Uwp/Features/VSAppCenterAnalytics/_postaction.csproj, templates/Uwp/Features/VSAppCenterAnalyticsVB/_postaction.vbproj
Update AppCenter feature NuGet packages to the latest versions. #2510
Update Microsoft.AppCenter.Analytics and Microsoft.AppCenter.Crashes from 1.7.0 to 1.9.0
=> Update Nuget Reference AppCenter

code/src/Core/Core.csproj
Add TreatWarningsAsError to Analyze configuration
#2520 Core project Analyze configuration is not reporting warnings
=> Analyze configuration should treat warnings as error

templates/Uwp/_composition/Prism/Feature.MultiView/App.xaml_postaction.cs
This PR ensures the WindowsManagerService can be initialized successfully regardless of the order is which the other feature templates are added to the OnInitializeAsync method.
This is related to issue #2533
=> Initialize WindowManagerService on UI thread for Prism

templates/Uwp/Projects/DefaultPrism/App.xaml.cs
- Remove services namespace from prism project
- #2576 Build v3.0.templates.tests.full_20180919.1 failed
=> Remove services namespace from prism project

code/test/Templates.Test/WACK/WindowsAppCertKitTests.cs
- Exclude background task for VB projects
#2358 Wack tests fail on 17134
=> Exclude background task for VB projects

code/src/Core/Locations/TemplatesSourceConfig.cs, code/test/Core.Test/Locations/RemoteTemplateSourceTests.cs, code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyTests.cs, code/test/Templates.Test/BuildRightClickWithLegacy/LegacyTemplatesSourceV2.cs
Templates from version 2.4 are not splitted and contain an extra templates folder, added code to move templates to correct folder and resolve package based on version. 
#2681 dev.tests.full failed
=> Fix rightclick on legacy project tests.

code/test/Templates.Test/GenTests/LanguageComparisonTests.cs
For #2696
Adds test to check that C# & VB versions of the same code have the equivalent exception handling.
=> Check for equivalent exception handling in generated apps

code/src/Installer.2017/source.extension.vsixmanifest
This adds support for Visual Studio 2019 by bumping the version range on both installation target and prerequisites. Removed dependency on MPF which is no longer needed.
Thanks,
Mads Kristensen
Visual Studio Extensibility
- Have you raised …
=> Added support for VS 2019

templates/Uwp/Pages/MasterDetail.CaliburnMicro/Views/MasterDetailViewPage.xaml.cs, templates/Uwp/Pages/MasterDetail.CodeBehind/Views/MasterDetailViewPage.xaml.cs, templates/Uwp/Pages/MasterDetail.CodeBehindVB/Views/MasterDetailViewPage.xaml.vb, templates/Uwp/Pages/MasterDetail.Prism/ViewModels/MasterDetailViewViewModel.cs, templates/Uwp/Pages/MasterDetail.Prism/Views/MasterDetailViewPage.xaml.cs, templates/Uwp/Pages/MasterDetailVB/ViewModels/MasterDetailViewViewModel.vb, templates/Uwp/_composition/MVVMLight/Project.SplitView.Page.MasterDetail/.template.config/template.json, templates/Uwp/_composition/MVVMLight/Project.SplitView.Page.MasterDetail/Views/wts.ItemNamePage_postaction.xaml.cs, templates/Uwp/_composition/MVVMLight/Project.SplitView.Page.MasterDetailVB/.template.config/template.json, templates/Uwp/_composition/MVVMLight/Project.SplitView.Page.MasterDetailVB/Views/wts.ItemNamePage_postaction.xaml.vb, templates/Uwp/_composition/Prism/Page.MasterDetail_Blank_TabbedPivot/.template.config/template.json, templates/Uwp/_composition/Prism/Page.MasterDetail_Blank_TabbedPivot/ViewModels/wts.ItemNameViewModel_postaction.cs, templates/Uwp/_composition/Prism/Page.MasterDetail_SplitView/.template.config/template.json, templates/Uwp/_composition/Prism/Page.MasterDetail_SplitView/Views/wts.ItemNamePage_postaction.xaml, templates/Uwp/_composition/Prism/Page.MasterDetail_SplitView/Views/wts.ItemNamePage_postaction.xaml.cs
Added Workarounds for issue on MasterDetail Control using projectType SplitView and frameworks MVVMLight and Prism
#2739 Error when navigating to MasterDetailPage on Prism App
#2739 Error when navigating second time to MasterDetailPage on Mvvmlight App
=> Workaround for issue on MasterDetail Control 

code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyFixture.cs, code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyTests.cs
Adapt legacy tests to work with splitted packages. 
Re-enable legacy tests for MVVMLight and SplitView
#2760 Legacy tests failed on full tests build
#2586 Re-enable rightclick with legacy project tests for MVVMLight and SplitView
=> Adapt legacy tests to work with splitted packages.

templates/Uwp/Features/MultiView/Services/ViewLifetimeControl.cs, templates/Uwp/Features/MultiView/Services/WindowManagerService.cs, templates/Uwp/Features/MultiView/Strings/en-us/Resources_postaction.resw
Multi-View template should throw meaningful exception or not crash if not hooking into released event #2743
=> MultiViews InternalReleased

code/src/Core/PostActions/Catalog/Merge/IEnumerableExtensions.cs, code/src/Core/PostActions/Catalog/Merge/MergeMode.cs, code/src/Core/PostActions/Catalog/Merge/PostactionFormatter.cs, code/test/Core.Test/Core.Test.csproj, code/test/Core.Test/PostActions/Catalog/MergeTest.cs, code/test/Core.Test/TestData/Merge/SourceWithOptionalContextLines.cs, code/test/Core.Test/TestData/Merge/Source_expectedWithOptionalContextLines.cs, code/test/Core.Test/TestData/Merge/Source_expectedmergeinfo.cs, code/test/Core.Test/TestData/Merge/Source_postaction.cs, docs/templates.md, templates/Uwp/Features/FirstUsePrompt/Services/ActivationService_postaction.cs, templates/Uwp/Features/FirstUsePromptVB/Services/ActivationService_postaction.vb, templates/Uwp/Features/HubNotifications/Services/ActivationService_postaction.cs, templates/Uwp/Features/HubNotificationsVB/Services/ActivationService_postaction.vb, templates/Uwp/Features/LiveTile/Services/ActivationService_postaction.cs, templates/Uwp/Features/LiveTileVB/Services/ActivationService_postaction.vb, templates/Uwp/Features/StoreNotifications/Services/ActivationService_postaction.cs, templates/Uwp/Features/StoreNotificationsVB/Services/ActivationService_postaction.vb, templates/Uwp/Features/UserActivity.MVVMLight/Services/ActivationService_postaction.cs, templates/Uwp/Features/UserActivity.MVVMLightVB/Services/ActivationService_postaction.vb, templates/Uwp/Features/UserActivity/Services/ActivationService_postaction.cs, templates/Uwp/Features/UserActivityVB/Services/ActivationService_postaction.vb, templates/Uwp/Features/WhatsNewPrompt/Services/ActivationService_postaction.cs, templates/Uwp/Features/WhatsNewPromptVB/Services/ActivationService_postaction.vb
- Add possibility to define optional context lines in the _postaction file, for cases where a context line might have been removed by another template. 
#2789 Failed Merge Postaction when adding first Settings, then Azure Notifications
=> Issue2789 optional contextlines in merge postactions

code/src/Core/Gen/GenComposer.cs, code/src/Core/Gen/IContextProvider.cs, code/src/UI/VisualStudio/RightClickActions.cs, code/src/UI/VisualStudio/SolutionWizard.cs, code/test/Fakes/FakeContextProvider.cs, code/test/VsEmulator/Main/MainViewModel.cs
- Set SafeProjectName and Projectname from installer and emulator
- Use projectname for file and foldernames, safeprojectname for namespaces
- #2892 Template Studio is unable to create an app (C#)
=> Set SafeProjectName from installer and emulator

templates/Uwp/_composition/_shared/Page.Ink.AddBasicInkServices._VB/Styles/CommandBar_postaction.xaml, templates/Uwp/_composition/_shared/Page.Ink.AddBasicInkServices/Styles/CommandBar_postaction.xaml
#2921 - Ink Page secondary commands style too large in Wide view
=> Update font size to ink header pages commandBar

_build/ProjectTemplate-SetPublishingData.ps1, code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.cs-CZ.vstemplate, code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.de-DE.vstemplate, code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.es-ES.vstemplate, code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.fr-FR.vstemplate, code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.it-IT.vstemplate, code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.ja-JP.vstemplate, code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.ko-KR.vstemplate, code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.pl-PL.vstemplate, code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.pt-BR.vstemplate, code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.ru-RU.vstemplate, code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.tr-TR.vstemplate, code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.vstemplate, code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.zh-CN.vstemplate, code/src/ProjectTemplates/CSharp.UWP.2017.Solution/CSharp.UWP.VS2017.Solution.zh-TW.vstemplate, code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.cs-CZ.vstemplate, code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.de-DE.vstemplate, code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.es-ES.vstemplate, code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.fr-FR.vstemplate, code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.it-IT.vstemplate, code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.ja-JP.vstemplate, code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.ko-KR.vstemplate, code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.pl-PL.vstemplate, code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.pt-BR.vstemplate, code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.ru-RU.vstemplate, code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.tr-TR.vstemplate, code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.vstemplate, code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.zh-CN.vstemplate, code/src/ProjectTemplates/VBNet.UWP.VS2017.Solution/VBNet.UWP.VS2017.Solution.zh-TW.vstemplate
- Change template id from guid to string containing categories and Template Name
- Set separate template id for C# and VB templates
#2938 VS2019: Add tags to project templates
=> Issue2938 changetemplateid

templates/Uwp/Features/WinAppDriver/Param_ProjectName.Tests.WinAppDriver/Param_ProjectName.Tests.WinAppDriver.csproj
Set RestoreProjectStyle to PackageReference for WinAppDriver tests template
#3005 Dev-nightly: WinAppDriver in c# is restoring packages to packages.config instead of proj file
=> Set RestoreProjectStyle to PackageReference

templates/Uwp/Features/UnitTests.App.MSTest._VB/.template.config/template.json, templates/Uwp/Features/UnitTests.App.MSTest/.template.config/template.json, templates/Uwp/Features/UnitTests.App.xUnit._VB/.template.config/template.json, templates/Uwp/Features/UnitTests.App.xUnit/.template.config/template.json
Remove Microsoft.NET.Test.Sdk from Test templates as this is added by VS
#3035 Dev-Nightly: Failure adding nuget Microsoft.Net.Test.Sdk 15.9.0 to XUnit and MSTest project in VS2019
=> Remove Microsoft.NET.Test.Sdk from Test templates as this is added by VS

code/src/Core/PostActions/Catalog/Merge/MergePostAction.cs, code/src/Core/PostActions/Catalog/Merge/MergeResourceDictionaryPostAction.cs, code/src/Core/PostActions/Catalog/Merge/SearchAndReplacePostAction.cs, code/test/Core.Test/PostActions/Catalog/MergePostactionTest.cs, code/test/Core.Test/PostActions/Catalog/MergeResourceDictionaryPostactionTest.cs, code/test/Core.Test/PostActions/Catalog/SearchAndReplacePostActionTest.cs
- Encoding check should only be done on new projects, not on right click
-#3006 Ensure encoding in postactions
=> Issue3007 ensureencoding

code/src/Core/PostActions/Catalog/NewItemGeneration/CopyFilesToProjectPostAction.cs
- Do not open proj files from right click addition
- #3065 Adding Test App features fails when using right click
=> Do not open proj files from right click addition

templates/Uwp/Pages/Map.CaliburnMicro/Views/MapPagePage.xaml, templates/Uwp/Pages/Map.CodeBehind._VB/Views/MapPagePage.xaml, templates/Uwp/Pages/Map.CodeBehind/Views/MapPagePage.xaml, templates/Uwp/Pages/Map.Prism/Views/MapPagePage.xaml, templates/Uwp/Pages/Map._VB/Views/MapPagePage.xaml, templates/Uwp/Pages/Map/Views/MapPagePage.xaml
Why does the MapPage include a `TickBar`? #3060
=> Remove TickBar from map page

_utils/List-CSharp-Templates-Without-VisualBasic-Equivalents.ps1, templates/Uwp/SC/_comp/T.SC.WebApi/.template.config/template.json, templates/Uwp/Services/WebApi.Prism/.template.config/template.json, templates/Uwp/Services/WebApi/.template.config/template.json, templates/Uwp/_comp/_shared/Services.WebApi/.template.config/template.json, templates/Uwp/_comp/_shared/Services.WebApi/Param_ProjectName.WebApi/Param_ProjectName.WebApi.csproj, templates/Uwp/_comp/_shared/Services.WebApi/Param_ProjectName.WebApi/Properties/launchSettings.json
For #3181 
(and a continuation from #3227)
- Adds a metapackage reference (no version number) to `Microsoft.AspNetCore.App`
- also fixed automated testing of WebApi project with StyleCop
**Note**
I'm having issues with SSL in a dev environment on my machine and so can't test this fully at the moment.
Equivalent Web API project created as part of a Xamarin app also has the same error, so hoping this is something on my machine and not in the templates. I'm not aware of having changed anything that might impact this so hoping it's not an issue with the templates.
=> Further Web API improvements

templates/Uwp/Projects/Default._VB/wts.DefaultProject.vbproj
For #3296
Removes project setting that applies to C# and not VB.
No other/related changes necessary.
=> Remove AppDesignerFolder from proj file

code/tools/TemplateValidator/TemplateJsonVerifier.cs, templates/Uwp/Features/CommandLine.Prism/.template.config/template.json, templates/Uwp/Features/CommandLine.Prism/Package_postaction.appxmanifest, templates/Uwp/Features/CommandLine._VB/.template.config/template.json, templates/Uwp/Features/CommandLine._VB/Package_postaction.appxmanifest, templates/Uwp/Features/CommandLine/.template.config/template.json, templates/Uwp/Features/CommandLine/Package_postaction.appxmanifest
- Quick summary of changes: 
Tests for commandline with special chars in names are failing with the following error:
`Reason: The file name "SV -_.,@! (ú)+=CS.exe" declared for element […] doesn't exist in the package. `
Added a regex to transform the Projectname to a safeprojectname.
#1976 Commandline support
=> Issue1976 commandlinesupport

code/test/Templates.Test/BaseGenAndBuildTests.cs, code/test/Templates.Test/BuildTemplatesTests/BuildCaliburnMicroProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/BuildCodeBehindProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/BuildMVVMBasicProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/BuildMVVMLightProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/BuildPrismProjectTests.cs, code/test/Templates.Test/CodeAnalysis/VBStyleProjectGenerationTests.cs, templates/Uwp/_comp/Prism/Service.IdentityOptionalLogin.MenuBar/ViewModels/ShellViewModel_postaction.cs
For #3347 
Combines some of the tests which have a large amount of overlap. While separate tests is better in a number of scenarios, these tests are hardly ever run separately and so the benefit of being able to have narrowly scoped tests loses out to having a test suite that takes less time to run.
Refactoring tests also found a bug where OptionalLogin on Prism didn't cope with the main page being renamed. There is a fix for this as part of this PR.
The old test should have caught this before but at least we know this is passing now.
Once this is merged, will need a full (overnight) build to verify everything still behaves as before.
=> Combine template tests

code/src/UI/VisualStudio/VsGenShell.cs
- Set startup project to WPF project using projectname (project type guid is not available here)
- #3372 Create VSIX entry Point for WPF
=> Set startup project by projectName

code/test/UI.Test/TemplatesFixture.cs, code/test/VsEmulator/CoreTemplateStudio.config.json, code/test/VsEmulator/Main/MainViewModel.cs, code/test/VsEmulator/TemplatesContent/TemplatesContentViewModel.cs
- Set UI Test Template Source Name 
- Set default version to 0.0.0.0 on CoreTS assemblies
- #3424 Build dev.templates.tests.full_20191106.1 failed
Also changing the LocalEnv to LocalEnvWinTS as this conflicts with WebTS LocalEnv on our machines
=> Fix UI Tests

templates/Uwp/Features/BackgroundTask.Prism/Param_ProjectName/App_postaction.xaml.cs, templates/Uwp/Features/CommandLine.Prism/App_postaction.xaml.cs
- Mark line "await Task.CompletedTask;" as optional context
#3437 Dev-nightly: Generation fails when adding all features on a Prism app
=> Mark line await Task.CompletedTask; as optional context

_utils/Synchronize-Files-Used-By-VisualBasic-Templates.ps1, templates/Uwp/_comp/_shared/Page.TabView.Blank._VB/App_postaction.xaml
I've fixed the folder comparison to update the templates and remove the name equivalency on composition templates.
Synchronize-Files-Used-By-VisualBasic-Templates.ps1 script changes more files than it should #3440
=> Fix Synchronize-Files-Used-By-VisualBasic-Templates.ps1 script

code/test/Templates.Test/BaseGenAndBuildTests.cs, code/test/Templates.Test/BuildRightClickWithLegacy/BuildRightClickWithLegacyTests.cs, code/test/Templates.Test/BuildTemplatesTests/Wpf/BuildPrismProjectTests.cs
- Correct Test setup 
- Remove possibility to get all projecttypes over all platforms and frameworks (there is no test with such a broad configuration)
- #3479 Build_AllWithMsix_Wp tests fail due to invalid test theory declaration for Prism
=> Issue3479 fixtemplatetests

docs/UWP/getting-started-endusers.md
Minimum Windows 10 version is the Fall Creators Update because (at least) UWP.UI.Controls require >= 10.0.16299
- If you've changed the UI:
- If you've included a new template:
- Be sure it's included in the list on this [UWP](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/UWP/getting-sta …
=> UWP Pre-req Win10 Fall Creators Update

code/src/UI/Extensions/ValidationResultExtensions.cs, code/src/UI/Launcher/WizardLauncher.cs, code/src/UI/ViewModels/Common/DataItems/SavedTemplateViewModel.cs, code/src/UI/ViewModels/NewItem/TemplateSelectionViewModel.cs
- Adapt wizard to changes in naming services (naming services return all validation errors now)
As the wizard validates names with each keystroke we decided to keep showing only the first error message.
- https://github.com/microsoft/CoreTemplateStudio/issues/101 Refactor naming
=> Issue101 refactornaming

code/test/Templates.Test/BuildTemplatesTests/Uwp/BuildCaliburnMicroProjectTests.cs, templates/Uwp/Pages/ContentGrid.CaliburnMicro/Views/ContentGridViewDetailPage.xaml.cs
- Corrected executionsets for caliburn (this should have been caught in PR validation)
- Add missing using
- #3552 Build dev.templates.publish failed
=> Fix failed builds

templates/Wpf/Features/MSIXPackaging/Param_ProjectName.Packaging/Param_ProjectName.Packaging.wapproj
- Pre-select x86 and x64 configuration 
- #3557 New WPF project Packaging 'mismatch between the processor architecture
=> Add AppxBuildConfigurationSelection

templates/Uwp/_comp/_shared/Services.SecuredWebApi/Param_ProjectName.WebApi/Extensions/ServiceCollectionExtensions.cs
- Add link to docs for secured web api
- #3603  Docs for secured web api is not linked on template
=> Add link to docs for secured web api

code/src/UI/VisualStudio/RightClickActions.cs
- Exclude hidden templates and templates that are not available for right click when evaluating visibility for right click options
- #3691 Dev-nightly: WPF projects should not show Add Services option
=> Remove services from WPF right click options

code/src/Installer/Installer.csproj, code/src/UI/UI.csproj, code/test/Fakes/Fakes.csproj, code/test/Templates.Test/Templates.Test.csproj, code/test/UI.Test/UI.Test.csproj, code/test/VsEmulator/VsEmulator.csproj
For #3730
Changes project settings so that files are not copied unnecessarily. This also avoids unnecessary rebuilds. In turn, this avoids the need to re-run test discovery EVERY time when manually triggering the execution of a test.
=> Remove all CopyToOutputDirectory=Always

templates/Wpf/Features/MSIXPackaging/Param_ProjectName.Packaging/Param_ProjectName.Packaging.wapproj, templates/Wpf/Features/MSIXPackaging/Param_ProjectName/Param_ProjectName_postaction.csproj
- Remove AnyCPU from packaging project and WPF project
- #3741 Dev-nightly: Msix template should not add AnyCPU configuration to the WPF project
=> Remove AnyCPU from packaging project and WPF project

code/test/Templates.Test/BaseGenAndBuildFixture.cs, code/test/Templates.Test/BaseGenAndBuildTests.cs, code/test/Templates.Test/BuildTemplatesTests/Uwp/BuildCaliburnMicroProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Uwp/BuildCodeBehindProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Uwp/BuildMVVMBasicProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Uwp/BuildMVVMLightProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Uwp/BuildPrismProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Wpf/BuildMVVMBasicProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Wpf/BuildMVVMLightProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Wpf/BuildPrismProjectTests.cs, code/test/Templates.Test/VBCodeAnalysis/VBStyleProjectGenerationTests.cs
- Add multiple instances of every multiinstance template to StyleCop G2 tests
#3742 Add two instances of each template that is multiInstance to stylecop tests
=> Add multiple instances of every multiinstance template to StyleCop tests

templates/Uwp/Services/SampleData.Prism/Param_ProjectName.Core/Services/SampleDataService.cs, templates/Uwp/Services/SampleData._VB/Param_ProjectName.Core/Services/SampleDataService.vb, templates/Uwp/Services/SampleData/Param_ProjectName.Core/Services/SampleDataService.cs
Fix inline comments being against the wrong properties in the `SampleDataService`
- Which issue does this PR relate to? #3787 
- Anything that requires particular review or attention? - nope, it's trivial
- Do all automated tests pass? yes
- Have automated tests been added for new features? n/a
- If you've changed the UI:
- Be sure it's included in the list on this [UWP](https://github.com/microsoft/WindowsTemplateStudio/blob/dev/docs/UWP/gett …
=> Put the SampleDataService Symbol comments against the correct properties

code/test/Templates.Test/BaseGenAndBuildTests.cs, code/test/Templates.Test/BuildTemplatesTests/BuildTemplatesTestFixture.cs, code/test/Templates.Test/BuildTemplatesTests/Uwp/BuildCaliburnMicroProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Uwp/BuildCodeBehindProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Uwp/BuildMVVMBasicProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Uwp/BuildMVVMLightProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Uwp/BuildPrismProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Wpf/BuildMVVMBasicProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Wpf/BuildMVVMLightProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Wpf/BuildPrismProjectTests.cs, code/test/Templates.Test/Frameworks.cs, code/test/Templates.Test/ProjectTypes.cs, code/test/Templates.Test/Templates.Test.csproj, code/test/Templates.Test/VisualTests/AccessibilityTests.cs, code/test/Templates.Test/VisualTests/VisualComparisonTests.cs, code/test/Templates.Test/VisualTests/WPF/AccessibilityTests.cs, code/test/Templates.Test/WACK/Uwp/WindowsAppCertKitTests.cs, code/test/Templates.Test/WACK/Wpf/WindowsAppCertKitTests.cs
This is just some refactoring of tests to remove inconsistent use of magic strings for Frameworks and ProjectTypes
- Which issue does this PR relate to? #3799 
- Applies to the following platforms:
As draft as will need updates once #3800 is merged
=> Remove magic strings from test code

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, docs/PULL_REQUEST_TEMPLATE.md
- Changed platform info in github templates from checkable bullet points to table 
- Also changed PR template format a bit as you cannot show a table in a bulleted list
- #3793 issue and PR templates to include indication of related platform(s) 
Applies to the following platforms:
=> Issue3793 Update Platform info in GitHub templates

code/test/Templates.Test/TemplateJsonValidationTests.cs, code/tools/TemplateValidator/TemplateJsonVerifier.cs, code/tools/TemplateValidator/ValidationTemplateInfo.cs
Add template tests for WPF
#3780 Add template verification tests for WPF templates
- Applies to the following platforms:
no
yes
Raised #3820 to make test maintenance easier and enable using TemplateJsonVerifier for WebTS
=> Issue3780 Add Template Tests for WPF

templates/Uwp/_comp/CaliburnMicro/Project.SplitView.TabbedNav.Page.Settings/ViewModels/ShellViewModel_postaction.cs, templates/Uwp/_comp/CaliburnMicro/Project.SplitView.TabbedNav/ViewModels/ShellViewModel.cs, templates/Uwp/_comp/CodeBehind/Project.SplitView.TabbedNav.Page.Settings._VB/Views/ShellPage_postaction.xaml.vb, templates/Uwp/_comp/CodeBehind/Project.SplitView.TabbedNav.Page.Settings/Views/ShellPage_postaction.xaml.cs, templates/Uwp/_comp/CodeBehind/Project.SplitView.TabbedNav._VB/Views/ShellPage.xaml.vb, templates/Uwp/_comp/CodeBehind/Project.SplitView.TabbedNav/Views/ShellPage.xaml.cs, templates/Uwp/_comp/MVVMBasic/Project.SplitView.TabbedNav.Page.Settings._VB/ViewModels/ShellViewModel_postaction.vb, templates/Uwp/_comp/MVVMBasic/Project.SplitView.TabbedNav.Page.Settings/ViewModels/ShellViewModel_postaction.cs, templates/Uwp/_comp/MVVMBasic/Project.SplitView.TabbedNav._VB/ViewModels/ShellViewModel.vb, templates/Uwp/_comp/MVVMBasic/Project.SplitView.TabbedNav/ViewModels/ShellViewModel.cs, templates/Uwp/_comp/MVVMLight/Project.SplitView.TabbedNav.Page.Settings._VB/ViewModels/ShellViewModel_postaction.vb, templates/Uwp/_comp/MVVMLight/Project.SplitView.TabbedNav.Page.Settings/ViewModels/ShellViewModel_postaction.cs, templates/Uwp/_comp/MVVMLight/Project.SplitView.TabbedNav._VB/ViewModels/ShellViewModel.vb, templates/Uwp/_comp/MVVMLight/Project.SplitView.TabbedNav/ViewModels/ShellViewModel.cs, templates/Uwp/_comp/Prism/Project.SplitView.TabbedNav.Page.Settings/ViewModels/ShellViewModel_postaction.cs, templates/Uwp/_comp/Prism/Project.SplitView.TabbedNav/ViewModels/ShellViewModel.cs
- Add comment on how to navigate to settings page in NavView
- #3784 Clicking on NavigationView's Settings item throws NullReferenceException
Applies to the following platforms:
=> Add comment on how to navigate to settings page in NavView

code/src/UI/Services/NavigationService.cs, code/src/UI/Views/NewItem/MainPage.xaml.cs, code/src/UI/Views/NewProject/MainPage.xaml.cs
Scroll position (offset) is lost when viewing the details of an item in the wizard #3804
=> Fix detail page scroll in wizard

code/test/Templates.Test/WACK/Wpf/WindowsAppCertKitTests.cs
- Fix wack tests 
- Add wack tests for CodeBehind
#3774 Add codebehind as a framework option for WPF
| No | Yes |
=> Fix wack tests and add wack tests for CodeBehind

code/src/UI/Views/Common/TemplateInfoPage.xaml
Fix visibility bindings in templates details page in Wizard
#3859 Dev-Nightly: Msix detail page should not show minimum required .net version
=> Fix visibility bindings in Details page

docs/UWP/platform-specific-recommendations.md
Remove links to Windows Mobile specific information & platform specific SDK docs that have been removed from docs.
For #3857
|  Yes | No |
Nope. Just a docs change.
yes.
n/a
- Be sure you reviewed the [Template Verification …
=> Remove outdated references for device family SDKs

code/src/UI/Services/GenerationService.cs
Show error message before closing the solution. 
Trying to create a WinUI3 solution in VS 16.8 fails, but the error message is not shown correctly in WTS.
Closing the solution after showing the error message fixes the problem.
=> Fix error handling for WinUI3 templates in VS Preview

code/src/UI/Views/NewProject/MainPage.xaml
Disable item focus to solve screen reader logical order.
#3893
=> Accessibility - Wizard - Pages section is not in logical order

code/src/UI/Controls/NotificationMarkdownBlock.xaml.cs, code/src/UI/Views/Common/TemplateInfoPage.xaml.cs
A11y_ Windows Template Studio_ MVVM Basic Details_Screenreader: Screenreader is not announcing the link “The Model-View View Model pattern”. #3897
A11y_Windows Template Studio_ Services Your project Details_Screenreader: Screenreader does not announce Alert Indication status after enter numbering in Edit field. #3894
=> Screen reader announces comments

code/src/UI/Controls/Notification.cs, code/src/UI/Resources/StringRes.Designer.cs, code/src/UI/Resources/StringRes.cs-CZ.resx, code/src/UI/Resources/StringRes.de-DE.resx, code/src/UI/Resources/StringRes.es-ES.resx, code/src/UI/Resources/StringRes.fr-FR.resx, code/src/UI/Resources/StringRes.it-IT.resx, code/src/UI/Resources/StringRes.ja-JP.resx, code/src/UI/Resources/StringRes.ko-KR.resx, code/src/UI/Resources/StringRes.pl-PL.resx, code/src/UI/Resources/StringRes.pt-BR.resx, code/src/UI/Resources/StringRes.resx, code/src/UI/Resources/StringRes.ru-RU.resx, code/src/UI/Resources/StringRes.tr-TR.resx, code/src/UI/Resources/StringRes.zh-CN.resx, code/src/UI/Resources/StringRes.zh-TW.resx, code/src/UI/ViewModels/NewItem/ChangesSummaryViewModel.cs, code/src/UI/ViewModels/NewItem/MainViewModel.cs, code/src/UI/Views/NewItem/MainPage.xaml, code/src/UI/Views/NewItem/WizardShell.xaml.cs
- Validate project path and project name match 
- Show notification in case there is a mismatch as this might cause postactions to fail
- Only allow temporary generation in case there is a mismatch
#3811 Can't create new files using Windows Template Studio after renaming the project
| yes | yes |yes |
=> Issue3811 validate project paths on right click

templates/Wpf/Testing/UnitTests.App.MSTest/Param_ProjectName.Tests.MSTest/Param_ProjectName.Tests.MSTest.csproj, templates/Wpf/Testing/UnitTests.App.NUnit/Param_ProjectName.Tests.NUnit/Param_ProjectName.Tests.NUnit.csproj, templates/Wpf/Testing/UnitTests.App.xUnit/Param_ProjectName.Tests.xUnit/Param_ProjectName.Tests.xUnit.csproj
Fix project references to use ProjectName instead of RootNamespace
Detected by full test pipeline https://winappstudio.visualstudio.com/WTS/_build/results?buildId=35473&view=results
#3613 WPF Testing Templates
| No | Yes|No |
=> Fix project references to use ProjectName instead of RootNamespace

templates/Wpf/_comp/CodeBehind/Project/Services/NavigationService.cs, templates/Wpf/_comp/MVVMBasic/Project/Services/NavigationService.cs, templates/Wpf/_comp/MVVMLight/Project/Services/NavigationService.cs
Call OnNavigatedFrom in backwards navitagion on WPF Templates
OnNavigatedFrom event is not invoked when navigating backwards in WPF templates #3944
=> Issue3944 on navigated from

templates/WinUI/_comp/MVVMToolkit/Project/Helpers/FrameExtensions.cs, templates/WinUI/_comp/MVVMToolkit/Project/Services/NavigationService.cs
Fix INavigationAware OnNavigatedFrom in WinUI3
Dev-nightly: OnNavigatedFrom event is not being invoked correctly in WinUI3 #3943
=> Fix INavigationAware OnNavigatedFrom in WinUI3

templates/Uwp/Testing/UnitTests.App.MSTest._VB/.template.config/template.json, templates/Uwp/Testing/UnitTests.App.MSTest._VB/Param_ProjectName.Tests.MSTest/Param_ProjectName.Tests.MSTest.vbproj, templates/Uwp/Testing/UnitTests.App.MSTest/.template.config/template.json, templates/Uwp/Testing/UnitTests.App.MSTest/Param_ProjectName.Tests.MSTest/Param_ProjectName.Tests.MSTest.csproj, templates/Uwp/Testing/UnitTests.App.xUnit._VB/.template.config/template.json, templates/Uwp/Testing/UnitTests.App.xUnit._VB/Param_ProjectName.Tests.xUnit/Param_ProjectName.Tests.xUnit.vbproj, templates/Uwp/Testing/UnitTests.App.xUnit/.template.config/template.json, templates/Uwp/Testing/UnitTests.App.xUnit/Param_ProjectName.Tests.xUnit/Param_ProjectName.Tests.xUnit.csproj
Move Microsoft.NET.Test.Sdk packages to csproj/vbproj file.
#3940 Test App with xUnit NuGet Package Microsoft.NET.Test.Sdk Upgrade Issue 
| Yes | No |No |
=> Move Microsoft.NET.Test.Sdk packages to csproj/vbproj file

templates/Wpf/_comp/MVVMToolkit/Project/Services/NavigationService.cs
Update NavigationService in WPF MVVM Toolkit
OnNavigatedFrom event is not invoked when navigating backwards in WPF templates #3944
| No |  Yes | No |
=> Update NavigationService in WPF MVVM Toolkit

code/test/Templates.Test/WACK/Wpf/WindowsAppCertKitTests.cs
Exclude testing projects from WPF WACK tests
#3613 WPF Testing Templates
=> Exclude testing projects from WPF WACK tests

templates/Uwp/Pages/TreeView.CodeBehind._VB/Views/wts.ItemNamePage.xaml, templates/Uwp/Pages/TreeView.CodeBehind/Views/wts.ItemNamePage.xaml, templates/Uwp/Pages/TreeView.Prism/Param_ProjectName/Views/wts.ItemNamePage.xaml, templates/Uwp/Pages/TreeView._VB/Views/wts.ItemNamePage.xaml, templates/Uwp/Pages/TreeView/Views/wts.ItemNamePage.xaml
Set CanReorderFalse in UWP TreeView Page Template
TreeViewPage Exception on Drop TreeViewItem #4056
| Yes | No | No |
=> Set CanReorderFalse in UWP TreeView Page Template

mockup/WinUI3/WinUIDesktopApp (Package)/WinUIDesktopApp (Package).wapproj, mockup/WinUI3/WinUIDesktopApp/App.xaml.cs, mockup/WinUI3/WinUIDesktopApp/Contracts/Views/IShellWindow.cs, mockup/WinUI3/WinUIDesktopApp/Services/ActivationService.cs, mockup/WinUI3/WinUIDesktopApp/Services/NavigationService.cs, mockup/WinUI3/WinUIDesktopApp/Views/ShellPage.xaml, mockup/WinUI3/WinUIDesktopApp/Views/ShellPage.xaml.cs
Adapt WinUI 3 Desktop Mockup for sharing code between different app models (Desktop and UWP)
- Use ShellPage instead of  ShellWindow to host the navigation view (Creating a new Window with this ShellPage as Content).
- Add `IsInteractive` check to ActivationService to support non-interactive activations (i.e. BackgroundTask).
- Prepare ActivationService and NavigationService for Blank projects support.
Proposal: C# Templates for WinUI 3 #3810
WinUI 3 Desktop App NavigationService should not use Window.Currrent #4032
=> WinUI 3 Desktop Mockup adaptions

docs/WinUI/readme.md, templates/WinUI/Features/MSIXPackaging/Param_ProjectName (Package)/Param_ProjectName (Package).wapproj, templates/WinUI/Features/MSIXPackaging/Param_ProjectName (Package)/build/Microsoft.WinUI.AppX.targets, templates/WinUI/Features/ThemeSelection/Services/ThemeSelectorService.cs, templates/WinUI/Pages/ContentGrid/.template.config/template.json, templates/WinUI/Pages/ContentGrid/Param_ProjectName/ViewModels/wts.ItemNameViewModel.cs, templates/WinUI/Pages/DataGrid/.template.config/template.json, templates/WinUI/Pages/DataGrid/Param_ProjectName/ViewModels/wts.ItemNameViewModel.cs, templates/WinUI/Pages/MasterDetail/.template.config/template.json, templates/WinUI/Pages/Settings/ViewModels/wts.ItemNameViewModel.cs, templates/WinUI/Pages/WebView/Contracts/Services/IWebViewService.cs, templates/WinUI/Pages/WebView/Services/WebViewService.cs, templates/WinUI/Pages/WebView/ViewModels/wts.ItemNameViewModel.cs, templates/WinUI/Projects/Default/.template.config/template.json, templates/WinUI/Projects/Default/wts.ProjectName/Properties/PublishProfiles/win10-arm64.pubxml, templates/WinUI/Projects/Default/wts.ProjectName/Properties/PublishProfiles/win10-x64.pubxml, templates/WinUI/Projects/Default/wts.ProjectName/Properties/PublishProfiles/win10-x86.pubxml, templates/WinUI/Projects/Default/wts.ProjectName/app.manifest, templates/WinUI/_comp/MVVMToolkit/Project.SplitView/ViewModels/ShellViewModel.cs, templates/WinUI/_comp/MVVMToolkit/Project/.template.config/template.json
- Update WinUI 3 Templates to WinUI 3 Preview 4
-  Uncomment setting storage access from ThemeSelectionService
- Remove not user using statements and add missing system using to some ViewModels
Update WinUI3 Templates to Preview 4 #4064
WinUI 3 Apps crash after reading Theme from SettingsStorage #3984
Theme is not applied to NavView items on App Startup when assigning Dark or Light Theme #3384
| Yes | No | Yes |
=> Update Win UI 3 Templates to Preview 4

code/src/UI/Services/ProjectMetadataService.cs
Check for empty value before adding metadata
#4040 Add AppModel (Desktop, UWP) to WinUI templates and entry points
=> Fix template tests

code/src/ProjectTemplates/CSharp.WinUI.Solution/CSharp.WinUI.Solution.cs-CZ.vstemplate, code/src/ProjectTemplates/CSharp.WinUI.Solution/CSharp.WinUI.Solution.de-DE.vstemplate, code/src/ProjectTemplates/CSharp.WinUI.Solution/CSharp.WinUI.Solution.es-ES.vstemplate, code/src/ProjectTemplates/CSharp.WinUI.Solution/CSharp.WinUI.Solution.fr-FR.vstemplate, code/src/ProjectTemplates/CSharp.WinUI.Solution/CSharp.WinUI.Solution.it-IT.vstemplate, code/src/ProjectTemplates/CSharp.WinUI.Solution/CSharp.WinUI.Solution.ja-JP.vstemplate, code/src/ProjectTemplates/CSharp.WinUI.Solution/CSharp.WinUI.Solution.ko-KR.vstemplate, code/src/ProjectTemplates/CSharp.WinUI.Solution/CSharp.WinUI.Solution.pl-PL.vstemplate, code/src/ProjectTemplates/CSharp.WinUI.Solution/CSharp.WinUI.Solution.pt-BR.vstemplate, code/src/ProjectTemplates/CSharp.WinUI.Solution/CSharp.WinUI.Solution.ru-RU.vstemplate, code/src/ProjectTemplates/CSharp.WinUI.Solution/CSharp.WinUI.Solution.tr-TR.vstemplate, code/src/ProjectTemplates/CSharp.WinUI.Solution/CSharp.WinUI.Solution.vstemplate, code/src/ProjectTemplates/CSharp.WinUI.Solution/CSharp.WinUI.Solution.zh-CN.vstemplate, code/src/ProjectTemplates/CSharp.WinUI.Solution/CSharp.WinUI.Solution.zh-TW.vstemplate
Setting sortOrder to move our templates higher in the New Project Dialog list
#4100 Move our templates higher up in the New Project Dialog template list
| No | No |Yes|
=> Move our templates higher in the New Project Dialog list

code/Nuget.Config, templates/WinUI/Projects/Default/.template.config/template.json
- Remove nuget package VCRTForwarders
- Incude WindowsCommunityToolkit nuget in PackageSources
#4113 Remove nuget package VCRTForwarders from WinUI3 templates
=> remove VCRTForwarders nuget reference from winUI preview 4

templates/WinUI/Pages/Settings/ViewModels/wts.ItemNameViewModel.cs
Don't refresh UI or save selected theme when it hasn't changed. (Because user clicks already selected option.)
For #4130
no
yes
n/a
n/a
- Be sure you reviewed the [Template Verification …
=> Don't save or refresh theme when not changed [WinUI3]

code/test/Templates.Test/BaseGenAndBuildTests.cs
Correct template selection for platforms with empty appModel 
Detected on nightly full test build:
https://winappstudio.visualstudio.com/WTS/_build/results?buildId=36408&view=results
=> Fix right click tests for WPF and UWP

templates/Uwp/Pages/ContentGrid.CaliburnMicro/Views/ContentGridViewDetailPage.xaml, templates/Uwp/Pages/ContentGrid.CodeBehind._VB/Views/ContentGridViewDetailPage.xaml, templates/Uwp/Pages/ContentGrid.CodeBehind/Views/ContentGridViewDetailPage.xaml, templates/Uwp/Pages/ContentGrid.Prism/Param_ProjectName/Views/ContentGridViewDetailPage.xaml, templates/Uwp/Pages/ContentGrid._VB/Views/ContentGridViewDetailPage.xaml, templates/Uwp/Pages/ContentGrid/Views/ContentGridViewDetailPage.xaml, templates/Uwp/Pages/MasterDetail.CaliburnMicro/Views/MasterDetailViewDetail/DetailsView.xaml, templates/Uwp/Pages/TwoPaneView.CodeBehind._VB/Views/wts.ItemNameDetailControl.xaml, templates/Uwp/Pages/TwoPaneView.CodeBehind/Views/wts.ItemNameDetailControl.xaml, templates/Uwp/Pages/TwoPaneView.Prism/Param_ProjectName/Views/wts.ItemNameDetailControl.xaml, templates/Uwp/Pages/TwoPaneView._VB/Views/wts.ItemNameDetailControl.xaml, templates/Uwp/Pages/TwoPaneView/Views/wts.ItemNameDetailControl.xaml, templates/Uwp/_comp/CaliburnMicro/Page.ContentGrid.Blank/Views/wts.ItemNameDetailPage_postaction.xaml, templates/Uwp/_comp/CaliburnMicro/Page.ContentGrid.SplitView.TabbedNav/Views/wts.ItemNameDetailPage_postaction.xaml, templates/Uwp/_comp/CodeBehind/Page.ContentGrid.Blank.MenuBar._VB/Views/wts.ItemNameDetailPage_postaction.xaml, templates/Uwp/_comp/CodeBehind/Page.ContentGrid.Blank.MenuBar/Views/wts.ItemNameDetailPage_postaction.xaml, templates/Uwp/_comp/CodeBehind/Page.ContentGrid.SplitView.TabbedNav._VB/Views/wts.ItemNameDetailPage_postaction.xaml, templates/Uwp/_comp/CodeBehind/Page.ContentGrid.SplitView.TabbedNav/Views/wts.ItemNameDetailPage_postaction.xaml, templates/Uwp/_comp/Prism/Page.ContentGrid.Blank.MenuBar/Views/wts.ItemNameDetailPage_postaction.xaml, templates/Uwp/_comp/Prism/Page.ContentGrid.SplitView.TabbedNav/Views/wts.ItemNameDetailPage_postaction.xaml, templates/Uwp/_comp/_shared/Page.ContentGrid.Blank.MenuBar._VB/Views/wts.ItemNameDetailPage_postaction.xaml, templates/Uwp/_comp/_shared/Page.ContentGrid.Blank.MenuBar/Views/wts.ItemNameDetailPage_postaction.xaml, templates/Uwp/_comp/_shared/Page.ContentGrid.SplitView.TabbedNav._VB/Views/wts.ItemNameDetailPage_postaction.xaml, templates/Uwp/_comp/_shared/Page.ContentGrid.SplitView.TabbedNav/Views/wts.ItemNameDetailPage_postaction.xaml, templates/Uwp/_comp/_shared/Page.MasterDetail._VB/Views/wts.ItemNameDetailControl.xaml, templates/Uwp/_comp/_shared/Page.MasterDetail/Views/wts.ItemNameDetailControl.xaml, templates/WinUI/Pages/ContentGrid/Param_ProjectName/Views/wts.ItemNameDetailPage.xaml, templates/WinUI/Pages/MasterDetail/Param_ProjectName/Views/wts.ItemNameDetailControl.xaml, templates/Wpf/Pages/ContentGrid.CodeBehind/Param_ProjectName/Views/wts.ItemNameDetailPage.xaml, templates/Wpf/Pages/ContentGrid/Param_ProjectName/Views/wts.ItemNameDetailPage.xaml
- Add tag IsTabStop to allow arrow scrolling on MasterDetail and ContentGrid
- Modify postaction template generations on MasterDetail and ContentGrid
Details pages does not scroll using arrows #4062
| Yes | Yes |Yes |
=> Details pages does not scroll using arrows

code/src/UI/Services/ProjectConfigInfoService.cs, code/src/UI/VisualStudio/RightClickActions.cs, templates/WinUI/_comp/MVVMToolkit/Project/Services/NavigationService.cs
- Add rightclick options for C# WinUI UWP projects
- Add infer methods for Project Type Blank and Framework Codebehind for C# WinUI projects
#4042
=> Add rightclick options for WinUI UWP projects

_build/ProjectTemplate-SetPublishingData.ps1
Refactor script to do replacements in template names and ids based on the passed environment configuration instead of passing more template ids and names.
The convention is that the "`.local`" in the vstemplate id and the "`; local`" in the vstemplate name should be replaced by the environment name and id passed as parameters.
#4144, #4146
=> Refactor script that does template id replacements for different environments

code/src/ItemTemplates/WinUI/Cpp/Cpp.WinUI.BlankPage/Cpp.WinUI.BlankPage.vstemplate, code/src/ItemTemplates/WinUI/Cpp/Cpp.WinUI.Desktop.BlankWindow/Cpp.WinUI.Desktop.BlankWindow.vstemplate, code/src/ItemTemplates/WinUI/Cpp/Cpp.WinUI.TemplatedControl/Cpp.WinUI.TemplatedControl.vstemplate, code/src/ItemTemplates/WinUI/Cpp/Cpp.WinUI.UserControl/Cpp.WinUI.UserControl.vstemplate, code/src/ProjectTemplates/WinUI/Cpp/Cpp.WinUI.RuntimeComponent/Cpp.WinUI.RuntimeComponent.vstemplate, code/test/Templates.Test/BaseGenAndBuildFixture.cs, code/test/Templates.Test/BuildTemplatesTests/WinUI/BuildCodeBehindProjectTests.cs, templates/WinUI/Features/MSIX.Cpp/Param_ProjectName (Package)/Param_ProjectName (Package).wapproj, templates/WinUI/Projects/Default.Desktop._Cpp/.template.config/template.json, templates/WinUI/Projects/Default.Desktop._Cpp/wts.ProjectName/App.xaml.cpp
- Updated WinUI 3 templates to Reunion 0.5 (C++)
- Fix WinUI Right click and OneByOne Tests
#4095 Update WinUI 3 templates to Reunion 0.5 
|No | No |Yes |
=> Issue4095 Update to Reunion 0.5 (C++)

templates/Wpf/Pages/Settings/Views/wts.ItemNamePage.xaml
Set RadioButton IsSelected property BindingMode to OneWay
Current Theme Not Correctly Selected on Settings Page #4118
=> Fix SettingsPage Selected Theme

code/test/Templates.Test/BuildTemplatesTests/Uwp/BuildToolkitMVVMProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Wpf/BuildCodeBehindProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Wpf/BuildMVVMBasicProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Wpf/BuildMVVMLightProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Wpf/BuildPrismProjectTests.cs, code/test/Templates.Test/BuildTemplatesTests/Wpf/BuildToolkitMVVMProjectTests.cs
- Fix executionset name for WPF Build_All_CheckWithStyleCop_G1_WpfAsync tests
- Move Build_All_CheckWithStyleCop_G1* tests on MVVMToolkit from MinimumMVVMToolkit to BuildMvvmToolkit execution set
#4223
=> Adjust test executionsets

templates/WinUI/Pages/Form/Param_ProjectName/Views/wts.ItemNamePage.xaml
Fix dates cropped adding a responsive behavior using VisualStateManager
FormPage Date and Time boxes show cropped on the narrow mode #4061
=> WinUI FormPage fix dates cropped

code/src/UI/Services/ProjectConfigInfoService.cs, code/test/Templates.Test/BaseGenAndBuildFixture.cs, code/test/Templates.Test/BaseGenAndBuildTests.cs, code/test/Templates.Test/BuildTemplatesTests/BuildTemplatesTestFixture.cs, code/test/Templates.Test/BuildTemplatesTests/WinUI/BuildNoneProjectTests.cs, code/test/Templates.Test/Frameworks.cs, code/test/Templates.Test/Templates.Test.csproj, docs/getting-started-developers.md, templates/WinUI/Features/MSIX/Param_ProjectName (Package)/Param_ProjectName (Package).wapproj
- The AssetTargetFallback property needs to be defined after the definition of the TargetPlatformVersion property as the former has a dependency on the latter.
- Update automated tests with latest changes: 
- Remove tests for Uwp templates
- Use Framework None instead of CodeBehind
- Rename ShellWindow to ShellPage
- #4197 Review + Re-enable WinUI Template Tests
=> Fix winui tests

templates/WinUI/Projects/Default.Blank/wts.ProjectName/App.xaml.cs, templates/WinUI/Projects/Default.Blank/wts.ProjectName/wts.ProjectName.csproj, templates/WinUI/Projects/Default/wts.ProjectName/App.xaml.cs, templates/WinUI/Projects/Default/wts.ProjectName/wts.ProjectName.csproj
- Update FrameworkReferences to 10.0.19041.16
- Add developer TODOs
#4229 Remove FrameworkReference once .NET 5.0.6 is available 
=> Add developer TODOs and update FrameworkReferences to 10.0.19041.16

templates/WinUI/Projects/Default.Blank/wts.ProjectName/App.xaml.cs, templates/WinUI/Projects/Default.Blank/wts.ProjectName/wts.ProjectName.csproj, templates/WinUI/Projects/Default/wts.ProjectName/App.xaml.cs, templates/WinUI/Projects/Default/wts.ProjectName/wts.ProjectName.csproj, templates/WinUI/SC/StyleCop/Param_ProjectName/Param_ProjectName_postaction.csproj
Remove fixed FrameworkReferences and related comments
#4229 Remove FrameworkReference once .NET SDK 5.0.204 or 5.0.300 is available
=> Remove fixed FrameworkReferences and related comments

templates/WinUI/Projects/Default.Blank/wts.ProjectName/wts.ProjectName.csproj, templates/WinUI/Projects/Default/wts.ProjectName/wts.ProjectName.csproj, templates/WinUI/SC/StyleCop/Param_ProjectName/Param_ProjectName_postaction.csproj
Exclude CA1416 warnings from project
#4314 Big number of warnings after compiling generated WinUI 3 app on VS 16.10
=> Exclude CA1416 warnings from project

templates/Wpf/Features/ToastNotifications/.template.config/template.json, templates/Wpf/Projects/Default.Prism/.template.config/template.json, templates/Wpf/Projects/Default/.template.config/template.json, templates/Wpf/Testing/UnitTests.App.MSTest/.template.config/template.json, templates/Wpf/Testing/UnitTests.App.NUnit/.template.config/template.json, templates/Wpf/Testing/UnitTests.App.xUnit/.template.config/template.json, templates/Wpf/Testing/UnitTests.Core.MSTest/.template.config/template.json, templates/Wpf/Testing/UnitTests.Core.NUnit/.template.config/template.json, templates/Wpf/Testing/UnitTests.Core.xUnit/.template.config/template.json, templates/Wpf/Testing/WinAppDriver/.template.config/template.json, templates/Wpf/_comp/MVVMToolkit/Project/.template.config/template.json, templates/Wpf/_comp/_shared/Project.Ribbon/.template.config/template.json, templates/Wpf/_comp/_shared/Service.IdentityCommon/.template.config/template.json
Update WPF nuget packages to latests versions
Update nuget packages in generated code #4346
_Updated packages_
MahApps.Metro 2.4.6
Microsoft.Extensions.Hosting 3.1.16
Microsoft.Extensions.Configuration 3.1.16
Microsoft.Extensions.Configuration.Binder 3.1.16
Microsoft.Extensions.Configuration.CommandLine 3.1.16
Microsoft.Extensions.Configuration.Json 3.1.16
Microsoft.Identity.Client 4.32.1
Microsoft.NET.Test.Sdk 16.10.0
Microsoft.Toolkit.Mvvm 7.0.2
Microsoft.Toolkit.Uwp.Notifications 7.0.2 …
=> [WPF] Update nuget packages in generated code

templates/WinUI/_comp/MVVMToolkit/Project.MenuBar.AddNavigationViewItem.Settings/Strings/en-us/Resources_postaction.resw, templates/WinUI/_comp/MVVMToolkit/Project.MenuBar.AddNavigationViewItem.Settings/ViewModels/ShellViewModel_postaction.cs, templates/WinUI/_comp/MVVMToolkit/Project.MenuBar.AddNavigationViewItem.Settings/Views/ShellPage_postaction.xaml, templates/WinUI/_comp/MVVMToolkit/Project.MenuBar/README_postaction.md, templates/WinUI/_comp/MVVMToolkit/Project.MenuBar/ViewModels/ShellViewModel.cs, templates/WinUI/_comp/MVVMToolkit/Project.MenuBar/Views/ShellPage.xaml
Fix some issues:
* comments on ShellPage and ShellViewModel
* Menu entry for settings page should show before exit on the File menu
* _menuViewsSettingsCommand should be _menuFileSettingsCommand on the ShellViewModel
* link to menubar docs on Readme.md
Add MenuBar project type for WinUI #4338
=> WinUI MenuBar fixes

README.md
docs fix to link to the latest version of the official C# guidelines
=> Update coding guidelines link

code/test/SharedFunctionality.Core.Tests/SharedFunctionality.Core.Tests.csproj
removing this unneeded dependency avoids issues building after a restore
=> Remove unneeded dependency

code/src/ProjectTemplates/WinUI/CS/Ts4WinUICsTemplate/Ts4WinUICsTemplate.vstemplate
For #4418
Add the same platform tags as the official WinUI templates that come with the WinAppSDK
For #4418
no
yes
n/a
na/
- Be sure you reviewed the [Template Verification …
=> Use Same project platform tags as WinnAppSDK templates

code/test/SharedFunctionality.Core.Tests/Diagnostics/FileHealthWriterTest.cs, code/test/SharedFunctionality.Core.Tests/Helpers/FsTests/EnsureFileEditableTests.cs, code/test/SharedFunctionality.Core.Tests/Helpers/FsTests/EnsureFolderExistsTests.cs, code/test/SharedFunctionality.Core.Tests/Helpers/FsTests/SafeCopyFileTests.cs, code/test/SharedFunctionality.Core.Tests/Helpers/FsTests/SafeRenameDirectoryTests.cs, code/test/SharedFunctionality.Core.Tests/Packaging/TemplatePackageTests.cs, code/test/SharedFunctionality.Core.Tests/PostActions/Catalog/AddProjectReferenceToContextPostActionTest.cs, code/test/SharedFunctionality.Core.Tests/PostActions/Catalog/AddSdkReferenceToContextPostActionTest.cs, code/test/SharedFunctionality.Core.Tests/PostActions/Catalog/Merge/MergePostactionTest.cs, code/test/SharedFunctionality.Core.Tests/PostActions/Catalog/Merge/NewItemGeneration/GenerateMergeInfoPostActionTest.cs, code/test/SharedFunctionality.Core.Tests/PostActions/Catalog/Merge/NewItemGeneration/GetMergeFilesFromProjectPostActionTest.cs, code/test/SharedFunctionality.Core.Tests/PostActions/Catalog/Merge/SearchAndReplacePostActionTest.cs, code/test/SharedFunctionality.Core.Tests/PostActions/Catalog/NewItemGeneration/CopyFilesToProjectPostActionTest.cs, code/test/SharedFunctionality.Core.Tests/PostActions/Catalog/NewItemGeneration/CreateSummaryPostActionTest.cs, code/test/SharedFunctionality.Tests/BaseGenAndBuildFixture.cs, code/test/SharedFunctionality.UI.Tests/SharedFunctionality.UI.Tests.csproj
This is the first part of the work for #4421 
It skips the tests that sometimes fail--without a clear indication why.
This is to increase the reliability of the tests that run as part of a PR.
For #4421
| No | No | No |
no
yes.
With the low-tech approach of running the test repeatedly and temporarily disabling any that fail until they repeatedly run without issue.
n/a
- Be sure you are …
=> Skip flaky tests (for now)

code/TemplateStudioForUWP/source.extension.vsixmanifest, code/TemplateStudioForWPF/source.extension.vsixmanifest, code/TemplateStudioForWinUICpp/source.extension.vsixmanifest, code/TemplateStudioForWinUICs/source.extension.vsixmanifest
For #4427
Remove the preview flag from published extensions.
|Yes | Yes | Yes |
no
yes
n/a
n/a
- Be sure you reviewed the [Template Verification Checklist](https://github.com/microsoft/TemplateStudio/wiki/Checklist:-Temp …
=> Don't indicate extensions as being in preview

code/test/TemplateStudioForUWP.Tests/TestData/UWP/SC/VBStyleAnalysis/.template.config/template.json
Consolidate VBStyleAnalyzer versions so that avoid a warning when running UWP VB.Net ManualOnly tests.
This change was made as part of manually verifying all  UWP tests, prior to the initial release.
Here are the test results
**Note.** The failing test is a "ManualOnly" test that verifies the accessibility of each generated page. **The failure is expected due to known external issues.**
Anyone wanting to recreate this test run should note the following:
- It takes a long time (1184.8 minutes is nearly 20 hours)
- Even VS2022 can't run all these tests at once without running out of memory. This means you can't just select everything, run the tests and leave it.
- Due to issues related to #4444 some of the tests report a false negative when run in parallel. …
=> Verify UWP testing

code/TemplateStudioForWinUICs/Templates/_catalog/projectTypes.json, code/test/SharedFunctionality.UI.Tests/ProjectTests/NewWinUICsProjectTest.cs
Updated projecttypes.json to reorder the project types. NavigationView is first so it is selected by default, followed by MenuBar, then Blank. This ordering follows the expected usage patterns as well.
#4499 
- Be sure you reviewed the [Template Verification Checklist](https://github.com/microsoft/TemplateStudio/wiki/Checklist:-Template …
=> Make NavigationView the default selected project.

code/TemplateStudioForWinUICs/TemplateStudioForWinUICs.csproj, code/TemplateStudioForWinUICs/Templates/Pg/Blank/Views/Param_ItemNamePage.xaml, code/TemplateStudioForWinUICs/Templates/Pg/CGrid/Param_ProjectName/Views/Param_ItemNameDetailPage.xaml, code/TemplateStudioForWinUICs/Templates/Pg/CGrid/Param_ProjectName/Views/Param_ItemNamePage.xaml, code/TemplateStudioForWinUICs/Templates/Pg/DGrid/Param_ProjectName/Views/Param_ItemNamePage.xaml, code/TemplateStudioForWinUICs/Templates/Pg/List/Param_ProjectName/Views/Param_ItemNameDetailControl.xaml, code/TemplateStudioForWinUICs/Templates/Pg/List/Param_ProjectName/Views/Param_ItemNamePage.xaml, code/TemplateStudioForWinUICs/Templates/Pg/Settings/Views/Param_ItemNamePage.xaml, code/TemplateStudioForWinUICs/Templates/Pg/WebView/Views/Param_ItemNamePage.xaml, code/TemplateStudioForWinUICs/Templates/Proj/Default/Param_ProjectName/Styles/Thickness.xaml, code/TemplateStudioForWinUICs/Templates/_comp/MT/Page.AddBackCommand/Views/Param_ItemNameDetailPage_postaction.xaml, code/TemplateStudioForWinUICs/Templates/_comp/MT/Project.MenuBar/Views/ShellPage.xaml, code/TemplateStudioForWinUICs/Templates/_comp/MT/Project.SplitView/Views/ShellPage.xaml, code/TemplateStudioForWinUICs/Templates/_comp/_shared/Page.AddTitle.Blank/Views/Param_ItemNamePage_postaction.xaml, code/TemplateStudioForWinUICs/Templates/_comp/_shared/Page.AddTitle.ContentGrid/Views/Param_ItemNamePage_postaction.xaml, code/TemplateStudioForWinUICs/Templates/_comp/_shared/Page.AddTitle.DataGrid/Views/Param_ItemNamePage_postaction.xaml, code/TemplateStudioForWinUICs/Templates/_comp/_shared/Page.AddTitle.Settings/Views/Param_ItemNamePage_postaction.xaml, code/TemplateStudioForWinUICs/Templates/_comp/_shared/Page.ListDetail.Blank.MenuBar/Views/Param_ItemNamePage_postaction.xaml, code/TemplateStudioForWinUICs/Templates/_comp/_shared/Page.ListDetail.SplitView/Views/Param_ItemNamePage_postaction.xaml, code/TemplateStudioForWinUICs/Templates/_comp/_shared/Page.SplitView.AddHeaderModeMinimal/Views/Param_ItemNamePage_postaction.xaml, code/TemplateStudioForWinUICs/Templates/_comp/_shared/Page.SplitView.AddHeaderModeNever/Views/Param_ItemNamePage_postaction.xaml
Removed unnecessary Page, Frame, and Grid Styles and BackgroundColors
Issue: #4463 
- ListDetail Control looks like it has some built-in styling
- Styling on ShellPage.xaml (SystemControlBackgroudAltHighBrush) needs to be included for theming (light/dark) to work
- It is possible that an issue with the maximize, minimize, and close buttons (on custom titlebar) blending in on light theme is fixed with the removal of styling
=> Remove custom styles to honor default control behaviors and designer feedback

code/src/ProjectTemplates/UWP/CS/Ts4UwpCsTemplate/Ts4UwpCsTemplate.cs-CZ.vstemplate, code/src/ProjectTemplates/UWP/CS/Ts4UwpCsTemplate/Ts4UwpCsTemplate.de-DE.vstemplate, code/src/ProjectTemplates/UWP/CS/Ts4UwpCsTemplate/Ts4UwpCsTemplate.es-ES.vstemplate, code/src/ProjectTemplates/UWP/CS/Ts4UwpCsTemplate/Ts4UwpCsTemplate.fr-FR.vstemplate, code/src/ProjectTemplates/UWP/CS/Ts4UwpCsTemplate/Ts4UwpCsTemplate.it-IT.vstemplate, code/src/ProjectTemplates/UWP/CS/Ts4UwpCsTemplate/Ts4UwpCsTemplate.ja-JP.vstemplate, code/src/ProjectTemplates/UWP/CS/Ts4UwpCsTemplate/Ts4UwpCsTemplate.ko-KR.vstemplate, code/src/ProjectTemplates/UWP/CS/Ts4UwpCsTemplate/Ts4UwpCsTemplate.pl-PL.vstemplate, code/src/ProjectTemplates/UWP/CS/Ts4UwpCsTemplate/Ts4UwpCsTemplate.pt-BR.vstemplate, code/src/ProjectTemplates/UWP/CS/Ts4UwpCsTemplate/Ts4UwpCsTemplate.ru-RU.vstemplate, code/src/ProjectTemplates/UWP/CS/Ts4UwpCsTemplate/Ts4UwpCsTemplate.tr-TR.vstemplate, code/src/ProjectTemplates/UWP/CS/Ts4UwpCsTemplate/Ts4UwpCsTemplate.vstemplate, code/src/ProjectTemplates/UWP/CS/Ts4UwpCsTemplate/Ts4UwpCsTemplate.zh-CN.vstemplate, code/src/ProjectTemplates/UWP/CS/Ts4UwpCsTemplate/Ts4UwpCsTemplate.zh-TW.vstemplate
Don't use a GUID that's also used in a different extension
Fixes #4511
Nope. THis is just me fixing a cut&paste error from the initial VS2022 support work
yes
n/a
n/a
- Be sure it's included …
=> Don't use GUID also used elsewhere

code/TemplateStudioForWinUICs/Templates/Proj/Default/Param_ProjectName/Helpers/TitleBarHelper.cs
Workaround for TitleBarHelper not updating correctly.
If `theme` param is default, it checks `Application.Current.RequestedTheme`, which returns the value of the default system theme, and it only has two posible values (dark and light).
With a boolean logic to check the actual system theme, it overrides the theme for the TitleBar.
Also deleted `if (theme != ElementTheme.Default)` because is redundant and aligned correctly the code that was inside the conditional clause.
#4599
Didn't tested
No
- Be sure you …
=> Workaround for TitleBar text not updating correctly

code/TemplateStudioForWinUICpp/Templates/Projects/Default/.template.config/template.json, code/TemplateStudioForWinUICs/Templates/Proj/Default/.template.config/template.json
I have updated nuget references to winappsdk to point to the latest version which is 1.2.3
https://www.nuget.org/packages/Microsoft.WindowsAppSDK
I have tested it locally and created projects do reference 1.2.3
=> Update to latest WinAppSDK version 1.2.3

_build/pipelines/release.yml
The release pipeline is failing because ESRP CodeSign version is too old and uses very old .Net core 2.0 dependency.
This PR updates it to 2.0 version so that it picks up modern .Net version and release pipeline becomes functional.
=> Update ESRP CodeSign version to 2.0 for release pipeline

code/TemplateStudioForWinUICs/Templates/Proj/Default/Param_ProjectName/MainWindow.xaml.cs
Fix a typo in `code/TemplateStudioForWinUICs/Templates/Proj/Default/Param_ProjectName/MainWindow.xaml.cs` line 25 comment `indows`, changed it to `windows`
=> Fix a typo: indows->windows in comment
